Insert into intgerrortbl values('M01','Part Name cannot be Empty')
Insert into intgerrortbl values('M02','Part Type cannot be Empty')
Insert into intgerrortbl values('M03','Party Not Found in the Account Master')
Insert into intgerrortbl values('M04','Part Not Found in the Item Master')
Insert into intgerrortbl values('M05','Sales Unit cannot be empty')
Insert into intgerrortbl values('M06','Purchase Unit cannot be empty')
Insert into intgerrortbl values('M07','Chapter No cannot be empty')
Insert into intgerrortbl values('M08','Party Name cannot be Empty')
Insert into intgerrortbl values('M09','Tax not mapped with Tax Master')
Insert into intgerrortbl values('M10','Consignee not Found')
Insert into intgerrortbl values('S01','SQL Structure not Generated Properly')
Insert into intgerrortbl values('S02','Importing From Xls was not properly Done')
Insert into intgerrortbl values('S03','File not found')
Insert into intgerrortbl values('S04','Fields have not been mapped for Uploading')
Insert into intgerrortbl values('S05','Cannot determine the Mode of the Record')
Insert into intgerrortbl values('S06','Condition for Updating Records not defined properly')
Insert into intgerrortbl values('S07','Record/s have been already Inserted')
Insert into intgerrortbl values('S08','Capital or Input Materials not Defined')
Insert into intgerrortbl values('T01','Transaction Date cannot be Empty')
Insert into intgerrortbl values('T02','Invoice No cannot be Empty')
Insert into intgerrortbl values('T03','Quantity should be Greater than Zero')
Insert into intgerrortbl values('T04','Rule cannot be Empty')
Insert into intgerrortbl values('T05','Labour Issue Date cannot be empty')
Insert into intgerrortbl values('T06','Labour Issue No. cannot be empty')
Insert into intgerrortbl values('T07','Vendor Invoice No. cannot be Empty')
Insert into intgerrortbl values('T08','Vendor Invoice Date cannot be Empty')
Insert into intgerrortbl values('T09','Document Type not defined in Document Master')
Insert into intgerrortbl values('T10','Labour Issue Item cannot be Empty')
Insert into intgerrortbl values('T11','Labour Consumed Qty cannot be Empty')
Insert into intgerrortbl values('T12','Labour Receipt Item cannot be Empty')
Insert into intgerrortbl values('T13','Issued Item not found against the Labour Issued No.')
Insert into intgerrortbl values('T14','Receipt Item not found against the Labour Receipt No.')
Insert into intgerrortbl values('T15','Transaction Date is not between the Financial Year')
Insert into intgerrortbl values('T16','Header Unique ID cannot be empty')
Insert into intgerrortbl values('T17','Detail Unique ID cannot be empty')
Insert into intgerrortbl values('T18','Manufacturer Ref. Bill not found')
