*!*	If (_Screen.ActiveForm.PCVTYPE="PH")

IF (main_vw.entry_ty='PH')
	IF !EMPT(ITEM_VW.U_FRPER)
		REPLACE ITEM_VW.U_FREIGHT WITH ((ITEM_VW.U_USDAMT+ITEM_VW.U_PACKCHG)*ITEM_VW.U_FRPER)/100
	ENDIF
	IF !EMPT(ITEM_VW.U_INSPER)
		REPLACE ITEM_VW.U_INSURA WITH ((ITEM_VW.U_USDAMT+ITEM_VW.U_PACKCHG)*ITEM_VW.U_INSPER)/100
	ENDIF
	REPLACE ITEM_VW.u_exchange WITH main_vw.u_exchange
	REPLACE ITEM_VW.U_USDAMT WITH (ITEM_VW.QTY*ITEM_VW.RATE)
*	REPLACE ITEM_VW.U_CIFAMT WITH ((ITEM_VW.U_USDAMT+ITEM_VW.U_FREIGHT+ITEM_VW.U_PACKCHG)*ITEM_VW.u_exchange)+(ITEM_VW.U_INSURA)
	REPLACE ITEM_VW.U_LANDCH WITH (((((ITEM_VW.U_USDAMT+ITEM_VW.U_PACKCHG)*ITEM_VW.u_exchange)+ITEM_VW.U_INSURA+ITEM_VW.U_FREIGHT)*ITEM_VW.U_LANDPER)/100)
	REPLACE ITEM_VW.U_CIFAMT WITH ((ITEM_VW.U_USDAMT+ITEM_VW.U_PACKCHG)*ITEM_VW.u_exchange)+(ITEM_VW.U_INSURA)+ITEM_VW.U_FREIGHT+ITEM_VW.U_LANDCH
	REPLACE ITEM_VW.U_ASSEAMT WITH ITEM_VW.U_CIFAMT
	REPLACE ITEM_VW.U_EXAMT WITH (ITEM_VW.U_ASSEAMT*ITEM_VW.U_BASDUTY1)/100
	REPLACE ITEM_VW.U_ACAMT WITH (((ITEM_VW.U_ASSEAMT+ITEM_VW.U_EXAMT)*ITEM_VW.U_ACDUTY)/100)
	REPLACE ITEM_VW.U_ACAMT1 WITH ((ITEM_VW.U_ACAMT*ITEM_VW.U_ACDUTY1)/100)
*	REPLACE ITEM_VW.U_HACAMT1 WITH  ITEM_VW.U_ACAMT1/2
	REPLACE ITEM_VW.U_CESSAMT WITH (((ITEM_VW.U_EXAMT+ITEM_VW.U_ACAMT+ITEM_VW.U_HACAMT1+ITEM_VW.U_ACAMT1)*ITEM_VW.U_CESSPER)/100)
	REPLACE ITEM_VW.U_HCESSAMT WITH  ITEM_VW.U_CESSAMT/2
	REPLACE ITEM_VW.U_INRVAL WITH (ITEM_VW.U_USDAMT)*ITEM_VW.u_exchange
	IF EMPT (ITEM_VW.RATE) AND !EMPT(ITEM_VW.U_USDAMT)
		REPLACE ITEM_VW.RATE WITH ITEM_VW.U_USDAMT/ITEM_VW.QTY
	ENDIF
	REPLACE ITEM_VW.EXAMT WITH ITEM_VW.U_EXAMT+ITEM_VW.U_ACAMT+ITEM_VW.U_ACAMT1+ITEM_VW.U_CESSAMT+ITEM_VW.U_SAAMT
*	REPLACE ITEM_VW.U_IMPAMT WITH ((ITEM_VW.U_CIFAMT+ITEM_VW.U_LANDCH+ITEM_VW.U_EXAMT+ITEM_VW.U_ACAMT+ITEM_VW.U_ACAMT1+ITEM_VW.U_CESSAMT+ITEM_VW.U_HCESSAMT+ITEM_VW.U_SAAMT)*ITEM_VW.U_IMPPER)/100
	REPLACE ITEM_VW.U_IMPAMT WITH ((ITEM_VW.U_CIFAMT+ITEM_VW.U_EXAMT+ITEM_VW.U_ACAMT+ITEM_VW.U_ACAMT1+ITEM_VW.U_CESSAMT+ITEM_VW.U_HCESSAMT+ITEM_VW.U_SAAMT)*ITEM_VW.U_IMPPER)/100
	TOTL =  ITEM_VW.U_USDAMT
ENDIF

IF (main_vw.entry_ty='PO' OR main_vw.entry_ty='AR')
	IF !EMPT(ITEM_VW.U_BASDUTY)
		REPLACE ITEM_VW.EXAMT WITH (ITEM_VW.U_ASSEAMT*ITEM_VW.U_BASDUTY)/100
	ENDIF	
	IF !EMPT(ITEM_VW.U_CESSPER)
		REPLACE ITEM_VW.U_CESSAMT WITH (ITEM_VW.EXAMT*ITEM_VW.U_CESSPER)/100
	ENDIF	
	IF !EMPT(ITEM_VW.U_HCESSPER)
		REPLACE ITEM_VW.U_HCESSAMT WITH (ITEM_VW.EXAMT*ITEM_VW.U_HCESSPER)/100
	ENDIF	


***************** ASHISH

	_curvouobj = _Screen.ActiveForm
	etsql_con = 1
	etsql_str=''
	str1=''
	SELECT item_vw

	mdbname = Company.DbName  

	etsql_str  = "select tax_name,level1 from stax_mas where tax_name = ?item_vw.tax_name"
	etsql_con  = _curvouobj.SqlConObj.DataConn([EXE],company.DbName,etsql_str,[itmst],"_curvouobj.nHandle",_curvouobj.DataSessionId,.t.)

    SELECT itmst
    SELECT item_vw
	replace item_vw.taxamt WITH ((ITEM_VW.U_ASSEAMT+ITEM_VW.u_packit+ITEM_VW.EXAMT+ITEM_VW.U_CESSAMT+ITEM_VW.U_HCESSAMT)*itmst.level1)/100
********************************  IF YOU WANT TO ADD ANY VALUE ADD HERE AFTER +ITEM_VW.U_PACKIT

**********ASHISH

ENDIF
IF main_vw.entry_ty='DM' AND main_vw.U_BOLT=.F.
	IF EMPTY(ITEM_VW.u_bundle)
		REPLA ITEM_VW.U_SWT WITH (ITEM_VW.U_EXPDESC)/1000
	ELSE
		REPLA ITEM_VW.U_SWT WITH (((ITEM_VW.U_EXPDESC)/1000)*ITEM_VW.u_bundle)
	ENDIF
	REPLACE ITEM_VW.U_GWT WITH (ITEM_VW.U_SWT+(ITEM_VW.U_SWT*main_vw.U_GPER)/100)

******* TO CALCULATE GROSS WEIGHT*********************
	IF !EMPT(ITEM_VW.U_BOXWT)
		REPLACE ITEM_VW.U_GROSSWT WITH ROUND(ITEM_VW.U_GWT+ITEM_VW.U_BOXWT/1000,3)
	ELSE
		REPLACE ITEM_VW.U_GROSSWT WITH ROUND(ITEM_VW.U_GWT+ITEM_VW.u_bundle/1000,3)
	ENDIF
******* END OF CALCULATE GROSS WEIGHT*********************

******* TO REPLACE QTY WITH GALVANIZED WT OF SECTION IN MT *********************
	REPLACE ITEM_VW.QTY WITH ITEM_VW.U_GWT
******* END TO REPLACE QTY WITH GALVANIZED WT OF SECTION IN MT *********************

******* TO CALCULATE SECTION(BLACK) WEIGHT IN KG*********************
	IF EMPT(ITEM_VW.U_WT)
	ELSE
		REPLACE ITEM_VW.U_EXPDESC WITH ITEM_VW.U_WT*ITEM_VW.U_APPACK
	ENDIF
	REPLACE ITEM_VW.U_PIECES WITH ITEM_VW.U_APPACK*ITEM_VW.u_bundle
******* END TO CALCULATE SECTION(BLACK) WEIGHT IN KG*********************

*!*	      IF EMPT(Item_VW.U_PIECES)
*!*	      	 && very important skip as below as we are relpacing pieces & bundles only at last line.
*!*	      	  rcn = recno()
*!*	      	  nonblankbundle=1
*!*	      	  do while !eof() and empty(Item_vw.u_pieces)
*!*	      	  	skip
*!*	      	  enddo
*!*	      	  if !empty(Item_vw.u_bundle)
*!*		      	  nonblankbundle = Item_vw.u_bundle
*!*	      	  endif
*!*	      	  go rcn
*!*		      Replace Item_VW.U_SWT WITH (Item_VW.U_EXPDESC*nonblankbundle/1000)
*!*	      ELSE
*!*	    	  Replace Item_VW.U_SWT WITH (Item_VW.U_EXPDESC*Item_VW.U_BUNDLE)/1000
*!*	      ENDIF

ENDIF

IF main_vw.entry_ty='DM' 
	IF  main_vw.U_BOLT=.F.
	
			REPLACE ITEM_VW.U_GWT WITH ROUND((ITEM_VW.U_SWT+(ITEM_VW.U_SWT*main_vw.U_GPER)/100),2)
			REPLACE ITEM_VW.QTY WITH ROUND((ITEM_VW.U_GWT)/1000,5)
		
		IF EMPT(ITEM_VW.u_bundle)
			REPLACE ITEM_VW.U_PIECES WITH ITEM_VW.U_APPACK
			REPLACE ITEM_VW.U_SWT WITH ITEM_VW.U_EXPDESC
		ELSE
			REPLACE ITEM_VW.U_PIECES WITH ITEM_VW.U_APPACK*ITEM_VW.u_bundle
			REPLACE ITEM_VW.U_SWT WITH ITEM_VW.U_EXPDESC*ITEM_VW.u_bundle
		ENDIF
		IF !EMPT(ITEM_VW.U_BOXWT)
			REPLACE ITEM_VW.U_GROSSWT WITH ROUND(ITEM_VW.U_GWT+ITEM_VW.U_BOXWT/1000,3)
		ELSE
			REPLACE ITEM_VW.U_GROSSWT WITH ROUND(ITEM_VW.U_GWT+ITEM_VW.u_bundle/1000,3)
		ENDIF
		REPLACE ITEM_VW.QTY WITH ITEM_VW.U_GWT
	ELSE 
	
			REPLACE ITEM_VW.U_GWT WITH ROUND((ITEM_VW.U_SWT+(ITEM_VW.U_SWT*main_vw.U_GPER)/100),2)
			REPLACE ITEM_VW.QTY WITH (ITEM_VW.U_GWT)
		
		IF EMPT(ITEM_VW.u_bundle)
			REPLACE ITEM_VW.U_PIECES WITH ITEM_VW.U_APPACK
			REPLACE ITEM_VW.U_SWT WITH ITEM_VW.U_EXPDESC
		ELSE
			REPLACE ITEM_VW.U_PIECES WITH ITEM_VW.U_APPACK*ITEM_VW.u_bundle
			REPLACE ITEM_VW.U_SWT WITH ITEM_VW.U_EXPDESC*ITEM_VW.u_bundle
		ENDIF
		IF !EMPT(ITEM_VW.U_BOXWT)
			REPLACE ITEM_VW.U_GROSSWT WITH ROUND(ITEM_VW.U_GWT+ITEM_VW.U_BOXWT,2)
		ELSE
			REPLACE ITEM_VW.U_GROSSWT WITH ROUND(ITEM_VW.U_GWT+ITEM_VW.u_bundle,2)
		ENDIF
		REPLACE ITEM_VW.QTY WITH ITEM_VW.U_GWT

	endif	
******* END TO REPLACE QTY WITH GALVANIZED WT OF SECTION IN MT *********************

******* TO CALCULATE SECTION(BLACK) WEIGHT IN KG*********************
	IF EMPT(ITEM_VW.U_WT)
	ELSE
		REPLACE ITEM_VW.U_EXPDESC WITH ITEM_VW.U_WT*ITEM_VW.U_APPACK
	ENDIF
	REPLACE ITEM_VW.U_PIECES WITH ITEM_VW.U_APPACK*ITEM_VW.u_bundle
ENDIF

IF main_vw.entry_ty='PT' OR main_vw.entry_ty='II'

*!*	WAIT wind('H1.......')
	IF (ITEM_VW.u_basduty#0)
		REPLACE ITEM_VW.EXAMT WITH (ITEM_VW.U_ASSEAMT)*(ITEM_VW.u_basduty/100)
	ENDIF
	IF (ITEM_VW.U_BASDUTY1#0)
		REPLACE ITEM_VW.U_EXAMT WITH (ITEM_VW.U_ASSEAMT)*(ITEM_VW.U_BASDUTY1/100)
	ENDIF
	IF (ITEM_VW.U_ACDUTY#0)
		REPLACE ITEM_VW.U_ACAMT WITH (ITEM_VW.U_ASSEAMT+ITEM_VW.U_EXAMT)*(ITEM_VW.U_ACDUTY/100)
	ENDIF
	IF (ITEM_VW.U_ACDUTY1#0)
		REPLACE ITEM_VW.U_ACAMT1 WITH (ITEM_VW.U_ACAMT)*(ITEM_VW.U_ACDUTY1/100)
	ENDIF
	IF (ITEM_VW.u_hacper#0)
		REPLACE ITEM_VW.U_HACAMT1 WITH (ITEM_VW.U_ACAMT)*(ITEM_VW.u_hacper/100)
	ENDIF
	IF (ITEM_VW.U_CESSPER#0)
*!*		WAIT wind('H2.......')
		IF!EMPTY(ITEM_VW.U_ADDDUTY)
			REPLACE ITEM_VW.U_CESSAMT WITH (ITEM_VW.U_ADDDUTY+ITEM_VW.EXAMT)*(ITEM_VW.U_CESSPER/100)
		ELSE
			REPLACE ITEM_VW.U_CESSAMT WITH (ITEM_VW.U_EXAMT+ITEM_VW.EXAMT+ITEM_VW.U_ACAMT+ITEM_VW.U_ACAMT1+ITEM_VW.U_HACAMT1)*(ITEM_VW.U_CESSPER/100)
		ENDIF
	ENDIF
	IF (ITEM_VW.U_HCESSPER#0)
*!*		WAIT wind('H3.......')
		IF!EMPTY(ITEM_VW.U_ADDDUTY)
			REPLACE ITEM_VW.U_HCESSAMT WITH (ITEM_VW.U_ADDDUTY+ITEM_VW.EXAMT)*(ITEM_VW.U_HCESSPER/100)
		ELSE
			REPLACE ITEM_VW.U_HCESSAMT WITH (ITEM_VW.U_EXAMT+ITEM_VW.EXAMT+ITEM_VW.U_ACAMT+ITEM_VW.U_ACAMT1+ITEM_VW.U_HACAMT1)*(ITEM_VW.U_HCESSPER/100)
		ENDIF
	ENDIF
	IF (ITEM_VW.U_IMPPER#0)
*!*		WAIT wind('H4.......')
		REPLACE ITEM_VW.u_impduty WITH (ITEM_VW.U_ASSEAMT+ITEM_VW.U_EXAMT+ITEM_VW.U_ACAMT+ITEM_VW.U_ACAMT1+ITEM_VW.U_CESSAMT+ITEM_VW.U_HCESSAMT+ITEM_VW.U_HACAMT1)*(ITEM_VW.U_IMPPER/100)
	ENDIF
ENDIF

*!*	IF (main_vw.entry_ty='AR')


*!*	***************** ASHISH

*!*		_curvouobj = _Screen.ActiveForm
*!*		etsql_con = 1
*!*		etsql_str=''
*!*		str1=''
*!*		SELECT item_vw

*!*		mdbname = Company.DbName  

*!*		etsql_str  = "select tax_name,level1 from stax_mas where tax_name = ?item_vw.tax_name"
*!*		etsql_con  = _curvouobj.SqlConObj.DataConn([EXE],company.DbName,etsql_str,[itmst],"_curvouobj.nHandle",_curvouobj.DataSessionId,.t.)

*!*	    SELECT itmst
*!*	    SELECT item_vw
*!*		replace item_vw.taxamt WITH ((ITEM_VW.U_ASSEAMT+ITEM_VW.u_packit)*itmst.level1)/100
*!*	********************************  IF YOU WANT TO ADD ANY VALUE ADD HERE AFTER +ITEM_VW.U_PACKIT

*!*	**********ASHISH

*!*	ENDIF
