IF EXISTS(SELECT * FROM SYSOBJECTS WHERE [NAME]='USP_ENT_EMAILCLIENT_DELETE' AND XTYPE='P')
BEGIN
	DROP PROCEDURE USP_ENT_EMAILCLIENT_DELETE
END
GO
Create Procedure USP_ENT_EMAILCLIENT_DELETE
@id varchar(20)
As
Begin
	Delete From eMailClient Where id=@id
End