If Exists(Select [name] From SysObjects Where xtype='P' and [Name]='USP_REP_UA_FORMVAT3_ANNEXURE9_DADOS')
Begin
	Drop Procedure USP_REP_UA_FORMVAT3_ANNEXURE9_DADOS
End
Go
      
CREATE PROCEDURE [dbo].[USP_REP_UA_FORMVAT3_ANNEXURE9_DADOS]
@SDATE SMALLDATETIME,@EDATE SMALLDATETIME            
AS        
BEGIN           
--EXPORT OUT OF COUNTRY     
select A.U_EXPDEL,NO1=RTRIM(A.U_VESSEL)+' DT.'+CONVERT(VARCHAR(10),A.U_SBDT,101),A.inv_no,A.date,VATONAMT=A.NET_AMT FROM STMAIN A
INNER JOIN AC_MAST AC ON(AC.AC_ID=A.AC_ID)
WHERE AC.ST_TYPE in ('OUT OF COUNTRY') and (A.DATE BETWEEN @SDATE AND @EDATE)      
END  
