IF EXISTS(SELECT * FROM SYSOBJECTS WHERE [NAME]='USP_ENT_INSERT_TO_DBF' AND XTYPE='P')
BEGIN
	DROP PROCEDURE USP_ENT_INSERT_TO_DBF
END
GO
CREATE PROCEDURE [dbo].[USP_ENT_INSERT_TO_DBF]
@ID VARCHAR(5)
AS
--SELECT * FROM CUSTFEATURE
--SELECT * FROM CUSTMNUTRANRPTDTS

SELECT A.RCOMP,A.RMACID,B.CCOMP,B.OPTIONTYPE
,CASE WHEN B.OPTIONTYPE = 'TRAN' THEN UPPER(B.DESC1) ELSE UPPER(B.DESC1)+UPPER(B.DESC2)+UPPER(B.DESC3) END AS OPTIONDESC
,A.BUG
FROM CUSTFEATURE A
INNER JOIN CUSTMNUTRANRPTDTS B ON (A.ID=B.FK_ID)
WHERE B.OPTIONTYPE <> 'COMPANY'
AND A.ID=@ID
