EXECUTE ADD_COLUMNS 'EPITEM','avl BIT DEFAULT 1 WITH VALUES'
EXECUTE ADD_COLUMNS 'PTITEM','avl BIT DEFAULT 1 WITH VALUES'

EXECUTE ADD_COLUMNS 'EPITEM','ITCSEC varchar(50)'
EXECUTE ADD_COLUMNS 'PTITEM','ITCSEC varchar(50)'


