
CREATE TABLE [prodmast](
	[ProductId] [int] NOT NULL ,
	[ProductNm] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ProductCd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[RegProdCd] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[IsActive] [bit] NULL ,
	[req_acti] [bit] NULL 

)ON [PRIMARY]



/* Generated by SQLEditor */

INSERT INTO prodmast([ProductId], [ProductNm], [ProductCd], [RegProdCd], [IsActive], [req_acti]) 
VALUES (52, 'Visual Udyog Standard Version', 'VudyogSTD', 'U8 STD', 1, 1)

INSERT INTO prodmast([ProductId], [ProductNm], [ProductCd], [RegProdCd], [IsActive], [req_acti]) 
VALUES (53, 'Visual Udyog Professional Version', 'VudyogPRO', 'U7 PRO', 1, 1)

INSERT INTO prodmast([ProductId], [ProductNm], [ProductCd], [RegProdCd], [IsActive], [req_acti]) 
VALUES (54, 'Visual Udyog Enterprise Version', 'VudyogENT', 'U6 ENT', 1, 1)

INSERT INTO prodmast([ProductId], [ProductNm], [ProductCd], [RegProdCd], [IsActive], [req_acti]) 
VALUES (51, 'Visual Udyog SDK', 'VudyogSDK', 'U9 SDK', 1, 0)

INSERT INTO prodmast([ProductId], [ProductNm], [ProductCd], [RegProdCd], [IsActive], [req_acti]) 
VALUES (55, 'USquare 10', '10USquare', 'U5 USQ', 1, 1)

INSERT INTO prodmast([ProductId], [ProductNm], [ProductCd], [RegProdCd], [IsActive], [req_acti]) 
VALUES (56, 'iTax 10', '10iTax', 'I5 ITX', 1, 1)

