IF EXISTS (SELECT XTYPE, NAME FROM SYSOBJECTS WHERE XTYPE = 'P' AND NAME = 'USP_REP_UA_ANNX2B')
BEGIN
	DROP PROCEDURE USP_REP_UA_ANNX2B
END
GO
set ANSI_NULLS ON
GO
set QUOTED_IDENTIFIER ON
go

/*
EXECUTE USP_REP_UA_ANNX2B'','','','04/01/2015','03/31/2016','','','','',0,0,'','','','','','','','','2015-2016',''
*/

-- =============================================
-- Author     :	GAURAV R. TANNA for the Bug-26160
-- Create date: 03/06/2015
-- Description:	This Stored procedure is useful to generate Uttarakhand Annexure 2B
-- Modify date: 
-- Modified By: 
-- Remark:    : 
-- =============================================
Create  PROCEDURE [dbo].[USP_REP_UA_ANNX2B]
@TMPAC NVARCHAR(50),@TMPIT NVARCHAR(50),@SPLCOND VARCHAR(8000),@SDATE  SMALLDATETIME,@EDATE SMALLDATETIME
,@SAC AS VARCHAR(60),@EAC AS VARCHAR(60)
,@SIT AS VARCHAR(60),@EIT AS VARCHAR(60)
,@SAMT FLOAT,@EAMT FLOAT
,@SDEPT AS VARCHAR(60),@EDEPT AS VARCHAR(60)
,@SCATE AS VARCHAR(60),@ECATE AS VARCHAR(60)
,@SWARE AS VARCHAR(60),@EWARE AS VARCHAR(60)
,@SINV_SR AS VARCHAR(60),@EINV_SR AS VARCHAR(60)
,@LYN VARCHAR(20)
,@EXPARA  AS VARCHAR(60)= NULL
AS

BEGIN
DECLARE @FCON AS NVARCHAR(2000)
EXECUTE   USP_REP_FILTCON 

@VTMPAC =@TMPAC,@VTMPIT =@TMPIT,@VSPLCOND =@SPLCOND
,@VSDATE=NULL,@VEDATE=@EDATE
,@VSAC =@SAC,@VEAC =@EAC
,@VSIT=@SIT,@VEIT=@EIT
,@VSAMT=@SAMT,@VEAMT=@EAMT
,@VSDEPT=@SDEPT,@VEDEPT=@EDEPT
,@VSCATE =@SCATE,@VECATE =@ECATE
,@VSWARE =@SWARE,@VEWARE  =@EWARE
,@VSINV_SR =@SINV_SR,@VEINV_SR =@SINV_SR
,@VMAINFILE='M',@VITFILE=Null,@VACFILE='AC'
,@VDTFLD ='DATE'
,@VLYN=Null
,@VEXPARA=@EXPARA
,@VFCON =@FCON OUTPUT

DECLARE @SQLCOMMAND NVARCHAR(4000), @MCON as NVARCHAR(2000)

---Temporary Cursor
--SELECT PART=3,PARTSR='AAA',SRNO='AAA',RATE=999.999,AMT1=NET_AMT,AMT2=M.TAXAMT,AMT3=M.TAXAMT,
--M.INV_NO,M.DATE,PARTY_NM=AC1.AC_NAME,ADDRESS=Ltrim(AC1.Add1)+' '+Ltrim(AC1.Add2)+' '+Ltrim(AC1.Add3),
--STM.FORM_NM,AC1.S_TAX,Item=Space(50),Qty=9999999999.9999,stm.level1,HSNCODE=SPACE(10)
--INTO #FORM2B
--FROM STACDET A 
--INNER JOIN STMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)
--INNER JOIN STAX_MAS STM ON (M.TAX_NAME=STM.TAX_NAME AND M.ENTRY_TY=STM.ENTRY_TY)
--INNER JOIN AC_MAST AC ON (A.AC_NAME=AC.AC_NAME)
--INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID)
--WHERE 1=2

Declare @MultiCo	VarChar(3)

Begin ------Fetch Single Co. Data
	 Set @MultiCo = 'NO'
	 EXECUTE USP_REP_SINGLE_CO_DATA_VAT
	  @TMPAC, @TMPIT, @SPLCOND, @SDATE, @EDATE
	 ,@SAC, @EAC, @SIT, @EIT, @SAMT, @EAMT
	 ,@SDEPT, @EDEPT, @SCATE, @ECATE,@SWARE
	 ,@EWARE, @SINV_SR, @EINV_SR, @LYN, 'ST'
	 ,@MFCON = @MCON OUTPUT

	 SELECT A.inv_no, I.ITEM, A.VATONAMT, STM.Level1, A.TAXAMT FROM VATTBL A
	 inner join STITEM I ON (I.Tran_cd = a.TRAN_CD And I.ENTRY_TY = A.BHENT And I.It_code = A.It_code)
	 inner join STAX_MAS STM ON (stm.entry_ty = A.BHENT And stm.Tax_Name = A.TAX_NAME)
	 WHERE A.ST_TYPE in ('LOCAL','') AND A.BHENT in ('ST') AND A.TAXAMT <> 0
	 AND (A.DATE BETWEEN @SDATE AND @EDATE) AND A.S_TAX = ''
	 ORDER BY A.INV_NO
	
End

END
--Print 'HR VAT FORM LS 07'

