/****** Object:  StoredProcedure [dbo].[USP_REP_118RECIND]    Script Date: 02/05/2010 09:58:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[USP_REP_118RECIND] 
	@TMPAC NVARCHAR(50),@TMPIT NVARCHAR(50),@SPLCOND VARCHAR(8000),@SDATE  SMALLDATETIME,@EDATE SMALLDATETIME
	,@SAC AS VARCHAR(60),@EAC AS VARCHAR(60)
	,@SIT AS VARCHAR(60),@EIT AS VARCHAR(60)
	,@SAMT FLOAT,@EAMT FLOAT
	,@SDEPT AS VARCHAR(60),@EDEPT AS VARCHAR(60)
	,@SCATE AS VARCHAR(60),@ECATE AS VARCHAR(60)
	,@SWARE AS VARCHAR(60),@EWARE AS VARCHAR(60)
	,@SINV_SR AS VARCHAR(60),@EINV_SR AS VARCHAR(60)
	,@LYN VARCHAR(20)
	,@EXPARA  AS VARCHAR(60)= null

AS

SET QUOTED_IDENTIFIER OFF

Declare @FCON as NVARCHAR(2000),@VSAMT DECIMAL(14,2),@VEAMT DECIMAL(14,2)
EXECUTE   USP_REP_FILTCON 
	@VTMPAC =@TMPAC,@VTMPIT =@TMPIT,@VSPLCOND =@SPLCOND
	,@VSDATE=@SDATE
	,@VEDATE=@EDATE
	,@VSAC =@SAC,@VEAC =@EAC
	,@VSIT=@SIT,@VEIT=@EIT
	,@VSAMT=@SAMT,@VEAMT=@EAMT
	,@VSDEPT=@SDEPT,@VEDEPT=@EDEPT
	,@VSCATE =@SCATE,@VECATE =@ECATE
	,@VSWARE =@SWARE,@VEWARE  =@EWARE
	,@VSINV_SR =@SINV_SR,@VEINV_SR =@SINV_SR
	,@VMAINFILE='PTMAIN',@VITFILE='PTITEM',@VACFILE='PTACDET'
	,@VDTFLD ='DATE'
	,@VLYN =NULL
	,@VEXPARA=@EXPARA
	,@VFCON =@FCON OUTPUT

IF @FCON IS NOT NULL OR @FCON <> ''
BEGIN
	SET @FCON = @FCON + 'AND PTMAIN.[RULE] = ''INDIGENIOUS'''
END

DECLARE @SQLCOMMAND NVARCHAR(4000), @VCOND NVARCHAR(2000)

SET @SQLCOMMAND='SELECT PTITEM.TRAN_CD,PTITEM.ENTRY_TY,PTITEM.INV_NO,PTITEM.DATE,IT_MAST.IT_NAME,PTITEM.QTY,PTITEM.ITSERIAL,PTITREF.RINV_NO,PTMAIN.U_AR3ANO,PTMAIN.U_AR3ADATE,PTMAIN.U_PINVNO,PTMAIN.U_PINVDT,PTITEM.U_EXPMARK,PTITEM.U_CIFAMT,PTITEM.U_ACAMT,PTITEM.U_EXAMT,PTITEM.U_ACAMT1,PTITEM.U_HACAMT1,PTITEM.U_CESSAMT,PTITEM.U_HCESSAMT,PTITEM.U_ADDDUTY,IT_MAST.P_UNIT,PTMAIN.[RULE],ARITREF.RINV_NO,ARITREF.RDATE,PTITEM.U_ASSEAMT,PTITEM.EXAMT FROM PTITEM '
SET @SQLCOMMAND=@SQLCOMMAND+'INNER JOIN PTMAIN ON(PTITEM.ENTRY_TY=PTMAIN.ENTRY_TY AND PTITEM.TRAN_CD=PTMAIN.TRAN_CD)'
SET @SQLCOMMAND=@SQLCOMMAND+'INNER JOIN IT_MAST ON (PTITEM.ITEM=IT_MAST.IT_NAME) '
SET @SQLCOMMAND=@SQLCOMMAND+'left JOIN PTITREF ON (PTITEM.ENTRY_TY=PTITREF.ENTRY_TY and PTITEM.DATE=PTITREF.DATE AND PTITEM.DOC_NO=PTITREF.DOC_NO AND PTITEM.ITSERIAL=PTITREF.ITSERIAL)'
SET @SQLCOMMAND=@SQLCOMMAND+'LEFT JOIN ARITEM ON (ARITEM.ENTRY_TY=PTITREF.RENTRY_TY AND ARITEM.inv_sr=ptitref.rinv_sr AND ARITEM.INV_NO=PTITREF.RINV_NO AND ARITEM.ITSERIAL=PTITREF.RITSERIAL) '
SET @SQLCOMMAND=@SQLCOMMAND+'LEFT JOIN ARITREF ON (ARitem.entry_ty=ARitref.entry_ty and ARITEM.DATE=ARITREF.DATE AND ARITEM.DOC_NO=ARITREF.DOC_NO AND ARITEM.ITSERIAL=ARITREF.ITSERIAL)'
--SET @SQLCOMMAND=@SQLCOMMAND+'LEFT JOIN SOITEM ON (SOITEM.ENTRY_TY=ARITREF.RENTRY_TY AND SOITEM.inv_sr=ARitref.rinv_sr AND SOITEM.INV_NO=ARITREF.RINV_NO AND SOITEM.ITSERIAL=ARITREF.RITSERIAL)'
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+RTRIM(@FCON)
SET @SQLCOMMAND=@SQLCOMMAND+'ORDER BY PTITEM.DATE,PTITEM.ITEM'
PRINT @SQLCOMMAND

EXECUTE SP_EXECUTESQL @SQLCOMMAND


