IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Salary Section17_1')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (1,'Salary Section17_1','Salary under Section 17(1)') END 
update Emp_Payroll_Section_Main_Master set [FORM16GROUP]='Salary under Section 17(1)' WHERE Section = 'Salary Section17_1'
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Salary Section17_2')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (2,'Salary Section17_2','Salary under Section 17(2)') END 
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Salary Section17_3')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (3,'Salary Section17_3','Salary under Section 17(3)') END 
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Income other than salary')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (4,'Income other than salary','Particulars of Income from sources other than salary') END 

IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Section 10')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (5,'Section 10','Allowance to the extent exempt U/S 10') END 
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Section 16 and 17')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (6,'Section 16 and 17','Deduction U/S 16 & 17') END 

IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Section 80C')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (7,'Section 80C','Dedcution under Chapter VIA') END 
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Section 80CCC')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (8,'Section 80CCC','Dedcution under Chapter VIA') END 
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Section 80CCD')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (9,'Section 80CCD','Dedcution under Chapter VIA') END 
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Section 80CCF')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (10,'Section 80CCF','Dedcution under Chapter VIA') END 
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Section 80E')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (11,'Section 80E','Dedcution under Chapter VIA') END 
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Section 80G')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (12,'Section 80G','Dedcution under Chapter VIA') END 
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Section 80GG')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (13,'Section 80GG','Dedcution under Chapter VIA') END 
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Section 80GGA')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (14,'Section 80GGA','Dedcution under Chapter VIA') END 
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Section 80GGC')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (15,'Section 80GGC','Dedcution under Chapter VIA') END 
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Section 80U')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (16,'Section 80U','Dedcution under Chapter VIA') END 
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Section 80DD')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (17,'Section 80DD','Dedcution under Chapter VIA') END 
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Section 80D')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (18,'Section 80D','Dedcution under Chapter VIA') END 
IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Section 80DDB')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (19,'Section 80DDB','Dedcution under Chapter VIA') END 

IF NOT EXISTS(SELECT [Section] FROM Emp_Payroll_Section_Main_Master WHERE Section = 'Others Deduction Under Section VI-A')BEGIN INSERT INTO Emp_Payroll_Section_Main_Master([SORTORD],[SECTION],[FORM16GROUP]) VALUES (20,'Others Deduction Under Section VI-A','Dedcution under Chapter VIA') END 


IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'section17_1')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Salary Section17_1','Salary as per provisons contained in section 17(1)','section17_1',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'section17_2')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Salary Section17_2','Value of prerequisites under section 17(2)','section17_2',0,'') END
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'section17_3')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Salary Section17_3','Profits in lieu of salary under section 17(3)','section17_3',0,'') END

IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'section80CCC')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Section 80CCC','section 80CCC','section80CCC',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'Section80CCD')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Section 80CCD','Section 80CCD','Section80CCD',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'Section80CCF')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Section 80CCF','Tax Saving Infrastructure Bond','Section80CCF',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'Section80U')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Section 80U','Section 80U','Section80U',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'Section80E')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Section 80E','Section 80E','Section80E',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'Section80G')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Section 80G','Section 80G','Section80G',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'Section80GG')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Section 80GG','Section 80GG','Section80GG',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'Section80GGA')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Section 80GGA','Section 80GGA','Section80GGA',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'Section80GGC')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Section 80GGC','Section 80GGC','Section80GGC',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'MedicalInsurance80D')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Section 80D','Medical Insurance','MedicalInsurance80D',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'Section80DDB')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Section 80DDB','Section 80DDB','Section80DDB',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'Section80DD')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Section 80DD','Section 80DD','Section80DD',0,'') END 

IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'HRA_10_13A')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Section 10','HRA U/S 10(13A)','HRA_10_13A',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'MediAmt')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (2,'Section 10','Medical Reimbursment','MediAmt',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'CONWAMT')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (3,'Section 10','Convayance/ Allowance','CONWAMT',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'LTCAmt')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (4,'Section 10','Leave Travel Concession (LTC)','LTCAmt',0,'') END 

IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'EntAmt')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Section 16 and 17','Entertainment Allowance','EntAmt',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'PTAmt')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (2,'Section 16 and 17','Tax on Payment','PTAmt',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'HBLoanAmt')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (3,'Section 16 and 17','H.B.Loan Interest Paid','HBLoanAmt',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'ChildEduAmt')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (4,'Section 16 and 17','Children Education Allowances','ChildEduAmt',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'ChildHostelAmt')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (5,'Section 16 and 17','Children Hostel Allowances','ChildHostelAmt',0,'') END 

IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'OtherDeductionVI_A')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Others Deduction Under Section VI-A','Other Deduction Under Chapter VI-A','OtherDeductionVI_A',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'OthIncomeDivedends')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Income other than salary','Dividends','OthIncomeDivedends',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'OthIncomeInterest')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (2,'Income other than salary','Interest','OthIncomeInterest',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'OthIncomeSpcify')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (3,'Income other than salary','Other Incomes (specify)','OthIncomeSpcify',0,'') END 

IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'EPF')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (1,'Section 80C','E.P.F','EPF',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'ULIP')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (2,'Section 80C','ULIP','ULIP',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'TutionFees')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (3,'Section 80C','Tution Fees','TutionFees',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'NSC')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (4,'Section 80C','NSC','NSC',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'LifeInsurancePolicy')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (5,'Section 80C','LIC','LifeInsurancePolicy',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'PPF')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (6,'Section 80C','PPF','PPF',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'HBLoanPrincipal')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (7,'Section 80C','HB Loan Principal','HBLoanPrincipal',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'TaxSavingFD')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (8,'Section 80C','Fixed Deposit above 5 years','TaxSavingFD',0,'') END 
IF NOT EXISTS(SELECT [Fld_Nm] FROM Emp_Payroll_Section_Master WHERE Fld_Nm = 'EquityLinkSavingsBond')BEGIN INSERT INTO Emp_Payroll_Section_Master([SORTORD],[SECTION],[SECTIONDET],[FLD_NM],[ISDEACTIVE],[DEACTFROM]) VALUES (9,'Section 80C','Equity Link Savings Bond','EquityLinkSavingsBond',0,'') END 