UPDATE r_status SET SQLQUERY ='EXECUTE USP_REP_SO_VOU;''SOMAIN.ENTRY_TY=''''SO'''' AND SOMAIN.TRAN_CD=0''' WHERE [GROUP]='SALES ORDER' AND [desc] ='SALES ORDER' AND [rep_nm] ='SO_VOU' 
UPDATE r_status SET SQLQUERY ='EXECUTE USP_REP_PO_VOU;''POMAIN.ENTRY_TY=''''PO'''' AND POMAIN.TRAN_CD=0''' WHERE [GROUP]='PURCHASE ORDER' AND [desc] ='PURCHASE ORDER' AND [rep_nm] ='PO_VOU' 
UPDATE LOTHER SET inter_use ='.T.' WHERE e_code ='SO' AND head_nm ='Delivery Terms' AND fld_nm ='U_DELTERMS'
