=ADDINARRY("UNSECURED LOANS,TRADING INCOME,TRADING EXPENSES,SUNDRY DEBTORS,SUNDRY CREDITORS,")

FUNCTION ADDINARRY
PARAMETERS mx
CLEAR
mx = ALLTRIM(mx)
x = IIF(RIGHT(mx,1)=",",LEFT(mx,LEN(mx)-1),mx)
?x
x = '<'+STRTRAN(x,",","><")+'>'
?x
