if exists(select [name] from sysobjects where [name]='USP_REP_MH704_ANN_J_2_DADOS' and xtype='P')
drop procedure USP_REP_MH704_ANN_J_2_DADOS
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO





-- =============================================
-- Author:		Pankaj M. Borse
-- Create date: 08/08/2014
-- Description:	MVAT Form 704 - Annexure-J_2 Dasod Bug-23111
-- Modified By: 
-- Remark:      

-- =============================================


create PROCEDURE [dbo].[USP_REP_MH704_ANN_J_2_DADOS]
@SDATE  SMALLDATETIME,@EDATE SMALLDATETIME

AS
Begin
Declare @FCON as NVARCHAR(2000),@VSAMT DECIMAL(14,2),@VEAMT DECIMAL(14,2)

PRINT @SDATE
Declare @SQLCOMMAND NVARCHAR(4000)
 DECLARE @RATE NUMERIC(12,2),@AMTA1 NUMERIC(12,2),@AMTB1 NUMERIC(12,2),@AMTC1 NUMERIC(12,2),@AMTD1 NUMERIC(12,2),@AMTE1 NUMERIC(12,2),@AMTF1 NUMERIC(12,2),@AMTG1 NUMERIC(12,2),@AMTH1 NUMERIC(12,2),@AMTI1 NUMERIC(12,2),@AMTJ1 NUMERIC(12,2),@AMTK1 NUMERIC(12,2),@AMTL1 NUMERIC(12,2),@AMTM1 NUMERIC(12,2),@AMTN1 NUMERIC(12,2),@AMTO1 NUMERIC(12,2)
 DECLARE @AMTA2 NUMERIC(12,2),@AMTB2 NUMERIC(12,2),@AMTC2 NUMERIC(12,2),@AMTD2 NUMERIC(12,2),@AMTE2 NUMERIC(12,2),@AMTF2 NUMERIC(12,2),@AMTG2 NUMERIC(12,2),@AMTH2 NUMERIC(12,2),@AMTI2 NUMERIC(12,2),@AMTJ2 NUMERIC(12,2),@AMTK2 NUMERIC(12,2),@AMTL2 NUMERIC(12,2),@AMTM2 NUMERIC(12,2),@AMTN2 NUMERIC(12,2),@AMTO2 NUMERIC(12,2)
 DECLARE @PER NUMERIC(12,2),@TAXAMT NUMERIC(12,2),@CHAR INT,@LEVEL NUMERIC(12,2)

SELECT ENTRY_TY,BCODE=(CASE WHEN EXT_VOU=1 THEN BCODE_NM ELSE ENTRY_TY END),STAX_ITEM  INTO #LCODE FROM LCODE --for bug-6755,LUBRI
 

Declare @NetEff as numeric (12,2), @NetTax as numeric (12,2)

SELECT PART=3,PARTSR='AAA',SRNO='AAAA',RATE=99.999,AMT1=NET_AMT,AMT2=M.TAXAMT,AMT3=M.NET_AMT,AMT4=M.NET_AMT,
PARTY_NM=AC1.AC_NAME--,ADDRESS=Ltrim(AC.Add1)+' '+Ltrim(AC.Add2)+' '+Ltrim(AC.Add3),
,M.INV_NO,M.DATE,STM.FORM_NM,AC1.S_TAX,STTYPE=SPACE(20),stm.rform_nm,ac.state
INTO #MHFRM704J_2
FROM PTACDET A 
INNER JOIN STMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)
INNER JOIN STAX_MAS STM ON (M.TAX_NAME=STM.TAX_NAME)
INNER JOIN AC_MAST AC ON (A.AC_NAME=AC.AC_NAME)
INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID)
WHERE 1=2


 SELECT @AMTA1=0,@AMTB1=0,@AMTC1=0,@AMTD1=0,@AMTE1=0,@AMTF1=0,@AMTG1=0,@AMTH1=0,@AMTI1=0,@AMTJ1=0,@AMTK1=0,@AMTL1=0,@AMTM1=0,@AMTN1=0,@AMTO1=0

select PER=0,VATONAMT=SUM(round(((M.gro_amt+M.tot_add+M.tot_tax)-M.tot_deduc),2))
,TAXAMT=SUM(M.TAXAMT),NET_AMT=SUM(M.NET_AMT),EXPAMT=CAST(0 AS DECIMAL(12,2)),M.PARTY_NM,AC.S_TAX
INTO #TEMP FROM PTMAIN M
INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)
WHERE 1=2
GROUP BY M.PARTY_NM,AC.S_TAX

DECLARE @STAX_ITEM BIT
SET @STAX_ITEM=0
SELECT @STAX_ITEM=STAX_ITEM FROM #LCODE WHERE ENTRY_TY='PT'
IF @STAX_ITEM=0 
BEGIN
INSERT INTO #TEMP 
select PER=0,VATONAMT=SUM(round(((M.gro_amt+M.tot_add+M.tot_tax)-M.tot_deduc),2))
,TAXAMT=SUM(M.TAXAMT),NET_AMT=SUM(M.NET_AMT),EXPAMT=CAST(0 AS DECIMAL(12,2)),M.PARTY_NM,AC.S_TAX
FROM PTMAIN M
INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)
WHERE M.TAX_NAME LIKE '%VAT%' AND AC.st_type IN ('LOCAL') AND  aC.s_tax<>' ' AND M.ENTRY_TY='PT' and (m.DATE BETWEEN @SDATE AND @EDATE)
GROUP BY M.PARTY_NM,AC.S_TAX
UNION ALL
select PER=0,VATONAMT=-SUM(round(((M.gro_amt+M.tot_add+M.tot_tax)-M.tot_deduc),2))
,TAXAMT=-SUM(M.TAXAMT),NET_AMT=-SUM(M.NET_AMT),EXPAMT=CAST(0 AS DECIMAL(12,2)),M.PARTY_NM,AC.S_TAX
FROM PRMAIN M
INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)
WHERE M.TAX_NAME LIKE '%VAT%'  AND AC.st_type IN ('LOCAL') AND  aC.s_tax<>' ' AND M.ENTRY_TY='PR' and (m.DATE BETWEEN @SDATE AND @EDATE)
GROUP BY M.PARTY_NM,AC.S_TAX
UNION ALL
select PER=0,VATONAMT=0
,TAXAMT=0,NET_AMT=0,EXPAMT=SUM(M.NET_AMT),M.PARTY_NM,AC.S_TAX
FROM STMAIN M
INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)
WHERE M.TAX_NAME LIKE '%VAT%'  AND AC.st_type IN ('LOCAL') AND  aC.s_tax<>' ' AND M.ENTRY_TY='ST' AND AC.[GROUP]='SUNDRY CREDITORS' and (m.DATE BETWEEN @SDATE AND @EDATE)
GROUP BY M.PARTY_NM,AC.S_TAX
END
else
begin
INSERT INTO #TEMP 
select PER=0,VATONAMT=SUM(round(d.u_asseamt+D.EXAMT+D.U_CESSAMT+D.U_HCESAMT+d.tot_add+D.TOT_DEDUC,2))
,TAXAMT=SUM(D.TAXAMT),NET_AMT=SUM(D.GRO_AMT),EXPAMT=CAST(0 AS DECIMAL(12,2)),D.PARTY_NM,AC.S_TAX
FROM PTITEM D
INNER JOIN AC_MAST AC ON (D.AC_ID=AC.AC_ID)
WHERE D.TAX_NAME LIKE '%VAT%' AND AC.st_type IN ('LOCAL') AND  aC.s_tax<>' ' AND D.ENTRY_TY='PT' and (d.DATE BETWEEN @SDATE AND @EDATE)
GROUP BY D.PARTY_NM,AC.S_TAX
UNION ALL
select PER=0,VATONAMT=-SUM(round((d.QTY*D.RATE)+D.EXAMT+D.U_CESSAMT+D.U_HCESAMT+d.tot_add+D.TOT_DEDUC,2))
,TAXAMT=-SUM(D.TAXAMT),NET_AMT=-SUM(D.GRO_AMT),EXPAMT=CAST(0 AS DECIMAL(12,2)),D.PARTY_NM,AC.S_TAX
FROM PRITEM D
INNER JOIN AC_MAST AC ON (D.AC_ID=AC.AC_ID)
WHERE D.TAX_NAME LIKE '%VAT%' AND AC.st_type IN ('LOCAL') AND  aC.s_tax<>' ' AND D.ENTRY_TY='PR' and (d.DATE BETWEEN @SDATE AND @EDATE)
GROUP BY D.PARTY_NM,AC.S_TAX
UNION ALL
select PER=0,VATONAMT=0
,TAXAMT=0,NET_AMT=0,EXPAMT=SUM(M.NET_AMT),M.PARTY_NM,AC.S_TAX
FROM STMAIN M
INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)
WHERE M.TAX_NAME LIKE '%VAT%'  AND AC.st_type IN ('LOCAL') AND  aC.s_tax<>' ' AND M.ENTRY_TY='ST' AND AC.[GROUP]='SUNDRY CREDITORS' and (M.DATE BETWEEN @SDATE AND @EDATE)
GROUP BY M.PARTY_NM,AC.S_TAX
end

Declare @vatONAMT as numeric(12,2),@TAXAMT1 as numeric(12,2),@NET_AMT as numeric(12,2),@EXPAMT as numeric(12,2),@INV_NO as varchar(15),@DATE as smalldatetime,@PARTY_NM as varchar(50),@ADDRESS as varchar(200),@ITEM as varchar(50),@FORM_NM as varchar(30),@S_TAX as varchar(30),@QTY as numeric(18,4),@STTYPE AS VARCHAR(20),@tax_name as varchar(20),@u_lrno as varchar(20),@rform_nm as varchar(15),@TYPOFCLR as varchar (10),@state as varchar(20)
SELECT @vatONAMT=0,@TAXAMT1 =0,@NET_AMT =0,@EXPAMT=0,@INV_NO ='',@DATE ='',@PARTY_NM ='',@ADDRESS ='',@ITEM ='',@FORM_NM='',@S_TAX ='',@QTY=0,@tax_name='',@u_lrno='',@rform_nm='',@TYPOFCLR='',@state =''
Declare cur_MHFRM704J_1 Cursor for
SELECT PER,SUM(VATONAMT),SUM(TAXAMT),SUM(NET_AMT),SUM(EXPAMT),PARTY_NM,S_TAX FROM #TEMP GROUP BY PER,PARTY_NM,S_TAX--WHERE S_TAX<>' '
OPEN CUR_MHFRM704J_1
FETCH NEXT FROM CUR_MHFRM704J_1 INTO @PER,@vatONAMT,@TAXAMT,@NET_AMT,@EXPAMT,@PARTY_NM,@S_TAX
WHILE (@@FETCH_STATUS=0)
BEGIN
	SET @vatONAMT=CASE WHEN @vatONAMT IS NULL THEN 0 ELSE @vatONAMT END
	SET @TAXAMT1=CASE WHEN @TAXAMT1 IS NULL THEN 0 ELSE @TAXAMT1 END
	SET @NET_AMT=CASE WHEN @NET_AMT IS NULL THEN 0 ELSE @NET_AMT END
	SET @EXPAMT=CASE WHEN @EXPAMT IS NULL THEN 0 ELSE @EXPAMT END
	SET @PARTY_NM=CASE WHEN @PARTY_NM IS NULL THEN '' ELSE @PARTY_NM END
	
	SET @S_TAX=CASE WHEN @S_TAX IS NULL THEN '' ELSE @S_TAX END
	
	INSERT INTO #MHFRM704J_2 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,AMT4,PARTY_NM,S_TAX)
                 VALUES (1,'1','A',@PER,@vatONAMT,@TAXAMT,@NET_AMT,@EXPAMT,@PARTY_NM,@S_TAX)
	
	SET @CHAR=@CHAR+1
	FETCH NEXT FROM CUR_MHFRM704J_1 INTO @PER,@vatONAMT,@TAXAMT,@NET_AMT,@EXPAMT,@PARTY_NM,@S_TAX
END
CLOSE CUR_MHFRM704J_1
DEALLOCATE CUR_MHFRM704J_1
drop table #temp
Update #MHFRM704J_2 set  PART = isnull(Part,0) , Partsr = isnull(PARTSR,''), SRNO = isnull(SRNO,''),
		             RATE = isnull(RATE,0), AMT1 = isnull(AMT1,0), AMT2 = isnull(AMT2,0), 
					 AMT3 = isnull(AMT3,0),
					 PARTY_NM = isnull(Party_nm,''),
					 FORM_NM = isnull(form_nm,''), S_TAX = isnull(S_tax,'')

SELECT SRNO=ROW_NUMBER() OVER (ORDER BY AMT2 DESC),S_TAX,AMT1,AMT2,AMT3 FROM #MHFRM704J_2 order by AMT2 DESC

End
