If Exists(Select [name] From SysObjects Where xtype='P' and [Name]='USP_REP_TG_FORM_VAT225')
Begin
	Drop Procedure USP_REP_TG_FORM_VAT225
End
GO
-- =============================================  
-- Author:		Guarav Tanna
-- Create date: 10/10/2014	for BUG-23935 (Initially created same as AP VAT)
-- Description:	This Stored procedure is useful to generate TG VAT FORM 225.
-- Remark:  
-- Modify by  : Sumit Gavate
-- Remark	  : Modify for Bug no - 27971
-- Modify date: 20/04/2015
-- =============================================  
CREATE Procedure [dbo].[USP_REP_TG_FORM_VAT225]  
@TMPAC NVARCHAR(50),@TMPIT NVARCHAR(50),@SPLCOND VARCHAR(8000),@SDATE SMALLDATETIME,@EDATE SMALLDATETIME  
,@SAC AS VARCHAR(60),@EAC AS VARCHAR(60)  
,@SIT AS VARCHAR(60),@EIT AS VARCHAR(60)  
,@SAMT FLOAT,@EAMT FLOAT  
,@SDEPT AS VARCHAR(60),@EDEPT AS VARCHAR(60)  
,@SCATE AS VARCHAR(60),@ECATE AS VARCHAR(60)  
,@SWARE AS VARCHAR(60),@EWARE AS VARCHAR(60)  
,@SINV_SR AS VARCHAR(60),@EINV_SR AS VARCHAR(60)  
,@LYN VARCHAR(20)  
,@EXPARA  AS VARCHAR(60)= null  
AS  
BEGIN  
Declare @FCON as NVARCHAR(2000),@VSAMT DECIMAL(14,2),@VEAMT DECIMAL(14,2)  
EXECUTE   USP_REP_FILTCON   
@VTMPAC =@TMPAC,@VTMPIT =@TMPIT,@VSPLCOND =@SPLCOND  
,@VSDATE=NULL  
,@VEDATE=@EDATE  
,@VSAC =@SAC,@VEAC =@EAC  
,@VSIT=@SIT,@VEIT=@EIT  
,@VSAMT=@SAMT,@VEAMT=@EAMT  
,@VSDEPT=@SDEPT,@VEDEPT=@EDEPT  
,@VSCATE =@SCATE,@VECATE =@ECATE  
,@VSWARE =@SWARE,@VEWARE  =@EWARE  
,@VSINV_SR =@SINV_SR,@VEINV_SR =@SINV_SR  
,@VMAINFILE='M',@VITFILE=NULL,@VACFILE=NULL  
,@VDTFLD ='DATE'  
,@VLYN=NULL  
,@VEXPARA=@EXPARA  
,@VFCON =@FCON OUTPUT  
  
DECLARE @SQLCOMMAND NVARCHAR(4000)  
DECLARE @RATE NUMERIC(12,2),@AMTA1 NUMERIC(12,2),@AMTB1 NUMERIC(12,2),@AMTC1 NUMERIC(12,2),@AMTD1 NUMERIC(12,2),@AMTE1 NUMERIC(12,2),@AMTF1 NUMERIC(12,2),@AMTG1 NUMERIC(12,2),@AMTH1 NUMERIC(12,2),@AMTI1 NUMERIC(12,2),@AMTJ1 NUMERIC(12,2),@AMTK1 NUMERIC(12,2),@AMTL1 NUMERIC(12,2),@AMTM1 NUMERIC(12,2),@AMTN1 NUMERIC(12,2),@AMTO1 NUMERIC(12,2)  
DECLARE @AMTA2 NUMERIC(12,2),@AMTB2 NUMERIC(12,2),@AMTC2 NUMERIC(12,2),@AMTD2 NUMERIC(12,2),@AMTE2 NUMERIC(12,2),@AMTF2 NUMERIC(12,2),@AMTG2 NUMERIC(12,2),@AMTH2 NUMERIC(12,2),@AMTI2 NUMERIC(12,2),@AMTJ2 NUMERIC(12,2),@AMTK2 NUMERIC(12,2),@AMTL2 NUMERIC(12,2),@AMTM2 NUMERIC(12,2),@AMTN2 NUMERIC(12,2),@AMTO2 NUMERIC(12,2)  
DECLARE @PER NUMERIC(12,2),@TAXAMT NUMERIC(12,2),@CHAR INT,@LEVEL NUMERIC(12,2)  
  
SELECT DISTINCT AC_NAME=SUBSTRING(AC_NAME1,2,CHARINDEX('"',SUBSTRING(AC_NAME1,2,100))-1) INTO #VATAC_MAST FROM STAX_MAS WHERE AC_NAME1 NOT IN ('"SALES"','"PURCHASES"') AND ISNULL(AC_NAME1,'')<>''
INSERT INTO #VATAC_MAST SELECT DISTINCT AC_NAME=SUBSTRING(AC_NAME1,2,CHARINDEX('"',SUBSTRING(AC_NAME1,2,100))-1) FROM STAX_MAS WHERE AC_NAME1 NOT IN ('"SALES"','"PURCHASES"') AND ISNULL(AC_NAME1,'')<>''
 

Declare @NetEff as numeric (12,2), @NetTax as numeric (12,2)

----Temporary Cursor1
-- bug-23933 - start here
/*
SELECT BHENT='PT',M.INV_NO,M.Date,A.AC_NAME,A.AMT_TY,STM.TAX_NAME,SET_APP=ISNULL(SET_APP,0),STM.ST_TYPE,M.NET_AMT,M.GRO_AMT,TAXONAMT=M.GRO_AMT+M.TOT_DEDUC+M.TOT_TAX+M.TOT_EXAMT+M.TOT_ADD,PER=STM.LEVEL1,MTAXAMT=M.TAXAMT,TAXAMT=A.AMOUNT,STM.FORM_NM,PARTY_NM=AC1.AC_NAME,AC1.S_TAX,M.U_IMPORM
,ADDRESS=LTRIM(AC1.ADD1)+ ' ' + LTRIM(AC1.ADD2) + ' ' + LTRIM(AC1.ADD3),M.TRAN_CD,VATONAMT=99999999999.99,Dbname=space(20),ItemType=space(1),It_code=999999999999999999-999999999999999999,ItSerial=Space(5)
INTO #formvat_200_A
FROM PTACDET A 
INNER JOIN PTMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)
INNER JOIN STAX_MAS STM ON (M.TAX_NAME=STM.TAX_NAME)
INNER JOIN AC_MAST AC ON (A.AC_NAME=AC.AC_NAME)
INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID)
WHERE 1=2 --A.AC_NAME IN ( SELECT AC_NAME FROM #VATAC_MAST)

alter table #formvat_200_A add recno int identity
*/
-- bug-23933 - end here

---Temporary Cursor2
-- Bug no - 27971 - Start
SELECT PART=3,PARTSR='AAA',SRNO='AAA',RATE=99999999.999,AMT1=NET_AMT,AMT2=M.TAXAMT,AMT3=M.TAXAMT,M.INV_NO,M.DATE,PARTY_NM=AC1.AC_NAME,
ADDRESS=Ltrim(AC1.Add1)+' '+Ltrim(AC1.Add2)+' '+Ltrim(AC1.Add3),STM.FORM_NM,AC1.S_TAX,Item=space(50) INTO #formvat_200 FROM PTACDET A 
INNER JOIN STMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD) INNER JOIN STAX_MAS STM ON (M.TAX_NAME=STM.TAX_NAME)
INNER JOIN AC_MAST AC ON (A.AC_NAME=AC.AC_NAME) INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID) WHERE 1=2
-- Bug no - 27971 - End

Declare @MultiCo	VarChar(3)
Declare @MCON as NVARCHAR(2000)
IF Exists(Select A.ID From SysObjects A Inner Join SysColumns B On(A.ID = B.ID) Where A.[Name] = 'STMAIN' And B.[Name] = 'DBNAME')
	Begin	------Fetch Records from Multi Co. Data
		 Set @MultiCo = 'YES'
		 EXECUTE USP_REP_MULTI_CO_DATA
		  @TMPAC, @TMPIT, @SPLCOND, @SDATE, @EDATE
		 ,@SAC, @EAC, @SIT, @EIT, @SAMT, @EAMT
		 ,@SDEPT, @EDEPT, @SCATE, @ECATE,@SWARE
		 ,@EWARE, @SINV_SR, @EINV_SR, @LYN, @EXPARA
		 ,@MFCON = @MCON OUTPUT

		-- bug-23933 - start here 
		--SET @SQLCOMMAND='Select * from '+@MCON
		---EXECUTE SP_EXECUTESQL @SQLCOMMAND
		SET @SQLCOMMAND='Insert InTo VATTBL Select * from '+@MCON
		-- bug-23933 - end here
		EXECUTE SP_EXECUTESQL @SQLCOMMAND
		---Drop Temp Table 
		SET @SQLCOMMAND='Drop Table '+@MCON
		EXECUTE SP_EXECUTESQL @SQLCOMMAND
	End
else
	Begin ------Fetch Single Co. Data
		 Set @MultiCo = 'NO'
		 -- bug-23933 - start here 
		 --EXECUTE USP_REP_SINGLE_CO_DATA
		 EXECUTE USP_REP_SINGLE_CO_DATA_VAT
		  @TMPAC, @TMPIT, @SPLCOND, @SDATE, @EDATE
		 ,@SAC, @EAC, @SIT, @EIT, @SAMT, @EAMT
		 ,@SDEPT, @EDEPT, @SCATE, @ECATE,@SWARE
		 ,@EWARE, @SINV_SR, @EINV_SR, @LYN, @EXPARA
		 ,@MFCON = @MCON OUTPUT

		/*
		--SET @SQLCOMMAND='Select * from '+@MCON
		---EXECUTE SP_EXECUTESQL @SQLCOMMAND
		SET @SQLCOMMAND='Insert InTo  #formvat_200_A Select * from '+@MCON
		EXECUTE SP_EXECUTESQL @SQLCOMMAND
		---Drop Temp Table 
		SET @SQLCOMMAND='Drop Table '+@MCON
		EXECUTE SP_EXECUTESQL @SQLCOMMAND
		*/
		-- bug-23933 - end here 
	End
-----
-----SELECT * from #form221_1 where (Date Between @Sdate and @Edate) and Bhent in('EP','PT','CN') and TAX_NAME In('','NO-TAX') and U_imporm = ''
-----
  
Declare @TAXONAMT as numeric(12,2),@TAXAMT1 as numeric(12,2),@ITEMAMT as numeric(12,2),@INV_NO as varchar(10),
	    @DATE as smalldatetime,@PARTY_NM as varchar(50),@ADDRESS as varchar(100),
		@FORM_NM as varchar(30),@S_TAX as varchar(30),@ITEM as varchar(100)



SELECT @TAXONAMT=0,@TAXAMT =0,@ITEMAMT =0,@INV_NO ='',@DATE ='',@PARTY_NM ='',@ADDRESS ='',@FORM_NM='',@S_TAX ='',@ITEM=''

SET @CHAR=66

SET @PER = 0
-- Bug no - 27971 - Start
INSERT INTO #FORMVAT_200(PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,INV_NO,DATE,PARTY_NM,ADDRESS,FORM_NM,S_TAX,ITEM)
select 1,'1','A',0,ISNULL(SUM(A.Net_Amt),0),ISNULL(SUM(A.taxamt),0),ISNULL(SUM(A.Gro_amt),0),ISNULL(A.inv_no,''),ISNULL(A.Date,''),
ISNULL(A.ac_name,''),Address='',ISNULL(A.Form_nm,''),ISNULL(A.S_tax,''),ISNULL(b.it_name,'')
from vattbl A Inner Join IT_MAST B on a.It_code = B.It_code where A.BHENT = 'PT' And A.Date Between @sdate and @edate
And A.S_tax <> '' GROUP BY A.ac_name,A.S_tax,A.Inv_No,A.Date,b.it_name,A.Form_nm
Order by A.ac_name,A.S_tax,A.Inv_No,A.Date,b.it_name

--declare Cur_VatPay cursor  for
--select Distinct A.Net_Amt,A.taxamt,A.Gro_amt,A.inv_no,A.Date,A.Party_nm,Address='',A.Form_nm,A.S_tax,b.item

-- bug-23933 - start here 
/*
select Distinct A.Net_Amt,A.taxamt,A.Gro_amt,A.inv_no,A.Date,A.ac_name,Address='',A.Form_nm,A.S_tax,b.item
--from #formvat_200_A A 
from vattbl A
Inner Join litem_vw B on a.bhent = b.entry_ty and a.tran_cd = b.tran_cd
where A.BHENT = 'PT' And A.Date Between @sdate and @edate
Order by A.Inv_No
*/
-- bug-23933 - end here 

--open Cur_VatPay
--FETCH NEXT FROM Cur_VatPay INTO @TAXONAMT,@TAXAMT,@ITEMAMT,@INV_NO,@DATE,@PARTY_NM,@ADDRESS,@FORM_NM,@S_TAX,@ITEM
-- WHILE (@@FETCH_STATUS=0)
-- BEGIN

--	SET @Per=CASE WHEN @Per IS NULL THEN 0 ELSE @Per END
--	SET @TAXONAMT=CASE WHEN @TAXONAMT IS NULL THEN 0 ELSE @TAXONAMT END
--	SET @TAXAMT=CASE WHEN @TAXAMT IS NULL THEN 0 ELSE @TAXAMT END
--	SET @ITEMAMT=CASE WHEN @ITEMAMT IS NULL THEN 0 ELSE @ITEMAMT END
--	SET @PARTY_NM=CASE WHEN @PARTY_NM IS NULL THEN '' ELSE @PARTY_NM END
--	SET @INV_NO=CASE WHEN @INV_NO IS NULL THEN '' ELSE @INV_NO END
--	SET @DATE=CASE WHEN @DATE IS NULL THEN '' ELSE @DATE END
--	SET @ADDRESS=CASE WHEN @ADDRESS IS NULL THEN '' ELSE @ADDRESS END
--	SET @S_TAX=CASE WHEN @S_TAX IS NULL THEN '' ELSE @S_TAX END
--	SET @FORM_NM=CASE WHEN @FORM_NM IS NULL THEN '' ELSE @FORM_NM END
--	SET @ITEM=CASE WHEN @ITEM IS NULL THEN '' ELSE @ITEM END
	
--	INSERT INTO #FORMVAT_200 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,INV_NO,DATE,PARTY_NM,ADDRESS,FORM_NM,S_TAX,ITEM)
--	VALUES (1,'1',CHAR(@CHAR),@PER,@TAXONAMT,@TAXAMT,@ITEMAMT,@INV_NO,@DATE,@PARTY_NM,@ADDRESS,@FORM_NM,@S_TAX,@ITEM)

-- SET @CHAR=@CHAR+1
-- FETCH NEXT FROM CUR_VatPay INTO @TAXONAMT,@TAXAMT,@ITEMAMT,@INV_NO,@DATE,@PARTY_NM,@ADDRESS,@FORM_NM,@S_TAX,@ITEM
--END


--CLOSE CUR_VatPay
--DEALLOCATE CUR_VatPay
-- Bug no - 27971 - End
----

SELECT * FROM #FORMVAT_200 order by cast(substring(partsr,1,case when (isnumeric(substring(partsr,1,2))=1) then 2 else 1 end) as int)  
  
END  
--Print 'AP VAT FORM 225'
