IF EXISTS (SELECT XTYPE, NAME FROM SYSOBJECTS WHERE XTYPE = 'P' AND NAME = 'USP_REP_HR_FORMLS8')
BEGIN
	DROP PROCEDURE USP_REP_HR_FORMLS8
END
GO
set ANSI_NULLS ON
GO
set QUOTED_IDENTIFIER ON
go

/*
EXECUTE USP_REP_HR_FORMLS8'','','','04/01/2010','03/31/2017','','','','',0,0,'','','','','','','','','2010-2011',''
*/

-- =============================================
-- Author:		Hetal L Patel
-- Create date: 16/05/2007
-- Description:	This Stored procedure is useful to generate HR VAT FORM LS 08
-- Modify date: 16/05/2007
-- Modified By: Sandeep Shah
-- Modify date: 18/01/2011
-- Remark:    : Store procedure update for TKT-5091
-- Modified By: GAURAV R. TANNA for the Bug-
-- Modify date: 01/06/2015
-- =============================================
--- added by suraj kumawat date on 31-08-2016 for this report only for Trading company it not should be mfg company 
IF Not EXISTS(select XTYPE,NAME from sysobjects where xtype='U' and name ='LITEMALL')
BEGIN
	delete FROM R_STATUS WHERE [group]='FORMR1AL' AND  [desc]='Form LS - 8' AND  [rep_nm]= 'HRFORMLS8' 
	print 'yes'
END 
Go
------
Create  PROCEDURE [dbo].[USP_REP_HR_FORMLS8]
@TMPAC NVARCHAR(50),@TMPIT NVARCHAR(50),@SPLCOND VARCHAR(8000),@SDATE  SMALLDATETIME,@EDATE SMALLDATETIME
,@SAC AS VARCHAR(60),@EAC AS VARCHAR(60)
,@SIT AS VARCHAR(60),@EIT AS VARCHAR(60)
,@SAMT FLOAT,@EAMT FLOAT
,@SDEPT AS VARCHAR(60),@EDEPT AS VARCHAR(60)
,@SCATE AS VARCHAR(60),@ECATE AS VARCHAR(60)
,@SWARE AS VARCHAR(60),@EWARE AS VARCHAR(60)
,@SINV_SR AS VARCHAR(60),@EINV_SR AS VARCHAR(60)
,@LYN VARCHAR(20)
,@EXPARA  AS VARCHAR(60)= NULL
AS

BEGIN
DECLARE @FCON AS NVARCHAR(2000)
EXECUTE   USP_REP_FILTCON 

@VTMPAC =@TMPAC,@VTMPIT =@TMPIT,@VSPLCOND =@SPLCOND
,@VSDATE=NULL,@VEDATE=@EDATE
,@VSAC =@SAC,@VEAC =@EAC
,@VSIT=@SIT,@VEIT=@EIT
,@VSAMT=@SAMT,@VEAMT=@EAMT
,@VSDEPT=@SDEPT,@VEDEPT=@EDEPT
,@VSCATE =@SCATE,@VECATE =@ECATE
,@VSWARE =@SWARE,@VEWARE  =@EWARE
,@VSINV_SR =@SINV_SR,@VEINV_SR =@SINV_SR
,@VMAINFILE='M',@VITFILE=Null,@VACFILE='AC'
,@VDTFLD ='DATE'
,@VLYN=Null
,@VEXPARA=@EXPARA
,@VFCON =@FCON OUTPUT

DECLARE @SQLCOMMAND NVARCHAR(4000), @MCON as NVARCHAR(2000)

---Temporary Cursor
SELECT PART=3,PARTSR='AAA',SRNO='AAA',I.ITEM,I.QTY,AMT1=NET_AMT,AMT2=M.TAXAMT,AMT3=M.TAXAMT,AMT4=M.TAXAMT,AMT5=M.TAXAMT
INTO #FORMLS8
FROM STACDET A 
INNER JOIN STMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)
INNER JOIN STITEM I ON (M.ENTRY_TY=I.ENTRY_TY AND M.TRAN_CD=M.TRAN_CD)
INNER JOIN STAX_MAS STM ON (M.TAX_NAME=STM.TAX_NAME)
INNER JOIN AC_MAST AC ON (A.AC_NAME=AC.AC_NAME)
INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID)
WHERE 1=2

Declare @MultiCo	VarChar(3)

Begin ------Fetch Single Co. Data
	 Set @MultiCo = 'NO'
	 --Changed by GAURAV R. TANNA for the Bug - start
	 --EXECUTE USP_REP_SINGLE_CO_DATA
	 EXECUTE USP_REP_SINGLE_CO_DATA_VAT
	  --CHanged by GAURAV R. TANNA for the Bug - End
	  @TMPAC, @TMPIT, @SPLCOND, @SDATE, @EDATE
	 ,@SAC, @EAC, @SIT, @EIT, @SAMT, @EAMT
	 ,@SDEPT, @EDEPT, @SCATE, @ECATE,@SWARE
	 ,@EWARE, @SINV_SR, @EINV_SR, @LYN, @EXPARA
	 ,@MFCON = @MCON OUTPUT

	 INSERT INTO #FORMLS8 (PART,PARTSR,SRNO,ITEM,QTY,AMT1,AMT2,AMT3,AMT4,AMT5)
	 SELECT  1 AS PART ,'1' AS PARTSR ,'A' AS SRNO, IT_NAME = case when cast(it.it_desc as varchar(250)) = '' then it.it_name else cast(it.it_desc as varchar(250))end , B.QTY, A.GRO_AMT as AMT1
	 ,AMT2= CASE WHEN PT.ST_TYPE IN('','local') then pt.gro_amt else 0 end
	 ,AMT3=CASE WHEN PT.ST_TYPE ='OUT OF STATE' then pt.gro_amt else 0 end
	 ,AMT4=CASE WHEN PT.ST_TYPE NOT IN('','local','OUT OF STATE') then pt.gro_amt else 0 end
	 ,AMT5=CASE WHEN PT.ST_TYPE IN('','local') then pt.TAXAMT else 0 end
	 FROM  VATTBL A  INNER JOIN STITEM B ON (A.BHENT =B.entry_ty AND A.TRAN_CD =B.Tran_cd AND A.ItSerial =B.itserial)
	 INNER JOIN IT_MAST IT ON (A.It_code =IT.It_code)
	 INNER JOIN STITREF STITF  ON (A.BHENT = STITF.entry_ty AND A.ItSerial =STITF.Itserial AND A.TRAN_CD =STITF.TRAN_CD)
	 INNER JOIN VATTBL PT ON (STITF.Rentry_ty = PT.BHENT AND STITF.RItSerial =PT.Itserial AND STITF.Itref_tran =PT.TRAN_CD)
	 WHERE A.BHENT='ST' AND A.U_IMPORM IN('Branch Transfer','Consignment Transfer') and ( a.Date between @SDATE and @EDATE )
			 
	 --SELECT  1,'1','A', I.IT_NAME, QTY = C.QTY, TAXONAMT=(C.GRO_AMT-(C.TAXAMT+C.TOT_NONTAX))
	 --,AMT2=CASE WHEN SAC.ST_TYPE = 'LOCAL' AND SAC.S_TAX <> '' THEN (((B.GRO_AMT-(B.TAXAMT+B.TOT_NONTAX)) * C.QTY)/B.QTY ) ELSE 0 END
	 --,AMT3=CASE WHEN SAC.ST_TYPE = 'OUT OF STATE' AND ISNULL(ST.FORM_NM,'') in ('C', 'C FORM', 'FORM C', 'C-FORM', 'FORM-C') THEN (((B.GRO_AMT-(B.TAXAMT+B.TOT_NONTAX)) * C.QTY)/B.QTY ) ELSE 0 END
	 --,AMT4=CASE WHEN (SAC.ST_TYPE <> 'LOCAL' AND ISNULL(ST.FORM_NM,'') not in ('C', 'C FORM', 'FORM C', 'C-FORM', 'FORM-C')) THEN (((B.GRO_AMT-(B.TAXAMT+B.TOT_NONTAX)) * C.QTY)/B.QTY ) ELSE 0 END
	 --,AMT5=((B.TAXAMT * C.QTY)/B.QTY )
	 --FROM  SSITEM C
	 --LEFT JOIN LITEMALL LL ON LL.ENTRY_TY=C.ENTRY_TY AND LL.TRAN_CD=C.TRAN_CD AND LL.ITSERIAL=C.ITSERIAL 
	 --LEFT JOIN ARITEM B ON LL.PENTRY_TY=B.ENTRY_TY AND LL.PTRAN_CD=B.TRAN_CD AND LL.PITSERIAL=B.ITSERIAL 
	 --LEFT JOIN STAX_MAS ST ON (ST.TAX_NAME = B.TAX_NAME AND ST.ENTRY_TY = B.ENTRY_TY)
	 --LEFT JOIN ARMAIN H ON H.ENTRY_TY=B.ENTRY_TY AND H.TRAN_CD=B.TRAN_CD  
	 --LEFT JOIN IT_MAST I ON I.IT_CODE = C.IT_CODE
	 --LEFT JOIN AC_MAST SAC ON SAC.AC_id =B.ac_id
	 --LEFT JOIN AC_MAST PAC ON PAC.ac_id =C.ac_id
	 --WHERE C.ENTRY_TY='SS' AND (C.DATE BETWEEN @SDATE AND @EDATE) 

		--Put in remarks by GAURAV R. TANNA for the Bug - start
		------SET @SQLCOMMAND='Select * from '+@MCON
		-------EXECUTE SP_EXECUTESQL @SQLCOMMAND
		----SET @SQLCOMMAND='Insert InTo #FORM_LS5 Select * from '+@MCON
		----EXECUTE SP_EXECUTESQL @SQLCOMMAND
		-------Drop Temp Table 
		----SET @SQLCOMMAND='Drop Table '+@MCON
		----EXECUTE SP_EXECUTESQL @SQLCOMMAND

		----Declare cur_formls5aa cursor for
		----SELECT A.PER,A.TAXONAMT,B.TAXAMT,ITEMAMT=B.GRO_AMT,A.INV_NO,A.DATE,A.PARTY_NM,A.ADDRESS,B.ITEM,FORM_NM=FORM_NO,A.S_TAX,B.QTY
		----FROM #FORM_LS5 A
		----Inner Join LITEM_VW B On (A.BHENT = B.ENTRY_TY AND A.TRAN_CD = B.TRAN_CD AND A.ITSERIAL=B.ITSERIAL)
		----inner join PTITEM C ON (C.ENTRY_TY =B.ENTRY_TY AND C.TRAN_CD=B.TRAN_CD AND C.ITSERIAL=B.ITSERIAL)
		----inner join PTMAIN D ON (D.ENTRY_TY =C.ENTRY_tY AND D.TRAN_CD=C.TRAN_CD )
		----WHERE A.ST_TYPE='OUT OF STATE' AND A.PER<>0 AND A.BHENT IN ('PT','P1') AND (A.DATE BETWEEN @SDATE AND @EDATE)
		--Put in remarks by GAURAV R. TANNA for the Bug - end
		
End

Update #formLS8 set  PART = isnull(Part,0) , Partsr = isnull(PARTSR,''), SRNO = isnull(SRNO,''),
		             ITEM = isnull(ITEM,''), QTY=ISNULL(QTY,0), AMT1 = isnull(AMT1,0), AMT2 = isnull(AMT2,0), 
					 AMT3 = isnull(AMT3,0), AMT4 = isnull(AMT4,0), AMT5 = isnull(AMT5,0)
					 
SELECT * FROM #FORMLS8 order by cast(substring(partsr,1,case when (isnumeric(substring(partsr,1,2))=1) then 2 else 1 end) as int)
END
--Print 'HR VAT FORM LS 08'