If Exists(Select [name] From SysObjects Where xType='P' and [Name]='USP_REP_SINGLE_CO_DATA_VAT')
Begin
	Drop Procedure USP_REP_SINGLE_CO_DATA_VAT
End
Go

-- =============================================
-- Author:		Pankaj M. Borse.
-- Create date: 29/03/2014
-- Description:	This Stored Procedure is useful to Fetch Single Co. Data NEIO
-- Modified By:	Gaurav - Date : 08/10/2014 - Bug - 23933
-- Modified By:	Gaurav - Date : 11/05/2015 - Bug - 26166
-- Modified By:	Suraj - Date : 21/08/2015 - Bug - 26509 I have changed into DNMAIN OR CNMAIN TABLE QUERY ADDED NEW FIELD U_GPRICE ON U_IMPORM
-- Modified By: Suraj - Date 10-02-2016 : -Bug 27603 - Need To Consider 'Ship To' Details when 'Ship To' is Selected in VAT Reports 

-- =============================================
CREATE PROCEDURE [dbo].[USP_REP_SINGLE_CO_DATA_VAT]
 @TMPAC NVARCHAR(50),@TMPIT NVARCHAR(50),@SPLCOND VARCHAR(8000),@SDATE  SMALLDATETIME,@EDATE SMALLDATETIME
 ,@SAC AS VARCHAR(60),@EAC AS VARCHAR(60)
 ,@SIT AS VARCHAR(60),@EIT AS VARCHAR(60)
 ,@SAMT FLOAT,@EAMT FLOAT
 ,@SDEPT AS VARCHAR(60),@EDEPT AS VARCHAR(60)
 ,@SCATE AS VARCHAR(60),@ECATE AS VARCHAR(60)
 ,@SWARE AS VARCHAR(60),@EWARE AS VARCHAR(60)
 ,@SINV_SR AS VARCHAR(60),@EINV_SR AS VARCHAR(60)
 ,@LYN VARCHAR(20)
 ,@EXPARA  AS VARCHAR(60)
 ,@MFCON NVARCHAR(2000) OUTPUT 
 AS
set nocount on
SET ARITHABORT OFF
SET ANSI_WARNINGS OFF
DECLARE @vatfltopt VARCHAR(25)
select @vatfltopt=vat_flt_opt from manufact
print @vatfltopt

 BEGIN

DECLARE @SQLCOMMAND NVARCHAR(4000)
Declare @NetEff as numeric (12,2), @NetTax as numeric (12,2)

SELECT ENTRY_TY,BCODE=(CASE WHEN EXT_VOU=1 THEN BCODE_NM ELSE ENTRY_TY END),STAX_ITEM  INTO #LCODE FROM LCODE
ALTER TABLE #lcode ADD  CONSTRAINT [PK_entry_ty] PRIMARY KEY CLUSTERED 
(
	[ENTRY_TY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]


Declare @Balance Numeric(17,2),@TBLNM VARCHAR(50),@TBLNAME1 Varchar(50),
        @TBLNAME2 Varchar(50) ,@TBLNAME3 Varchar(50),@TBLNAME4 Varchar(50),@TBLNAME5 Varchar(50)
 
Select @TBLNM = (SELECT substring(rtrim(ltrim(str(RAND( (DATEPART(mm, GETDATE()) * 100000 )
		+ (DATEPART(ss, GETDATE()) * 1000 )+ DATEPART(ms, GETDATE())) , 20,15))),3,20) as No),
		@Balance = 0,@SQLCOMMAND = ''

Select @TBLNAME1 =  'VATTBL'-- '##TMP1'+@TBLNM

SET @SQLCOMMAND ='TRUNCATE TABLE VATTBL'   
EXECUTE SP_EXECUTESQL @SQLCOMMAND
print  'vat11232'

IF @EXPARA like '%PT%' OR @EXPARA=''
BEGIN
print  'vat1123'
SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.DATE,Ac_Name= case when isnull(m.sac_id,0) <> 0 and isnull(ship.mailname,'''')<>'''' then ship.mailname else (case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end) end,M.AC_ID,AMT_TY='''',TAX_NAME= CASE WHEN Lc.STAX_ITEM=1 THEN ISNULL(D.TAX_NAME,'''') ELSE ISNULL(M.TAX_NAME,'''') END ,SET_APP=0,(CASE WHEN isnull(M.SAC_ID,0) <>0 THEN SHIP.ST_TYPE else AC.ST_TYPE end) as st_type ,NET_AMT=round(M.Net_amt,2),D.GRO_AMT,PER=ISNULL(STM.LEVEL1,0),TAXAMT= D.TAXAMT,ISNULL(STM.FORM_NM,''''),ISNULL(STM.RFORM_NM,''''),(CASE WHEN ISNULL(M.SAC_ID,0) <>0 THEN (CASE WHEN SHIP.ST_TYPE=''LOCAL'' THEN SHIP.S_TAX ELSE SHIP.C_TAX END) ELSE (CASE WHEN AC.ST_TYPE=''LOCAL'' THEN AC.S_TAX ELSE AC.C_TAX END) END) AS S_TAX,M.U_IMPORM'-- PANKAJ
 ----SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3),M.TRAN_CD,VATONAMT = CASE WHEN Lc.STAX_ITEM=1 THEN round(d.u_asseamt+D.EXAMT+D.U_CESSAMT+D.U_HCESAMT+d.tot_add+D.TOT_DEDUC,2) else round(((M.gro_amt+M.tot_add+M.tot_tax)-M.tot_deduc),2) end,DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE'  -- changes for bug-1060,libri,bug-5315,bug-17565 - PANKAJ 
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS= ( CASE WHEN ISNULL(M.SAC_ID,0)<> 0 THEN RTRIM(SHIP.ADD1)+ '' '' + RTRIM(SHIP.ADD2) + '' '' + RTRIM(SHIP.ADD3) ELSE RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3) END) ,M.TRAN_CD,VATONAMT = CASE WHEN Lc.STAX_ITEM=1 THEN round(d.u_asseamt+D.EXAMT+D.U_CESSAMT+D.U_HCESAMT+d.tot_add+D.TOT_DEDUC,2) else round(((M.gro_amt+M.tot_add+M.tot_tax)-M.tot_deduc),2) end,DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE' -- -Bug 27603
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+'  FROM PTMAIN M '
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN PTITEM D ON (M.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD )'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT OUTER JOIN STAX_MAS STM ON (D.TAX_NAME=STM.TAX_NAME And STM.Entry_ty = D.Entry_ty)' -- ADDED PANKAJ
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT JOIN SHIPTO SHIP ON (SHIP.SHIPTO_ID=M.SAC_ID)'-- Bug-24864
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN #LCODE lc  ON (lc.ENTRY_TY=D.ENTRY_TY)'-- for bug-4832 added 
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''''-- for bug-4832 added 
 PRINT @SQLCOMMAND
 EXECUTE SP_EXECUTESQL @SQLCOMMAND
 END
 --SET @SQLCOMMAND='SELECT * FROM '+@TBLNAME1 +''
 -- EXECUTE SP_EXECUTESQL @SQLCOMMAND

IF @EXPARA LIKE '%ST%' OR @EXPARA=''
BEGIN
SET @SQLCOMMAND=''
SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
  SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.DATE,Ac_Name=case when isnull(m.sac_id,0) <> 0 and isnull(ship.mailname,'''')<>'''' then ship.mailname else (case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end) end,M.AC_ID,AMT_TY='''',TAX_NAME= CASE WHEN Lc.STAX_ITEM=1 THEN ISNULL(D.TAX_NAME,'''') ELSE ISNULL(M.TAX_NAME,'''') END ,SET_APP=0,CASE WHEN ISNULL(M.SAC_ID,0) <>0 THEN SHIP.ST_TYPE else AC.ST_TYPE end,NET_AMT=round(M.Net_amt,2),D.GRO_AMT,PER=ISNULL(STM.LEVEL1,0),TAXAMT= D.TAXAMT,ISNULL(STM.FORM_NM,''''),ISNULL(STM.RFORM_NM,''''),CASE WHEN M.SAC_ID <>0 THEN (CASE WHEN SHIP.ST_TYPE=''LOCAL'' THEN SHIP.S_TAX ELSE SHIP.C_TAX END) ELSE (CASE WHEN AC.ST_TYPE=''LOCAL'' THEN AC.S_TAX ELSE AC.C_TAX END) END as S_TAX,M.U_IMPORM'-- PANKAJ
  --SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3),M.TRAN_CD,VATONAMT = CASE WHEN Lc.STAX_ITEM=1 THEN round(d.u_asseamt+D.EXAMT+D.U_CESSAMT+D.U_HCESAMT+d.tot_add+D.TOT_DEDUC,2) else round(((M.gro_amt+M.tot_add+M.tot_tax)-M.tot_deduc),2) end,DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE'  --changes for bug-1060,libri,bug-5315,bug-17565 - PANKAJ
   SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=( CASE WHEN ISNULL(M.SAC_ID,0)<> 0 THEN RTRIM(SHIP.ADD1)+ '' '' + RTRIM(SHIP.ADD2) + '' '' + RTRIM(SHIP.ADD3) ELSE RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3) END),M.TRAN_CD,VATONAMT = CASE WHEN Lc.STAX_ITEM=1 THEN round(d.u_asseamt+D.EXAMT+D.U_CESSAMT+D.U_HCESAMT+d.tot_add+D.TOT_DEDUC,2) else round(((M.gro_amt+M.tot_add+M.tot_tax)-M.tot_deduc),2) end,DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE'  ---- -Bug 27603
  SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM STMAIN M '
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN STITEM D ON (M.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD )'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT OUTER JOIN STAX_MAS STM ON (D.TAX_NAME=STM.TAX_NAME And STM.Entry_ty = D.Entry_ty)' -- ADDED PANKAJ
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
  SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT JOIN SHIPTO SHIP ON (SHIP.SHIPTO_ID=M.SAC_ID)'-- Bug-24864
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN #LCODE lc  ON (lc.ENTRY_TY=D.ENTRY_TY)'-- for bug-4832 added 
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''''-- for bug-4832 added 
 PRINT @SQLCOMMAND
 EXECUTE SP_EXECUTESQL @SQLCOMMAND
END


-- Sales Return
IF @EXPARA LIKE '%ST%' OR @EXPARA=''
BEGIN
SET @SQLCOMMAND=''
SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.DATE,Ac_Name=case when isnull(m.sac_id,0) <> 0 and isnull(ship.mailname,'''')<>'''' then ship.mailname else (case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end) end,M.AC_ID,AMT_TY='''',TAX_NAME= CASE WHEN Lc.STAX_ITEM=1 THEN ISNULL(D.TAX_NAME,'''') ELSE ISNULL(M.TAX_NAME,'''') END ,SET_APP=0,(CASE WHEN ISNULL(M.SAC_ID,0) <>0 THEN SHIP.ST_TYPE else AC.ST_TYPE end) AS ST_TYPE,NET_AMT=round(M.Net_amt,2),D.GRO_AMT,PER=ISNULL(STM.LEVEL1,0),TAXAMT= D.TAXAMT,ISNULL(STM.FORM_NM,''''),ISNULL(STM.RFORM_NM,''''),CASE WHEN M.SAC_ID <>0 THEN (CASE WHEN SHIP.ST_TYPE=''LOCAL'' THEN SHIP.S_TAX ELSE SHIP.C_TAX END) ELSE (CASE WHEN AC.ST_TYPE=''LOCAL'' THEN AC.S_TAX ELSE AC.C_TAX END) END as S_TAX,U_IMPORM=M.U_IMPORM'-- PANKAJ
---SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3),M.TRAN_CD,VATONAMT = CASE WHEN Lc.STAX_ITEM=1 THEN round(d.u_asseamt+D.EXAMT+D.U_CESSAMT+D.U_HCESAMT+d.tot_add+D.TOT_DEDUC,2) else round(((M.gro_amt+M.tot_add+M.tot_tax)-M.tot_deduc),2) end,DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE'  --changes for bug-1060,libri,bug-5315,bug-17565 - PANKAJ
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=( CASE WHEN ISNULL(M.SAC_ID,0)<> 0 THEN RTRIM(SHIP.ADD1)+ '' '' + RTRIM(SHIP.ADD2) + '' '' + RTRIM(SHIP.ADD3) ELSE RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3) END),M.TRAN_CD,VATONAMT = CASE WHEN Lc.STAX_ITEM=1 THEN round(d.u_asseamt+D.EXAMT+D.U_CESSAMT+D.U_HCESAMT+d.tot_add+D.TOT_DEDUC,2) else round(((M.gro_amt+M.tot_add+M.tot_tax)-M.tot_deduc),2) end,DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE'  ---- -Bug 27603
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+'  FROM SRMAIN M '
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN SRITEM D ON (M.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD )'
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)'
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT OUTER JOIN STAX_MAS STM ON (D.TAX_NAME=STM.TAX_NAME And STM.Entry_ty = D.Entry_ty)' -- ADDED PANKAJ
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT JOIN SHIPTO SHIP ON (SHIP.SHIPTO_ID=M.SAC_ID)'-- Bug-24864
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN #LCODE lc  ON (lc.ENTRY_TY=D.ENTRY_TY)'-- for bug-4832 added 
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''''-- for bug-4832 added 
PRINT @SQLCOMMAND
EXECUTE SP_EXECUTESQL @SQLCOMMAND
END 
 -- pURCHASE RETURN
IF @EXPARA LIKE '%PT%' OR @EXPARA=''
BEGIN 
SET @SQLCOMMAND=''
SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.DATE,Ac_Name=case when isnull(m.sac_id,0) <> 0 and isnull(ship.mailname,'''')<>'''' then ship.mailname else (case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end) end,M.AC_ID,AMT_TY='''',TAX_NAME= CASE WHEN Lc.STAX_ITEM=1 THEN ISNULL(D.TAX_NAME,'''') ELSE ISNULL(M.TAX_NAME,'''') END ,SET_APP=0,(CASE WHEN isnull(M.SAC_ID,0) <>0 THEN SHIP.ST_TYPE else AC.ST_TYPE end) as st_type,NET_AMT=round(M.Net_amt,2),D.GRO_AMT,PER=ISNULL(STM.LEVEL1,0),TAXAMT= D.TAXAMT,ISNULL(STM.FORM_NM,''''),ISNULL(STM.RFORM_NM,''''),CASE WHEN M.SAC_ID <>0 THEN (CASE WHEN SHIP.ST_TYPE=''LOCAL'' THEN SHIP.S_TAX ELSE SHIP.C_TAX END) ELSE (CASE WHEN AC.ST_TYPE=''LOCAL'' THEN AC.S_TAX ELSE AC.C_TAX END) END as S_TAX,U_IMPORM='''''-- PANKAJ
---SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3),M.TRAN_CD,VATONAMT =round((d.QTY*D.RATE)+D.EXAMT+d.tot_add+D.TOT_DEDUC,2),DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE'  --changes for bug-1060,libri,bug-5315,bug-17565 - PANKAJ
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=( CASE WHEN ISNULL(M.SAC_ID,0)<> 0 THEN RTRIM(SHIP.ADD1)+ '' '' + RTRIM(SHIP.ADD2) + '' '' + RTRIM(SHIP.ADD3) ELSE RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3) END),M.TRAN_CD,VATONAMT =round((d.QTY*D.RATE)+D.EXAMT+d.tot_add+D.TOT_DEDUC,2),DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE'  ---- -Bug 27603
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+'  FROM PRMAIN M '
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN PRITEM D ON (M.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD )'
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)'
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT OUTER JOIN STAX_MAS STM ON (D.TAX_NAME=STM.TAX_NAME And STM.Entry_ty = D.Entry_ty)' -- ADDED PANKAJ
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT JOIN SHIPTO SHIP ON (SHIP.SHIPTO_ID=M.SAC_ID)'-- Bug-24864
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN #LCODE lc  ON (lc.ENTRY_TY=D.ENTRY_TY)'-- for bug-4832 added 
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''''-- for bug-4832 added 
PRINT @SQLCOMMAND
EXECUTE SP_EXECUTESQL @SQLCOMMAND
END
 
 -- Bug-23933 - Start here - Gaurav
/*
 SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.Date,Ac_Name=case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end,M.AC_ID,A.AMT_TY,ISNULL(STM.TAX_NAME,''''),SET_APP=ISNULL(SET_APP,0),AC.ST_TYPE,NET_AMT=round(M.Net_amt,2),M.GRO_AMT,PER=ISNULL(STM.LEVEL1,0),TAXAMT=D.TAXAMT,ISNULL(STM.FORM_NM,''''),ISNULL(STM.RFORM_NM,''''),AC1.S_TAX,U_IMPORM=space(1)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC1.ADD1)+ '' '' + RTRIM(AC1.ADD2) + '' '' + RTRIM(AC1.ADD3),M.TRAN_CD,VATONAMT=round (((M.Net_amt+m.tot_fdisc-M.TAXAMT-M.TOT_NONTAX-D.TOT_NONTAX+m.tot_tax)*(D.Gro_amt))/(M.Gro_amt),2)-(m.tot_tax),DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM=case when isnull(AC1.MailName,'''') = '''' then AC1.Ac_Name else AC1.MailName end,IT.U_GVTYPE'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM EPACDET A '
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN EPMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN EPITEM D ON (M.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD)' ---And A.Amount = D.TaxAmt)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT OUTER JOIN STAX_MAS STM ON (D.TAX_NAME=STM.TAX_NAME) And STM.Entry_ty = A.Entry_ty'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (A.AC_ID=AC.AC_ID)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''''
*/
-- Bug-23933 - End here - Gaurav
IF @EXPARA LIKE '%"OTHER"%' OR @EXPARA=''
BEGIN 
print 'other expara '
SET @SQLCOMMAND=''
 SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.Date,Ac_Name=case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end,M.AC_ID,A.AMT_TY,ISNULL(STM.TAX_NAME,''''),SET_APP=ISNULL(SET_APP,0),AC.ST_TYPE,NET_AMT=round((M.Net_amt*D.Gro_amt)/M.Gro_amt,2),M.GRO_AMT,PER=ISNULL(STM.LEVEL1,0),TAXAMT=D.TAXAMT,ISNULL(STM.FORM_NM,''''),ISNULL(STM.RFORM_NM,''''),AC1.S_TAX,U_IMPORM=space(1)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC1.ADD1)+ '' '' + RTRIM(AC1.ADD2) + '' '' + RTRIM(AC1.ADD3),M.TRAN_CD,VATONAMT=round (((M.Net_amt+m.tot_fdisc-M.TAXAMT-M.TOT_NONTAX-D.TOT_NONTAX+m.tot_tax)*(D.Gro_amt))/(M.Gro_amt),2)-(m.tot_tax),DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM=case when isnull(AC1.MailName,'''') = '''' then AC1.Ac_Name else AC1.MailName end,IT.U_GVTYPE'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM SBACDET A '
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN SBMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN SBITEM D ON (M.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD)' ---And A.Amount = D.TaxAmt)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT OUTER JOIN STAX_MAS STM ON (D.TAX_NAME=STM.TAX_NAME) And STM.Entry_ty = A.Entry_ty'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (A.AC_ID=AC.AC_ID)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''''

 PRINT @SQLCOMMAND
 PRINT'SB'
 EXECUTE SP_EXECUTESQL @SQLCOMMAND
 
SET @SQLCOMMAND=''
 SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.DATE,Ac_Name=case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end,AMT_TY='' '',M.AC_ID,ISNULL(STM.TAX_NAME,''''),SET_APP=ISNULL(SET_APP,0),AC.ST_TYPE,NET_AMT=round((M.Net_amt*D.Gro_amt)/M.Gro_amt,2),M.GRO_AMT,PER=ISNULL(STM.LEVEL1,0),TAXAMT=D.TAXAMT,FORM_NM=ISNULL(STM.FORM_NM,''''),ISNULL(STM.RFORM_NM,''''),AC.S_TAX,U_IMPORM=space(1)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3),M.TRAN_CD,VATONAMT=round (((M.Net_amt+m.tot_fdisc-M.TAXAMT-M.TOT_NONTAX-D.TOT_NONTAX)*(D.Gro_amt))/M.Gro_amt,2),DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM IRMAIN M '
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IRITEM D ON (M.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD )'--  And M.TaxAmt = D.TaxAmt)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT OUTER JOIN STAX_MAS STM ON (D.TAX_NAME=STM.TAX_NAME) And STM.Entry_ty = M.Entry_ty'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
  SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''''

 EXECUTE SP_EXECUTESQL @SQLCOMMAND

 SET @SQLCOMMAND=''
 SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.DATE,Ac_Name=case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end,M.AC_ID,AMT_TY='''',TAX_NAME='''',SET_APP=0,AC.ST_TYPE,M.NET_AMT,M.GRO_AMT,PER=0,TAXAMT=M.TAXAMT,FORM_NM='''',RFORM_NM='''',AC.S_TAX,U_IMPORM=space(1)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3),M.TRAN_CD,VATONAMT=M.NET_AMT,DBNAME=space(20),ItemType=space(1),IT_CODE=999999999999999999-999999999999999999,ITSERIAL=space(5),PARTY_NM='''',VATTYPE='''''
 --SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM JVACDET A '
 --SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN JVMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)'

 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM JVMAIN M  '
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''''
 EXECUTE SP_EXECUTESQL @SQLCOMMAND

 SET @SQLCOMMAND=''
SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,DATE=M.U_CLDT,Ac_Name=case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end,M.AC_ID,AMT_TY='' '',TAX_NAME='''',SET_APP=0,AC.ST_TYPE,M.NET_AMT,M.GRO_AMT,PER=0,TAXAMT=M.TAXAMT,FORM_NM='''',RFORM_NM='''',AC.S_TAX,U_IMPORM=space(1)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3),M.TRAN_CD,VATONAMT=M.NET_AMT,DBNAME=space(20),ItemType=space(1),IT_CODE=999999999999999999-999999999999999999,ITSERIAL=space(5),PARTY_NM='''',VATTYPE='''''
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM BPMAIN M '
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''''  --ADD 'tds' by sandeep on 06/11/2013 for bug-20342
 EXECUTE SP_EXECUTESQL @SQLCOMMAND
 
 SET @SQLCOMMAND=''
SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.DATE,Ac_Name=case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end,M.AC_ID,AMT_TY='' '',ISNULL(STM.TAX_NAME,''''),SET_APP=ISNULL(STM.SET_APP,0),AC.ST_TYPE,NET_AMT=round(M.Net_amt,2),D.GRO_AMT,PER=ISNULL(STM.LEVEL1,0),TAXAMT=D.TAXAMT,ISNULL(STM.FORM_NM,''''),ISNULL(STM.RFORM_NM,''''),AC.S_TAX,U_IMPORM=space(10)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3),M.TRAN_CD,VATONAMT=CASE WHEN D.U_VATONAMT <> 0 THEN D.U_VATONAMT ELSE D.GRO_AMT END,DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM EPMAIN M '
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN EPITEM D ON (M.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD )'--And M.TaxAmt = D.TaxAmt)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT OUTER JOIN STAX_MAS STM ON (D.TAX_NAME=STM.TAX_NAME) And STM.Entry_ty = M.Entry_ty'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where (M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''')'
 EXECUTE SP_EXECUTESQL @SQLCOMMAND
 --EXECUTE SP_EXECUTESQL @SQLCOMMAND

 /*
SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.DATE,Ac_Name=case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end,AMT_TY='' '',M.AC_ID,ISNULL(M.TAX_NAME,''''),SET_APP=0,AC.ST_TYPE,M.NET_AMT,M.GRO_AMT,PER=0,TAXAMT=M.TAXAMT,FORM='' '',RFORM_NM='''',AC.S_TAX,U_IMPORM=space(10)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3),M.TRAN_CD,VATONAMT=M.NET_AMT,DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,IT.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM EPMAIN M '
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN EPITEM D ON (M.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
  SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where (M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''')'
 EXECUTE SP_EXECUTESQL @SQLCOMMAND
 */
-- SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.Date,Ac_Name=case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end,M.AC_ID,A.AMT_TY,ISNULL(STM.TAX_NAME,''''),SET_APP=ISNULL(SET_APP,0),AC.ST_TYPE,NET_AMT=round((M.Net_amt*D.Gro_amt)/M.Gro_amt,2),M.GRO_AMT,PER=ISNULL(STM.LEVEL1,0),TAXAMT=D.TAXAMT,ISNULL(STM.FORM_NM,''''),ISNULL(STM.RFORM_NM,''''),AC1.S_TAX,U_IMPORM=space(1)'
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC1.ADD1)+ '' '' + RTRIM(AC1.ADD2) + '' '' + RTRIM(AC1.ADD3),M.TRAN_CD,VATONAMT=(d.QTY*D.RATE)+D.EXAMT+d.tot_add+D.TOT_DEDUC,DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM=case when isnull(AC1.MailName,'''') = '''' then AC1.Ac_Name else AC1.MailName end,IT.U_GVTYPE'
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM DNACDET A '
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN DNMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)'
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN DNITEM D ON (M.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD)' 
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT OUTER JOIN STAX_MAS STM ON (D.TAX_NAME=STM.TAX_NAME) And STM.Entry_ty = A.Entry_ty'
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (A.AC_ID=AC.AC_ID)'
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID)'
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''''
 

-- EXECUTE SP_EXECUTESQL @SQLCOMMAND
--SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.Date,Ac_Name=case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end,M.AC_ID,A.AMT_TY,ISNULL(STM.TAX_NAME,''''),SET_APP=ISNULL(SET_APP,0),AC.ST_TYPE,NET_AMT=round((M.Net_amt*D.Gro_amt)/M.Gro_amt,2),M.GRO_AMT,PER=ISNULL(STM.LEVEL1,0),TAXAMT=D.TAXAMT,ISNULL(STM.FORM_NM,''''),ISNULL(STM.RFORM_NM,''''),AC1.S_TAX,U_IMPORM=space(1)'
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC1.ADD1)+ '' '' + RTRIM(AC1.ADD2) + '' '' + RTRIM(AC1.ADD3),M.TRAN_CD,VATONAMT=(d.QTY*D.RATE)+D.EXAMT+d.tot_add+D.TOT_DEDUC,DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM=case when isnull(AC1.MailName,'''') = '''' then AC1.Ac_Name else AC1.MailName end,IT.U_GVTYPE'
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM CNACDET A '
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN CNMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)'
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN CNITEM D ON (M.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD)' 
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT OUTER JOIN STAX_MAS STM ON (D.TAX_NAME=STM.TAX_NAME) And STM.Entry_ty = A.Entry_ty'
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (A.AC_ID=AC.AC_ID)'
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID)'
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
-- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''''
--EXECUTE SP_EXECUTESQL @SQLCOMMAND

SET @SQLCOMMAND=''
SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.DATE,Ac_Name=case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end,M.AC_ID,AMT_TY='' '',ISNULL(STM.TAX_NAME,''''),SET_APP=ISNULL(STM.SET_APP,0),AC.ST_TYPE,NET_AMT=M.Net_amt,D.GRO_AMT,PER=ISNULL(STM.LEVEL1,0),TAXAMT=D.TAXAMT,ISNULL(STM.FORM_NM,''''),ISNULL(STM.RFORM_NM,''''),AC.S_TAX,m.U_GPRICE'-- FOR BUG-26509
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3),M.TRAN_CD,VATONAMT=(d.QTY*D.RATE)+D.EXAMT+d.tot_add+D.TOT_DEDUC,DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM DNMAIN M '
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN DNITEM D ON (D.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD )'-- And M.TaxAmt = D.TaxAmt)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT OUTER JOIN STAX_MAS STM ON (D.TAX_NAME=STM.TAX_NAME) And STM.Entry_ty = D.Entry_ty'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where (M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''')'
 EXECUTE SP_EXECUTESQL @SQLCOMMAND

 SET @SQLCOMMAND=''
 SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.DATE,Ac_Name=case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end,M.AC_ID,AMT_TY='' '',ISNULL(STM.TAX_NAME,''''),SET_APP=ISNULL(STM.SET_APP,0),AC.ST_TYPE,NET_AMT=M.Net_amt,D.GRO_AMT,PER=ISNULL(STM.LEVEL1,0),TAXAMT=D.TAXAMT,ISNULL(STM.FORM_NM,''''),ISNULL(STM.RFORM_NM,''''),AC.S_TAX,m.U_GPRICE'-- FOR BUG-26509
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3),M.TRAN_CD,VATONAMT=(d.QTY*D.RATE)+D.EXAMT+d.tot_add+D.TOT_DEDUC,DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,D.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM CNMAIN M '
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN CNITEM D ON (D.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD )'-- And M.TaxAmt = D.TaxAmt)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' LEFT OUTER JOIN STAX_MAS STM ON (D.TAX_NAME=STM.TAX_NAME) And STM.Entry_ty = D.Entry_ty'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where (M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''')'
 EXECUTE SP_EXECUTESQL @SQLCOMMAND
----SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
---- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.DATE,Ac_Name=case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end,M.AC_ID,AMT_TY='' '',ISNULL(M.TAX_NAME,''''),SET_APP=0,Ac.ST_TYPE,M.NET_AMT,M.GRO_AMT,PER=0,TAXAMT=M.TAXAMT,FORM_NM='' '',RFORM_NM='''',AC.S_TAX,U_IMPORM=space(1)'
---- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3),M.TRAN_CD,VATONAMT=(d.QTY*D.RATE)+D.EXAMT+d.tot_add+D.TOT_DEDUC,DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,IT.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE'
---- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM DNMAIN M '
---- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)'
---- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN DNITEM D ON (M.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD)'
---- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
----SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where M.Tax_name = '' '' or RTRIM(M.Tax_name) = ''NO-TAX''or d.Tax_name = '' '' or RTRIM(D.Tax_name) = ''NO-TAX'' and (M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''')'
  

---- EXECUTE SP_EXECUTESQL @SQLCOMMAND

---- SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
---- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.DATE,Ac_Name=case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end,M.AC_ID,AMT_TY='' '',ISNULL(M.TAX_NAME,''''),SET_APP=0,Ac.ST_TYPE,M.NET_AMT,M.GRO_AMT,PER=0,TAXAMT=M.TAXAMT,FORM_NM='' '',RFORM_NM='''',AC.S_TAX,U_IMPORM=space(1)'
---- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3),M.TRAN_CD,VATONAMT=(d.QTY*D.RATE)+D.EXAMT+d.tot_add+D.TOT_DEDUC,DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,IT.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE'
---- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM CNMAIN M '
---- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)'
---- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN CNITEM D ON (M.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD)'
---- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
---- SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where  M.Tax_name = '' '' or RTRIM(M.Tax_name) = ''NO-TAX''or d.Tax_name = '' '' or RTRIM(D.Tax_name) = ''NO-TAX'' and (M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''')'
----print's4'
---- EXECUTE SP_EXECUTESQL @SQLCOMMAND

SET @SQLCOMMAND=''
SET @SQLCOMMAND='INSERT INTO '+@TBLNAME1 
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' SELECT M.ENTRY_TY,M.INV_NO,M.DATE,Ac_Name=case when isNull(AC.MailName,'''') = '''' then AC.Ac_Name else AC.MailName end,M.AC_ID,AMT_TY='' '',ISNULL(M.TAX_NAME,''''),SET_APP=0,Ac.ST_TYPE,M.NET_AMT,M.GRO_AMT,PER=0,TAXAMT=M.TAXAMT,FORM_NM='' '',RFORM_NM='''',AC.S_TAX,U_IMPORM=space(1)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' ,ADDRESS=RTRIM(AC.ADD1)+ '' '' + RTRIM(AC.ADD2) + '' '' + RTRIM(AC.ADD3),M.TRAN_CD,VATONAMT=M.NET_AMT,DBNAME=space(20),ItemType=case when it.vatcap=1 then ''C'' else ''I'' end,IT.IT_CODE,D.ITSERIAL,PARTY_NM='''',IT.U_GVTYPE'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' FROM OBMAIN M '
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN AC_MAST AC ON (M.AC_ID=AC.AC_ID)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN OBITEM D ON (M.ENTRY_TY=D.ENTRY_TY AND M.TRAN_CD=D.TRAN_CD)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' INNER JOIN IT_MAST IT  ON (D.IT_CODE=IT.IT_CODE)'
 SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+' where AC.Typ = ''INPUT VAT'' Or AC.Typ = ''OUTPUT VAT'' and  (M.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''')'
 EXECUTE SP_EXECUTESQL @SQLCOMMAND
END
 SET @MFCON= @TBLNAME1--Commented by Archana K. on 26/02/14 for Bug-21922
  Print @MFCON 
 END
set ANSI_NULLS OFF

