If Exists(Select [name] From SysObjects Where xtype='P' and [Name]='USP_REP_CH_FORM1')
Begin
	Drop Procedure USP_REP_CH_FORM1
End
Go
/*
    EXECUTE USP_REP_CH_FORM1 '','','','04/01/2010','03/31/2019','','','','',0,0,'','','','','','','','','2013-2014',''
*/
CREATE PROCEDURE [dbo].[USP_REP_CH_FORM1]
@TMPAC NVARCHAR(50),@TMPIT NVARCHAR(50),@SPLCOND VARCHAR(8000),@SDATE  SMALLDATETIME,@EDATE SMALLDATETIME
,@SAC AS VARCHAR(60),@EAC AS VARCHAR(60)
,@SIT AS VARCHAR(60),@EIT AS VARCHAR(60)
,@SAMT FLOAT,@EAMT FLOAT
,@SDEPT AS VARCHAR(60),@EDEPT AS VARCHAR(60) 
,@SCATE AS VARCHAR(60),@ECATE AS VARCHAR(60)
,@SWARE AS VARCHAR(60),@EWARE AS VARCHAR(60)
,@SINV_SR AS VARCHAR(60),@EINV_SR AS VARCHAR(60)
,@LYN VARCHAR(20)
,@EXPARA  AS VARCHAR(60)= null

AS
BEGIN
SET NOCOUNT ON
Declare @FCON as NVARCHAR(2000),@VSAMT DECIMAL(14,2),@VEAMT DECIMAL(14,2)
EXECUTE  USP_REP_FILTCON 
@VTMPAC =@TMPAC,@VTMPIT =@TMPIT,@VSPLCOND =@SPLCOND
,@VSDATE=NULL
,@VEDATE=@EDATE
,@VSAC =@SAC,@VEAC =@EAC
,@VSIT=@SIT,@VEIT=@EIT
,@VSAMT=@SAMT,@VEAMT=@EAMT
,@VSDEPT=@SDEPT,@VEDEPT=@EDEPT
,@VSCATE =@SCATE,@VECATE =@ECATE
,@VSWARE =@SWARE,@VEWARE  =@EWARE
,@VSINV_SR =@SINV_SR,@VEINV_SR =@SINV_SR
,@VMAINFILE='M',@VITFILE=NULL,@VACFILE=NULL
,@VDTFLD ='DATE'
,@VLYN=NULL
,@VEXPARA=@EXPARA
,@VFCON =@FCON OUTPUT

---- Temprory Table Creation.
SELECT PART=3,PARTSR='AAA',SRNO='AAA',RATE=99.999,AMT1=CAST('0' AS NUMERIC(20,2)),AMT2=CAST('0' AS NUMERIC(20,2)),AMT3=CAST('0' AS NUMERIC(20,2)),
M.INV_NO,M.DATE,PARTY_NM=AC1.AC_NAME,ADDRESS=Ltrim(AC1.Add1)+' '+Ltrim(AC1.Add2)+' '+Ltrim(AC1.Add3),STM.FORM_NM,AC1.S_TAX
,STM.RFORM_NM,CAST('0' AS NUMERIC(20,2)) AS AMT4,CAST('0' AS NUMERIC(20,2)) AS AMT5
,TAX_NAME=CAST('' AS VARCHAR(12)),n.item,EIT_NAME=CAST('' AS VARCHAR(50)),CONTTAX=CAST(0 AS DECIMAL(12,2)),CTYPE=CAST('' AS VARCHAR(2)) 
INTO #CH_CST_FORM1
FROM PTACDET A 
INNER JOIN STMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)
INNER JOIN STAX_MAS STM ON (M.TAX_NAME=STM.TAX_NAME)
INNER JOIN AC_MAST AC ON (A.AC_NAME=AC.AC_NAME)
INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID)
inner join stitem n on (m.tran_cd=n.tran_cd) 
WHERE 1=2

Declare @MultiCo	VarChar(3)
Declare @MCON as NVARCHAR(2000)
IF Exists(Select A.ID From SysObjects A Inner Join SysColumns B On(A.ID = B.ID) Where A.[Name] = 'STMAIN' And B.[Name] = 'DBNAME')
	Begin	------Fetch Records from Multi Co. Data
		 Set @MultiCo = 'YES'
		 EXECUTE USP_REP_MULTI_CO_DATA
		  @TMPAC, @TMPIT, @SPLCOND, @SDATE, @EDATE
		 ,@SAC, @EAC, @SIT, @EIT, @SAMT, @EAMT
		 ,@SDEPT, @EDEPT, @SCATE, @ECATE,@SWARE
		 ,@EWARE, @SINV_SR, @EINV_SR, @LYN, @EXPARA
		 ,@MFCON = @MCON OUTPUT

	End
else
	Begin ------Fetch Single Co. Data
		 Set @MultiCo = 'NO'
		 EXECUTE USP_REP_SINGLE_CO_DATA_vat
		  @TMPAC, @TMPIT, @SPLCOND, @SDATE, @EDATE
		 ,@SAC, @EAC, @SIT, @EIT, @SAMT, @EAMT
		 ,@SDEPT, @EDEPT, @SCATE, @ECATE,@SWARE
		 ,@EWARE, @SINV_SR, @EINV_SR, @LYN, @EXPARA
		 ,@MFCON = @MCON OUTPUT

	End
DECLARE @AMTA1 DECIMAL(18,2),@AMTA2 DECIMAL(18,2),@AMTA3 DECIMAL(18,2),@AMTA4 DECIMAL(18,2),@AMTA5 DECIMAL(18,2)


---1. Gross amount receivable by the dealer
SET @AMTA1 = 0
SELECT @AMTA1 =ISNULL(SUM(CASE WHEN BHENT ='ST' THEN GRO_AMT ELSE -GRO_AMT END),0) FROM VATTBL WHERE BHENT  IN('ST','CN') AND ( DATE BETWEEN @SDATE AND @EDATE )
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','A',0,@AMTA1,0,0,'')
--Deduct:
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','B1',0,0,0,0,'')
     --  i) Sales of Goods Outside the State (as defined in section 4 of the Act)
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 =ISNULL(SUM(CASE WHEN BHENT ='ST' THEN GRO_AMT ELSE -GRO_AMT END),0) FROM VATTBL WHERE BHENT IN('ST','CN') AND ( DATE BETWEEN @SDATE AND @EDATE )
AND ST_TYPE ='OUT OF STATE' AND U_IMPORM NOT IN('Branch Transfer','Consignment Transfer')
AND (RTRIM(LTRIM(REPLACE(REPLACE(RFORM_NM,'FORM',''),'-',''))) ='H' OR RTRIM(LTRIM(REPLACE(REPLACE(TAX_NAME,'FORM',''),'-',''))) ='H' )
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','B2',0,@AMTA1,@AMTA2,0,'')
       --ii)Sales of goods in course of export outside India (as defined in section 5 of the Act) 
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 =ISNULL(SUM(CASE WHEN BHENT ='ST' THEN GRO_AMT ELSE -GRO_AMT END),0) FROM VATTBL WHERE BHENT IN('ST','CN') AND ( DATE BETWEEN @SDATE AND @EDATE )
AND ST_TYPE ='OUT OF COUNTRY' ---AND U_IMPORM ='Export Out of India'
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','B3',0,@AMTA1,@AMTA2,0,'')
-- iii)Turnover of goods transferred outside the State (as referred to in section 6A(2))
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 =ISNULL(SUM(CASE WHEN BHENT ='ST' THEN GRO_AMT ELSE -GRO_AMT END),0) FROM VATTBL WHERE BHENT IN('ST','CN') AND ( DATE BETWEEN @SDATE AND @EDATE )
AND ST_TYPE ='OUT OF STATE' AND U_IMPORM IN('Branch Transfer','Consignment Transfer') AND TAX_NAME  NOT LIKE '%EXEMPTED%' 
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','B4',0,@AMTA1,@AMTA2,0,'')

-- 2. Balance Turnover on Inter-State  Sale & sales with in the state
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(AMT1),0) FROM #CH_CST_FORM1 WHERE PART=1 AND PARTSR='1' AND SRNO ='A'
SELECT @AMTA2 = ISNULL(SUM(AMT1),0) FROM #CH_CST_FORM1 WHERE PART=1 AND PARTSR='1' AND SRNO IN('B2','B3','B4')
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','C1',0,(@AMTA1 - @AMTA2),0,0,'')
-- Deduct:
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','C2',0,0,0,0,'')
--   Turnover of sales within the State
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 =ISNULL(SUM(CASE WHEN BHENT ='ST' THEN GRO_AMT ELSE -GRO_AMT END),0) FROM VATTBL WHERE BHENT IN('ST','CN') AND ( DATE BETWEEN @SDATE AND @EDATE )
AND ST_TYPE in('','local') 
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','C3',0,@AMTA1,@AMTA2,0,'')

--   3. Balance turnover or Inter State sales
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(AMT1),0) FROM #CH_CST_FORM1 WHERE PART=1 AND PARTSR='1' AND SRNO ='C1'
SELECT @AMTA2 = ISNULL(SUM(AMT1),0) FROM #CH_CST_FORM1 WHERE PART=1 AND PARTSR='1' AND SRNO ='C3'
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','D1',0,(@AMTA1-@AMTA2),0,0,'')
--Deduct:
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','D2',0,0,0,0,'')
-- Cost or freight delivery or installation when such cost is  separately charged.
SET @AMTA1 = 0
SET @AMTA2 = 0
select @AMTA1=isnull(sum(a.u_frtamt),0) from stitem a inner join AC_MAST b on (a.Ac_id= b.Ac_id ) where a.entry_ty ='st' 
and  ( a.date between @sdate and @EDATE ) and b.st_type ='out of state' and  isnull((a.u_frtamt),0) <> 0
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','D3',0,@AMTA1,@AMTA2,0,'')
-- 4.Balance:Total Turnover on Inter State sales
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(AMT1),0) FROM #CH_CST_FORM1 WHERE PART=1 AND PARTSR='1' AND SRNO ='D1'
SELECT @AMTA2 = ISNULL(SUM(AMT1),0) FROM #CH_CST_FORM1 WHERE PART=1 AND PARTSR='1' AND SRNO ='D3'
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','E1',0,(@AMTA1-@AMTA2),0,0,'')
-- (i) Turnover of Inter State Sale of goods unconditionally exempt from tax under the Punjab VAT Act 2005 (as applicable to UT Chandigarh.)
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 =ISNULL(SUM(CASE WHEN BHENT ='ST' THEN GRO_AMT ELSE -GRO_AMT END),0) FROM VATTBL WHERE BHENT IN('ST','CN') AND ( DATE BETWEEN @SDATE AND @EDATE )
AND ST_TYPE in('OUT OF STATE') AND TAX_NAME LIKE '%EXEMPTED%'
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','E2',0,@AMTA1,@AMTA2,0,'')
--(ii) Turnover of Sale of goods returned by the Purchaser within a period of six months under the section 8A of Central Sales Tax Act 1956.
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(A.GRO_AMT),0) FROM VATTBL A  INNER JOIN SRITREF B ON (A.BHENT=B.ENTRY_TY AND A.TRAN_CD=B.TRAN_CD and A.Itserial =B.itserial)
WHERE A.BHENT ='SR' AND A.ST_TYPE ='OUT OF STATE'  AND  ( A.DATE BETWEEN @SDATE AND @EDATE ) AND DATEDIFF(MM,B.Rdate,A.DATE )  <= 6
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','E3',0,@AMTA1,@AMTA2,0,'')
---(iii) Turnover in respect of subsequent sales falling under clause(a) and (b) of section 6(2) of the Act. 
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 =ISNULL(SUM(CASE WHEN BHENT ='ST' THEN GRO_AMT ELSE -GRO_AMT END),0) FROM VATTBL WHERE BHENT IN('ST','CN') AND ( DATE BETWEEN @SDATE AND @EDATE )
AND ST_TYPE in('OUT OF STATE') AND
(RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(TAX_NAME,'FORM',''),'-',''),'/','')))  IN('EII','E2','E1','EI')  OR (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(RFORM_NM ,'FORM',''),'-',''),'/',''))))  IN('EII','E2','E1','EI'))
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','E4',0,@AMTA1,@AMTA2,0,'')
--5 A. Balance Taxable Turnover in respect of Inter State Sales.
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(AMT1),0) FROM #CH_CST_FORM1 WHERE PART=1 AND PARTSR='1' AND SRNO ='E1'
SELECT @AMTA2 = ISNULL(SUM(AMT1),0) FROM #CH_CST_FORM1 WHERE PART=1 AND PARTSR='1' AND SRNO  in('E2','E3','E4')
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','F',0,(@AMTA1-@AMTA2),0,0,'')
---6. Goods wise break of above 
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','G1',0,@AMTA1,@AMTA2,0,'')

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SET @AMTA1 = 0
SET @AMTA2 = 0
SET @AMTA3 = 0
SET @AMTA4 = 0
---1. Gross amount receivable by the dealer
SELECT @AMTA1 =ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON(A.It_code =b.IT_CODE )
WHERE A.BHENT  IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.S_TAX <> '' AND ISNULL(B.u_IT_IMP,0)= 1
SELECT @AMTA2 =ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON(A.It_code =b.IT_CODE )
WHERE A.BHENT  IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.S_TAX ='' AND ISNULL(B.u_IT_IMP,0)= 1

SELECT @AMTA3 =ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON(A.It_code =b.IT_CODE )
WHERE A.BHENT  IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.S_TAX <> '' AND ISNULL(B.u_IT_IMP,0)= 0
SELECT @AMTA4 =ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON(A.It_code =b.IT_CODE )
WHERE A.BHENT  IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.S_TAX ='' AND ISNULL(B.u_IT_IMP,0)= 0

     --  i) Sales of Goods Outside the State (as defined in section 4 of the Act)
SELECT @AMTA1 = @AMTA1 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL  A  LEFT OUTER JOIN IT_MAST B ON (A.It_code =B.It_code )
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE )
AND A.ST_TYPE ='OUT OF STATE' AND A.U_IMPORM NOT IN('Branch Transfer','Consignment Transfer')
AND (RTRIM(LTRIM(REPLACE(REPLACE(A.RFORM_NM,'FORM',''),'-',''))) ='H' OR RTRIM(LTRIM(REPLACE(REPLACE(A.TAX_NAME,'FORM',''),'-',''))) ='H' )
AND A.S_TAX <> '' AND ISNULL(B.u_IT_IMP,0)= 1
SELECT @AMTA2 = @AMTA2 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL  A  LEFT OUTER JOIN IT_MAST B ON (A.It_code =B.It_code )
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE )
AND A.ST_TYPE ='OUT OF STATE' AND A.U_IMPORM NOT IN('Branch Transfer','Consignment Transfer')
AND (RTRIM(LTRIM(REPLACE(REPLACE(A.RFORM_NM,'FORM',''),'-',''))) ='H' OR RTRIM(LTRIM(REPLACE(REPLACE(A.TAX_NAME,'FORM',''),'-',''))) ='H' )
AND A.S_TAX = '' AND ISNULL(B.u_IT_IMP,0)= 1

SELECT @AMTA3 = @AMTA3 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL  A  LEFT OUTER JOIN IT_MAST B ON (A.It_code =B.It_code )
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE )
AND A.ST_TYPE ='OUT OF STATE' AND A.U_IMPORM NOT IN('Branch Transfer','Consignment Transfer')
AND (RTRIM(LTRIM(REPLACE(REPLACE(A.RFORM_NM,'FORM',''),'-',''))) ='H' OR RTRIM(LTRIM(REPLACE(REPLACE(A.TAX_NAME,'FORM',''),'-',''))) ='H' )
AND A.S_TAX <> '' AND ISNULL(B.u_IT_IMP,0)= 0

SELECT @AMTA4 = @AMTA4 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL  A  LEFT OUTER JOIN IT_MAST B ON (A.It_code =B.It_code )
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE )
AND A.ST_TYPE ='OUT OF STATE' AND A.U_IMPORM NOT IN('Branch Transfer','Consignment Transfer')
AND (RTRIM(LTRIM(REPLACE(REPLACE(A.RFORM_NM,'FORM',''),'-',''))) ='H' OR RTRIM(LTRIM(REPLACE(REPLACE(A.TAX_NAME,'FORM',''),'-',''))) ='H' )
AND A.S_TAX = '' AND ISNULL(B.u_IT_IMP,0)= 0
 --ii)Sales of goods in course of export outside India (as defined in section 5 of the Act) 
SELECT @AMTA1 = @AMTA1 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.It_code =B.It_code)
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE ='OUT OF COUNTRY' AND A.S_TAX <> '' AND ISNULL(B.u_IT_IMP,0)= 1
SELECT @AMTA2 = @AMTA2 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.It_code =B.It_code)
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE ='OUT OF COUNTRY' AND A.S_TAX ='' AND ISNULL(B.u_IT_IMP,0)= 1

SELECT @AMTA3 = @AMTA3 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.It_code =B.It_code)
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE ='OUT OF COUNTRY' AND A.S_TAX <> '' AND ISNULL(B.u_IT_IMP,0)= 0
SELECT @AMTA4 = @AMTA4 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.It_code =B.It_code)
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE ='OUT OF COUNTRY' AND A.S_TAX ='' AND ISNULL(B.u_IT_IMP,0)= 0
--------
SELECT @AMTA1 =@AMTA1 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A  INNER JOIN IT_MAST B ON (A.It_code =B.IT_CODE )
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) 
AND A.ST_TYPE ='OUT OF STATE' AND A.U_IMPORM IN('Branch Transfer','Consignment Transfer') AND A.TAX_NAME  NOT LIKE '%EXEMPTED%' 
AND A.S_TAX <> '' AND ISNULL(B.u_IT_IMP,0)= 1
SELECT @AMTA2 =@AMTA2 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A  INNER JOIN IT_MAST B ON (A.It_code =B.IT_CODE )
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) 
AND A.ST_TYPE ='OUT OF STATE' AND A.U_IMPORM IN('Branch Transfer','Consignment Transfer') AND A.TAX_NAME  NOT LIKE '%EXEMPTED%' 
AND A.S_TAX = '' AND ISNULL(B.u_IT_IMP,0)= 1

SELECT @AMTA3 =@AMTA3 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A  INNER JOIN IT_MAST B ON (A.It_code =B.IT_CODE )
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) 
AND A.ST_TYPE ='OUT OF STATE' AND A.U_IMPORM IN('Branch Transfer','Consignment Transfer') AND A.TAX_NAME  NOT LIKE '%EXEMPTED%' 
AND A.S_TAX <> '' AND ISNULL(B.u_IT_IMP,0)= 0
SELECT @AMTA4 =@AMTA4 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A  INNER JOIN IT_MAST B ON (A.It_code =B.IT_CODE )
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) 
AND A.ST_TYPE ='OUT OF STATE' AND A.U_IMPORM IN('Branch Transfer','Consignment Transfer') AND A.TAX_NAME  NOT LIKE '%EXEMPTED%' 
AND A.S_TAX = '' AND ISNULL(B.u_IT_IMP,0)= 0

--   Turnover of sales within the State
SELECT @AMTA1 = @AMTA1 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.It_code =B.It_code )
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE in('','local') AND A.S_TAX <>'' AND ISNULL(B.u_IT_IMP,0)= 1
SELECT @AMTA2 = @AMTA2 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.It_code =B.It_code )
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE in('','local') AND A.S_TAX ='' AND ISNULL(B.u_IT_IMP,0)= 1

SELECT @AMTA3 = @AMTA3 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.It_code =B.It_code )
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE in('','local') AND A.S_TAX <>'' AND ISNULL(B.u_IT_IMP,0)= 0
SELECT @AMTA4 = @AMTA4 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.It_code =B.It_code )
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE in('','local') AND A.S_TAX ='' AND ISNULL(B.u_IT_IMP,0)= 0
-- Cost or freight delivery or installation when such cost is  separately charged.
select @AMTA1= @AMTA1 - isnull(sum(a.u_frtamt),0) from stitem a inner join AC_MAST b on (a.Ac_id= b.Ac_id ) LEFT OUTER JOIN IT_MAST C ON (A.It_code  =C.It_code ) where a.entry_ty ='st' 
and  ( a.date between @sdate and @EDATE ) and b.st_type ='out of state' and  isnull((a.u_frtamt),0) <> 0  AND B.S_TAX <> '' AND ISNULL(C.u_IT_IMP,0)= 1
select @AMTA2= @AMTA2 - isnull(sum(a.u_frtamt),0) from stitem a inner join AC_MAST b on (a.Ac_id= b.Ac_id ) LEFT OUTER JOIN IT_MAST C ON (A.It_code  =C.It_code ) where a.entry_ty ='st' 
and  ( a.date between @sdate and @EDATE ) and b.st_type ='out of state' and  isnull((a.u_frtamt),0) <> 0  AND B.S_TAX = '' AND ISNULL(C.u_IT_IMP,0)= 1

select @AMTA3= @AMTA3 - isnull(sum(a.u_frtamt),0) from stitem a inner join AC_MAST b on (a.Ac_id= b.Ac_id ) LEFT OUTER JOIN IT_MAST C ON (A.It_code  =C.It_code ) where a.entry_ty ='st' 
and  ( a.date between @sdate and @EDATE ) and b.st_type ='out of state' and  isnull((a.u_frtamt),0) <> 0  AND B.S_TAX <> '' AND ISNULL(C.u_IT_IMP,0)= 0
select @AMTA4= @AMTA4 - isnull(sum(a.u_frtamt),0) from stitem a inner join AC_MAST b on (a.Ac_id= b.Ac_id ) LEFT OUTER JOIN IT_MAST C ON (A.It_code  =C.It_code ) where a.entry_ty ='st' 
and  ( a.date between @sdate and @EDATE ) and b.st_type ='out of state' and  isnull((a.u_frtamt),0) <> 0  AND B.S_TAX = '' AND ISNULL(C.u_IT_IMP,0)= 0
-- (i) Turnover of Inter State Sale of goods unconditionally exempt from tax under the Punjab VAT Act 2005 (as applicable to UT Chandigarh.)
SELECT @AMTA1 = @AMTA1 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.IT_CODE =B.IT_CODE)
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE in('OUT OF STATE') AND A.TAX_NAME LIKE '%EXEMPTED%'
AND A.S_TAX <> '' AND ISNULL(B.u_IT_IMP,0)= 1
SELECT @AMTA2 = @AMTA2 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.IT_CODE =B.IT_CODE)
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE in('OUT OF STATE') AND A.TAX_NAME LIKE '%EXEMPTED%'
AND A.S_TAX = '' AND ISNULL(B.u_IT_IMP,0)= 1

SELECT @AMTA3 = @AMTA3 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.IT_CODE =B.IT_CODE)
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE in('OUT OF STATE') AND A.TAX_NAME LIKE '%EXEMPTED%'
AND A.S_TAX <> '' AND ISNULL(B.u_IT_IMP,0)= 0
SELECT @AMTA4 = @AMTA4 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.IT_CODE =B.IT_CODE)
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE in('OUT OF STATE') AND A.TAX_NAME LIKE '%EXEMPTED%'
AND A.S_TAX = '' AND ISNULL(B.u_IT_IMP,0)= 0
--(ii) Turnover of Sale of goods returned by the Purchaser within a period of six months under the section 8A of Central Sales Tax Act 1956.
SELECT @AMTA1 = @AMTA1 - ISNULL(SUM(A.GRO_AMT),0) FROM VATTBL A  INNER JOIN SRITREF B ON (A.BHENT=B.ENTRY_TY AND A.TRAN_CD=B.TRAN_CD and A.Itserial =B.itserial)
INNER JOIN IT_MAST C ON(A.IT_CODE = C.IT_CODE)
WHERE A.BHENT ='SR' AND A.ST_TYPE ='OUT OF STATE'  AND  ( A.DATE BETWEEN @SDATE AND @EDATE ) AND DATEDIFF(MM,B.Rdate,A.DATE )  <= 6  AND A.S_TAX <> '' AND ISNULL(C.u_IT_IMP,0) = 1
SELECT @AMTA2 = @AMTA2 - ISNULL(SUM(A.GRO_AMT),0) FROM VATTBL A  INNER JOIN SRITREF B ON (A.BHENT=B.ENTRY_TY AND A.TRAN_CD=B.TRAN_CD and A.Itserial =B.itserial)
INNER JOIN IT_MAST C ON(A.IT_CODE = C.IT_CODE)
WHERE A.BHENT ='SR' AND A.ST_TYPE ='OUT OF STATE'  AND  ( A.DATE BETWEEN @SDATE AND @EDATE ) AND DATEDIFF(MM,B.Rdate,A.DATE )  <= 6  AND A.S_TAX = '' AND ISNULL(C.u_IT_IMP,0) = 1

SELECT @AMTA3 = @AMTA3 - ISNULL(SUM(A.GRO_AMT),0) FROM VATTBL A  INNER JOIN SRITREF B ON (A.BHENT=B.ENTRY_TY AND A.TRAN_CD=B.TRAN_CD and A.Itserial =B.itserial)
INNER JOIN IT_MAST C ON(A.IT_CODE = C.IT_CODE)
WHERE A.BHENT ='SR' AND A.ST_TYPE ='OUT OF STATE'  AND  ( A.DATE BETWEEN @SDATE AND @EDATE ) AND DATEDIFF(MM,B.Rdate,A.DATE )  <= 6  AND A.S_TAX <> '' AND ISNULL(C.u_IT_IMP,0) = 0
SELECT @AMTA4 = @AMTA4 - ISNULL(SUM(A.GRO_AMT),0) FROM VATTBL A  INNER JOIN SRITREF B ON (A.BHENT=B.ENTRY_TY AND A.TRAN_CD=B.TRAN_CD and A.Itserial =B.itserial)
INNER JOIN IT_MAST C ON(A.IT_CODE = C.IT_CODE)
WHERE A.BHENT ='SR' AND A.ST_TYPE ='OUT OF STATE'  AND  ( A.DATE BETWEEN @SDATE AND @EDATE ) AND DATEDIFF(MM,B.Rdate,A.DATE )  <= 6  AND A.S_TAX = '' AND ISNULL(C.u_IT_IMP,0) = 0


---(iii) Turnover in respect of subsequent sales falling under clause(a) and (b) of section 6(2) of the Act. 
SELECT @AMTA1 = @AMTA1 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.IT_CODE =B.IT_CODE)
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE in('OUT OF STATE') AND
(RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(A.TAX_NAME,'FORM',''),'-',''),'/','')))  IN('EII','E2','E1','EI','E I','E II','E 1','E 2')  OR (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(A.RFORM_NM ,'FORM',''),'-',''),'/',''))))  IN('EII','E2','E1','EI','E I','E II','E 1','E 2'))
AND A.S_TAX <> '' AND ISNULL(B.u_IT_IMP,0) = 1
SELECT @AMTA2 = @AMTA2 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.IT_CODE =B.IT_CODE)
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE in('OUT OF STATE') AND
(RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(A.TAX_NAME,'FORM',''),'-',''),'/','')))  IN('EII','E2','E1','EI','E I','E II','E 1','E 2')  OR (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(A.RFORM_NM ,'FORM',''),'-',''),'/',''))))  IN('EII','E2','E1','EI','E I','E II','E 1','E 2'))
AND A.S_TAX = '' AND ISNULL(B.u_IT_IMP,0) = 1

SELECT @AMTA3 = @AMTA3 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.IT_CODE =B.IT_CODE)
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE in('OUT OF STATE') AND
(RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(A.TAX_NAME,'FORM',''),'-',''),'/','')))  IN('EII','E2','E1','EI','E I','E II','E 1','E 2')  OR (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(A.RFORM_NM ,'FORM',''),'-',''),'/',''))))  IN('EII','E2','E1','EI','E I','E II','E 1','E 2'))
AND A.S_TAX <> '' AND ISNULL(B.u_IT_IMP,0) = 0
SELECT @AMTA4 = @AMTA4 - ISNULL(SUM(CASE WHEN A.BHENT ='ST' THEN A.GRO_AMT ELSE -A.GRO_AMT END),0) FROM VATTBL A LEFT OUTER JOIN IT_MAST B ON (A.IT_CODE =B.IT_CODE)
WHERE A.BHENT IN('ST','CN') AND ( A.DATE BETWEEN @SDATE AND @EDATE ) AND A.ST_TYPE in('OUT OF STATE') AND
(RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(A.TAX_NAME,'FORM',''),'-',''),'/','')))  IN('EII','E2','E1','EI','E I','E II','E 1','E 2')  OR (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(A.RFORM_NM ,'FORM',''),'-',''),'/',''))))  IN('EII','E2','E1','EI','E I','E II','E 1','E 2'))
AND A.S_TAX = '' AND ISNULL(B.u_IT_IMP,0) = 0


----------------------------------------------------------------------------------------------------------------------------------------------------------------------------



--(A) Declare goods :-
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','G2',0,0,0,0,'')
--(i) Sold to registered dealers on prescribed declaration-vide declaration attached.
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','G3',0,@AMTA1,0,0,'')

--(ii) Sold otherwise.
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','G4',0,@AMTA2,0,0,'')
---(B) Other goods :-
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','G5',0,0,0,0,'')


---  (i) Sold to registered dealers on prescribed declaration-vide declaration attached.
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','G6',0,@AMTA3,0,0,'')
---(ii) Sold other-wise.
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','G7',0,@AMTA4,0,0,'')
---Total : 
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','G8',0,(@AMTA1 + @AMTA2 + @AMTA3 + @AMTA4),0,0,'')

--7. (i)  Taxable at
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM)
SELECT 1 AS PART,'3' AS PARTSR,'H' AS SRNO,PER,ISNULL(SUM((CASE WHEN BHENT ='ST' THEN VATONAMT ELSE -VATONAMT END)),0),ISNULL(SUM((CASE WHEN BHENT ='ST' THEN TAXAMT ELSE -TAXAMT END)),0),0 AS AMT3,'' AS PERTY_NM FROM VATTBL WHERE BHENT IN('ST','SR','CN') AND ST_TYPE ='OUT OF STATE' 
AND TAX_NAME LIKE '%C.S.T%' AND PER > 0 GROUP BY PER ORDER BY PER
IF NOT EXISTS(SELECT TOP 1 SRNO FROM #CH_CST_FORM1 WHERE PART = 1 AND PARTSR ='3' AND SRNO ='H' )
BEGIN
	INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'3','H',0,0,0,0,'')	
END


--7. 8. Total tax payable on                                                                                    Rs.
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 =ISNULL(SUM(AMT1),0),@AMTA2 =ISNULL(SUM(AMT2),0)   FROM #CH_CST_FORM1 WHERE PART = 1 AND PARTSR ='3' AND SRNO ='H' 
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'4','I',0,@AMTA1,@AMTA2,0,'')
---9. Tax Paid, if any, by means of Treasury challan/Cheque/Drafts.
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,s_tax,rform_nm,inv_no,date) SELECT 
1 as PART,'5' as PARTSR ,'J1' as SRNO,0 as rate,a.net_amt,0 as amt2,0 as amt3,a.bank_nm,b.bsrcode,ISNULL(a.DEP_MODE,''),a.U_CHALNO,a.U_CHALDT
from BPMAIN a inner join AC_MAST b on(a.bank_nm =b.ac_name) where a.entry_ty ='bp' and a.party_nm ='cst payable' 
--and a.U_NATURE ='cst' 
and a.date between @SDATE and @EDATE 
SET @AMTA1 = 0
SET @AMTA2 = 0
IF NOT EXISTS(SELECT TOP 1 SRNO FROM #CH_CST_FORM1  WHERE PART = 1 AND PARTSR = '5' AND SRNO ='J1')
BEGIN
	INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','J1',0,@AMTA1,@AMTA2,0,'')
END

---Tax Paid Total
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 =isnull(sum(amt1),0) FROM #CH_CST_FORM1  WHERE PART = 1 AND PARTSR = '5' AND SRNO ='J1'
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','K',0,@AMTA1,@AMTA2,0,'')
---10. Balance due/excess paid, if any 
SET @AMTA1 = 0
SELECT @AMTA1 =ISNULL(SUM(AMT2),0) FROM #CH_CST_FORM1 WHERE PART = 1 AND PARTSR ='3' AND SRNO ='H' 
SET @AMTA2 = 0
SELECT @AMTA2 =ISNULL(SUM(AMT1),0) FROM #CH_CST_FORM1  WHERE PART = 1 AND PARTSR = '5' AND SRNO ='J1'
INSERT INTO #CH_CST_FORM1 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'7','L',0,(@AMTA1 - @AMTA2),0,0,'')

-----------------
Update #CH_CST_FORM1 set  PART = isnull(Part,'') , Partsr = isnull(PARTSR,''), SRNO = isnull(SRNO,''),
RATE = isnull(RATE,0), AMT1 = isnull(AMT1,0), AMT2 = isnull(AMT2,0), AMT3 = isnull(AMT3,0),
INV_NO = isnull(INV_NO,''), DATE = isnull(Date,''),PARTY_NM = isnull(Party_nm,''), ADDRESS = isnull(Address,''),
FORM_NM = isnull(form_nm,''), S_TAX = isnull(S_tax,'')
,RFORM_NM = isnull(rform_nm,''), AMT4 = isnull(AMT4,0), AMT5 = isnull(AMT5,0)

SELECT * FROM #CH_CST_FORM1 order by cast(substring(partsr,1,case when (isnumeric(substring(partsr,1,2))=1) then 2 else 1 end) as int), partsr,SRNO

end

set ANSI_NULLS OFF






