IF EXISTS(SELECT XTYPE FROM SYSOBJECTS WHERE XTYPE='P' AND name ='USP_REP_DM_VATFORM30A')
BEGIN
 DROP PROCEDURE USP_REP_DM_VATFORM30A
END
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
EXECUTE USP_REP_DM_VATFORM30A'','','','04/01/2015','03/31/2016','','','','',0,0,'','','','','','','','','2015-2016',''
*/
-- =============================================
-- Author	   : Sumit.S.Gavate
-- Create date : 10/05/2016
-- Description : This Stored procedure is useful to generate Daman & Diu VAT FORM 30A
-- Modify date : 
-- Modified By : 
-- Modify date : 
-- Remark      :
-- =============================================
Create PROCEDURE [dbo].[USP_REP_DM_VATFORM30A]
@TMPAC NVARCHAR(50),@TMPIT NVARCHAR(50),@SPLCOND VARCHAR(8000),@SDATE  SMALLDATETIME,@EDATE SMALLDATETIME
,@SAC AS VARCHAR(60),@EAC AS VARCHAR(60)
,@SIT AS VARCHAR(60),@EIT AS VARCHAR(60)
,@SAMT FLOAT,@EAMT FLOAT
,@SDEPT AS VARCHAR(60),@EDEPT AS VARCHAR(60)
,@SCATE AS VARCHAR(60),@ECATE AS VARCHAR(60)
,@SWARE AS VARCHAR(60),@EWARE AS VARCHAR(60)
,@SINV_SR AS VARCHAR(60),@EINV_SR AS VARCHAR(60)
,@LYN VARCHAR(20)
,@EXPARA  AS VARCHAR(60)= null
AS
DECLARE @vatfltopt VARCHAR(25)
select @vatfltopt=vat_flt_opt from manufact
print @vatfltopt
Begin

Declare @FCON as NVARCHAR(2000),@VSAMT DECIMAL(14,2),@VEAMT DECIMAL(14,2)
EXECUTE   USP_REP_FILTCON 
@VTMPAC =@TMPAC,@VTMPIT =@TMPIT,@VSPLCOND =@SPLCOND
,@VSDATE=NULL
,@VEDATE=@EDATE
,@VSAC =@SAC,@VEAC =@EAC
,@VSIT=@SIT,@VEIT=@EIT
,@VSAMT=@SAMT,@VEAMT=@EAMT
,@VSDEPT=@SDEPT,@VEDEPT=@EDEPT
,@VSCATE =@SCATE,@VECATE =@ECATE
,@VSWARE =@SWARE,@VEWARE  =@EWARE
,@VSINV_SR =@SINV_SR,@VEINV_SR =@SINV_SR
,@VMAINFILE='M',@VITFILE=NULL,@VACFILE=NULL
,@VDTFLD ='DATE'
,@VLYN=NULL
,@VEXPARA=@EXPARA
,@VFCON =@FCON OUTPUT

Declare @SQLCOMMAND NVARCHAR(4000)
DECLARE @RATE NUMERIC(12,2),@AMTA1 NUMERIC(12,2),@AMTB1 NUMERIC(12,2),@AMTC1 NUMERIC(12,2),@AMTD1 NUMERIC(12,2)
DECLARE @AMTA2 NUMERIC(12,2),@AMTB2 NUMERIC(12,2),@AMTC2 NUMERIC(12,2),@AMTD2 NUMERIC(12,2),@PER NUMERIC(12,2),
		@TAXAMT NUMERIC(12,2),@CHAR INT,@LEVEL NUMERIC(12,2)

SELECT PART=3,PARTSR='AAA',SRNO='AAAA',RATE=99999.999,AMT1=m.NET_AMT,AMT2=m.NET_AMT,AMT3=m.NET_AMT,AMT4=m.NET_AMT,AMT5=m.NET_AMT,AMT6=m.NET_AMT,
AMT7=m.NET_AMT,AMT8=m.NET_AMT,AMT9=m.NET_AMT,AMT10=m.NET_AMT,AMT11=m.NET_AMT,AMT12=m.NET_AMT,M.INV_NO,M.DATE,PARTY_NM=AC1.AC_NAME,
ADDRESS=Ltrim(AC1.Add1)+' '+Ltrim(AC1.Add2)+' '+Ltrim(AC1.Add3),State = SPACE(25),AC1.S_TAX,ISNULL(I.It_code,0) as It_code,I.It_name,
ST_Type = AC1.ST_Type,BHENT = S.Entry_ty INTO #DMVAT30A FROM PTACDET A
INNER JOIN STITEM S ON (A.ENTRY_TY=S.ENTRY_TY AND A.TRAN_CD=S.TRAN_CD) INNER JOIN STMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)
INNER JOIN STAX_MAS STM ON (M.TAX_NAME=STM.TAX_NAME) INNER JOIN AC_MAST AC ON (A.AC_NAME=AC.AC_NAME) INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID)
INNER JOIN IT_MAST I ON (S.It_code = ISNULL(I.It_code,0)) WHERE 1=2

Declare @MultiCo	VarChar(3)
Declare @MCON as NVARCHAR(2000)
EXECUTE USP_REP_SINGLE_CO_DATA_VAT @TMPAC, @TMPIT, @SPLCOND, @SDATE, @EDATE,@SAC, @EAC, @SIT, @EIT, @SAMT, @EAMT,@SDEPT, @EDEPT,
		@SCATE, @ECATE,@SWARE,@EWARE, @SINV_SR, @EINV_SR, @LYN, @EXPARA,@MFCON = @MCON OUTPUT	

DECLARE @Fld_name CHAR(25),@HeadDetail Bit,@SqlStr VARCHAR(MAX)
SELECT @Fld_name = '',@SqlStr = ''
Select DISTINCT @Fld_name = 'P.' + RTRIM(LTRIM(fld_nm)),@HeadDetail = att_file from DCMAST where head_nm like '%Labour%' AND Entry_ty = 'PT'

SET @SqlStr = 'SELECT A.BHENT,A.Inv_no,A.Date,A.S_TAX,A.AC_NAME,A.ST_Type,ISNULL(A.It_code,0) as It_code,I.it_name,A.U_IMPORM,AMT1=0,AMT2=0,AMT3=0,AMT4=0,AMT5=0,'
SET @SqlStr = @SqlStr + ' ISNULL(SUM(AMT6),0) as AMT6,AMT7 = 0,AMT8 = 0,AMT9=0,AMT10=0,AMT11=0,AMT12=0,AC.State INTO ##Table1 '
SET @SqlStr = @SqlStr + ' FROM VATTBL A INNER JOIN AC_MAST AC ON (A.AC_ID = AC.Ac_id) INNER JOIN IT_MAST I ON (ISNULL(A.It_code,0) = ISNULL(I.It_code,0)) '
SET @SqlStr = @SqlStr + ' INNER JOIN (Select A.*,' + RTRIM(LTRIM(@Fld_name)) + ' as AMT6 from VATTBL A INNER JOIN PTITEM P ON '
SET @SqlStr = @SqlStr + ' (A.BHENT = P.entry_ty AND A.Date = P.date AND A.TRAN_CD = P.Tran_cd AND A.INV_NO = P.inv_no AND A.it_code = P.It_code AND '
SET @SqlStr = @SqlStr + ' A.itSerial = P.Itserial) WHERE A.BHENT IN(''PT'',''P1'') AND A.St_Type IN(''OUT OF COUNTRY'',''OUT OF STATE'') AND ' + RTRIM(LTRIM(@Fld_name)) + ' > 0) B '
SET @SqlStr = @SqlStr + ' ON (A.TRAN_CD = B.TRAN_CD AND A.INV_NO = B.INV_NO AND A.BHENT = B.BHENT AND ISNULL(A.It_code,0) = ISNULL(B.It_code,0) '
SET @SqlStr = @SqlStr + ' AND A.ItSerial = B.ItSerial AND A.AC_ID = B.AC_ID)'
SET @SqlStr = @SqlStr + ' GROUP BY A.BHENT,A.Inv_no,A.Date,ISNULL(A.It_code,0),A.ST_Type,A.S_TAX,A.AC_NAME,I.it_name,A.U_IMPORM,AC.State'
EXECUTE(@SqlStr)

INSERT Into #DMVAT30A (PART,PARTSR,SRNO,BHENT,Inv_no,Date,S_tax,PARTY_NM,St_type,it_code,it_name,AMT1,AMT2,AMT3,AMT4,AMT5,AMT6,AMT7,AMT8,AMT9,AMT10,AMT11,AMT12,RATE,STATE)
SELECT 1,'1','A',BHENT,Inv_no,Date,S_TAX,AC_NAME,ST_Type,ISNULL(It_code,0) as It_code,it_name,ISNULL(SUM(AMT1),0) AS AMT1,ISNULL(SUM(AMT2),0) AS AMT2,
ISNULL(SUM(AMT3),0) AS AMT3,ISNULL(SUM(AMT4),0) AS AMT4,ISNULL(SUM(AMT5),0) AS AMT5,ISNULL(SUM(AMT6),0) AS AMT6,ISNULL(SUM(AMT7),0) AS AMT7,
ISNULL(SUM(AMT8),0) AS AMT8,ISNULL(SUM(AMT9),0) as AMT9,ISNULL(SUM(AMT10),0) AS AMT10,ISNULL(SUM(AMT11),0) AS AMT11,ISNULL(SUM(AMT12),0) AS AMT12,
0,State FROM (SELECT A.BHENT,A.Inv_no,A.Date,A.S_TAX,A.AC_NAME,A.ST_Type,ISNULL(A.It_code,0) as It_code,I.it_name,A.U_IMPORM,
ISNULL(SUM(B.VATONAMT),0) as AMT1,AMT2=0,AMT3=0,AMT4=0,AMT5=0,AMT6=0,AMT7=0,AMT8=0,ISNULL(SUM(A.Gro_AMT),0) AS AMT9,AMT10=0,AMT11=0,AMT12=0,AC.State
FROM VATTBL A INNER JOIN AC_MAST AC ON (A.AC_ID = AC.Ac_id) INNER JOIN IT_MAST I ON (ISNULL(A.It_code,0) = ISNULL(I.It_code,0)) INNER JOIN 
(Select * from VATTBL WHERE BHENT IN('PT','P1') AND ST_Type = 'OUT OF COUNTRY' AND U_IMPORM NOT IN('Branch Transfer','Consignment Transfer') AND 
(U_IMPORM in('Direct Imports','Import from Outside India','High Seas Purchases')) AND 
LTRIM(RTRIM(REPLACE(REPLACE(ISNULL(Form_Nm,''),'-',''),'FORM',''))) = 'H') B ON (A.TRAN_CD = B.TRAN_CD AND A.INV_NO = B.INV_NO AND A.BHENT = B.BHENT AND
ISNULL(A.It_code,0) = ISNULL(B.It_code,0) AND A.ItSerial = B.ItSerial AND A.AC_ID = B.AC_ID)
GROUP BY A.BHENT,A.Inv_no,A.Date,ISNULL(A.It_code,0),A.ST_Type,A.S_TAX,A.AC_NAME,I.it_name,A.U_IMPORM,A.PER,AC.State
UNION
SELECT A.BHENT,A.Inv_no,A.Date,A.S_TAX,A.AC_NAME,A.ST_Type,ISNULL(A.It_code,0) as It_Code,I.it_name,A.U_IMPORM,AMT1=0,ISNULL(SUM(B.VATONAMT),0) as AMT2,
AMT3=0,AMT4=0,AMT5=0,AMT6=0,AMT7=0,AMT8=0,ISNULL(SUM(A.Gro_AMT),0) AS AMT9,AMT10=0,AMT11=0,AMT12=0,AC.State FROM VATTBL A
INNER JOIN AC_MAST AC ON (A.AC_ID = AC.Ac_id) INNER JOIN IT_MAST I ON (ISNULL(A.It_code,0) = ISNULL(I.It_code,0)) INNER JOIN
(Select * from VATTBL WHERE BHENT IN('PT','P1') AND St_Type IN('OUT OF COUNTRY','OUT OF STATE') AND U_IMPORM IN('Branch Transfer','Consignment Transfer')) B
ON (A.TRAN_CD = B.TRAN_CD AND A.INV_NO = B.INV_NO AND A.BHENT = B.BHENT AND ISNULL(A.It_code,0) = ISNULL(B.It_code,0) AND A.ItSerial = B.ItSerial
AND A.AC_ID = B.AC_ID) GROUP BY A.BHENT,A.Inv_no,A.Date,ISNULL(A.It_code,0),A.ST_Type,A.S_TAX,A.AC_NAME,I.it_name,A.U_IMPORM,A.PER,AC.State
UNION
SELECT A.BHENT,A.Inv_no,A.Date,A.S_TAX,A.AC_NAME,A.ST_Type,ISNULL(A.It_code,0) as it_code,I.it_name,A.U_IMPORM,AMT1=0,AMT2=0,ISNULL(SUM(B.VATONAMT),0) as
AMT3,AMT4=0,AMT5=0,AMT6=0,AMT7=0,AMT8=0,ISNULL(SUM(A.Gro_AMT),0) AS AMT9,AMT10=0,AMT11=0,AMT12=0,AC.State FROM VATTBL A INNER JOIN AC_MAST AC ON
(A.AC_ID = AC.Ac_id) INNER JOIN IT_MAST I ON (ISNULL(A.It_code,0) = ISNULL(I.It_code,0)) INNER JOIN (Select * from VATTBL WHERE BHENT IN('PT') AND
PER <> 0 AND TAXAMT > 0 AND ST_Type = 'OUT OF STATE' AND U_IMPORM NOT IN('Branch Transfer','Consignment Transfer')
AND LTRIM(RTRIM(REPLACE(REPLACE(ISNULL(Form_Nm,''),'-',''),'FORM',''))) = 'C') B
ON (A.TRAN_CD = B.TRAN_CD AND A.INV_NO = B.INV_NO AND A.BHENT = B.BHENT AND ISNULL(A.It_code,0) = ISNULL(B.It_code,0) AND A.ItSerial = B.ItSerial
AND A.AC_ID = B.AC_ID) GROUP BY A.BHENT,A.Inv_no,A.Date,ISNULL(A.It_code,0),A.ST_Type,A.S_TAX,A.AC_NAME,I.it_name,A.U_IMPORM,A.PER,AC.State
UNION
SELECT A.BHENT,A.Inv_no,A.Date,A.S_TAX,A.AC_NAME,A.ST_Type,ISNULL(A.It_code,0) as It_code,I.it_name,A.U_IMPORM,AMT1=0,AMT2=0,AMT3=0,
ISNULL(SUM(B.VATONAMT),0) as AMT4,AMT5=0,AMT6=0,AMT7=0,AMT8=0,ISNULL(SUM(A.Gro_AMT),0) AS AMT9,AMT10=0,AMT11=0,AMT12=0,AC.State FROM VATTBL A
INNER JOIN AC_MAST AC ON (A.AC_ID = AC.Ac_id) INNER JOIN IT_MAST I ON (ISNULL(A.It_code,0) = ISNULL(I.It_code,0)) INNER JOIN
(Select * from VATTBL WHERE BHENT IN('PT') AND PER = 0 AND TAXAMT = 0 AND ST_Type = 'OUT OF STATE' AND
U_IMPORM NOT IN('Branch Transfer','Consignment Transfer') AND
LTRIM(RTRIM(REPLACE(REPLACE(ISNULL(Form_Nm,''),'-',''),'FORM',''))) = 'C') B ON (A.TRAN_CD = B.TRAN_CD AND A.INV_NO = B.INV_NO AND A.BHENT = B.BHENT
AND ISNULL(A.It_code,0) = ISNULL(B.It_code,0) AND A.ItSerial = B.ItSerial AND A.AC_ID = B.AC_ID)
GROUP BY A.BHENT,A.Inv_no,A.Date,ISNULL(A.It_code,0),A.ST_Type,A.S_TAX,A.AC_NAME,I.it_name,A.U_IMPORM,A.PER,AC.State
UNION
SELECT A.BHENT,A.Inv_no,A.Date,A.S_TAX,A.AC_NAME,A.ST_Type,ISNULL(A.It_code,0) as It_code,I.it_name,A.U_IMPORM,AMT1=0,AMT2=0,AMT3=0,AMT4=0,
ISNULL(SUM(B.VATONAMT),0) as AMT5,AMT6=0,AMT7=0,AMT8=0,ISNULL(SUM(A.Gro_AMT),0) AS AMT9,AMT10=0,AMT11=0,AMT12=0,AC.State FROM VATTBL A
INNER JOIN AC_MAST AC ON (A.AC_ID = AC.Ac_id) INNER JOIN IT_MAST I ON (ISNULL(A.It_code,0) = ISNULL(I.It_code,0)) INNER JOIN
(Select * from VATTBL WHERE BHENT IN('PT','P1') AND PER = 0 AND TAXAMT = 0 AND ST_Type = 'OUT OF COUNTRY' AND
U_IMPORM NOT IN('Branch Transfer','Consignment Transfer','Direct Imports','Import from Outside India','High Seas Purchases') AND
LTRIM(RTRIM(REPLACE(REPLACE(ISNULL(Form_Nm,''),'-',''),'FORM',''))) = 'H') B  ON (A.TRAN_CD = B.TRAN_CD AND A.INV_NO = B.INV_NO AND A.BHENT = B.BHENT
AND ISNULL(A.It_code,0) = ISNULL(B.It_code,0) AND A.ItSerial = B.ItSerial AND A.AC_ID = B.AC_ID)
GROUP BY A.BHENT,A.Inv_no,A.Date,ISNULL(A.It_code,0),A.ST_Type,A.S_TAX,A.AC_NAME,I.it_name,A.U_IMPORM,A.PER,AC.State
UNION SELECT * from ##Table1
UNION
SELECT A.BHENT,A.Inv_no,A.Date,A.S_TAX,A.AC_NAME,A.ST_Type,ISNULL(A.It_code,0) as It_code,I.it_name,A.U_IMPORM,AMT1=0,AMT2=0,AMT3=0,AMT4=0,AMT5=0,AMT6=0,
ISNULL(SUM(B.VATONAMT),0) as AMT7,AMT8=0,ISNULL(SUM(A.Gro_AMT),0) AS AMT9,AMT10=0,AMT11=0,AMT12=0,AC.State FROM VATTBL A
INNER JOIN AC_MAST AC ON (A.AC_ID = AC.Ac_id) INNER JOIN IT_MAST I ON (ISNULL(A.It_code,0) = ISNULL(I.It_code,0)) INNER JOIN
(Select * from VATTBL WHERE BHENT IN('PT','P1') AND S_TAX = '' AND ST_TYPE IN ('OUT OF COUNTRY','OUT OF STATE') AND
U_IMPORM NOT IN('Branch Transfer','Consignment Transfer') AND LTRIM(RTRIM(REPLACE(REPLACE(ISNULL(Form_Nm,''),'-',''),'FORM',''))) NOT IN ('H','C')) B
ON (A.TRAN_CD = B.TRAN_CD AND A.INV_NO = B.INV_NO AND A.BHENT = B.BHENT AND ISNULL(A.It_code,0) = ISNULL(B.It_code,0) AND A.ItSerial = B.ItSerial
AND A.AC_ID = B.AC_ID) GROUP BY A.BHENT,A.Inv_no,A.Date,ISNULL(A.It_code,0),A.ST_Type,A.S_TAX,A.AC_NAME,I.it_name,A.U_IMPORM,A.PER,AC.State
UNION
SELECT A.BHENT,A.Inv_no,A.Date,A.S_TAX,A.AC_NAME,A.ST_Type,ISNULL(A.It_code,0) as It_code,I.it_name,A.U_IMPORM,AMT1=0,AMT2=0,AMT3=0,
AMT4=0,AMT5=0,AMT6=0,AMT7=0,ISNULL(SUM(B.VATONAMT),0) as AMT8,ISNULL(SUM(A.Gro_AMT),0) AS AMT9,AMT10=0,AMT11=0,AMT12=0,AC.State FROM VATTBL A
INNER JOIN AC_MAST AC ON (A.AC_ID = AC.Ac_id) INNER JOIN IT_MAST I ON (ISNULL(A.It_code,0) = ISNULL(I.It_code,0)) INNER JOIN
(Select * from VATTBL WHERE BHENT IN('PT','P1') AND ST_Type IN('OUT OF STATE','OUT OF COUNTRY') AND PER = 1 AND S_tax <> '' AND
(TAX_NAME Like '%CST%' OR TAX_NAME Like '%C.S.T%') AND 
U_IMPORM NOT IN('Branch Transfer','Consignment Transfer','Direct Imports','Import from Outside India','High Seas Purchases') AND
LTRIM(RTRIM(REPLACE(REPLACE(ISNULL(Form_Nm,''),'-',''),'FORM',''))) NOT IN ('C','H')) B
ON (A.TRAN_CD = B.TRAN_CD AND A.INV_NO = B.INV_NO AND A.BHENT = B.BHENT AND ISNULL(A.It_code,0) = ISNULL(B.It_code,0) AND A.ItSerial = B.ItSerial
AND A.AC_ID = B.AC_ID) GROUP BY A.BHENT,A.Inv_no,A.Date,ISNULL(A.It_code,0),A.ST_Type,A.S_TAX,A.AC_NAME,I.it_name,A.U_IMPORM,A.PER,AC.State
UNION
SELECT A.BHENT,A.Inv_no,A.Date,A.S_TAX,A.AC_NAME,A.ST_Type,ISNULL(A.It_code,0) as It_code,I.it_name,A.U_IMPORM,AMT1=0,AMT2=0,AMT3=0,
AMT4=0,AMT5=0,AMT6=0,AMT7=0,AMT8=0,ISNULL(SUM(A.Gro_AMT),0) AS AMT9,ISNULL(SUM(B.VATONAMT),0) as AMT10,AMT11=0,AMT12=0,AC.State FROM VATTBL A
INNER JOIN AC_MAST AC ON (A.AC_ID = AC.Ac_id) INNER JOIN IT_MAST I ON (ISNULL(A.It_code,0) = ISNULL(I.It_code,0)) INNER JOIN
(Select * from VATTBL WHERE BHENT IN('PT','P1') AND ST_Type IN('OUT OF STATE','OUT OF COUNTRY') AND PER = 4 AND S_tax <> '' AND
(TAX_NAME Like '%CST%' OR TAX_NAME Like '%C.S.T%') AND 
U_IMPORM NOT IN('Branch Transfer','Consignment Transfer','Direct Imports','Import from Outside India','High Seas Purchases') AND
LTRIM(RTRIM(REPLACE(REPLACE(ISNULL(Form_Nm,''),'-',''),'FORM',''))) NOT IN ('C','H')) B
ON (A.TRAN_CD = B.TRAN_CD AND A.INV_NO = B.INV_NO AND A.BHENT = B.BHENT AND ISNULL(A.It_code,0) = ISNULL(B.It_code,0) AND A.ItSerial = B.ItSerial
AND A.AC_ID = B.AC_ID) GROUP BY A.BHENT,A.Inv_no,A.Date,ISNULL(A.It_code,0),A.ST_Type,A.S_TAX,A.AC_NAME,I.it_name,A.U_IMPORM,A.PER,AC.State
UNION
SELECT A.BHENT,A.Inv_no,A.Date,A.S_TAX,A.AC_NAME,A.ST_Type,ISNULL(A.It_code,0) as It_code,I.it_name,A.U_IMPORM,AMT1=0,AMT2=0,AMT3=0,
AMT4=0,AMT5=0,AMT6=0,AMT7=0,AMT8=0,ISNULL(SUM(A.Gro_AMT),0) AS AMT9,AMT10=0,ISNULL(SUM(B.VATONAMT),0) as AMT11,AMT12=0,AC.State FROM VATTBL A
INNER JOIN AC_MAST AC ON (A.AC_ID = AC.Ac_id) INNER JOIN IT_MAST I ON (ISNULL(A.It_code,0) = ISNULL(I.It_code,0)) INNER JOIN
(Select * from VATTBL WHERE BHENT IN('PT','P1') AND ST_Type IN('OUT OF STATE','OUT OF COUNTRY') AND PER = 12.5 AND S_tax <> '' AND
(TAX_NAME Like '%CST%' OR TAX_NAME Like '%C.S.T%') AND
U_IMPORM NOT IN('Branch Transfer','Consignment Transfer','Direct Imports','Import from Outside India','High Seas Purchases') AND
LTRIM(RTRIM(REPLACE(REPLACE(ISNULL(Form_Nm,''),'-',''),'FORM',''))) NOT IN ('C','H')) B
ON (A.TRAN_CD = B.TRAN_CD AND A.INV_NO = B.INV_NO AND A.BHENT = B.BHENT AND ISNULL(A.It_code,0) = ISNULL(B.It_code,0) AND A.ItSerial = B.ItSerial
AND A.AC_ID = B.AC_ID) GROUP BY A.BHENT,A.Inv_no,A.Date,ISNULL(A.It_code,0),A.ST_Type,A.S_TAX,A.AC_NAME,I.it_name,A.U_IMPORM,A.PER,AC.State
UNION
SELECT A.BHENT,A.Inv_no,A.Date,A.S_TAX,A.AC_NAME,A.ST_Type,ISNULL(A.It_code,0) as It_code,I.it_name,A.U_IMPORM,AMT1=0,AMT2=0,AMT3=0,
AMT4=0,AMT5=0,AMT6=0,AMT7=0,AMT8=0,ISNULL(SUM(A.Gro_AMT),0) AS AMT9,AMT10=0,AMT11=0,ISNULL(SUM(B.VATONAMT),0) as AMT12,AC.State FROM VATTBL A
INNER JOIN AC_MAST AC ON (A.AC_ID = AC.Ac_id) INNER JOIN IT_MAST I ON (ISNULL(A.It_code,0) = ISNULL(I.It_code,0)) INNER JOIN
(Select * from VATTBL WHERE BHENT IN('PT','P1') AND ST_Type IN('OUT OF STATE','OUT OF COUNTRY') AND PER = 20 AND S_tax <> '' AND
(TAX_NAME Like '%CST%' OR TAX_NAME Like '%C.S.T%') AND
U_IMPORM NOT IN('Branch Transfer','Consignment Transfer','Direct Imports','Import from Outside India','High Seas Purchases') AND
LTRIM(RTRIM(REPLACE(REPLACE(ISNULL(Form_Nm,''),'-',''),'FORM',''))) NOT IN ('C','H')) B
ON (A.TRAN_CD = B.TRAN_CD AND A.INV_NO = B.INV_NO AND A.BHENT = B.BHENT AND ISNULL(A.It_code,0) = ISNULL(B.It_code,0) AND A.ItSerial = B.ItSerial
AND A.AC_ID = B.AC_ID) GROUP BY A.BHENT,A.Inv_no,A.Date,ISNULL(A.It_code,0),A.ST_Type,A.S_TAX,A.AC_NAME,I.it_name,A.U_IMPORM,A.PER,AC.State
) FINAL
WHERE (AMT1 + AMT2 + AMT3 + AMT4 + AMT5 + AMT6 + AMT7 + AMT8 + AMT9 + AMT10 + AMT11 + AMT12) > 0
AND Date Between @sdate and @edate GROUP BY BHENT,Inv_no,Date,S_TAX,AC_NAME,ST_Type,It_code,it_name,State
ORDER BY Date,Inv_no,AC_NAME,it_name,S_TAX

DROP TABLE ##Table1

IF NOT EXISTS(SELECT TOP 1 PART FROM #DMVAT30A )
BEGIN
	INSERT INTO #DMVAT30A (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,INV_NO,DATE,PARTY_NM,ADDRESS,S_TAX,It_code)
	VALUES (1,'1','A',0,0,0,0,'','','','','',0)
END

Update #DMVAT30A SET PART = ISNULL(Part,0) , Partsr = ISNULL(PARTSR,''), SRNO = ISNULL(SRNO,''),RATE = ISNULL(RATE,0),AMT1 = ISNULL(AMT1,0),
AMT2 = ISNULL(AMT2,0),AMT3 = ISNULL(AMT3,0),AMT4 = ISNULL(AMT4,0),AMT5 = ISNULL(AMT5,0),AMT6 = ISNULL(AMT6,0),AMT7 = ISNULL(AMT7,0),AMT8 = ISNULL(AMT8,0),
AMT9 = ISNULL(AMT9,0),AMT10 = ISNULL(AMT10,0),AMT11 = ISNULL(AMT11,0),AMT12 = ISNULL(AMT12,0), INV_NO = ISNULL(INV_NO,''), DATE = ISNULL(Date,''), 
PARTY_NM = ISNULL(Party_nm,''), ADDRESS = ISNULL(Address,''),S_TAX = ISNULL(S_tax,''),State = ISNULL(State,''),it_name = ISNULL(it_name,''),
ST_Type = ISNULL(ST_Type,0),It_code = ISNULL(IT_code,0)


SELECT * FROM #DMVAT30A WHERE (AMT1 + AMT2 + AMT3 + AMT4 + AMT5 + AMT7 + AMT8 + AMT9 + AMT10 + AMT11 + AMT12) > 0
order by cast(substring(partsr,1,case when (isnumeric(substring(partsr,1,2))=1) then 2 else 1 end) as int), partsr,SRNO

End
GO


