If Exists(Select [name] From SysObjects Where xtype='P' and [Name]='USP_REP_CH_VATFORM15')
Begin
	Drop Procedure USP_REP_CH_VATFORM15
End
Go
/*
	=========================================
	Author  : Suraj Kumawat
	DATE : 23-06-2016  for bug-28048
	
	=========================================
    EXECUTE USP_REP_CH_VATFORM15 '','','','04/01/2010','03/31/2019','','','','',0,0,'','','','','','','','','2013-2014',''
*/
CREATE PROCEDURE [dbo].[USP_REP_CH_VATFORM15]
@TMPAC NVARCHAR(50),@TMPIT NVARCHAR(50),@SPLCOND VARCHAR(8000),@SDATE  SMALLDATETIME,@EDATE SMALLDATETIME
,@SAC AS VARCHAR(60),@EAC AS VARCHAR(60)
,@SIT AS VARCHAR(60),@EIT AS VARCHAR(60)
,@SAMT FLOAT,@EAMT FLOAT
,@SDEPT AS VARCHAR(60),@EDEPT AS VARCHAR(60) 
,@SCATE AS VARCHAR(60),@ECATE AS VARCHAR(60)
,@SWARE AS VARCHAR(60),@EWARE AS VARCHAR(60)
,@SINV_SR AS VARCHAR(60),@EINV_SR AS VARCHAR(60)
,@LYN VARCHAR(20)
,@EXPARA  AS VARCHAR(60)= null

AS
BEGIN
SET NOCOUNT ON
Declare @FCON as NVARCHAR(2000),@VSAMT DECIMAL(14,2),@VEAMT DECIMAL(14,2)
EXECUTE  USP_REP_FILTCON 
@VTMPAC =@TMPAC,@VTMPIT =@TMPIT,@VSPLCOND =@SPLCOND
,@VSDATE=NULL
,@VEDATE=@EDATE
,@VSAC =@SAC,@VEAC =@EAC
,@VSIT=@SIT,@VEIT=@EIT
,@VSAMT=@SAMT,@VEAMT=@EAMT
,@VSDEPT=@SDEPT,@VEDEPT=@EDEPT
,@VSCATE =@SCATE,@VECATE =@ECATE
,@VSWARE =@SWARE,@VEWARE  =@EWARE
,@VSINV_SR =@SINV_SR,@VEINV_SR =@SINV_SR
,@VMAINFILE='M',@VITFILE=NULL,@VACFILE=NULL
,@VDTFLD ='DATE'
,@VLYN=NULL
,@VEXPARA=@EXPARA
,@VFCON =@FCON OUTPUT

---- Temprory Table Creation.
SELECT PART=3,PARTSR='AAA',SRNO='AAA',RATE=99.999,AMT1=CAST('0' AS NUMERIC(20,2)),AMT2=CAST('0' AS NUMERIC(20,2)),AMT3=CAST('0' AS NUMERIC(20,2)),
M.INV_NO,M.DATE,PARTY_NM=AC1.AC_NAME,ADDRESS=Ltrim(AC1.Add1)+' '+Ltrim(AC1.Add2)+' '+Ltrim(AC1.Add3),STM.FORM_NM,AC1.S_TAX
,STM.RFORM_NM,CAST('0' AS NUMERIC(20,2)) AS AMT4,CAST('0' AS NUMERIC(20,2)) AS AMT5
,TAX_NAME=CAST('' AS VARCHAR(12)),n.item,EIT_NAME=CAST('' AS VARCHAR(50)),CONTTAX=CAST(0 AS DECIMAL(12,2)),CTYPE=CAST('' AS VARCHAR(2)) 
INTO #CH_VAT_FORM15
FROM PTACDET A 
INNER JOIN STMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)
INNER JOIN STAX_MAS STM ON (M.TAX_NAME=STM.TAX_NAME)
INNER JOIN AC_MAST AC ON (A.AC_NAME=AC.AC_NAME)
INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID)
inner join stitem n on (m.tran_cd=n.tran_cd) 
WHERE 1=2

Declare @MultiCo	VarChar(3)
Declare @MCON as NVARCHAR(2000)
IF Exists(Select A.ID From SysObjects A Inner Join SysColumns B On(A.ID = B.ID) Where A.[Name] = 'STMAIN' And B.[Name] = 'DBNAME')
	Begin	------Fetch Records from Multi Co. Data
		 Set @MultiCo = 'YES'
		 EXECUTE USP_REP_MULTI_CO_DATA
		  @TMPAC, @TMPIT, @SPLCOND, @SDATE, @EDATE
		 ,@SAC, @EAC, @SIT, @EIT, @SAMT, @EAMT
		 ,@SDEPT, @EDEPT, @SCATE, @ECATE,@SWARE
		 ,@EWARE, @SINV_SR, @EINV_SR, @LYN, @EXPARA
		 ,@MFCON = @MCON OUTPUT

	End
else
	Begin ------Fetch Single Co. Data
		 Set @MultiCo = 'NO'
		 EXECUTE USP_REP_SINGLE_CO_DATA_vat
		  @TMPAC, @TMPIT, @SPLCOND, @SDATE, @EDATE
		 ,@SAC, @EAC, @SIT, @EIT, @SAMT, @EAMT
		 ,@SDEPT, @EDEPT, @SCATE, @ECATE,@SWARE
		 ,@EWARE, @SINV_SR, @EINV_SR, @LYN, @EXPARA
		 ,@MFCON = @MCON OUTPUT

	End
DECLARE @AMTA1 DECIMAL(18,2),@AMTA2 DECIMAL(18,2),@AMTA3 DECIMAL(18,2),@AMTA4 DECIMAL(18,2),@AMTA5 DECIMAL(18,2)

---1. SALES DETAILS
---Gross Sales*
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='ST' AND  ( DATE BETWEEN @SDATE  AND @EDATE )
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','A',0,@AMTA1,0,0,'')
---Less : Zero rated sales
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 =  @AMTA1 + ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='ST' AND U_IMPORM NOT IN('Export Out of India') 
AND ( DATE BETWEEN @SDATE AND @EDATE ) 
AND (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(RFORM_NM,'FORM',''),'-',''),' ',''))) = 'H' OR RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(TAX_NAME ,'FORM',''),'-',''),' ',''))) = 'H' )
---Export out of India
SELECT @AMTA1 = @AMTA1 + ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='ST' AND U_IMPORM IN('Export Out of India')  AND ST_TYPE ='OUT OF COUNTRY'
AND ( DATE BETWEEN @SDATE AND @EDATE ) AND (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(RFORM_NM,'FORM',''),'-',''),' ',''))) = 'H' OR RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(TAX_NAME ,'FORM',''),'-',''),' ',''))) = 'H' )
---Sales against E1/E2 forms
SELECT @AMTA1 = @AMTA1 +  ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='ST' 
AND ( DATE BETWEEN @SDATE AND @EDATE ) AND (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(RFORM_NM,'FORM',''),'-',''),'/',''),' ',''))) IN('E1','E2','EI','EII','E 1','E 2','E I','E II') OR RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(TAX_NAME ,'FORM',''),'-',''),'/',''),' ',''))) IN('E1','E2','EI','EII','E 1','E 2','E I','E II'))
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','B',0,@AMTA1,0,0,'')

---Less : Inter- state sales
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='ST' AND  ( DATE BETWEEN @SDATE  AND @EDATE )
AND ST_TYPE ='OUT OF STATE' AND TAX_NAME LIKE '%C.S.T%'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','C',0,@AMTA1,0,0,'')
---Less : Tax free sales
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='ST' AND  ( DATE BETWEEN @SDATE  AND @EDATE )
AND TAX_NAME  like '%Exempted%' AND PER = 0 AND U_IMPORM not IN('Branch Transfer','Consignment Transfer') 
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','D',0,@AMTA1,0,0,'')
---Less : Deductions(Sales return, Cash/trade discount etc.)
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='SR' AND  ( DATE BETWEEN @SDATE  AND @EDATE )
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','E',0,@AMTA1,0,0,'')
---Less : 
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='ST' AND  ( DATE BETWEEN @SDATE  AND @EDATE )
AND U_IMPORM = 'Tax element included in sales' 
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','F',0,@AMTA1,0,0,'')
---Net sales subject to VAT
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 =ISNULL(SUM(AMT1),0) FROM #CH_VAT_FORM15 WHERE PART = 1  AND PARTSR ='1' AND SRNO = 'A'
SELECT @AMTA2 =ISNULL(SUM(AMT1),0) FROM #CH_VAT_FORM15 WHERE PART = 1  AND PARTSR ='1' AND SRNO IN('B','C','D','E','F')
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','G',0,(@AMTA1-@AMTA2),0,0,'')
---Branch Transfers/Consignment Transfers
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='ST' AND  ( DATE BETWEEN @SDATE  AND @EDATE )
AND U_IMPORM IN('Branch Transfer','Consignment Transfer') 
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','H',0,@AMTA1,0,0,'')

--- 2. PURCHASE DETAILS
---	(A)Gross Purchases (excluding capital goods and but including goods received by stock transfer)
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='PT' AND  ( DATE BETWEEN @SDATE  AND @EDATE )
AND itemtype = 'I'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (2,'2','A',0,@AMTA1,0,0,'')
---( b )	Less : Imports from outside India
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT in('PT','P1') AND  (DATE BETWEEN @SDATE  AND @EDATE )
and ST_TYPE ='OUT OF COUNTRY' 
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (2,'2','B',0,@AMTA1,0,0,'')
---( c )	Less : Inter-State Purchases/goods received from Branches/principals outside U.T., Chandigarh
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='PT' AND  ( DATE BETWEEN @SDATE  AND @EDATE )
AND ST_TYPE ='OUT OF STATE' 
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (2,'2','C',0,@AMTA1,0,0,'')
---( d )	Less : Tax free Purchases											
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='PT' AND  ( DATE BETWEEN @SDATE  AND @EDATE )
AND Tax_name like '%Exempted%' AND PER = 0  aND U_IMPORM not IN('Branch Transfer','Consignment Transfer') 
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (2,'2','D',0,@AMTA1,0,0,'')
---( e )	Less : Purchases liable to purchase Tax u/s 19(1) and 20 
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='PT' AND  ( DATE BETWEEN @SDATE  AND @EDATE )
AND U_IMPORM ='Purchases liable to purchase Tax u/s 19(1) and 20 ' and S_TAX <> ''
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (2,'2','E',0,@AMTA1,0,0,'')
---( f )	Less : Deductions(purchases return and cash /trade discount etc.)
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='PR' AND  ( DATE BETWEEN @SDATE  AND @EDATE )
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (2,'2','F',0,@AMTA1,0,0,'')
---( g )	Net: purchases eligible for input tax credit [a-(b+c+d+e+f)]
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(AMT1),0) FROM #CH_VAT_FORM15 WHERE PART = 2 AND PARTSR ='2' AND SRNO = 'A'
SELECT @AMTA2 = ISNULL(SUM(AMT1),0) FROM #CH_VAT_FORM15 WHERE PART = 2 AND PARTSR ='2' AND SRNO IN( 'B','C','D','E','F')
PRINT @AMTA1
PRINT @AMTA2
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (2,'2','G',0,(@AMTA1-@AMTA2),0,0,'')
---( h )	Purchases of capital goods eligible for input tax credit
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='PT' AND  ( DATE BETWEEN @SDATE  AND @EDATE )
AND S_TAX <> '' AND itemtype ='C' AND TAXAMT <> 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (2,'2','H',0,@AMTA1,0,0,'')
--3	OUTPUT TAX					
---( a )	VAT on net taxable sales within the return period
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 =ISNULL(SUM(TAXAMT),0) FROM VATTBL WHERE BHENT ='ST' AND  ( DATE BETWEEN @SDATE AND @EDATE ) 
AND  TAX_NAME LIKE '%VAT%'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (3,'3','A',0,@AMTA1,0,0,'')
---( b )	Add : Purchases Tax on turnover as per Col. 2( e )
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(TAXAMT),0) FROM VATTBL WHERE BHENT ='PT' AND  ( DATE BETWEEN @SDATE  AND @EDATE )
AND U_IMPORM ='Purchases liable to purchase Tax u/s 19(1) and 20 ' and S_TAX <> '' AND TAX_NAME LIKE '%VAT%'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (3,'3','B',0,@AMTA1,0,0,'')
---( c )	LESS	Add/Less : Output tax for prior period adjustment
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A LEFT OUTER JOIN JVACDET B ON (A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.VAT_ADJ ='Adjustment to Output Tax' AND ( A.DATE BETWEEN @SDATE AND @EDATE ) 
AND A.party_nm ='VAT PAYABLE'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (3,'3','C',0,@AMTA1,0,0,'')
---( d )	Total Output tax					
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 =ISNULL(SUM(AMT1),0) FROM #CH_VAT_FORM15 WHERE PART = 3 AND PARTSR = '3' AND SRNO in('A','B')
SELECT @AMTA2 =ISNULL(SUM(AMT1),0) FROM #CH_VAT_FORM15 WHERE PART = 3 AND PARTSR = '3' AND SRNO ='C'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (3,'3','D',0,(@AMTA1-@AMTA2),0,0,'')
--- 4	INPUT TAX CREDIT ON ACTUAL BASIS					
---( a )	ITC brought forward from previous year
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='ITC brought forward from previous year' AND A.party_nm ='VAT PAYABLE' AND (A.DATE BETWEEN @SDATE AND @EDATE )
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (4,'4','A',0,@AMTA1,0,0,'')
---( b )	Add ITC on Non Capital goods
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(TAXAMT),0) FROM VATTBL WHERE BHENT = 'PT' AND S_TAX <> '' AND ( DATE BETWEEN @SDATE AND @EDATE) AND itemtype ='I' and tax_name like '%vat%'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (4,'4','B',0,@AMTA1,0,0,'')
---( c )	Add ITC on Capital goods
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(TAXAMT),0) FROM VATTBL WHERE BHENT = 'PT' AND S_TAX <> '' AND ( DATE BETWEEN @SDATE AND @EDATE) AND itemtype ='C' and tax_name like '%vat%'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (4,'4','C',0,@AMTA1,0,0,'')
---( d )	Add: Installment of ITC on stock held on appointed day
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='Installment of ITC on stock held on appointed day' AND A.party_nm ='VAT PAYABLE'  AND (A.DATE BETWEEN @SDATE AND @EDATE )
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (4,'4','D',0,@AMTA1,0,0,'')
---( e )	Add TDS, if any
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='TDS' AND A.party_nm ='VAT PAYABLE'  AND (A.DATE BETWEEN @SDATE AND @EDATE )
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (4,'4','E',0,@AMTA1,0,0,'')
---( f )	Less: Apportionment of ITC on manufacturing tax free goods
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='Apportionment of ITC on manufacturing tax free goods' AND A.party_nm ='VAT PAYABLE'  AND (A.DATE BETWEEN @SDATE AND @EDATE )
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (4,'4','F',0,@AMTA1,0,0,'')

---( g )	Less: Apportionment of ITC for branch transfer
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='Apportionment of ITC for branch transfer' AND A.party_nm ='VAT PAYABLE'  AND (A.DATE BETWEEN @SDATE AND @EDATE )
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (4,'4','G',0,@AMTA1,0,0,'')

---( h )	LESS	Add/Less : adjustment ITC for purchase return/discount
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='Adjustment to Input Tax' AND A.party_nm ='VAT PAYABLE'  AND (A.DATE BETWEEN @SDATE AND @EDATE )
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (4,'4','H',0,@AMTA1,0,0,'')
---( i )	ADD	Add/Less : reversal of ITC
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='Reversal of Input Tax Credit' AND A.party_nm ='VAT PAYABLE'  AND (A.DATE BETWEEN @SDATE AND @EDATE )
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (4,'4','I',0,@AMTA1,0,0,'')
---( j )	Total input tax credit available
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(AMT1),0) FROM #CH_VAT_FORM15 WHERE PART = 4 AND PARTSR = '4' AND SRNO IN('A','B','C','D','E','I')
SELECT @AMTA2 = ISNULL(SUM(AMT1),0) FROM #CH_VAT_FORM15 WHERE PART = 4 AND PARTSR = '4' AND SRNO IN('F','G','H')
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (4,'4','J',0,(@AMTA1-@AMTA2) ,0,0,'')

---4-A	INPUT TAX CREDIT ON NOTIONAL BASIS					
--( a )	Brought forward from previous year
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (5,'5','A',0,@AMTA1,0,0,'')

--( b )	Add ITC notional on Non Capital goods
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (5,'5','B',0,@AMTA1,0,0,'')
--( c )	Add ITC notional on Capital goods
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (5,'5','C',0,@AMTA1,0,0,'')

--( d )	Less: Apportionment of Notional ITC on manufacturing tax free goods
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (5,'5','D',0,@AMTA1,0,0,'')

--( e )	Reversal of Notional ITC on account of sales
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (5,'5','E',0,@AMTA1,0,0,'')

--( f )	Reversal of Notional ITC on branch transfer and consignment
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (5,'5','F',0,@AMTA1,0,0,'')
--( g )	Reversal of Notional ITC on purchase return
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (5,'5','G',0,@AMTA1,0,0,'')
--( h )	Total Notional input tax credit available
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (5,'5','H',0,@AMTA1,0,0,'')

--5	TAX PAYABLE/EXCESS INPUT TAX CREDIT
--( a )	Total output tax [as per 3 ( d )]
SET @AMTA1 = 0
set @AMTA5 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(AMT1),0) FROM #CH_VAT_FORM15 WHERE PART = 3 AND PARTSR ='3' AND SRNO = 'D'
set @AMTA5 = @AMTA1
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (6,'6','A',0,@AMTA1,0,0,'')
--( b )	Less:Total actual ITC as per col. 4(j)
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(AMT1),0) FROM #CH_VAT_FORM15 WHERE PART = 4 AND PARTSR ='4' AND SRNO = 'J'
set @AMTA5 = @AMTA5 -  @AMTA1
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (6,'6','B',0,@AMTA1,0,0,'')
--( c )	Difference(a-b) (if output tax is more than input tax, balance is adjusted out on Notional ITC, if any otherwise amount is to be deposited)
SET @AMTA1 = @AMTA5
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (6,'6','C',0,@AMTA1,0,0,'')
--( d )	Excess ITC if any, after adjustment in (c)
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (6,'6','D1',0,@AMTA1,0,0,'')

-- d (i) Actual
SET @AMTA1 = case when @AMTA5 < 0 then abs(@AMTA5) else 0 end
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (6,'6','D2',0,@AMTA1,0,0,'')
-- d  d (ii) Notional
SET @AMTA1 = case when @AMTA5 > 0 then @AMTA5 else 0 end
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (6,'6','D3',0,@AMTA1,0,0,'')
-- ( e )	CST liability  for the return period, if any.
-- 
SET @AMTA5 = 0
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='CST liability  for the return period' AND A.party_nm ='CST PAYABLE'  AND (A.DATE BETWEEN @SDATE AND @EDATE )
SET @AMTA5 = @AMTA1
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (6,'6','E',0,@AMTA1,0,0,'')
-- ( f )	Excess actual ITC as per col. (d) if any
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 =ISNULL(SUM(AMT1),0) FROM #CH_VAT_FORM15 WHERE PART = 6 AND PARTSR ='6' AND SRNO ='D2'
SET @AMTA5 = @AMTA5- @AMTA1
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (6,'6','F',0,@AMTA1,0,0,'')
-- ( g )	Difference(e-f) (if output tax is more than input tax, Balance is adjusted out of Notional ITC, if any .Otherwise amount is to be deposited)
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (6,'6','G',0,@AMTA5,0,0,'')
-- ( h )	Excess ITC if any, after adjustment under (g) :to be carried down to next return period
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (6,'6','H1',0,@AMTA1,0,0,'')
--   h(i) Actual
SET @AMTA1 = CASE  WHEN @AMTA5 < 0  THEN abs(@AMTA5) ELSE 0 END
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (6,'6','H2',0,@AMTA1,0,0,'')
--    h(ii) Notional
SET @AMTA1 = CASE  WHEN @AMTA5 > 0  THEN @AMTA5 ELSE 0 END
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (6,'6','H3',0,@AMTA1,0,0,'')
--  6*	DETAILS OF TAX PAYMENT DURING THE RETURN PERIOD						
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,s_tax,rform_nm,inv_no,date)
SELECT 7 as PART,'7' as PARTSR ,'A' as SRNO,0 as rate,a.net_amt,0 as amt2,0 as amt3,a.bank_nm,b.bsrcode,isnull(a.DEP_MODE,''),a.U_CHALNO,a.U_CHALDT
from BPMAIN a inner join AC_MAST b on(a.bank_nm =b.ac_name) where a.entry_ty ='bp' and a.party_nm ='VAT payable'
and a.date between @SDATE and @EDATE 
IF NOT EXISTS(SELECT TOP 1 SRNO FROM #CH_VAT_FORM15 WHERE PART = 7 AND PARTSR ='7' AND SRNO ='A')
BEGIN
	INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (7,'7','A',0,@AMTA1,0,0,'')
END
--------------------------------------------------------------------------------------------------------------------------------------
												--WORKSHEET --
--------------------------------------------------------------------------------------------------------------------------------------
----1	BREAK UP OF TAXABLE SALES AND PURCHASES IN UNION TERRITORY, CHANDIGARH(EXCLUDING CAPITAL GOODS)
--- Commented by Suraj Kumawat Date on 07-07-2016  Start
--SET @AMTA1 = 0
--SET @AMTA2 = 0
--SELECT DISTINCT LEVEL1 AS PER INTO #AA FROM STAX_MAS  WHERE LEVEL1 IN(SELECT DISTINCT PER FROM VATTBL WHERE BHENT IN('PT','SR')  AND PER >0  AND ST_TYPE IN('','lOCAL') )
--select isnull(sum(CASE WHEN BHENT ='PT' THEN vatonamt ELSE - vatonamt END ),0) AS VATONAMT,isnull(SUM(CASE WHEN BHENT ='PT' THEN TAXAMT ELSE - TAXAMT END ),0) AS TAXAMT,PER INTO #pp FROM VATTBL WHERE BHENT IN('PT','PR') AND PER >0  AND ST_TYPE IN('','lOCAL') GROUP BY PER  ORDER BY PER 
--select isnull(sum(CASE WHEN BHENT ='ST' THEN vatonamt ELSE - vatonamt END ),0)AS VATONAMT,isnull(SUM(CASE WHEN BHENT ='ST' THEN TAXAMT ELSE - TAXAMT END ),0) AS TAXAMT,PER INTO #ss FROM VATTBL WHERE BHENT IN('ST','SR') AND PER >0  AND ST_TYPE IN('','lOCAL')GROUP BY PER  ORDER BY PER 

--INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,AMT4,PARTY_NM) SELECT 8 AS PART ,'8' AS PARTSR ,'A' AS SRNO
--,A.PER,isnull(B.VATONAMT,0) AS AMT1,isnull(B.TAXAMT,0) AS AMT2,isnull(C.VATONAMT,0) AS AMT3,isnull(C.TAXAMT,0) AS AMT4,'' as party_nm FROM #AA A LEFT OUTER JOIN #SS B ON (A.PER =B.PER)
--LEFT OUTER JOIN #PP C ON (A.PER =C.PER) WHERE (ISNULL(B.VATONAMT,0)+ ISNULL(B.TAXAMT,0)+ISNULL(C.VATONAMT,0)+ISNULL(C.TAXAMT ,0)) > 0 ORDER BY A.PER 
--IF NOT EXISTS(SELECT TOP 1 SRNO FROM #CH_VAT_FORM15 WHERE PART = 8 AND PARTSR ='8' AND SRNO ='A')
--BEGIN
--	INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (8,'8','A',0,@AMTA1,0,0,'')	
--END
--- Commented by Suraj Kumawat Date on 07-07-2016  End : 
--- Added by suraj Kumawat Date on 07-07-2016  Start : 
---1%
set @AMTA1 = 0
set @AMTA2 = 0
set @AMTA3 = 0
set @AMTA4 = 0
select @AMTA3 = isnull(sum(CASE WHEN BHENT ='PT' THEN vatonamt ELSE - vatonamt END ),0),@AMTA4 =isnull(SUM(CASE WHEN BHENT ='PT' THEN TAXAMT ELSE - TAXAMT END ),0) FROM VATTBL WHERE BHENT IN('PT','PR','DN') AND PER = 1  AND ST_TYPE IN('','lOCAL')  and s_tax <> '' and itemtype <> 'C'
select @AMTA1 =isnull(sum(CASE WHEN BHENT ='ST' THEN vatonamt ELSE - vatonamt END ),0),@AMTA2 =isnull(SUM(CASE WHEN BHENT ='ST' THEN TAXAMT ELSE - TAXAMT END ),0) FROM VATTBL WHERE BHENT IN('ST','SR','CN') AND PER = 1   AND ST_TYPE IN('','lOCAL') and itemtype <> 'C'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,AMT4,PARTY_NM) VALUES(8,'8','A',1,@AMTA1,@AMTA2,@AMTA3,@AMTA4,'')
---4%
set @AMTA1 = 0
set @AMTA2 = 0
set @AMTA3 = 0
set @AMTA4 = 0
select @AMTA3 = isnull(sum(CASE WHEN BHENT ='PT' THEN vatonamt ELSE - vatonamt END ),0),@AMTA4 =isnull(SUM(CASE WHEN BHENT ='PT' THEN TAXAMT ELSE - TAXAMT END ),0) FROM VATTBL WHERE BHENT IN('PT','PR','DN') AND PER = 4  AND ST_TYPE IN('','lOCAL')    and s_tax <> '' and itemtype <> 'C'
select @AMTA1 =isnull(sum(CASE WHEN BHENT ='ST' THEN vatonamt ELSE - vatonamt END ),0),@AMTA2 =isnull(SUM(CASE WHEN BHENT ='ST' THEN TAXAMT ELSE - TAXAMT END ),0) FROM VATTBL WHERE BHENT IN('ST','SR','CN') AND PER = 4   AND ST_TYPE IN('','lOCAL') and itemtype <> 'C'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,AMT4,PARTY_NM) VALUES(8,'8','A',4,@AMTA1,@AMTA2,@AMTA3,@AMTA4,'')
---5%
set @AMTA1 = 0
set @AMTA2 = 0
set @AMTA3 = 0
set @AMTA4 = 0
select @AMTA3 = isnull(sum(CASE WHEN BHENT ='PT' THEN vatonamt ELSE - vatonamt END ),0),@AMTA4 =isnull(SUM(CASE WHEN BHENT ='PT' THEN TAXAMT ELSE - TAXAMT END ),0) FROM VATTBL WHERE BHENT IN('PT','PR','DN') AND PER = 5  AND ST_TYPE IN('','lOCAL')    and s_tax <> '' and itemtype <> 'C'
select @AMTA1 =isnull(sum(CASE WHEN BHENT ='ST' THEN vatonamt ELSE - vatonamt END ),0),@AMTA2 =isnull(SUM(CASE WHEN BHENT ='ST' THEN TAXAMT ELSE - TAXAMT END ),0) FROM VATTBL WHERE BHENT IN('ST','SR','CN') AND PER = 5   AND ST_TYPE IN('','lOCAL') and itemtype <> 'C'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,AMT4,PARTY_NM) VALUES(8,'8','A',5,@AMTA1,@AMTA2,@AMTA3,@AMTA4,'')
---8.8%
set @AMTA1 = 0
set @AMTA2 = 0
set @AMTA3 = 0
set @AMTA4 = 0
select @AMTA3 = isnull(sum(CASE WHEN BHENT ='PT' THEN vatonamt ELSE - vatonamt END ),0),@AMTA4 =isnull(SUM(CASE WHEN BHENT ='PT' THEN TAXAMT ELSE - TAXAMT END ),0) FROM VATTBL WHERE BHENT IN('PT','PR','DN') AND PER = 8.8  AND ST_TYPE IN('','lOCAL')    and s_tax <> '' and itemtype <> 'C'
select @AMTA1 =isnull(sum(CASE WHEN BHENT ='ST' THEN vatonamt ELSE - vatonamt END ),0),@AMTA2 =isnull(SUM(CASE WHEN BHENT ='ST' THEN TAXAMT ELSE - TAXAMT END ),0) FROM VATTBL WHERE BHENT IN('ST','SR','CN') AND PER = 8.8   AND ST_TYPE IN('','lOCAL') and itemtype <> 'C'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,AMT4,PARTY_NM) VALUES(8,'8','A',8.8,@AMTA1,@AMTA2,@AMTA3,@AMTA4,'')
---12.5%
set @AMTA1 = 0
set @AMTA2 = 0
set @AMTA3 = 0
set @AMTA4 = 0
select @AMTA3 = isnull(sum(CASE WHEN BHENT ='PT' THEN vatonamt ELSE - vatonamt END ),0),@AMTA4 =isnull(SUM(CASE WHEN BHENT ='PT' THEN TAXAMT ELSE - TAXAMT END ),0) FROM VATTBL WHERE BHENT IN('PT','PR','DN') AND PER = 12.5  AND ST_TYPE IN('','lOCAL')    and s_tax <> '' and itemtype <> 'C'
select @AMTA1 =isnull(sum(CASE WHEN BHENT ='ST' THEN vatonamt ELSE - vatonamt END ),0),@AMTA2 =isnull(SUM(CASE WHEN BHENT ='ST' THEN TAXAMT ELSE - TAXAMT END ),0) FROM VATTBL WHERE BHENT IN('ST','SR','CN') AND PER = 12.5  AND ST_TYPE IN('','lOCAL') and itemtype <> 'C'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,AMT4,PARTY_NM) VALUES(8,'8','A',12.5,@AMTA1,@AMTA2,@AMTA3,@AMTA4,'')
---20%
set @AMTA1 = 0
set @AMTA2 = 0
set @AMTA3 = 0
set @AMTA4 = 0
select @AMTA3 = isnull(sum(CASE WHEN BHENT ='PT' THEN vatonamt ELSE - vatonamt END ),0),@AMTA4 =isnull(SUM(CASE WHEN BHENT ='PT' THEN TAXAMT ELSE - TAXAMT END ),0) FROM VATTBL WHERE BHENT IN('PT','PR','DN') AND PER = 20  AND ST_TYPE IN('','lOCAL')    and s_tax <> '' and itemtype <> 'C'
select @AMTA1 =isnull(sum(CASE WHEN BHENT ='ST' THEN vatonamt ELSE - vatonamt END ),0),@AMTA2 =isnull(SUM(CASE WHEN BHENT ='ST' THEN TAXAMT ELSE - TAXAMT END ),0) FROM VATTBL WHERE BHENT IN('ST','SR','CN') AND PER = 20  AND ST_TYPE IN('','lOCAL') and itemtype <> 'C'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,AMT4,PARTY_NM) VALUES(8,'8','A',20,@AMTA1,@AMTA2,@AMTA3,@AMTA4,'')
---22%
set @AMTA1 = 0
set @AMTA2 = 0
set @AMTA3 = 0
set @AMTA4 = 0
select @AMTA3 = isnull(sum(CASE WHEN BHENT ='PT' THEN vatonamt ELSE - vatonamt END ),0),@AMTA4 =isnull(SUM(CASE WHEN BHENT ='PT' THEN TAXAMT ELSE - TAXAMT END ),0) FROM VATTBL WHERE BHENT IN('PT','PR','DN') AND PER = 22  AND ST_TYPE IN('','lOCAL')  and s_tax <> '' and itemtype <> 'C'
select @AMTA1 =isnull(sum(CASE WHEN BHENT ='ST' THEN vatonamt ELSE - vatonamt END ),0),@AMTA2 =isnull(SUM(CASE WHEN BHENT ='ST' THEN TAXAMT ELSE - TAXAMT END ),0) FROM VATTBL WHERE BHENT IN('ST','SR','CN') AND PER = 22  AND ST_TYPE IN('','lOCAL') and itemtype <> 'C'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,AMT4,PARTY_NM) VALUES(8,'8','A',22,@AMTA1,@AMTA2,@AMTA3,@AMTA4,'')
set @AMTA1 = 0
set @AMTA2 = 0
set @AMTA3 = 0
set @AMTA4 = 0
SELECT @AMTA1 =ISNULL(SUM(AMT1),0),@AMTA2 =ISNULL(SUM(AMT2),0),@AMTA3 =ISNULL(SUM(AMT3),0),@AMTA4 =ISNULL(SUM(AMT4),0) FROM #CH_VAT_FORM15 WHERE  PART = 8 AND PARTSR ='8' AND SRNO ='A' 
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,AMT4,PARTY_NM) VALUES(8,'8','A',0,@AMTA1,@AMTA2,@AMTA3,@AMTA4,'Total')

--- Added by suraj Kumawat Date on 07-07-2016  End :

---2	BREAK UP OF GOODS SOLD UNDER WORKS CONTRACT						
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (9,'9','A',0,@AMTA1,0,0,'')
------3	BREAK UP OF ZERO RATED SALES
--Sale against H form
SET @AMTA1 = 0
SET @AMTA2 = 0

----SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='ST' AND U_IMPORM NOT IN('Export Out of India','High Sea Sales')  AND ST_TYPE <> 'OUT OF COUNTRY'
----AND ( DATE BETWEEN @SDATE AND @EDATE ) AND (RTRIM(LTRIM(REPLACE(REPLACE(RFORM_NM,'FORM',''),'-',''))) = 'H' OR RTRIM(LTRIM(REPLACE(REPLACE(TAX_NAME ,'FORM',''),'-',''))) = 'H' )

SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='ST' AND U_IMPORM NOT IN('Export Out of India') 
AND ( DATE BETWEEN @SDATE AND @EDATE ) AND (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(RFORM_NM,'FORM',''),'-',''),' ',''))) = 'H' OR RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(TAX_NAME ,'FORM',''),'-',''),' ',''))) = 'H' )

SELECT @AMTA2 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='SR' AND U_IMPORM NOT IN('Export Out of India')
AND ( DATE BETWEEN @SDATE AND @EDATE ) AND (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(RFORM_NM,'FORM',''),'-',''),' ',''))) = 'H' OR RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(TAX_NAME ,'FORM',''),'-',''),' ',''))) = 'H' )
---discount 
set @AMTA3 = 0
SELECT @AMTA3 = ISNULL(SUM(b.ITDISCAMT),0) FROM VATTBL a inner join STITEM b on(a.BHENT =b.entry_ty and a.TRAN_CD =b.Tran_cd and a.ItSerial =b.itserial) WHERE a.BHENT ='ST' AND a.U_IMPORM NOT IN('Export Out of India') 
AND ( a.DATE BETWEEN @SDATE AND @EDATE ) 
AND (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(a.RFORM_NM,'FORM',''),'-',''),' ',''))) = 'H' OR RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(a.TAX_NAME ,'FORM',''),'-',''),' ',''))) = 'H' )
print 'test'
print @AMTA3
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) VALUES  (10,'10','A',0,@AMTA1,@AMTA2,(@AMTA1-(@AMTA2+@AMTA3)),'',@AMTA3)
---Export out of India
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='ST' AND U_IMPORM IN('Export Out of India')  AND ST_TYPE ='OUT OF COUNTRY'
AND ( DATE BETWEEN @SDATE AND @EDATE ) AND (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(RFORM_NM,'FORM',''),'-',''),' ',''))) = 'H' OR RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(TAX_NAME ,'FORM',''),'-',''),' ',''))) = 'H' )
SELECT @AMTA2 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='SR' AND U_IMPORM IN('Export Out of India')  AND ST_TYPE ='OUT OF COUNTRY'
AND ( DATE BETWEEN @SDATE AND @EDATE ) AND (RTRIM(LTRIM(REPLACE(REPLACE(RFORM_NM,'FORM',''),'-',''))) = 'H' OR RTRIM(LTRIM(REPLACE(REPLACE(TAX_NAME ,'FORM',''),'-',''))) = 'H' )
---discount 
set @AMTA3 = 0
SELECT @AMTA3 = ISNULL(SUM(b.ITDISCAMT),0) FROM VATTBL a inner join STITEM b on(a.BHENT =b.entry_ty and a.TRAN_CD =b.Tran_cd and a.ItSerial =b.itserial) WHERE a.BHENT ='ST' AND a.U_IMPORM IN('Export Out of India') AND A.ST_TYPE ='OUT OF COUNTRY'
AND ( a.DATE BETWEEN @SDATE AND @EDATE ) 
AND (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(a.RFORM_NM,'FORM',''),'-',''),' ',''))) = 'H' OR RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(a.TAX_NAME ,'FORM',''),'-',''),' ',''))) = 'H' )

INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) VALUES  (10,'10','B',0,@AMTA1,@AMTA2,(@AMTA1-(@AMTA2+@AMTA3)),'',@AMTA3)
---Sales against E1/E2 forms
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='ST' 
AND ( DATE BETWEEN @SDATE AND @EDATE ) AND (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(RFORM_NM,'FORM',''),'-',''),'/',''),' ',''))) IN('E1','E2','EI','EII','E 1','E 2','E I','E II') OR RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(TAX_NAME ,'FORM',''),'-',''),'/',''),' ',''))) IN('E1','E2','EI','EII','E 1','E 2','E I','E II'))
SELECT @AMTA2 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='SR' 
AND ( DATE BETWEEN @SDATE AND @EDATE ) AND (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(RFORM_NM,'FORM',''),'-',''),'/',''),' ',''))) IN('E1','E2','EI','EII','E 1','E 2','E I','E II') OR RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(TAX_NAME ,'FORM',''),'-',''),'/',''),' ',''))) IN('E1','E2','EI','EII','E 1','E 2','E I','E II'))
---discount 
set @AMTA3 = 0
SELECT @AMTA3 = ISNULL(SUM(b.ITDISCAMT),0) FROM VATTBL a inner join STITEM b on(a.BHENT =b.entry_ty and a.TRAN_CD =b.Tran_cd and a.ItSerial =b.itserial) WHERE a.BHENT ='ST' 
AND ( a.DATE BETWEEN @SDATE AND @EDATE ) 
AND (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(A.RFORM_NM,'FORM',''),'-',''),'/',''),' ',''))) IN('E1','E2','EI','EII','E 1','E 2','E I','E II') OR RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(A.TAX_NAME ,'FORM',''),'-',''),'/',''),' ',''))) IN('E1','E2','EI','EII','E 1','E 2','E I','E II'))

INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) VALUES  (10,'10','C',0,@AMTA1,@AMTA2,(@AMTA1-(@AMTA2+@AMTA3)),'',@AMTA3)
---4	BREAK UP OF DEDUCTIONS FROM SALES AND PURCHASES						
SET @AMTA1 = 0
SET @AMTA2 = 0
---Sales_Returns or purchase
SELECT @AMTA2 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='PR' AND  (DATE BETWEEN @SDATE AND @EDATE )
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (11,'11','A',0,0,@AMTA2,0,'')
---Cash/Trade Discount
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (11,'11','B',0,@AMTA1,0,0,'')
---Amount charged separately as interest for sales by hire-purchase/installments purchase
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (11,'11','C',0,@AMTA1,0,0,'')
---Cancellation_of_sales
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (11,'11','D',0,@AMTA1,@AMTA2,0,'')
---Sales  Returns
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0) FROM VATTBL WHERE BHENT ='SR' AND  (DATE BETWEEN @SDATE AND @EDATE )

INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (11,'11','E',0,@AMTA1,0,0,'')
---Change_in_nature_of_sales
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (11,'11','F',0,@AMTA1,0,0,'')
---Change in sale consideration
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (11,'11','G',0,@AMTA1,0,0,'')
---Others(Pl. specify nature
SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (11,'11','H',0,@AMTA1,0,0,'')
---Total Deductions
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1 = ISNULL(SUM(AMT1),0),@AMTA2 = ISNULL(SUM(AMT2),0) FROM #CH_VAT_FORM15 WHERE PART =11 AND PARTSR ='11' AND SRNO IN('A','B','C','D','E','F','G','H')
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (11,'11','I',0,@AMTA1,@AMTA2,0,'')
---5	PRIOR PERIOD ADJUSTMENTS						
--Cancellation of sales --Cancellation of purchase
SET @AMTA1 = 0
SET @AMTA2 = 0
SET @AMTA3 = 0
SET @AMTA4 = 0
SELECT @AMTA1 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='Cancellation of sales' 
AND  (A.date BETWEEN @SDATE AND @EDATE ) AND A.PARTY_NM ='VAT PAYABLE'
--SELECT @AMTA2 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
--WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='Adjustment to Output Tax'
--AND  (A.date BETWEEN @SDATE AND @EDATE ) AND A.PARTY_NM ='VAT PAYABLE'
SELECT @AMTA3 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='Cancellation of purchase'
AND  (A.date BETWEEN @SDATE AND @EDATE ) AND A.PARTY_NM ='VAT PAYABLE'
--SELECT @AMTA4 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
--WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='Adjustment to Input Tax'
--AND  (A.date BETWEEN @SDATE AND @EDATE ) AND A.PARTY_NM ='VAT PAYABLE'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,AMT4,PARTY_NM) VALUES  (12,'12','A',0,@AMTA1,@AMTA2,@AMTA3,@AMTA4,'')
--Sales Returns --Purchase returns
SET @AMTA1 = 0
SET @AMTA2 = 0
SET @AMTA3 = 0
SET @AMTA4 = 0
SELECT @AMTA1 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='Sales Returns'
AND  (A.date BETWEEN @SDATE AND @EDATE ) AND A.PARTY_NM ='VAT PAYABLE'
SELECT @AMTA3 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='Purchase returns'
AND  (A.date BETWEEN @SDATE AND @EDATE ) AND A.PARTY_NM ='VAT PAYABLE'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,AMT4,PARTY_NM) VALUES  (12,'12','B',0,@AMTA1,@AMTA2,@AMTA3,@AMTA4,'')
--Change in nature of sales --Change in nature of Purchase 
SET @AMTA1 = 0
SET @AMTA2 = 0
SET @AMTA3 = 0
SET @AMTA4 = 0
SELECT @AMTA1 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='Change in nature of sales'
AND  (A.date BETWEEN @SDATE AND @EDATE ) AND A.PARTY_NM ='VAT PAYABLE'
SELECT @AMTA3 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='Change in nature of Purchase'
AND  (A.date BETWEEN @SDATE AND @EDATE ) AND A.PARTY_NM ='VAT PAYABLE'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,AMT4,PARTY_NM) VALUES  (12,'12','C',0,@AMTA1,@AMTA2,@AMTA3,@AMTA4,'')
---Change in sales consideration  --Change in Purchase consideration
SET @AMTA1 = 0
SET @AMTA2 = 0
SET @AMTA3 = 0
SET @AMTA4 = 0
SELECT @AMTA1 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='Change in sales consideration'
AND  (A.date BETWEEN @SDATE AND @EDATE ) AND A.PARTY_NM ='VAT PAYABLE'
SELECT @AMTA3 = ISNULL(SUM(B.AMOUNT),0) FROM JVMAIN A INNER JOIN JVACDET B ON (A.entry_ty =B.ENTRY_TY AND A.Tran_cd =B.Tran_cd AND B.amt_ty ='DR') 
WHERE A.entry_ty ='J4' AND A.VAT_ADJ ='Change in Purchase consideration'
AND  (A.date BETWEEN @SDATE AND @EDATE ) AND A.PARTY_NM ='VAT PAYABLE'
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,AMT4,PARTY_NM) VALUES  (12,'12','D',0,@AMTA1,@AMTA2,@AMTA3,@AMTA4,'')
--Sales Total -- Purchase Total
SET @AMTA1 = 0
SET @AMTA2 = 0
SET @AMTA3 = 0
SET @AMTA4 = 0
SELECT @AMTA1 =ISNULL(SUM(AMT1),0),@AMTA2 =ISNULL(SUM(AMT2),0),@AMTA3 =ISNULL(SUM(AMT3),0),@AMTA4 =ISNULL(SUM(AMT4),0) FROM #CH_VAT_FORM15 WHERE PART = 12 AND PARTSR ='12' AND SRNO IN('A','B','C','D')
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,AMT4,PARTY_NM) VALUES  (12,'12','E',0,@AMTA1,@AMTA2,@AMTA3,@AMTA4,'')

--6		Any other adjustment (Please specify)

SET @AMTA1 = 0
SET @AMTA2 = 0
INSERT INTO #CH_VAT_FORM15 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (13,'13','A',0,@AMTA1,0,0,'')
------------------------------------------------------------------------------------------------------------------
Update #CH_VAT_FORM15 set  PART = isnull(Part,'') , Partsr = isnull(PARTSR,''), SRNO = isnull(SRNO,''),
RATE = isnull(RATE,0), AMT1 = isnull(AMT1,0), AMT2 = isnull(AMT2,0), AMT3 = isnull(AMT3,0),
INV_NO = isnull(INV_NO,''), DATE = isnull(Date,''),PARTY_NM = isnull(Party_nm,''), ADDRESS = isnull(Address,''),
FORM_NM = isnull(form_nm,''), S_TAX = isnull(S_tax,'')
,RFORM_NM = isnull(rform_nm,''), AMT4 = isnull(AMT4,0), AMT5 = isnull(AMT5,0)

SELECT * FROM #CH_VAT_FORM15 order by PART,SRNO

end

set ANSI_NULLS OFF


