If Exists (Select [name] from sysobjects Where xtype='P' and [name]='USP_REP_DTA_EOU_REG')
Begin
	Drop Procedure USP_REP_DTA_EOU_REG
End
Go

CREATE PROCEDURE  [dbo].[USP_REP_DTA_EOU_REG]
@TMPAC NVARCHAR(50),@TMPIT NVARCHAR(50),@SPLCOND VARCHAR(8000),@SDATE  SMALLDATETIME,@EDATE SMALLDATETIME
,@SAC AS VARCHAR(60),@EAC AS VARCHAR(60)
,@SIT AS VARCHAR(60),@EIT AS VARCHAR(60)
,@SAMT FLOAT,@EAMT FLOAT
,@SDEPT AS VARCHAR(60),@EDEPT AS VARCHAR(60)
,@SCATE AS VARCHAR(60),@ECATE AS VARCHAR(60)
,@SWARE AS VARCHAR(60),@EWARE AS VARCHAR(60)
,@SINV_SR AS VARCHAR(60),@EINV_SR AS VARCHAR(60)
,@LYN VARCHAR(20)
,@EXPARA  AS VARCHAR(60)= NULL
AS
SET QUOTED_IDENTIFIER OFF 
DECLARE @FCON AS NVARCHAR(1000)

EXECUTE   USP_REP_FILTCON 
@VTMPAC =@TMPAC,@VTMPIT =@TMPIT,@VSPLCOND =@SPLCOND
,@VSDATE=NULL
 ,@VEDATE=@EDATE
,@VSAC =@SAC,@VEAC =@EAC
,@VSIT=@SIT,@VEIT=@EIT
,@VSAMT=@SAMT,@VEAMT=@EAMT
,@VSDEPT=@SDEPT,@VEDEPT=@EDEPT
,@VSCATE =@SCATE,@VECATE =@ECATE
,@VSWARE =@SWARE,@VEWARE  =@EWARE
,@VSINV_SR =@SINV_SR,@VEINV_SR =@SINV_SR
,@VMAINFILE='STMAIN',@VITFILE=NULL,@VACFILE=NULL
,@VDTFLD ='AREDATE'
,@VLYN =NULL
,@VEXPARA=@EXPARA
,@VFCON =@FCON OUTPUT

IF @FCON IS NOT NULL OR @FCON <> ''
BEGIN
	SET @FCON = @FCON 
END

DECLARE @SQLCOMMAND NVARCHAR(4000),@VCOND NVARCHAR(2000)
DECLARE @U_BASDUTY NUMERIC(12,2),@U_CESSPER NUMERIC(12,2),@U_HCESPER NUMERIC(12,2)	


SET @SQLCOMMAND='SELECT STMAIN.ENTRY_TY,STMAIN.TRAN_CD,STMAIN.DATE,STMAIN.PARTY_NM,STMAIN.NET_AMT,STMAIN.[RULE],STMAIN.BONDSRNO,STMAIN.INV_NO,STMAIN.CATE'
SET @SQLCOMMAND=@SQLCOMMAND+', STMAIN.U_EXPDEL,STMAIN.ARENO,STMAIN.AREDESC,STMAIN.U_CSEAL,STITEM.U_ASSEAMT,STITEM.ITEM,STITEM.QTY,STITEM.RATE'
SET @SQLCOMMAND=@SQLCOMMAND+', STITEM.ITSERIAL,STITEM.gro_amt,STITEM.U_CUSTAMT,STITEM.U_CUSTPER,STITEM.examt,STITEM.u_Basduty,STITEM.U_CESSAMT'
SET @SQLCOMMAND=@SQLCOMMAND+', STITEM.U_CESSPER,STITEM.U_HCESAMT,STITEM.U_HCESSPER,STITEM.CCDAMT,STITEM.CCDPER,STITEM.u_cvdAMT,STITEM.u_cvdPER,STITEM.taxamt,STITEM.EXAMT'
SET @SQLCOMMAND=@SQLCOMMAND+', STITEM.HCDAMT,STITEM.HCDPER,STITEM.U_CESSAMT3,STITEM.U_CESSPER3,STITEM.U_HCESAMT3,STITEM.U_HCESPER3'
SET @SQLCOMMAND=@SQLCOMMAND+', IT_DESC=(CASE WHEN ISNULL(IT_MAST.IT_ALIAS,'''')='''' THEN IT_MAST.IT_NAME ELSE IT_MAST.IT_ALIAS END)'
SET @SQLCOMMAND=@SQLCOMMAND+', MAILNAME=(CASE WHEN ISNULL(AC_MAST.MAILNAME,'''')='''' THEN AC_MAST.AC_NAME ELSE AC_MAST.MAILNAME END) '
SET @SQLCOMMAND=@SQLCOMMAND+', IT_MAST.RATEUNIT,ac_mast.city'
SET @SQLCOMMAND=@SQLCOMMAND+' FROM STMAIN INNER JOIN STITEM ON (STMAIN.ENTRY_TY=STITEM.ENTRY_TY AND STMAIN.TRAN_CD=STITEM.TRAN_CD)'
SET @SQLCOMMAND=@SQLCOMMAND+' INNER JOIN IT_MAST ON (STITEM.IT_CODE=IT_MAST.IT_CODE) '
--SET @SQLCOMMAND=@SQLCOMMAND+' INNER JOIN CURR_MAST ON (STMAIN.FCID = CURR_MAST.CURRENCYID)'
SET @SQLCOMMAND=@SQLCOMMAND+' INNER JOIN AC_MAST ON (AC_MAST.AC_ID=STMAIN.AC_ID) '
--SET @SQLCOMMAND=@SQLCOMMAND+' LEFT JOIN AC_MAST AC_MAST1 ON (AC_MAST1.AC_NAME=STMAIN.U_DELIVER) '
SET @SQLCOMMAND=@SQLCOMMAND+RTRIM(@FCON)
SET @SQLCOMMAND=@SQLCOMMAND+' and STMAIN.ENTRY_TY = ''ST'' AND STMAIN.CATE=''DTA SALES'''

print @SQLCOMMAND
EXECUTE SP_EXECUTESQL @SQLCOMMAND

