If Exists(Select [name] From SysObjects Where xtype='P' and [Name]='USP_REP_DL_FORMVAT16')
Begin
	Drop Procedure USP_REP_DL_FORMVAT16
End
Go
/*
EXECUTE USP_REP_DL_FORMVAT16 '','','','04/01/2016','03/31/2017','','','','',0,0,'','','','','','','','','2013-2014',''
 > YEAR(@SDATE)
EXECUTE USP_REP_DL_FORMVAT16 '','','','04/01/2016','03/31/2017','','','','',0,0,'','','','','','','','','2016-2017',''
*/
CREATE PROCEDURE [dbo].[USP_REP_DL_FORMVAT16]
@TMPAC NVARCHAR(50),@TMPIT NVARCHAR(50),@SPLCOND VARCHAR(8000),@SDATE  SMALLDATETIME,@EDATE SMALLDATETIME
,@SAC AS VARCHAR(60),@EAC AS VARCHAR(60)
,@SIT AS VARCHAR(60),@EIT AS VARCHAR(60)
,@SAMT FLOAT,@EAMT FLOAT
,@SDEPT AS VARCHAR(60),@EDEPT AS VARCHAR(60) 
,@SCATE AS VARCHAR(60),@ECATE AS VARCHAR(60)
,@SWARE AS VARCHAR(60),@EWARE AS VARCHAR(60)
,@SINV_SR AS VARCHAR(60),@EINV_SR AS VARCHAR(60)
,@LYN VARCHAR(20)
,@EXPARA  AS VARCHAR(60)= null
--,@OUTPUTB NVARCHAR(MAX)
AS
BEGIN
SET NOCOUNT ON
Declare @FCON as NVARCHAR(2000),@VSAMT DECIMAL(14,2),@VEAMT DECIMAL(14,2)
EXECUTE  USP_REP_FILTCON 
@VTMPAC =@TMPAC,@VTMPIT =@TMPIT,@VSPLCOND =@SPLCOND
,@VSDATE=NULL
,@VEDATE=@EDATE
,@VSAC =@SAC,@VEAC =@EAC
,@VSIT=@SIT,@VEIT=@EIT
,@VSAMT=@SAMT,@VEAMT=@EAMT
,@VSDEPT=@SDEPT,@VEDEPT=@EDEPT
,@VSCATE =@SCATE,@VECATE =@ECATE
,@VSWARE =@SWARE,@VEWARE  =@EWARE
,@VSINV_SR =@SINV_SR,@VEINV_SR =@SINV_SR
,@VMAINFILE='M',@VITFILE=NULL,@VACFILE=NULL
,@VDTFLD ='DATE'
,@VLYN=NULL
,@VEXPARA=@EXPARA
,@VFCON =@FCON OUTPUT

DECLARE @SQLCOMMAND NVARCHAR(4000)
DECLARE @RATE  NUMERIC(20,2),@AMTA1  NUMERIC(20,2),@AMTB1  NUMERIC(20,2),@AMTC1 NUMERIC(20,2),@AMTD1 NUMERIC(20,2),@AMTE1 NUMERIC(20,2),@AMTF1 NUMERIC(20,2),@AMTG1 NUMERIC(20,2),@AMTH1 NUMERIC(20,2),@AMTI1 NUMERIC(20,2),@AMTJ1 NUMERIC(20,2),@AMTK1 NUMERIC(20,2),@AMTL1 NUMERIC(20,2),@AMTM1 NUMERIC(20,2),@AMTN1 NUMERIC(20,2),@AMTO1 NUMERIC(20,2)
DECLARE @AMTA2 NUMERIC(20,2),@AMTB2 NUMERIC(20,2),@AMTC2 NUMERIC(20,2),@AMTD2 NUMERIC(20,2),@AMTE2 NUMERIC(20,2),@AMTF2 NUMERIC(20,2),@AMTG2 NUMERIC(20,2),@AMTH2 NUMERIC(20,2),@AMTI2 NUMERIC(20,2),@AMTJ2 NUMERIC(20,2),@AMTK2 NUMERIC(20,2),@AMTL2 NUMERIC(20,2),@AMTM2 NUMERIC(20,2),@AMTN2 NUMERIC(20,2),@AMTO2 NUMERIC(20,2)
DECLARE @PER NUMERIC(20,2),@TAXAMT NUMERIC(20,2),@CHAR INT,@LEVEL NUMERIC(20,2),@TAXNAME NVARCHAR(50),@TYPE NVARCHAR(50),@PARTY_NM as varchar(50)
DECLARE @AMTA3 NUMERIC(20,2),@AMTA4 NUMERIC(20,2),@AMTA5 NUMERIC(20,2) --Added by Priyanka on 27022014
DECLARE @CNT INT,@SRNO VARCHAR(1),@IT_NAME VARCHAR(50),@EIT_NAME VARCHAR(50),@QTR VARCHAR(10)-- ADDED BY PANKAJ

SELECT DISTINCT AC_NAME=SUBSTRING(AC_NAME1,2,CHARINDEX('"',SUBSTRING(AC_NAME1,2,100))-1) INTO #VATAC_MAST FROM STAX_MAS WHERE AC_NAME1 NOT IN ('"SALES"','"PURCHASES"') AND ISNULL(AC_NAME1,'')<>''
INSERT INTO #VATAC_MAST SELECT DISTINCT AC_NAME=SUBSTRING(AC_NAME1,2,CHARINDEX('"',SUBSTRING(AC_NAME1,2,100))-1) FROM STAX_MAS WHERE AC_NAME1 NOT IN ('"SALES"','"PURCHASES"') AND ISNULL(AC_NAME1,'')<>''
SELECT ENTRY_TY,BCODE=(CASE WHEN EXT_VOU=1 THEN BCODE_NM ELSE ENTRY_TY END)  INTO #LCODE FROM LCODE 
Declare @NetEff as NUMERIC(20,2), @NetTax as NUMERIC(20,2)
print 'a'
print @LYN
----Temporary Cursor1
--SELECT BHENT='PT',M.INV_NO,M.Date,A.AC_NAME,A.AC_ID,A.AMT_TY,STM.TAX_NAME,SET_APP=ISNULL(SET_APP,0),STM.ST_TYPE,NET_AMT=CAST('0' AS NUMERIC(20,2)),GRO_AMT=CAST('0' AS NUMERIC(20,2)),PER=STM.LEVEL1,TAXAMT=A.AMOUNT,STM.FORM_NM,STM.RFORM_NM,AC1.S_TAX,M.U_IMPORM
--,ADDRESS=LTRIM(AC1.ADD1)+ ' ' + LTRIM(AC1.ADD2) + ' ' + LTRIM(AC1.ADD3),M.TRAN_CD,VATONAMT=CAST('0' AS NUMERIC(20,2)),Dbname=space(20),itemtype=space(1),It_code=999999999999999999-999999999999999999,ItSerial=Space(5),PARTY_NM=AC1.AC_NAME
----,STM.RFORM_NM,CAST('0' AS NUMERIC(20,2)) AS AMT4,CAST('0' AS NUMERIC(20,2)) AS AMT5 --Added by Priyanka on 25022014
--INTO VATTBL
--FROM STACDET A 
--INNER JOIN STMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)
--INNER JOIN STAX_MAS STM ON (M.TAX_NAME=STM.TAX_NAME)
--INNER JOIN AC_MAST AC ON (A.AC_NAME=AC.AC_NAME)
--INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID)
--WHERE 1=2 --A.AC_NAME IN ( SELECT AC_NAME FROM #VATAC_MAST)


--alter table VATTBL add recno int identity
---Temporary Cursor2
SELECT PART=3,PARTSR='AAA',SRNO='AAA',RATE=99.999,AMT1=CAST('0' AS NUMERIC(20,2)),AMT2=CAST('0' AS NUMERIC(20,2)),AMT3=CAST('0' AS NUMERIC(20,2)),
M.INV_NO,M.DATE,PARTY_NM=AC1.AC_NAME,ADDRESS=Ltrim(AC1.Add1)+' '+Ltrim(AC1.Add2)+' '+Ltrim(AC1.Add3),STM.FORM_NM,AC1.S_TAX
,STM.RFORM_NM,CAST('0' AS NUMERIC(20,2)) AS AMT4,CAST('0' AS NUMERIC(20,2)) AS AMT5 --Added by Priyanka on 25022014
,TAX_NAME=CAST('' AS VARCHAR(12)),n.item,EIT_NAME=CAST('' AS VARCHAR(50)),CONTTAX=CAST(0 AS DECIMAL(12,2)),CTYPE=CAST('' AS VARCHAR(2)) -- Added by Pankaj on 03.03.2014
INTO #FORMDVAT16
FROM PTACDET A 
INNER JOIN STMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)
INNER JOIN STAX_MAS STM ON (M.TAX_NAME=STM.TAX_NAME)
INNER JOIN AC_MAST AC ON (A.AC_NAME=AC.AC_NAME)
INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID)
inner join stitem n on (m.tran_cd=n.tran_cd) 
WHERE 1=2
print 'b'

Declare @MultiCo	VarChar(3)
Declare @MCON as NVARCHAR(2000)
IF Exists(Select A.ID From SysObjects A Inner Join SysColumns B On(A.ID = B.ID) Where A.[Name] = 'STMAIN' And B.[Name] = 'DBNAME')
	Begin	------Fetch Records from Multi Co. Data
		 Set @MultiCo = 'YES'
		 EXECUTE USP_REP_MULTI_CO_DATA
		  @TMPAC, @TMPIT, @SPLCOND, @SDATE, @EDATE
		 ,@SAC, @EAC, @SIT, @EIT, @SAMT, @EAMT
		 ,@SDEPT, @EDEPT, @SCATE, @ECATE,@SWARE
		 ,@EWARE, @SINV_SR, @EINV_SR, @LYN, @EXPARA
		 ,@MFCON = @MCON OUTPUT

		--SET @SQLCOMMAND='Select * from '+@MCON
		---EXECUTE SP_EXECUTESQL @SQLCOMMAND
		--SET @SQLCOMMAND='Insert InTo  VATTBL Select * from '+@MCON
		--EXECUTE SP_EXECUTESQL @SQLCOMMAND
		---Drop Temp Table 
		--SET @SQLCOMMAND='Drop Table '+@MCON
		----SET @SQLCOMMAND='SELECT * FROM '+@MCON
		--EXECUTE SP_EXECUTESQL @SQLCOMMAND
	End
else
	Begin ------Fetch Single Co. Data
		 Set @MultiCo = 'NO'
		 EXECUTE USP_REP_SINGLE_CO_DATA_vat
		  @TMPAC, @TMPIT, @SPLCOND, @SDATE, @EDATE
		 ,@SAC, @EAC, @SIT, @EIT, @SAMT, @EAMT
		 ,@SDEPT, @EDEPT, @SCATE, @ECATE,@SWARE
		 ,@EWARE, @SINV_SR, @EINV_SR, @LYN, @EXPARA
		 ,@MFCON = @MCON OUTPUT

		--SET @SQLCOMMAND='Select * from '+@MCON
		---EXECUTE SP_EXECUTESQL @SQLCOMMAND
		--SET @SQLCOMMAND='Insert InTo VATTBL1 Select * from '+@MCON
		--EXECUTE SP_EXECUTESQL @SQLCOMMAND
		-----Drop Temp Table 
		--SET @SQLCOMMAND='Drop Table '+@MCON
		----SET @SQLCOMMAND='SELECT * FROM '+@MCON
		--EXECUTE SP_EXECUTESQL @SQLCOMMAND
	End

print 'c'

--select top 3  tax_name,max(net_amt),it_name from #1 where tax_name<>'' group by tax_name,it_name order by max(net_amt) desc

--drop table #1 

--R4 Turnover Details
SET @AMTC1=0
SELECT @AMTC1= ISNULL(SUM(a.GRO_AMT),0) FROM VATTBL a WHERE (a.bhent='ST') AND (DATE BETWEEN @SDATE AND @EDATE)
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'4','A',0,@AMTC1,0,0,'')  

SET @AMTB1=0
SELECT @AMTB1=ISNULL(SUM(a.GRO_AMT),0) FROM VATTBL a WHERE (a.bhent='ST') AND (DATE BETWEEN @SDATE AND @EDATE) and a.st_type='OUT OF STATE'
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'4','B',0,@AMTB1,0,0,'')

SET @AMTA1=0
SELECT @AMTA1=ISNULL(SUM(a.GRO_AMT),0) FROM VATTBL a WHERE (a.bhent='ST') AND (DATE BETWEEN @SDATE AND @EDATE) and a.st_type in('LOCAL','')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'4','C',0,@AMTA1,0,0,'')

-----Commented by suraj kumawat for on date 23-07-2016 Start : 
--SET @CNT=1
--while @CNT<=5
--BEGIN
--	SET @SRNO=CASE WHEN @CNT=1 THEN 'A' WHEN @CNT=2 THEN 'B' WHEN @CNT=3 THEN 'C' WHEN @CNT=4 THEN 'D' WHEN @CNT=5 THEN 'E' END  
--	INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'3',@SRNO,0,0,0,0,'')  
--	SET @CNT=@CNT+1	
--END

--SET @CNT=1
-- DECLARE ITEM CURSOR FOR SELECT TOP 5 sum(A.TAXAMT),ST.LEVEL1,D.IT_NAME,D.EIT_NAME from VATTBL A
--INNER JOIN STAX_MAS ST ON (ST.ENTRY_TY='ST' AND a.tax_name=st.tax_name) 
--INNER JOIN IT_MAST D ON (D.IT_CODE=A.IT_CODE)
--where  ST.LEVEL1<>0 
--GROUP BY ST.LEVEL1,D.IT_NAME,D.EIT_NAME
--ORDER BY SUM(A.TAXAMT) DESC
--OPEN ITEM
--FETCH NEXT FROM ITEM INTO @AMTA1,@PER,@IT_NAME,@EIT_NAME
--WHILE @@FETCH_STATUS=0
--BEGIN
--	SET @SRNO=CASE WHEN @CNT=1 THEN 'A' WHEN @CNT=2 THEN 'B' WHEN @CNT=3 THEN 'C' WHEN @CNT=4 THEN 'D' WHEN @CNT=5 THEN 'E' END  
--	UPDATE #FORMDVAT16 SET AMT1=@AMTA1,ITEM=@IT_NAME,EIT_NAME=@EIT_NAME,RATE=@PER WHERE PARTSR='3' AND SRNO=@SRNO
--	FETCH NEXT FROM ITEM INTO @AMTA1,@PER,@IT_NAME,@EIT_NAME
--	SET @CNT=@CNT+1
--END 
--CLOSE ITEM
--DEALLOCATE ITEM
--select * from VATTBL
---- Commented by suraj kumawat date on 23-07-2016  End
---------------------------------------------------------
------ Added by Suraj Kumawat date on 23-07-2016 Start : 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,ITEM,EIT_NAME) select top 5  c.* from (select 1 as part,'3' as partsr,'A' as srno,a.PER
,isnull(sum(a.taxamt),0) as taxamt,isnull(sum(a.gro_amt),0)as gro_amt ,0 as amt3,'' as part_nm
,b.it_name
, (case when cast(b.it_desc as varchar(150)) ='' then b.it_name else cast(b.it_desc as varchar(150)) end) as descr
 from VATTBL a inner join it_mast b on (a.It_code =b.It_code) where a.BHENT  ='st' and a.TAX_NAME like '%vat%'
and a.per > 0 
group by a.PER,b.it_name, cast(b.it_desc as varchar(150))) c order by c.GRO_AMT desc
------ Added by Suraj Kumawat date on 23-07-2016 End : 
if not exists(select top 1 srno from #FORMDVAT16 where PART = 1 and PARTSR ='3') 
begin
	INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'3','A',0,0,0,0,'') 
end
---------------------------------------------------------
---VAT 1% 
SET @AMTA1=0
SET @AMTA2=0
SET @PER  =0
SELECT  @AMTA1=ISNULL(SUM(a.vatonamt),0),@AMTA2=ISNULL(SUM(a.TAXAMT),0) FROM VATTBL a WHERE (a.bhent='ST') AND a.PER = 1 AND (a.DATE BETWEEN @SDATE AND @EDATE) and a.Tax_Name like '%VAT%' 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','A',@PER,@AMTA1,@AMTA2,0,'')  
---VAT 5% 
SET @AMTA1=0
SET @AMTA2=0
SET @PER  =0
SELECT  @AMTA1=isnull(SUM(a.vatonamt),0),@AMTA2=isnull(SUM(a.TAXAMT),0) FROM VATTBL a 
WHERE (a.bhent='ST') AND a.PER = 5 AND (a.DATE BETWEEN @SDATE AND @EDATE) and a.Tax_Name like '%VAT%' 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','C',@PER,@AMTA1,@AMTA2,0,'')

---VAT 12.5% 
SET @AMTA1=0
SET @AMTA2=0
SET @PER  =0
SELECT  @AMTA1=isnull(SUM(a.vatonamt),0),@AMTA2=isnull(SUM(a.TAXAMT),0) FROM VATTBL a 
WHERE (a.bhent='ST') AND a.PER = 12.5 AND (a.DATE BETWEEN @SDATE AND @EDATE) and a.Tax_Name like '%VAT%' 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','D',@PER,@AMTA1,@AMTA2,0,'')

---VAT 20% 
SET @AMTA1=0
SET @AMTA2=0
SET @PER  =0
SELECT  @AMTA1=isnull(SUM(a.vatonamt),0),@AMTA2=isnull(SUM(a.TAXAMT),0) FROM VATTBL a 
WHERE (a.bhent='ST') AND a.PER = 20 AND (a.DATE BETWEEN @SDATE AND @EDATE) and a.Tax_Name like '%VAT%' 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','E',@PER,@AMTA1,@AMTA2,0,'')  

---Work ContractVAT 5% 
SET @AMTA1=0
SET @AMTA2=0
SET @PER  =0
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','G',0,0,0,0,'')

---Work ContractVAT 12.5% 
SET @AMTA1=0
SET @AMTA2=0
SET @PER  =0
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','H',0,0,0,0,'')  
--R5.7 Exempted sales & Other deduction claimed
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1=isnull(SUM(a.vatonamt),0) FROM VATTBL a WHERE (A.st_type IN('Local','')) AND a.bhent='ST'
and a.tax_name LIKE '%EXEMPTED%' AND (DATE BETWEEN @SDATE AND @EDATE)
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','I',0,@AMTA1,0,0,'')  

--Added by Priyanka on 25022014--start
SET @AMTA1 = 0
SET @AMTA2 = 0
--R5.8 Charges towards labour, services and other like charges
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','I1',0,0,0,0,'') 

--Added by Pankaj on 03.03.2014--start
--R5.9 Charges towards cost of land, if any, in civil works contracts
SET @AMTA1=0
SET @AMTA2=0
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','I2',0,0,0,0,'') 
--Added by Pankaj on 03.03.2014--end

----R5.10 Sale of Diesel & Petrol as have suffered tax in the hands of various Oil Marketing Companies in Delhi 
set @AMTA1= 0
set @AMTA2= 0
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','I3',0,0,0,0,'')

---Sales within Delhi against Form ‘H’
set @AMTA1= 0
set @AMTA2= 0
SELECT @AMTA1=isnull(SUM(a.vatonamt),0),@AMTA2=isnull(SUM(a.taxamt),0) FROM VATTBL A WHERE  A.BHENT ='ST' AND A.st_type IN('','Local') 
AND (RTRIM(LTRIM(REPLACE(REPLACE(RTRIM(LTRIM(replace(a.rform_nm,'FORM',''))),'-',''),' ','')))='H' OR  RTRIM(LTRIM(REPLACE(RTRIM(LTRIM(replace(A.TAX_NAME,'FORM',''))),'-','')))='H')
AND (a.DATE BETWEEN @SDATE AND @EDATE)
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','I4',0,@AMTA1,@AMTA2,0,'') 
--Added by Priyanka on 25022014--end

--R5.8 Output Tax before adjustments --Commented by Priyanka on 25022014
--R5.12 Output Tax before adjustments --Added by Priyanka on 25022014
SET @AMTA1=0
SET @AMTA2=0
SELECT @AMTA1=isnull(sum(amt1),0),@AMTA2=isnull(sum(amt2),0) FROM #FORMDVAT16  WHERE PARTSR='5' and SRNO IN ('A','B','C','D','E','F','G','H','I','I1','I2','I3','I4')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','J',0,@AMTA1,@AMTA2,0,'')  
--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','J',0,0,@AMTA2,0,'')  

--R5.13 Output Tax before adjustments --Added by Priyanka on 25022014
SET @AMTA1=0
SET @AMTA2=0
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','K',0,@AMTA1,@AMTA2,0,'')  

--R6 Turnover of Purchases in Delhi (excluding tax) & tax credit
--R6.1 Capital goods
SET @AMTA1=0
SET @AMTB1=0
SELECT @AMTA1=isnull(SUM(a.VATONAMT),0),@AMTB1=isnull(SUM(a.TAXAMT),0) FROM VATTBL a 
WHERE a.ST_TYPE in ('LOCAL','') AND a.bhent='PT' AND A.ITEMTYPE = 'C' AND (A.DATE BETWEEN @SDATE AND @EDATE) and a.S_TAX <> ''
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'6','A',0,@AMTA1,@AMTB1,0,'')
--R6.2 Other goods (Total)
SET @AMTA1=0
SET @AMTB1=0
SELECT @AMTA1=isnull(SUM(A.VATONAMT),0),@AMTB1=isnull(SUM(A.TAXAMT),0)  FROM  VATTBL a 
WHERE a.ST_TYPE in ('LOCAL','') AND a.BHENT='PT' AND a.ITEMTYPE = 'I' AND (a.DATE BETWEEN @SDATE AND @EDATE) and a.S_TAX <> ''
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'6','B',0,@AMTA1,@AMTB1,0,'')

---R6.2(1) Goods taxable at 1%
SET @AMTA1=0
SET @AMTA2=0
SET @PER  =0
SELECT  @AMTA1=isnull(SUM(a.VATONAMT),0),@AMTA2=isnull(SUM(a.TAXAMT),0) FROM VATTBL a WHERE a.bhent='PT' AND a.PER = 1 AND (a.DATE BETWEEN @SDATE AND @EDATE) and a.Tax_Name like '%VAT%'
and a.ST_TYPE in ('LOCAL','')  and a.s_tax<>'' AND a.ITEMTYPE <> 'C' 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','C',@PER,@AMTA1,@AMTA2,0,'')  

---VAT 5% 
SET @AMTA1=0
SET @AMTA2=0
SET @PER  =0
SELECT  @AMTA1=isnull(SUM(a.VATONAMT),0),@AMTA2=isnull(SUM(a.TAXAMT),0) FROM VATTBL a
WHERE a.bhent='PT' AND a.PER = 5 AND (a.DATE BETWEEN @SDATE AND @EDATE) and a.Tax_Name like '%VAT%'
and a.ST_TYPE in ('LOCAL','')  and a.s_tax<>'' AND a.ITEMTYPE <> 'C'
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','E',@PER,@AMTA1,@AMTA2,0,'')

---VAT 12.5% 
SET @AMTA1=0
SET @AMTA2=0
SET @PER  =0
SELECT  @AMTA1=isnull(SUM(a.VATONAMT),0),@AMTA2=isnull(SUM(a.TAXAMT),0) FROM VATTBL a 
WHERE a.bhent='PT' AND a.PER = 12.5 AND (a.DATE BETWEEN @SDATE AND @EDATE) and a.Tax_Name like '%VAT%'
and a.ST_TYPE in ('LOCAL','')  and a.s_tax<>'' AND a.ITEMTYPE <> 'C' 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','F',@PER,@AMTA1,@AMTA2,0,'')  

---VAT 20% 
SET @AMTA1=0
SET @AMTA2=0
SET @PER  =0
SELECT  @AMTA1=isnull(SUM(a.VATONAMT),0),@AMTA2=isnull(SUM(a.TAXAMT),0)FROM VATTBL a 
WHERE a.bhent='PT' AND a.PER = 20 AND (a.DATE BETWEEN @SDATE AND @EDATE) and a.Tax_Name like '%VAT%'
and a.ST_TYPE in ('LOCAL','')  and a.s_tax<>'' AND a.ITEMTYPE <> 'C' 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','G',@PER,@AMTA1,@AMTA2,0,'') 

--Commented by Priyanka on 25022014--start
-----Work ContractVAT 4% 
---INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','H',0,0,0,0,'')  
--Commented by Priyanka on 25022014--end

---Work ContractVAT 5% 
SET @AMTA1=0
SET @AMTA2=0
SET @PER  =0
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','I',0,0,0,0,'')  

---Work ContractVAT 12.5% 
SET @AMTA1=0
SET @AMTA2=0
SET @PER  =0
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','J',0,0,0,0,'')  

----R6.2(8) Exempted purchase
--SELECT @AMTA1=SUM(a.NET_AMT) FROM VATTBL a inner join #lcode lc on (a.bhent=lc.entry_ty)
-- WHERE (a.st_type = 'Local' AND a.TAX_NAME='EXEMPTED-L') AND lc.BCODE='PT' AND A.ITEMTYPE <> 'C' AND  (A.DATE BETWEEN @SDATE AND @EDATE)
--SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
--SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','K',@PER,@AMTA1,@AMTA2,0,'')  
--Commented by Priyanka on 25022014--end

--Added by Priyanka on 25022014--start



--R6.3 Local purchases not eligible for credit of Input Tax
SET @AMTA1=0
SET @AMTA2=0
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','J1',0,0,0,0,'')  
--Added by Priyanka on 25022014--end

--R6.2(9) Purchases from unregistered dealers --Commented by Priyanka on 25022014

--R6.3(1) Purchases from unregistered dealers 
SET @AMTA1=0
SET @AMTA2=0
SELECT @AMTA1 = ISNULL(SUM(A.vatonamt),0) FROM VATTBL A INNER JOIN IT_MAST B ON (A.It_code=B.It_code)
WHERE A.BHENT ='PT' AND A.ST_TYPE IN('','LOCAL') AND
A.S_TAX =''  AND ( A.DATE BETWEEN @SDATE AND @EDATE )
and  ( LTRIM(RTRIM(REPLACE(REPLACE(RTRIM(LTRIM(replace(A.form_nm,'FORM',''))),'-',''),' ',''))) != 'H')
and A.u_imporm not in('Composition Dealer','Against Retail Invoices','Non Creditable Goods','Invoices not eligible for ITC' ) AND  B.U_SHCODE NOT IN('Sch VII','Sch-VII','Schedule-VII','Schedule VII','Schedule-7','Schedule 7')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','L',0,@AMTA1,0,0,'')

--Added by Priyanka on 25022014--start
--R6.3(2) Purchases from Composition dealers
SET @AMTA1=0
SET @AMTA2=0
SET @PER=0
SELECT @AMTA1 = ISNULL(SUM(vatonamt),0) FROM VATTBL WHERE BHENT ='PT' AND ST_TYPE IN('','LOCAL') 
AND ( DATE BETWEEN @SDATE AND @EDATE ) AND u_imporm='Composition Dealer' and S_TAX = ''  and LTRIM(RTRIM(REPLACE(REPLACE(RTRIM(LTRIM(replace(TAX_NAME,'FORM',''))),'-',''),' ',''))) != 'H'
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','L1',@PER,@AMTA1,@AMTA2,0,'')

--R6.3(3) Purchase of Non creditable goods (Schedule-VII)

SET @AMTA1=0
SET @AMTA2=0
SELECT @AMTA1=isnull(SUM(a.vatonamt),0) FROM VATTBL a INNER JOIN IT_MAST B ON  ( A.It_code =B.It_code )
WHERE A.BHENT ='PT' AND (A.DATE BETWEEN @SDATE AND @EDATE) AND B.U_SHCODE  IN('Sch VII','Sch-VII','SchVII','Schedule-VII','Schedule VII','Schedule-7','Schedule 7','Schedule7')
AND ST_TYPE IN('','LOCAL')  AND U_IMPORM = 'Non Creditable Goods'
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','L2',@PER,@AMTA1,@AMTA2,0,'')  

--R6.3(4) Purchase of Tax Free Goods (Exempted)
SET @AMTA1=0
SET @AMTA2=0
SET @PER = 0
SELECT @AMTA1=SUM(vatonamt)FROM VATTBL WHERE  BHENT ='PT'  AND tax_name like '%EXEMPTED%' and ( DATE BETWEEN @SDATE AND @EDATE) 
AND ST_TYPE IN('','LOCAL')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','L3',@PER,@AMTA1,@AMTA2,0,'')

--R6.3(5) Purchases of labour and services related to works contract
SET @AMTA1=0
SET @AMTA2=0
set @PER = 0
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','L4',@PER,@AMTA1,@AMTA2,0,'')  

--R6.3(6) Purchases against tax invoices not eligible for ITC
SET @AMTA1=0
SET @AMTA2=0
SELECT @AMTA1=ISNULL(SUM(a.VATONAMT),0) FROM VATTBL a  WHERE a.st_type IN('LOCAL','')
AND a.bhent='PT' AND A.DATE BETWEEN @SDATE AND @EDATE  and a.u_imporm ='Invoices not eligible for ITC' 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','L5',0,@AMTA1,0,0,'') 

--R6.3(7) Purchase of goods against retail invoices
SET @AMTA1=0
SET @AMTA2=0
SET @PER = 0
SELECT @AMTA1=isnull(SUM(a.vatonamt),0) FROM VATTBL a WHERE a.u_imporm='Against Retail Invoices' AND a.bhent='PT' AND 
A.DATE BETWEEN @SDATE AND @EDATE  AND a.st_type IN('LOCAL','') 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','L6',@PER,@AMTA1,@AMTA2,0,'')

--R6.3(8) Purchase of Diesel & Petrol taxable in the hands of various Oil Marketing Companies in Delhi
SET @AMTA1=0
SET @AMTA2=0
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','L7',0,0,0,0,'')

--R6.3(9) Purchases from Delhi dealers against Form ‘H’
SET @AMTA1=0
SET @AMTA2=0
SELECT @AMTA1=ISNULL(SUM(a.vatonamt),0)FROM VATTBL a
WHERE  A.BHENT='PT' AND A.st_type in('LOCAL','') AND (a.DATE BETWEEN @SDATE AND @EDATE) 
and  ( LTRIM(RTRIM(REPLACE(REPLACE(RTRIM(LTRIM(replace(form_nm,'FORM',''))),'-',''),' ',''))) = 'H' OR  LTRIM(RTRIM(REPLACE(REPLACE(RTRIM(LTRIM(replace(TAX_NAME,'FORM',''))),'-',''),' ',''))) = 'H')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','L8',@PER,@AMTA1,@AMTA2,0,'')  

--R6.3(10) Purchase of Capital Goods (Used for manufacturing of non-creditable goods)
SET @AMTA1=0
SET @AMTA2=0
SET @PER = 0
SELECT @AMTA1=isnull(SUM(a.vatonamt),0) FROM VATTBL a INNER JOIN IT_MAST B ON  ( A.It_code =B.It_code )
WHERE A.BHENT ='PT' AND (A.DATE BETWEEN @SDATE AND @EDATE) AND B.U_SHCODE  NOT IN('Sch VII','Sch-VII','SchVII','Schedule-VII','Schedule VII','Schedule-7','Schedule 7','Schedule7')
AND ST_TYPE IN('','LOCAL')  AND U_IMPORM = 'Non Creditable Goods' AND A.itemtype='C' 

INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','L9',@PER,@AMTA1,@AMTA2,0,'')  
--Added by Priyanka on 25022014--end

--Tax credit before adjustments Sub Total (A)
SET @AMTA2=0
SELECT @AMTA2=sum(amt2),@AMTA1=SUM(amt1) FROM #FORMDVAT16  WHERE PARTSR='6' and SRNO IN ('A','B','C','D','E','F','G','H','I','J','J1','K','L','L1','L2','L3','L4','L5','L6','L7','L8','L9')
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','M',0,@AMTA1,@AMTA2,0,'') 

--Adjustments to tax credits (Complete Annexure and enter Total A4 here) (B)
SET @AMTA2=0
SELECT @AMTA2=AMT2 FROM #FORMDVAT16   WHERE PARTSR='6' --and SRNO='A'

SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','N',0,0,@AMTA2,0,'') 

--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','O',0,0,0,0,'') 




----------------------------------------------------------------------------------------------------

--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'7','A',0,0,@AMTC1,0,'')
--R7.2 Add : Interest, if payable

SET @AMTA1=0
SELECT  @AMTA1= ISNULL(SUM(net_amt),0) FROM  BPMAIN WHERE entry_ty ='BP' AND U_NATURE = 'INTEREST' AND party_nm ='VAT PAYABLE' AND ( DATE BETWEEN @SDATE AND @EDATE)
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'7A','B',0,0,@AMTA1,0,'') 
--R7.3 Add : Penalty, if payable

SET @AMTA1=0
SELECT  @AMTA1= ISNULL(SUM(net_amt),0) FROM  BPMAIN WHERE entry_ty ='BP' AND U_NATURE = 'Penalty' AND party_nm ='VAT PAYABLE' AND ( DATE BETWEEN @SDATE AND @EDATE)
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'7A','C',0,0,@AMTA1,0,'')
--R7.4 Less : Tax deducted at source
SET @AMTA1=0
SELECT  @AMTA1= ISNULL(SUM(net_amt),0) FROM  BPMAIN WHERE entry_ty ='BP' AND U_NATURE = 'TDS' AND party_nm ='VAT PAYABLE' AND ( DATE BETWEEN @SDATE AND @EDATE)
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'7A','D',0,0,@AMTA1,0,'') 

--Added by PANKAJ on 04.03.2014
--R7.6 Adjustment of excess balance under CST towards DVAT liability
SET @AMTB2=0
SELECT @AMTB2=ISNULL(SUM(C.amount),0) FROM  JVMAIN A  
inner JOIN JVACDET C on (A.entry_ty = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD AND C.amt_ty ='CR')
where A.ENTRY_TY in('J4')  and A.VAT_ADJ='Adjustment Towards CST'  AND A.party_nm ='VAT PAYABLE' AND ( A.date BETWEEN @SDATE AND @EDATE) 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'7A','D2',0,0,@AMTB2,0,'')

--Added by PANKAJ on 04.03.2014
--R7.7 Balance payable [(R7.1+R7.2+R7.3) – (R7.4+R7.5 +R7.6)]
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'7A','F',0,0,0,0,'')


-- ******************** PART 8 ********************************************


Declare @TAXONAMT as NUMERIC(20,2),@TAXAMT1 as NUMERIC(20,2),@ITEMAMT as NUMERIC(20,2),@INV_NO as varchar(10),@DATE as smalldatetime,@ADDRESS as varchar(100),@ITEM as varchar(50),@FORM_NM as varchar(30),@S_TAX as varchar(30),@QTY as numeric(18,2),@u_chqdt as smalldatetime
SELECT @TAXONAMT=0,@TAXAMT =0,@ITEMAMT =0,@INV_NO ='',@DATE ='',@PARTY_NM ='',@ADDRESS ='',@ITEM ='',@FORM_NM='',@S_TAX ='',@QTY=0,@u_chqdt=''


SET @CHAR=65
SET @PER = 0
declare Cur_VatPay cursor  for
select Taxonamt=A.NET_AMT,A.Gro_amt,A.taxamt,INV_NO='',B.Date,Party_nm=RTRIM(B.BANK_NM)+' '+RTRIM(ac.s_tax),Address='',Form_nm=B.U_CHALNO,S_tax=B.U_CHQDT
from VATTBL A inner join #lcode lc on (a.bhent=lc.entry_ty)
Inner Join Bpmain B On(A.Bhent = B.Entry_Ty And A.Tran_cd = B.Tran_cd) INNER JOIN AC_MAST AC ON (AC.ac_name=B.bank_nm)
where lc.bcode = 'BP' And B.Date Between @sdate and @edate And B.Party_nm like '%VAT PAYABLE%'  AND B.U_NATURE NOT IN('INTEREST','Penalty','TDS')
open Cur_VatPay
FETCH NEXT FROM Cur_VatPay INTO @TAXONAMT,@ITEMAMT,@TAXAMT,@INV_NO,@DATE,@PARTY_NM,@ADDRESS,@FORM_NM,@S_TAX
	WHILE (@@FETCH_STATUS=0)
	BEGIN
	SET @PER=CASE WHEN @PER IS NULL THEN 0 ELSE @PER END
	SET @TAXONAMT=CASE WHEN @TAXONAMT IS NULL THEN 0 ELSE @TAXONAMT END
	SET @TAXAMT=CASE WHEN @TAXAMT IS NULL THEN 0 ELSE @TAXAMT END
	SET @ITEMAMT=CASE WHEN @ITEMAMT IS NULL THEN 0 ELSE @ITEMAMT END
	SET @QTY=CASE WHEN @QTY IS NULL THEN 0 ELSE @QTY END
	SET @PARTY_NM=CASE WHEN @PARTY_NM IS NULL THEN '' ELSE @PARTY_NM END
	SET @INV_NO=CASE WHEN @INV_NO IS NULL THEN '' ELSE @INV_NO END
	SET @DATE=CASE WHEN @DATE IS NULL THEN '' ELSE @DATE END
	SET @ADDRESS=CASE WHEN @ADDRESS IS NULL THEN '' ELSE @ADDRESS END
	SET @ITEM=CASE WHEN @ITEM IS NULL THEN '' ELSE @ITEM END
	SET @S_TAX=CASE WHEN @S_TAX IS NULL THEN '' ELSE @S_TAX END
	SET @FORM_NM=CASE WHEN @FORM_NM IS NULL THEN '' ELSE @FORM_NM END

	--INSERT INTO #FORM01 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'8','Z',0,@AMTJ1-@AMTK1,@AMTK1,0,'') 
	if @TAXONAMT <> 0
	begin
	INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,INV_NO,DATE,PARTY_NM,ADDRESS,FORM_NM,S_TAX)
	 VALUES (1,'8','A',@PER,0,@TAXONAMT,@ITEMAMT,@INV_NO,@DATE,@PARTY_NM,@ADDRESS,@FORM_NM,@S_TAX)
   end 

	SET @CHAR=@CHAR+1
	FETCH NEXT FROM CUR_VatPay INTO @TAXONAMT,@ITEMAMT,@TAXAMT,@INV_NO,@DATE,@PARTY_NM,@ADDRESS,@FORM_NM,@S_TAX --@ITEM,@QTY
END
CLOSE CUR_VatPay
DEALLOCATE CUR_VatPay
	--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,INV_NO,DATE,PARTY_NM,ADDRESS,FORM_NM,S_TAX) 
 --  VALUES (1,'8','A',0,0,0,0,'','','','','','')




--R10.Details of Bank Account
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'9','A',0,0,0,0,'') 

--Added by PANKAJ on 04.03.2014
--R10.1 Account No.
SELECT @AMTA1=(SELECT AMT2 FROM #FORMDVAT16 WHERE PARTSR='8A' AND SRNO='C')
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SELECT @PARTY_NM=vaccno FROM MANUFACT
SET @PARTY_NM=CASE WHEN @PARTY_NM IS NULL THEN '' ELSE @PARTY_NM END
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'9','B',0,0,0,0,@PARTY_NM) 
SELECT @PARTY_NM=vatbkactype FROM MANUFACT
SET @PARTY_NM=CASE WHEN @PARTY_NM IS NULL THEN '' ELSE @PARTY_NM END
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'9','C',0,0,0,0,@PARTY_NM) 
SELECT @PARTY_NM=vatbkmicrno FROM MANUFACT
SET @PARTY_NM=CASE WHEN @PARTY_NM IS NULL THEN '' ELSE @PARTY_NM END
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'9','D',0,0,0,0,@PARTY_NM) 
SELECT @PARTY_NM=FBname+','+vatbkbranch FROM MANUFACT
SET @PARTY_NM=CASE WHEN @PARTY_NM IS NULL THEN '' ELSE @PARTY_NM END
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'9','E',0,0,0,0,@PARTY_NM)

--R11 Inter-state trade and exports/ imports

SET @AMTA1=0
SELECT @AMTA1=SUM(A.GRO_AMT) from VATTBL A   where a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') 
AND ((RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(REPLACE(a.form_nm,'FORM',''))),'-',''),'/',''),' ',''))))='C' 
OR (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(REPLACE(a.TAX_NAME,'FORM',''))),'-',''),'/',''),' ','')))) ='C')
AND (a.bhent in ('PT')) AND (a.DATE BETWEEN @SDATE AND @EDATE) 
AND A.itemtype<>'C'
SET @AMTA2=0

SELECT @AMTA2=SUM(A.GRO_AMT) from VATTBL A   where a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') 
AND ((RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(REPLACE(a.rform_nm,'FORM',''))),'-',''),'/',''),' ',''))))='C' 
OR (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(REPLACE(a.TAX_NAME,'FORM',''))),'-',''),'/',''),' ','')))) ='C')
AND (a.bhent in ('ST')) AND (a.DATE BETWEEN @SDATE AND @EDATE) 
AND A.itemtype<>'C'
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','A',0,@AMTA2,@AMTA1,0,'')

--R11.2 Against C+E1/E2 Forms
SET @AMTA1=0

SELECT @AMTA1=ISNULL(SUM(A.GRO_AMT),0) from VATTBL A  where a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY')
AND ((RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(REPLACE(a.form_nm,'FORM',''))),'-',''),'/',''),' ','')))) IN ('C','E1','E2')
OR (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(REPLACE(a.TAX_NAME,'FORM',''))),'-',''),'/',''),' ','')))) IN ('C','E1','E2'))
AND (a.bhent in ('PT')) AND (a.DATE BETWEEN @SDATE AND @EDATE) 
SET @AMTA2=0
SELECT @AMTA2=SUM(a.GRO_AMT) FROM VATTBL a  WHERE  a.bhent='ST' AND a.st_type in ('OUT OF COUNTRY','OUT OF STATE') 
AND ((RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(REPLACE(a.Rform_nm,'FORM',''))),'-',''),'/',''),' ','')))) IN ('C','E1','E2')
OR (RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(REPLACE(a.TAX_NAME,'FORM',''))),'-',''),'/',''),' ','')))) IN ('C','E1','E2'))
AND (a.DATE BETWEEN @SDATE AND @EDATE)
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','B',0,@AMTA2,@AMTA1,0,'')

--Commented by Priyanka on 26022014--start
----R11.3 Inward/outward Stock Transfer against F Forms
SET @AMTA1 = 0
SET @AMTA2 = 0 
SELECT @AMTA1=ISNULL(SUM(A.GRO_AMT),0) from VATTBL a  where A.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') AND (A.BHENT in ('PT'))
AND (a.DATE BETWEEN @SDATE AND @EDATE) AND a.U_IMPORM IN('Branch Transfer') 
AND (LTRIM(RTRIM(REPLACE(REPLACE(LTRIM(RTRIM(REPLACE(a.FORM_NM,'FORM',''))),'-',''),' ','')))='F' OR LTRIM(RTRIM(REPLACE(REPLACE(LTRIM(RTRIM(REPLACE(a.TAX_NAME,'FORM',''))),'-',''),' ','')))='F')

SELECT @AMTA2=ISNULL(SUM(A.GRO_AMT),0) from VATTBL  a where a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') AND (A.BHENT in ('ST')) 
AND (a.DATE BETWEEN @SDATE AND @EDATE)  AND a.U_IMPORM IN('Branch Transfer') 
AND (LTRIM(RTRIM(REPLACE(REPLACE(LTRIM(RTRIM(REPLACE(a.RFORM_NM,'FORM',''))),'-',''),' ','')))='F' 
OR LTRIM(RTRIM(REPLACE(REPLACE(LTRIM(RTRIM(REPLACE(a.TAX_NAME,'FORM',''))),'-',''),' ','')))='F')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','C1',0,@AMTA2,@AMTA1,0,'')

--R11.4 Inward/outward Stock Transfer (Consignment) against F Forms
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1=ISNULL(SUM(A.GRO_AMT),0) from VATTBL a where a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') 
AND (A.BHENT in ('PT'))
AND (a.DATE BETWEEN @SDATE AND @EDATE)  AND a.U_IMPORM IN('Consignment Transfer') 
AND (rtrim(ltrim(replace(replace(ltrim(rtrim(replace(a.FORM_NM,'form',''))),'-',''),' ','')))='F' OR ltrim(rtrim(replace(replace(rtrim(ltrim(replace(a.tax_name,'form',''))),'-',''),' ','')))='F')

SELECT @AMTA2=isnull(SUM(A.gro_amt),0) from VATTBL  a where a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') AND (A.BHENT in ('ST'))
AND (a.DATE BETWEEN @SDATE AND @EDATE)  AND a.U_IMPORM IN('Consignment Transfer')
AND LTRIM(RTRIM(REPLACE(REPLACE(LTRIM(RTRIM(REPLACE(A.rform_nm,'FORM',''))),'-',''),' ',''))) ='F'

INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','C2',0,@AMTA2,@AMTA1,0,'')

--R11.5 Own goods received/transferred after job work against F Forms 
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1=ISNULL(SUM(A.net_amt ),0) from IIMAIN A INNER JOIN AC_MAST B ON (A.Ac_id =B.Ac_id ) where a.ENTRY_TY = 'LI' AND (a.DATE BETWEEN @SDATE AND @EDATE) AND 
B.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY')
SELECT @AMTA2=ISNULL(SUM(A.net_amt ),0) from IRMAIN A  INNER JOIN AC_MAST B ON (A.Ac_id =B.Ac_id ) where a.ENTRY_TY = 'LR' AND (a.DATE BETWEEN @SDATE AND @EDATE) AND
B.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','C3',0,@AMTA2,@AMTA1,0,'')

--R11.6 Other dealers goods received/returned after job work against F Forms
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1=ISNULL(SUM(A.net_amt),0) from IIMAIN A  INNER JOIN AC_MAST B ON (A.Ac_id =B.Ac_id )WHERE A.entry_ty ='IL' AND (A.DATE BETWEEN @SDATE AND @EDATE) AND
B.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY')
SELECT @AMTA2=ISNULL(SUM(A.net_amt),0) from IRMAIN A INNER JOIN AC_MAST B ON (A.Ac_id =B.Ac_id ) WHERE A.entry_ty ='RL' AND (A.DATE BETWEEN @SDATE AND @EDATE) AND
B.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','C4',0,@AMTA2,@AMTA1,0,'')

--Added by Priyanka on 26022014--end

SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1=ISNULL(SUM(A.GRO_AMT ),0) from VATTBL a where a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY')
AND LTRIM(RTRIM(REPLACE(REPLACE(LTRIM(RTRIM(REPLACE(A.FORM_NM,'FORM',''))),'-',''),' ','')))='H'
AND (a.BHENT in ('PT')) AND (a.DATE BETWEEN @SDATE AND @EDATE) AND a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY')

SELECT @AMTA2=ISNULL(SUM(A.GRO_AMT),0) from VATTBL a where  A.BHENT = 'ST' AND A.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') 
AND LTRIM(RTRIM(REPLACE(REPLACE(LTRIM(RTRIM(REPLACE(A.RFORM_NM,'FORM',''))),'-',''),' ','')))='H'
AND (a.DATE BETWEEN @SDATE AND @EDATE) AND a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','D',0,@AMTA2,@AMTA1,0,'')

--R11.8 Against I Forms --Added by Priyanka on 27022014
set @AMTA1 = 0
set @AMTA2 = 0
SELECT @AMTA1=SUM(A.GRO_AMT) from VATTBL a where a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') 
AND ltrim(rtrim(replace(replace(ltrim(rtrim(replace(a.form_nm,'form',''))),'-',''),' ',''))) ='I'
AND a.bhent in ('PT')  AND (a.DATE BETWEEN @SDATE AND @EDATE) 
SELECT @AMTA2=SUM(A.GRO_AMT) from VATTBL a where a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') 
AND ltrim(rtrim(replace(replace(ltrim(rtrim(replace(a.rform_nm,'form',''))),'-',''),' ',''))) ='I'
AND a.bhent in ('st')  AND (a.DATE BETWEEN @SDATE AND @EDATE) 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','E',0,@AMTA2,@AMTA1,0,'')

--R11.9 Against J Forms --Added by Priyanka on 27022014
set @AMTA1 = 0
set @AMTA2 = 0
SELECT @AMTA1=isnull(SUM(A.gro_amt),0) from VATTBL a where a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') 
AND ltrim(rtrim(replace(replace(rtrim(ltrim(replace(a.FORM_NM ,'form',''))),'-',''),' ',''))) = 'J'
AND a.bhent in ('PT') AND (a.DATE BETWEEN @SDATE AND @EDATE) 
SELECT @AMTA2=isnull(SUM(A.gro_amt),0) from VATTBL a where a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') 
AND ltrim(rtrim(replace(replace(rtrim(ltrim(replace(a.RFORM_NM,'form',''))),'-',''),' ',''))) = 'J'
AND a.bhent in ('st') AND (a.DATE BETWEEN @SDATE AND @EDATE) 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','F',0,@AMTA2,@AMTA1,0,'')

--R11.10 Exports to /Imports from outside India --Added by Priyanka on 27022014
--- Commented for bug*-28100 Start:
--SELECT @AMTA1=SUM(A.NET_AMT) from VATTBL a inner join #lcode lc on (a.bhent=lc.entry_ty)
--INNER JOIN AC_MAST AC ON(AC.ac_name=A.PARTY_NM)
--where (lc.bcode in ('PT','EP')) AND (a.DATE BETWEEN @SDATE AND @EDATE) AND aC.ST_TYPE='OUT OF COUNTRY'
--SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
--SELECT @AMTA2=SUM(A.NET_AMT) from VATTBL a inner join #lcode lc on (a.bhent=lc.entry_ty)
--INNER JOIN AC_MAST AC ON(AC.ac_name=A.PARTY_NM)
--where (lc.bcode in ('ST')) AND (a.DATE BETWEEN @SDATE AND @EDATE) AND aC.ST_TYPE='OUT OF COUNTRY'
--SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
----- Added for bug-28100 
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1=ISNULL(SUM(A.GRO_AMT),0) from VATTBL A where A.BHENT  in ('PT') AND (a.DATE BETWEEN @SDATE AND @EDATE) AND A.ST_TYPE='OUT OF COUNTRY'
SELECT @AMTA2=ISNULL(SUM(A.GRO_AMT),0) from VATTBL a where A.BHENT in ('ST') AND (a.DATE BETWEEN @SDATE AND @EDATE) AND A.ST_TYPE='OUT OF COUNTRY'
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','G',0,@AMTA2,@AMTA1,0,'')

--Commented by Priyanka on 27022014--start
----R11.7(1) Exempted sale / purchase including High Sea Sale etc
--SELECT @AMTA1=SUM(A.NET_AMT) from VATTBL a inner join #lcode lc on (a.bhent=lc.entry_ty)
--where a.ST_TYPE in ('OUT OF STATE','OUT OF COUNTRY') AND (lc.bcode in ('PT','EP')) AND (a.DATE BETWEEN @SDATE AND @EDATE) AND a.itemtype='I'
--or a.U_IMPORM='High Seas Purchases' or a.tax_name='EXEMPTED'
--SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
--SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
--SELECT @AMTA1=SUM(A.NET_AMT) from VATTBL a inner join #lcode lc on (a.bhent=lc.entry_ty)
-- where ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') AND (lc.bcode in ('ST')) AND (a.DATE BETWEEN @SDATE AND @EDATE) AND a.itemtype='I'
--or a.U_IMPORM='High Sea Sales' or a.tax_name='EXEMPTED'
--SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','H',0,@AMTA2,@AMTA1,0,'')

----R11.8 Others (not supported by any Form)
--SELECT @AMTA1=SUM(A.NET_AMT) from VATTBL a inner join #lcode lc on (a.bhent=lc.entry_ty)
--left join stax_mas st on (st.entry_ty=a.bhent and st.tax_name=a.tax_name)
--where a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY')AND st.form_nm<>'' and st.rform_nm<>''  AND (lc.bcode in ('PT','EP')) AND (a.DATE BETWEEN @SDATE AND @EDATE) AND a.itemtype='I'
--SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
--SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
--SELECT @AMTA2=SUM(A.NET_AMT) from VATTBL a inner join #lcode lc on (a.bhent=lc.entry_ty)
--left join stax_mas st on (st.entry_ty=a.bhent and st.tax_name=a.tax_name)
--where  a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') AND st.form_nm='' and st.rform_nm='' AND (lc.bcode in ('ST')) AND (a.DATE BETWEEN @SDATE AND @EDATE) AND a.itemtype='I'
--SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','I',0,@AMTA2,@AMTA1,0,'')

----R11.9 Capital goods
----select * from VATTBL a inner join #lcode lc on (a.bhent=lc.entry_ty) where a.ST_TYPE='OUT OF STATE' AND (lc.bcode in ('PT','EP')) --AND a.itemtype='C'
--SELECT @AMTA1=SUM(A.NET_AMT) from VATTBL a inner join #lcode lc on (a.bhent=lc.entry_ty)
--where a.ST_TYPE='OUT OF STATE' AND (lc.bcode in ('PT','EP')) AND (a.DATE BETWEEN @SDATE AND @EDATE) AND a.itemtype='C'
--SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
--SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
--SELECT @AMTA2=SUM(A.NET_AMT) from VATTBL a inner join #lcode lc on (a.bhent=lc.entry_ty)
--where a.ST_TYPE='OUT OF STATE' AND (lc.bcode in ('ST')) AND (a.DATE BETWEEN @SDATE AND @EDATE) AND a.itemtype='C'
--SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','J',0,@AMTA2,@AMTA1,0,'')
--Commented by Priyanka on 27022014--end

--Added by Priyanka on 27022014--start

--R11.11 Sale of Exempted Goods (Schedule I)
--- commented for bug-28100 Start :
--SELECT @AMTA1=SUM(A.NET_AMT) from VATTBL a inner join #lcode lc on (a.bhent=lc.entry_ty)
--where a.ST_TYPE in ('OUT OF STATE','OUT OF COUNTRY','LOCAL') 
--AND (lc.bcode in ('PT','EP')) AND (a.DATE BETWEEN @SDATE AND @EDATE)
--AND a.tax_name='EXEMPTED'
--SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
--SELECT @AMTA2=SUM(A.NET_AMT) from VATTBL a inner join #lcode lc on (a.bhent=lc.entry_ty)
--where ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY','LOCAL') 
--AND (lc.bcode in ('ST')) AND (a.DATE BETWEEN @SDATE AND @EDATE)
--AND a.tax_name='EXEMPTED'
--SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
--- commented for bug-28100 End :
---- added for bug-28100 Start
set @AMTA1 = 0
set @AMTA2 = 0
SELECT @AMTA1=isnull(SUM(A.GRO_AMT),0) from VATTBL A INNER JOIN IT_MAST B ON (A.It_code =B.It_code)
where A.bhent ='PT' AND (a.DATE BETWEEN @SDATE AND @EDATE) AND a.tax_name like '%EXEMPTED%' 
and a.st_type in('OUT OF STATE','OUT OF COUNTRY') AND B.U_SHCODE IN('Schedule I','Schedule-I','Sch I','Sch-I','Sch-1','Sch 1') 

SELECT @AMTA2=isnull(SUM(A.GRO_AMT),0) from VATTBL a  INNER JOIN IT_MAST B ON (A.It_code =B.It_code)
where a.bhent in ('ST') AND (a.DATE BETWEEN @SDATE AND @EDATE) AND a.tax_name like '%EXEMPTED%' AND B.U_SHCODE IN('Schedule I','Schedule-I','Sch I','Sch-I','Sch-1','Sch 1') and a.ST_TYPE in('OUT OF STATE','OUT OF COUNTRY')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','G1',0,@AMTA2,@AMTA1,0,'')

--R11.12 High Sea Sales/Purchases
set @AMTA1 = 0
SELECT @AMTA1=isnull(SUM(A.GRO_AMT),0) from VATTBL a where a.ST_TYPE in ('OUT OF STATE','OUT OF COUNTRY')
AND bhent in ('PT') AND (a.DATE BETWEEN @SDATE AND @EDATE) AND a.U_IMPORM='High Seas Purchases'
set @AMTA2 = 0
SELECT @AMTA2=isnull(SUM(A.gro_amt),0) from VATTBL a  where ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') 
AND a.bhent in ('ST') AND (a.DATE BETWEEN @SDATE AND @EDATE)  AND a.U_IMPORM='High Sea Sales'
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','G2',0,@AMTA2,@AMTA1,0,'')

--R11.13 Sale/Purchases without Forms
set @AMTA1 = 0
set @AMTA2 = 0
SELECT @AMTA1=isnull(SUM(gro_amt),0) from VATTBL where ST_TYPE in ('OUT OF STATE','OUT OF COUNTRY') AND  bhent in ('PT')
AND (DATE BETWEEN @SDATE AND @EDATE)
AND FORM_NM = ''

SELECT @AMTA2=isnull(SUM(gro_amt),0) from VATTBL where ST_TYPE in ('OUT OF STATE','OUT OF COUNTRY') AND  bhent in ('ST')
AND (DATE BETWEEN @SDATE AND @EDATE) AND RFORM_NM = ''
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','G3',0,@AMTA2,@AMTA1,0,'')

--R11.14 Capital goods purchased against C Form
SET @AMTA1 = 0
SET @AMTA2 = 0
SELECT @AMTA1=isnull(SUM(gro_amt),0) from VATTBL where ST_TYPE in ('OUT OF STATE','OUT OF COUNTRY') AND  bhent in ('PT')
AND (DATE BETWEEN @SDATE AND @EDATE) AND itemtype='C' 
AND ltrim(rtrim(replace(replace(ltrim(rtrim(replace(form_nm,'form',''))),'-',''),' ',''))) = 'c'

SELECT @AMTA2=isnull(SUM(gro_amt),0) from VATTBL where ST_TYPE in ('OUT OF STATE','OUT OF COUNTRY') AND  bhent in ('ST') 
AND (DATE BETWEEN @SDATE AND @EDATE) AND itemtype='C' 
AND ltrim(rtrim(replace(replace(ltrim(rtrim(replace(rform_nm,'form',''))),'-',''),' ',''))) = 'c'
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'10','G4',0,@AMTA2,@AMTA1,0,'')

--************************* Annexure -1 ****************************************
--A1.1 Sales Cancelled
SET @AMTA1 =0 
SET @AMTA2 =0 
set @PARTY_NM = ''
SELECT @AMTA3=ISNULL(SUM(A.GRO_AMT),0),@AMTA4=ISNULL(SUM(A.TAXAMT),0) FROM  VATTBL A where a.BHENT IN ('DN') AND A.U_IMPORM ='Sales Cancelled'  AND a.PER IN(1,12.5,5,20) and a.Tax_name like '%vat%'
set @PARTY_NM =(SELECT distinct  CAST((A.PER )AS VARCHAR(50)) +',' FROM  VATTBL A where BHENT IN ('DN') AND A.U_IMPORM ='Sales Cancelled'  AND a.PER IN(12.5,5,1,20) and a.Tax_name like '%vat%' FOR XML PATH(''))
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) 
VALUES (1,'11','A',0,0,0,@AMTA3, CASE WHEN SUBSTRING(isnull(@PARTY_NM,''),1,1)=',' THEN SUBSTRING(isnull(@PARTY_NM,''),1,LEN(isnull(@PARTY_NM,''))) ELSE isnull(@PARTY_NM,'') END,@AMTA4)

--A1.2 Nature of sale changed [Section 8(1) (b)] --Added by Priyanka on 27022014
SET @AMTA1=0 
SET @AMTA2=0 
SET @AMTA3 = 0
SET @AMTA4 = 0
set @PARTY_NM = ''
SELECT @AMTA1=ISNULL(SUM(A.GRO_AMT),0),@AMTA2 = ISNULL(SUM(A.TAXAMT),0) FROM  VATTBL A where A.BHENT IN ('CN') AND A.U_IMPORM ='Change in Nature of Sale' AND A.PER IN(1,12.5,5,20) and a.Tax_name like '%vat%'
SELECT @AMTA3=ISNULL(SUM(A.GRO_AMT),0),@AMTA4 = ISNULL(SUM(A.TAXAMT),0) FROM  VATTBL A where A.BHENT IN ('DN') AND A.U_IMPORM ='Change in Nature of Sale'  AND A.PER IN(1,12.5,5,20) and a.Tax_name like '%vat%' 
set @PARTY_NM =(SELECT DISTINCT  CAST((A.PER )AS VARCHAR(50))+',' FROM  VATTBL A where A.BHENT IN ('DN','CN') AND A.U_IMPORM ='Change in Nature of Sale' AND A.PER IN(12.5,5,1,20) FOR XML PATH(''))
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) VALUES (1,'11','B',0,@AMTA1,@AMTA2,@AMTA3,CASE WHEN SUBSTRING(isnull(@PARTY_NM,''),1,1)=',' THEN SUBSTRING(isnull(@PARTY_NM,''),1,LEN(isnull(@PARTY_NM,''))) ELSE isnull(@PARTY_NM,'') END,@AMTA4) 

--A1.3 Change in agreed consideration [Section 8(1) (c )]
SET @AMTA1=0 
SET @AMTA2=0 
SET @AMTA3 = 0
SET @AMTA4 = 0
set @PARTY_NM = ''
SELECT @AMTA1=ISNULL(SUM(A.GRO_AMT),0) ,@AMTA2=ISNULL(SUM(A.TAXAMT),0) FROM  VATTBL A where A.BHENT IN ('CN') AND A.U_IMPORM ='Change in agreed consideration' AND A.PER IN(1,12.5,5,20)  and a.Tax_name like '%vat%' 
SELECT @AMTA3=ISNULL(SUM(A.GRO_AMT),0),@AMTA4=ISNULL(SUM(A.TAXAMT),0) FROM  VATTBL A where A.BHENT IN ('DN') AND A.U_IMPORM ='Change in agreed consideration'  AND A.PER IN(1,12.5,5,20)  and a.Tax_name like '%vat%' 
set @PARTY_NM =(SELECT DISTINCT CAST((A.PER )AS VARCHAR(50))+',' FROM  VATTBL A where A.BHENT IN ('DN','CN') AND A.U_IMPORM ='Change in agreed consideration' AND A.PER IN(12.5,5,1,20) FOR XML PATH(''))
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) VALUES (1,'11','C',0,@AMTA1,@AMTA2,@AMTA3,CASE WHEN SUBSTRING(isnull(@PARTY_NM,''),1,1)=',' THEN SUBSTRING(isnull(@PARTY_NM,''),1,LEN(isnull(@PARTY_NM,''))) ELSE isnull(@PARTY_NM,'') END,@AMTA4)

--A1.4 Goods sold returned [Section 8(1)(d)] --Added by Priyanka on 27022014
--- Commented by Suraj Kumawat date on 28-06-2016 Start
--DECLARE @TEMP1 VARCHAR(20)
--SET @AMTA2=0 
--SET @AMTA3=0 
--SET @AMTA5=0 
--SET @ADDRESS=''

--DECLARE TEMPLVL CURSOR FOR SELECT 
--st.level1
--FROM  VATTBL A 
--inner join stax_mas st on (a.tax_name=st.tax_name and a.bhent=st.entry_ty)  
--where a.bhent='SR'  and st.level1 in(1,5,12.5,20)
--GROUP BY ST.LEVEL1
--OPEN TEMPLVL
--FETCH NEXT FROM TEMPLVL INTO @FORM_NM
--WHILE @@FETCH_STATUS=0
--BEGIN
--	IF(@ADDRESS='')
--	BEGIN
--		SET @ADDRESS=@FORM_NM
--		FETCH NEXT FROM TEMPLVL INTO @FORM_NM
--	END	
--	ELSE
--	BEGIN
--		SET @ADDRESS=@ADDRESS+','+@FORM_NM
--		FETCH NEXT FROM TEMPLVL INTO @FORM_NM
--	END
--END
--CLOSE TEMPLVL
--DEALLOCATE TEMPLVL


--SELECT @AMTA2=SUM(a.TAXAMT) 
--,@AMTA5=SUM(a.NET_AMT) --Added by Priyanka on 27022014
--FROM  VATTBL A 
----inner join stax_mas st on (a.tax_name=st.tax_name and a.bhent=st.entry_ty)  --Added by Priyanka on 27022014 
--where a.bhent='SR'  and a.per in(1,5,12.5,20) and a.TAX_NAME like '%vat%'
----Group by st.level1 --Added by Priyanka on 27022014

--SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
--SET @AMTA3=CASE WHEN @AMTA3 IS NULL THEN 0 ELSE @AMTA3 END  --Added by Priyanka on 27022014
--SET @AMTA5=CASE WHEN @AMTA5 IS NULL THEN 0 ELSE @AMTA5 END  --Added by Priyanka on 27022014

--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'11','D',0,0,@AMTA2,0,'') --Commented by Priyanka on 27022014
--- --- Commented by Suraj Kumawat date on 28-06-2016 end :
SET @AMTA1=0 
SET @AMTA2=0 
SET @AMTA3 = 0
SET @AMTA4 = 0
set @PARTY_NM = ''
SELECT @AMTA3=ISNULL(SUM(A.GRO_AMT),0) ,@AMTA4=ISNULL(SUM(A.TAXAMT),0) FROM  VATTBL A where A.BHENT IN ('SR','CN') AND  A.PER IN(1,12.5,5,20)  and a.Tax_name like '%vat%' 
set @PARTY_NM =(SELECT DISTINCT CAST((A.PER )AS VARCHAR(50))+',' FROM  VATTBL A where A.BHENT IN ('SR','CN') AND  A.PER IN(12.5,5,1,20) FOR XML PATH(''))
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) VALUES (1,'11','D',0,0,0,@AMTA3,@ADDRESS,@AMTA4)
--A1.5 Bad debts written off [Section 8(1) (e) and Rule 7A] --Added by Priyanka on 27022014
SET @AMTA1=0 
SET @AMTA3=0 
SET @AMTA5=0 
SELECT @AMTA3=ISNULL(SUM(C.amount),0) FROM  JVMAIN A
inner JOIN JVACDET C on (A.entry_ty = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD AND C.amt_ty ='CR')
	where A.ENTRY_TY in('J4')  and A.VAT_ADJ='Bad Debts Written Off'  AND A.party_nm ='VAT PAYABLE' AND ( A.date BETWEEN @SDATE AND @EDATE)
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4,AMT5) VALUES (1,'11','E',0,0,0,@AMTA3,'',0,0)

--A1.6 Bad debts recovered [Rule 7A(3)] --Added by Priyanka on 27022014
SET @AMTA1=0 
SELECT @AMTA1=ISNULL(SUM(C.amount),0) FROM  JVMAIN A
inner JOIN JVACDET C on (A.entry_ty = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD AND C.amt_ty ='CR')
where A.ENTRY_TY in('J4')  and A.VAT_ADJ='Bad Debts Recovered'  AND A.party_nm ='VAT PAYABLE' AND ( A.date BETWEEN @SDATE AND @EDATE)
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) VALUES (1,'11','F',0,@AMTA1,0,0,'',0)

--A1.7 Tax payable on goods held on date of cancellation of registration (Section 23) --Added by Priyanka on 27022014

SET @AMTA1=0 
SET @AMTA3=0 
SET @AMTA5=0 
SELECT @AMTA1=ISNULL(SUM(C.amount),0) FROM  JVMAIN A
inner JOIN JVACDET C on (A.entry_ty = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD AND C.amt_ty ='CR')
where A.ENTRY_TY in('J4')  and A.VAT_ADJ='Tax Payable on Goods Held on the Date of Cancellation of Registration'  AND A.party_nm ='VAT PAYABLE' AND ( A.date BETWEEN @SDATE AND @EDATE)
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) VALUES (1,'11','G',0,@AMTA1,0,0,'',0) 
--A1.8 Other adjustments , if any (specify) --Added by Priyanka on 27022014
SET @AMTA1=0 
SET @AMTA2=0 
SET @AMTA3=0 
SET @AMTA4=0 
set @PARTY_NM = ''

SElECT @AMTA1=ISNULL(SUM(A.GRO_AMT),0),@AMTA2 = ISNULL(SUM(A.TAXAMT),0) FROM  VATTBL A where A.BHENT IN ('CN') AND A.U_IMPORM ='Other Adjustments (Sales)' AND A.PER IN(1,12.5,5,20)
SELECT @AMTA3=ISNULL(SUM(A.GRO_AMT),0),@AMTA4 =ISNULL(SUM(A.TAXAMT),0) FROM  VATTBL A where A.BHENT IN ('DN') AND A.U_IMPORM ='Other Adjustments (Sales)'  AND A.PER IN(1,12.5,5,20)
SET @PARTY_NM =(SELECT DISTINCT ','+ CAST((A.PER )AS VARCHAR(50)) FROM  VATTBL A where A.BHENT IN ('DN','CN') AND A.U_IMPORM ='Other Adjustments (Sales)' AND A.PER IN(12.5,5,1,20) FOR XML PATH(''))
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) 
VALUES (1,'11','H',0,@AMTA1,@AMTA2,@AMTA3,ISNULL(@PARTY_NM,''),@AMTA4)
--Total --Added by Priyanka on 27022014
SET @AMTA1=0 --Added by Priyanka on 27022014
SET @AMTA2=0 --Added by Priyanka on 27022014
SET @AMTA3=0 --Added by Priyanka on 27022014
SET @AMTA4=0 --Added by Priyanka on 27022014
SET @AMTA5=0 --Added by Priyanka on 27022014
SELECT @AMTA1=ISNULL(SUM(AMT1),0),@AMTA2=ISNULL(SUM(AMT2),0)
,@AMTA3=ISNULL(SUM(AMT3),0),@AMTA4=ISNULL(SUM(AMT4),0),@AMTA5=ISNULL(SUM(AMT5),0)
FROM #FORMDVAT16 WHERE PARTSR='11' 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4,AMT5) VALUES (1,'11','L',0,@AMTA1,@AMTA2,@AMTA3,'Total',@AMTA4,@AMTA5)

--A2 Total net increase/ (decrease) in Output Tax (A-B)
SET @AMTA1=0 --Added by Priyanka on 27022014
SET @AMTA2=0 --Added by Priyanka on 27022014
SELECT @AMTA1=ISNULL(SUM(AMT2),0),@AMTA2=ISNULL(SUM(AMT4),0) FROM #FORMDVAT16 WHERE PARTSR='11' and SRNO='L'
SET @AMTB1=@AMTA1-@AMTA2 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'12','A',0,0,@AMTB1,0,'')

Update #FORMDVAT16 Set AMT2 =@AMTB1 where Partsr = '5' and Srno = 'K'
--R5.14 Total Output Tax (R5.12 + R5.13) --Added by Priyanka on 25022014
SELECT @AMTA1=AMT2 FROM #FORMDVAT16  WHERE PARTSR='5' and SRNO='J'
SELECT @AMTB1=AMT2 FROM #FORMDVAT16  WHERE PARTSR='5' and SRNO='K'
SELECT @AMTB2=AMT1 FROM #FORMDVAT16  WHERE PARTSR='5' and SRNO='J'
SELECT @AMTC1=AMT1 FROM #FORMDVAT16  WHERE PARTSR='5' and SRNO='K'
SET @AMTA2=@AMTA1+@AMTB1
SET @AMTA3=@AMTB2+@AMTC1
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTB1=CASE WHEN @AMTB1 IS NULL THEN 0 ELSE @AMTB1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','L',@PER,@AMTA1,@AMTA2,0,'')  
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','L',0,0,@AMTA2,0,'')  

--R5.10 Total Output Tax --Commented by Priyanka on 25022014


--A3 Adjustments to Tax Credits

SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 
SELECT @AMTA1=ISNULL(SUM(C.amount),0) FROM  JVMAIN A
inner JOIN JVACDET C on (A.entry_ty = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD AND C.amt_ty ='CR')
where A.ENTRY_TY in('J4')  and A.VAT_ADJ='Reversal of ITC on Goods Sold Below Purchase Price'  
AND A.party_nm ='VAT PAYABLE' AND ( A.date BETWEEN @SDATE AND @EDATE)
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT5) VALUES (1,'13','A',0,0,0,0,'',@AMTA1)
--Added by Priyanka on 27022014--end

--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'13','A',0,0,0,0,'') --Commented by Priyanka on 27022014

--A3.2 Receipt of debit notes from the seller [Section 10(1)] --Added by Priyanka on 27022014
SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 

SET @ADDRESS=''
DECLARE TEMPLVL CURSOR FOR SELECT ST.level1 FROM   VATTBL A 
inner join dNMAIN v on (A.BHENT = v.ENTRY_TY AND A.TRAN_CD = v.TRAN_CD)
inner join stax_mas st on (a.tax_name=st.tax_name and a.bhent=st.entry_ty)  
where   A.BHENT IN ('DN') AND v.U_GPRICE IN('Receipt of Debit Notes from the seller','Receipt of Debit Notes from seller')  and st.level1 in(1,5,12.5,20) and st.tax_name like '%vat%'
GROUP BY ST.LEVEL1
OPEN TEMPLVL
FETCH NEXT FROM TEMPLVL INTO @FORM_NM
WHILE @@FETCH_STATUS=0
BEGIN
	IF(@ADDRESS='')
	BEGIN
		SET @ADDRESS=@FORM_NM
		FETCH NEXT FROM TEMPLVL INTO @FORM_NM
	END	
	ELSE
	BEGIN
		SET @ADDRESS=@ADDRESS+','+@FORM_NM
		FETCH NEXT FROM TEMPLVL INTO @FORM_NM
	END
END
CLOSE TEMPLVL
DEALLOCATE TEMPLVL
SELECT @AMTA2=SUM(TAXAMT), 
@AMTA5=SUM(gro_amt) --Added by Priyanka on 27022014
 FROM (SELECT DISTINCT A.TAXAMT,A.gro_amt  FROM  VATTBL A 
inner join dNMAIN v on (A.BHENT = v.ENTRY_TY AND A.TRAN_CD = v.TRAN_CD)
where   A.BHENT IN ('DN') AND v.U_GPRICE IN('Receipt of Debit Notes from the seller','Receipt of Debit Notes from seller') and a.per in(1,5,12.5,20) and a.TAX_NAME like '%vat%')C



SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
SET @AMTA3=CASE WHEN @AMTA3 IS NULL THEN 0 ELSE @AMTA3 END  
SET @AMTA5=CASE WHEN @AMTA5 IS NULL THEN 0 ELSE @AMTA5 END  

--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'13','B',0,@AMTA1,0,0,'') --Commented by Priyanka on 27022014
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4,AMT5) 
VALUES (1,'13','B',0,0,@AMTA2,0,'',@AMTA5,0) 

--A3.3 Receipt of credit notes from seller [Section 10(1)] --Added by Priyanka on 27022014

SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 
SET @ADDRESS=''

DECLARE TEMPLVL CURSOR FOR SELECT ST.level1 FROM   VATTBL A 
inner join CNMAIN v on (A.BHENT = v.ENTRY_TY AND A.TRAN_CD = v.TRAN_CD)
inner join stax_mas st on (a.tax_name=st.tax_name and a.bhent=st.entry_ty)  
where   A.BHENT IN ('CN') AND v.U_GPRICE IN('Receipt of Credit notes from seller','Receipt of Credit Notes from the seller') and st.level1 in(1,5,12.5,20) and st.tax_name like '%vat%'
GROUP BY ST.LEVEL1
OPEN TEMPLVL
FETCH NEXT FROM TEMPLVL INTO @FORM_NM
WHILE @@FETCH_STATUS=0
BEGIN
	IF(@ADDRESS='')
	BEGIN
		SET @ADDRESS=@FORM_NM
		FETCH NEXT FROM TEMPLVL INTO @FORM_NM
	END	
	ELSE
	BEGIN
		SET @ADDRESS=@ADDRESS+','+@FORM_NM
		FETCH NEXT FROM TEMPLVL INTO @FORM_NM
	END
END
CLOSE TEMPLVL
DEALLOCATE TEMPLVL
SELECT @AMTA1=SUM(TAXAMT), 
@AMTA4=SUM(gro_amt) --Added by Priyanka on 27022014
 FROM (SELECT DISTINCT A.TAXAMT,A.GRO_AMT  FROM  VATTBL A 
inner join CNMAIN v on (A.BHENT = v.ENTRY_TY AND A.TRAN_CD = v.TRAN_CD)
where   A.BHENT IN ('CN') AND v.U_GPRICE IN('Receipt of Credit notes from seller','Receipt of Credit Notes from the seller') and a.per in(1,5,12.5,20) and a.TAX_NAME like '%vat%')C

SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA3=CASE WHEN @AMTA3 IS NULL THEN 0 ELSE @AMTA3 END  
SET @AMTA4=CASE WHEN @AMTA4 IS NULL THEN 0 ELSE @AMTA4 END  

INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4,AMT5) VALUES (1,'13','C',0,@AMTA1,0,0,@ADDRESS,@AMTA4,0) 
--A3.4 Goods purchased returned or rejected [Section 10(1)] --Added by Priyanka on 27022014
SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 

SET @ADDRESS=''

DECLARE TEMPLVL CURSOR FOR SELECT st.level1
FROM  VATTBL A 
inner join stax_mas st on (a.tax_name=st.tax_name and a.bhent=st.entry_ty) 
where a.bhent IN('PR','DN')  and st.level1 in(1,5,12.5,20) and st.tax_name like'%vat%'
Group by st.level1
OPEN TEMPLVL
FETCH NEXT FROM TEMPLVL INTO @FORM_NM
WHILE @@FETCH_STATUS=0
BEGIN
	IF(@ADDRESS='')
	BEGIN
		SET @ADDRESS=@FORM_NM
		FETCH NEXT FROM TEMPLVL INTO @FORM_NM
	END	
	ELSE
	BEGIN
		SET @ADDRESS=@ADDRESS+','+@FORM_NM
		FETCH NEXT FROM TEMPLVL INTO @FORM_NM
	END
END
CLOSE TEMPLVL
DEALLOCATE TEMPLVL

SELECT distinct @AMTA2=SUM(a.TAXAMT), 
@AMTA5=SUM(a.gro_amt) --Added by Priyanka on 27022014
FROM  VATTBL A 
where a.bhent in('PR','DN') and a.per in(1,5,12.5,20) and a.TAX_NAME like '%vat%'
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
SET @AMTA3=CASE WHEN @AMTA3 IS NULL THEN 0 ELSE @AMTA3 END  --Added by Priyanka on 27022014
SET @AMTA5=CASE WHEN @AMTA5 IS NULL THEN 0 ELSE @AMTA5 END  --Added by Priyanka on 27022014

--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'13','D',0,0,@AMTA2,0,'') --Commented by Priyanka on 27022014
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT5) VALUES (1,'13','D',0,0,@AMTA2,0,@ADDRESS,@AMTA5) 

--A3.5 Change in use of goods, for purposes other than for which credit is allowed [Section 10(2)(a)] --Added by Priyanka on 27022014
SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 
--SELECT @AMTA2=SUM(C.amount) 
--,@AMTA3=st.level1,@AMTA5=SUM(v.net_amt) --Added by Priyanka on 27022014
--FROM  VATTBL A 
--inner join VATMAIN_VW v on (A.BHENT = v.ENTRY_TY AND A.TRAN_CD = v.TRAN_CD) and VAT_ADJ='Change in use of goods for purposes other than for which credit is allowed'
--inner JOIN   JVACDET C on (A.BHENT = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD) 
--inner join ac_mast ac on (c.ac_id=ac.ac_id)
--inner join stax_mas st on (a.tax_name=st.tax_name and a.bhent=st.entry_ty) 
--where C.entry_ty='J4' AND   ac.typ ='Input VAT'  and c.amt_ty='CR' 
--Group by st.level1 --Added by Priyanka on 27022014 

SELECT @AMTA2=0
,@AMTA3=0,@AMTA5=SUM(c.amount)
FROM  jvmain A  inner join JVACDET c on (a.entry_ty =c.entry_ty and a.Tran_cd =c.Tran_cd and c.amt_ty ='cr') 
where a.entry_ty = 'j4' and a.VAT_ADJ='Change in use of goods for purposes other than for which credit is allowed'
and  (a.date between @SDATE and @EDATE ) and a.party_nm='vat payable'

SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
SET @AMTA3=CASE WHEN @AMTA3 IS NULL THEN 0 ELSE @AMTA3 END  --Added by Priyanka on 27022014
SET @AMTA5=CASE WHEN @AMTA5 IS NULL THEN 0 ELSE @AMTA5 END  --Added by Priyanka on 27022014

--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'13','E',0,0,@AMTA2,0,'') --Commented by Priyanka on 27022014
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT5) VALUES (1,'13','E',0,0,@AMTA2,@AMTA3,'',@AMTA5) --Added by Priyanka on 27022014

--A3.6 Change in use of goods for purposes for which credit is allowed [Section 10(2)(b) --Added by Priyanka on 27022014
SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 
--SELECT @AMTA1=SUM(C.amount) 
--,@AMTA3=st.level1,@AMTA4=SUM(v.net_amt) --Added by Priyanka on 27022014
--FROM  VATTBL A 
--inner join VATMAIN_VW v on (A.BHENT = v.ENTRY_TY AND A.TRAN_CD = v.TRAN_CD) and VAT_ADJ='Change in use of goods for purposes other than for which credit is allowed'
--inner JOIN   JVACDET C on (A.BHENT = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD) 
--inner join ac_mast ac on (c.ac_id=ac.ac_id)
--inner join stax_mas st on (a.tax_name=st.tax_name and a.bhent=st.entry_ty)  --Added by Priyanka on 27022014 
--where C.entry_ty='J4' AND   ac.typ ='Input VAT'  and c.amt_ty='CR'
--Group by st.level1 --Added by Priyanka on 27022014 


SELECT @AMTA1=0
,@AMTA3=0,@AMTA4=SUM(c.amount)
FROM  jvmain A  inner join JVACDET c on (a.entry_ty =c.entry_ty and a.Tran_cd =c.Tran_cd and c.amt_ty ='cr') 
where a.entry_ty = 'j4' and a.VAT_ADJ='Change in use of goods for purposes which credit is allowed'
and  (a.date between @SDATE and @EDATE ) and a.party_nm='vat payable'
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA3=CASE WHEN @AMTA3 IS NULL THEN 0 ELSE @AMTA3 END  --Added by Priyanka on 27022014
SET @AMTA4=CASE WHEN @AMTA4 IS NULL THEN 0 ELSE @AMTA4 END  --Added by Priyanka on 27022014

--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'13','F',0,@AMTA1,0,0,'') --Commented by Priyanka on 27022014
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) VALUES (1,'13','F',0,@AMTA1,0,@AMTA3,'',@AMTA4) --Added by Priyanka on 27022014

--A3.7 Tax credit disallowed in respect of stock transfer out of Delhi [Section 10(3)] --Added by Priyanka on 27022014
SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 

SELECT @AMTA2=0
,@AMTA3=0,@AMTA5=SUM(c.amount)
FROM  jvmain A  inner join JVACDET c on (a.Tran_cd =c.Tran_cd and a.entry_ty =c.entry_ty and c.amt_ty ='dr')
where  a.entry_ty ='J4'  and a.VAT_ADJ='Tax credit disallowed in respect of stock transfer out of Delhi' 
and (a.date between @sdate and @EDATE )  and a.party_nm='vat payable'
--SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END  --Commented by Priyanka on 27022014
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END  --Added by Priyanka on 27022014
SET @AMTA3=CASE WHEN @AMTA3 IS NULL THEN 0 ELSE @AMTA3 END  --Added by Priyanka on 27022014
SET @AMTA5=CASE WHEN @AMTA5 IS NULL THEN 0 ELSE @AMTA5 END  --Added by Priyanka on 27022014

--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'13','G',0,@AMTA1,0,0,'') --Commented by Priyanka on 27022014
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT5) VALUES (1,'13','G',0,0,@AMTA2,@AMTA3,'',@AMTA5) --Added by Priyanka on 27022014
 
--A3.8 Tax credit for Transitional stock held on 1st April 2005 (Section 14) --Added by Priyanka on 27022014
SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 
--SELECT @AMTA1=SUM(C.amount) 
--,@AMTA3=st.level1,@AMTA4=SUM(v.net_amt) --Added by Priyanka on 27022014
--FROM  VATTBL A 
--inner join VATMAIN_VW v on (A.BHENT = v.ENTRY_TY AND A.TRAN_CD = v.TRAN_CD) and VAT_ADJ='Tax Credit for Transitional Stock Held on 1st April'
--inner JOIN   JVACDET C on (A.BHENT = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD) 
--inner join ac_mast ac on (c.ac_id=ac.ac_id)
--inner join stax_mas st on (a.tax_name=st.tax_name and a.bhent=st.entry_ty)  --Added by Priyanka on 27022014 
--where C.entry_ty='J4' AND   ac.typ ='Input VAT'  and c.amt_ty='CR'
--Group by st.level1 --Added by Priyanka on 27022014 
SELECT @AMTA1=0
,@AMTA3=0,@AMTA4=SUM(c.amount)
FROM  JVMAIN A  INNER JOIN JVACDET C ON (A.entry_ty = C.entry_ty AND A.Tran_cd =C.Tran_cd AND C.amt_ty ='DR')
WHERE  A.entry_ty='J4'  AND A.VAT_ADJ='Tax Credit for Transitional Stock Held on 1st April'  AND A.party_nm ='VAT PAYABLE'
AND ( A.DATE BETWEEN @SDATE AND @EDATE )
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA3=CASE WHEN @AMTA3 IS NULL THEN 0 ELSE @AMTA3 END  --Added by Priyanka on 27022014
SET @AMTA4=CASE WHEN @AMTA4 IS NULL THEN 0 ELSE @AMTA4 END  --Added by Priyanka on 27022014
--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'13','H',0,@AMTA1,0,0,'') --Commented by Priyanka on 27022014
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) VALUES (1,'13','H',0,@AMTA1,0,@AMTA3,'',@AMTA4) --Added by Priyanka on 27022014

--A3.9 Tax credit for purchase of Second-hand goods (Section 15) --Added by Priyanka on 27022014
SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 
--SELECT @AMTA1=SUM(C.amount) 
--,@AMTA3=st.level1,@AMTA4=SUM(v.net_amt) --Added by Priyanka on 27022014
--FROM  VATTBL A 
--inner join VATMAIN_VW v on (A.BHENT = v.ENTRY_TY AND A.TRAN_CD = v.TRAN_CD) and VAT_ADJ='Tax Credit for Purchase of Second–Hand Goods' 
--inner JOIN   JVACDET C on (A.BHENT = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD) 
--inner join ac_mast ac on (c.ac_id=ac.ac_id)
--inner join stax_mas st on (a.tax_name=st.tax_name and a.bhent=st.entry_ty)  --Added by Priyanka on 27022014 
--where V.ENTRY_TY='J4' AND  RTRIM(ac.typ) ='Input VAT'  and c.amt_ty='CR'
--Group by st.level1 --Added by Priyanka on 27022014 

 SELECT @AMTA1=0
,@AMTA3=0,@AMTA4=SUM(C.AMOUNT) 
FROM  JVMAIN  A  INNER JOIN JVACDET C ON (A.ENTRY_TY =C.entry_ty AND A.Tran_cd =C.Tran_cd AND C.amt_ty ='CR')
WHERE A.VAT_ADJ='Tax Credit for Purchase of Second–Hand Goods' AND A.ENTRY_TY='J4' AND A.party_nm ='VAT PAYABLE'
AND ( A.date BETWEEN @SDATE AND @EDATE)
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA3=CASE WHEN @AMTA3 IS NULL THEN 0 ELSE @AMTA3 END  --Added by Priyanka on 27022014
SET @AMTA4=CASE WHEN @AMTA4 IS NULL THEN 0 ELSE @AMTA4 END  --Added by Priyanka on 27022014
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) VALUES (1,'13','I',0,@AMTA1,0,@AMTA3,'',@AMTA4) 

--A3.10 Tax credit for goods held on the date of withdrawal from Composition Scheme [Section 16] --Added by Priyanka on 27022014
SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 
--SELECT @AMTA1=SUM(C.amount) 
--,@AMTA3=st.level1,@AMTA4=SUM(v.net_amt) --Added by Priyanka on 27022014
--FROM  VATTBL A 
--inner join VATMAIN_VW v on (A.BHENT = v.ENTRY_TY AND A.TRAN_CD = v.TRAN_CD) and VAT_ADJ='Tax Credit on Goods Held on Date of Withdrawal from Composition Scheme' 
--inner JOIN   JVACDET C on (A.BHENT = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD) 
--inner join ac_mast ac on (c.ac_id=ac.ac_id)
--inner join stax_mas st on (a.tax_name=st.tax_name and a.bhent=st.entry_ty)  --Added by Priyanka on 27022014 
--where V.ENTRY_TY='J4' AND  RTRIM(ac.typ) ='Input VAT'  and c.amt_ty='CR'
--Group by st.level1 --Added by Priyanka on 27022014 
SELECT @AMTA1=0  ,@AMTA4=ISNULL(SUM(c.amount),0) FROM  jvmain A  inner join JVACDET C ON(A.Tran_cd=C.Tran_cd AND A.entry_ty =C.entry_ty AND C.amt_ty ='DR')
where a.entry_ty ='J4' and a.VAT_ADJ='Tax Credit on Goods Held on Date of Withdrawal from Composition Scheme'  and a.party_nm ='VAT PAYABLE'
AND ( A.DATE BETWEEN @SDATE AND @EDATE)
--inner JOIN   JVACDET C on (A.BHENT = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD) 
--inner join ac_mast ac on (c.ac_id=ac.ac_id)
--inner join stax_mas st on (a.tax_name=st.tax_name and a.bhent=st.entry_ty)  --Added by Priyanka on 27022014 
--where V.ENTRY_TY='J4' AND  RTRIM(ac.typ) ='Input VAT'  and c.amt_ty='CR'
--Group by st.level1 --Added by Priyanka on 27022014 

--SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
--SET @AMTA3=CASE WHEN @AMTA3 IS NULL THEN 0 ELSE @AMTA3 END  --Added by Priyanka on 27022014
--SET @AMTA4=CASE WHEN @AMTA4 IS NULL THEN 0 ELSE @AMTA4 END  --Added by Priyanka on 27022014

--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'13','J',0,@AMTA1,0,0,'') --Commented by Priyanka on 27022014
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) VALUES (1,'13','J',0,@AMTA1,0,@AMTA3,'',@AMTA4) --Added by Priyanka on 27022014

--A3.11 Tax credit for trading stock and raw materials held at the time of registration (Section 20) --Added by Priyanka on 27022014
SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 
--SELECT @AMTA1=SUM(C.amount) 
--,@AMTA3=st.level1,@AMTA4=SUM(v.net_amt) --Added by Priyanka on 27022014
--FROM  VATTBL A 
--inner join VATMAIN_VW v on (A.BHENT = v.ENTRY_TY AND A.TRAN_CD = v.TRAN_CD) and VAT_ADJ=' Tax Credit for Trading Stock and Raw Materials Held at the Time of Registration' 
--inner JOIN   JVACDET C on (A.BHENT = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD) 
--inner join ac_mast ac on (c.ac_id=ac.ac_id)
--inner join stax_mas st on (a.tax_name=st.tax_name and a.bhent=st.entry_ty)  --Added by Priyanka on 27022014 
--where V.ENTRY_TY='J4' AND  RTRIM(ac.typ) ='Input VAT'  and c.amt_ty='DR'
--Group by st.level1 --Added by Priyanka on 27022014 

SELECT @AMTA1=0
,@AMTA3=0,@AMTA4=isnull(SUM(b.amount),0)
FROM  JVMAIN A INNER JOIN JVACDET B ON (A.Tran_cd =B.Tran_cd AND A.entry_ty =B.entry_ty AND B.amt_ty ='cr')
WHERE A.entry_ty ='J4' AND A.VAT_ADJ='Tax Credit for Trading Stock and Raw Materials Held at the Time of Registration' 
and a.party_nm ='vat payable'
AND  (A.DATE BETWEEN @SDATE AND @EDATE)
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) VALUES (1,'13','K',0,@AMTA1,0,@AMTA3,'',@AMTA4) 

--A3.12 Tax credit disallowed for goods lost or destroyed (Rule 7) --Added by Priyanka on 27022014
SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 
--SELECT @AMTA2=SUM(C.amount) 
--,@AMTA3=st.level1,@AMTA5=SUM(v.net_amt) --Added by Priyanka on 27022014
--FROM  VATTBL A 
--inner join VATMAIN_VW v on (A.BHENT = v.ENTRY_TY AND A.TRAN_CD = v.TRAN_CD) and VAT_ADJ='Tax Credit for Goods Lost Or Destroyed' 
--inner JOIN   JVACDET C on (A.BHENT = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD) 
--inner join ac_mast ac on (c.ac_id=ac.ac_id)
--inner join stax_mas st on (a.tax_name=st.tax_name and a.bhent=st.entry_ty)  --Added by Priyanka on 27022014 
--where V.ENTRY_TY='J4' AND  RTRIM(ac.typ) ='Input VAT'  and c.amt_ty='CR'
--Group by st.level1 --Added by Priyanka on 27022014 

SELECT @AMTA2=0
,@AMTA3=0,@AMTA5=isnull(SUM(b.amount),0) 
FROM  jvmain A inner join JVACDET b on (a.entry_ty =b.entry_ty and a.Tran_cd =b.Tran_cd and b.amt_ty ='cr')
where a.entry_ty ='J4' and a.VAT_ADJ='Tax Credit for Goods Lost Or Destroyed'  and a.party_nm ='vat payable'
AND  (A.DATE BETWEEN @SDATE AND @EDATE)
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT5) VALUES (1,'13','L',0,0,@AMTA2,@AMTA3,'',@AMTA5)

--A3.13 Tax credit adjustment on sale or stock transfer of capital goods [Section9(9)(a)] --Added by Priyanka on 27022014
SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 
--SELECT @AMTA2=SUM(C.amount) 
--,@AMTA3=st.level1,@AMTA5=SUM(v.net_amt) --Added by Priyanka on 27022014
--FROM  VATTBL A 
--inner join VATMAIN_VW v on (A.BHENT = v.ENTRY_TY AND A.TRAN_CD = v.TRAN_CD) and VAT_ADJ='Balance Tax Credit on Capital Goods' 
--inner JOIN   JVACDET C on (A.BHENT = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD) 
--inner join ac_mast ac on (c.ac_id=ac.ac_id)
--inner join stax_mas st on (a.tax_name=st.tax_name and a.bhent=st.entry_ty)  --Added by Priyanka on 27022014 
--where V.ENTRY_TY='J4' AND  RTRIM(ac.typ) ='Input VAT'  and c.amt_ty='CR'
--Group by st.level1 --Added by Priyanka on 27022014 

SELECT @AMTA2=0
,@AMTA3=0,@AMTA5=isnull(SUM(C.amount),0)
FROM  JVMAIN A	INNER JOIN JVACDET C ON (A.entry_ty =C.entry_ty AND A.Tran_cd =C.Tran_cd AND C.amt_ty ='CR')
WHERE  A.entry_ty ='J4' and A.VAT_ADJ='Balance Tax Credit on Capital Goods' AND A.party_nm ='VAT PAYABLE'
AND (A.date BETWEEN @SDATE AND @EDATE)

--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'13','M',0,0,@AMTA2,0,'') --Commented by Priyanka on 27022014
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT5) 
VALUES (1,'13','M',0,0,@AMTA2,@AMTA3,'',@AMTA5) --Added by Priyanka on 27022014

--A3.14 Second or Third installment of balance tax credit on capital goods. [Section 9(9)(a)] --Added by Priyanka on 27022014
SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 
--SELECT @AMTA1=SUM(C.amount) 
--,@AMTA3=st.level1,@AMTA4=SUM(v.net_amt) --Added by Priyanka on 27022014
--FROM  VATTBL A 
--inner join VATMAIN_VW v on (A.BHENT = v.ENTRY_TY AND A.TRAN_CD = v.TRAN_CD) and VAT_ADJ='Balance Tax Credit on Capital Goods' 
--inner JOIN   JVACDET C on (A.BHENT = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD) 
--inner join ac_mast ac on (c.ac_id=ac.ac_id)
--inner join stax_mas st on (a.tax_name=st.tax_name and a.bhent=st.entry_ty)  --Added by Priyanka on 27022014 
--where V.ENTRY_TY='J4' AND  RTRIM(ac.typ) ='Input VAT'  and c.amt_ty='DR'
--Group by st.level1 --Added by Priyanka on 27022014 

SELECT @AMTA1=0
,@AMTA3=0,@AMTA4=ISNULL(SUM(C.amount),0)
FROM  JVMAIN A INNER JOIN JVACDET C ON (A.entry_ty =C.entry_ty AND A.Tran_cd =C.Tran_cd AND C.amt_ty ='CR')
WHERE A.entry_ty ='J4' AND A.VAT_ADJ='Installment of Balance Tax Credit on Capital Goods' 
AND A.party_nm ='VAT PAYABLE' AND  ( A.date BETWEEN @SDATE AND @EDATE )
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) VALUES (1,'13','M1',0,@AMTA1,0,@AMTA3,'',@AMTA4) --Added by Priyanka on 27022014

--Added by Priyanka on 27022014--start
--A3.15 Second, Third or Fourth installment of balance tax credit on right to use goods. [Section 9(11)]
SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA3=CASE WHEN @AMTA3 IS NULL THEN 0 ELSE @AMTA3 END
SET @AMTA4=CASE WHEN @AMTA4 IS NULL THEN 0 ELSE @AMTA4 END
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4) VALUES (1,'13','M2',0,@AMTA1,0,@AMTA3,'',@AMTA4)

--A3.16 Other adjustments, if any (specify) --Added by Priyanka on 27022014
SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 
--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'13','N',0,@AMTA2,@AMTA2,0,'') --Commented by Priyanka on 27022014
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4,AMT5) VALUES (1,'13','N',0,@AMTA2,@AMTA2,@AMTA3,'',@AMTA4,@AMTA5) --Added by Priyanka on 27022014

SET @AMTA1=0 --Added by Priyanka on 27022014
SET @AMTA2=0 --Added by Priyanka on 27022014
SET @AMTA3=0 --Added by Priyanka on 27022014
SET @AMTA4=0 --Added by Priyanka on 27022014
SET @AMTA5=0 --Added by Priyanka on 27022014
SELECT @AMTA1=SUM(AMT1),@AMTA2=SUM(AMT2) 
,@AMTA3=SUM(AMT3),@AMTA4=SUM(AMT4),@AMTA5=SUM(AMT5) --Added by Priyanka on 27022014
FROM #FORMDVAT16 WHERE PARTSR='13'
--SET @AMTB1=@AMTA1-@AMTA2 
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
SET @AMTA3=CASE WHEN @AMTA3 IS NULL THEN 0 ELSE @AMTA3 END  
SET @AMTA4=CASE WHEN @AMTA4 IS NULL THEN 0 ELSE @AMTA4 END  
SET @AMTA5=CASE WHEN @AMTA5 IS NULL THEN 0 ELSE @AMTA5 END  
SET @AMTB1=CASE WHEN @AMTB1 IS NULL THEN 0 ELSE @AMTB1 END
--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'13','R',0,@AMTA1,@AMTA2,0,'Total:') --Commented by Priyanka on 27022014
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM,AMT4,AMT5) VALUES (1,'13','R',0,@AMTA1,@AMTA2,@AMTA3,'Total:',@AMTA4,@AMTA5) --Added by Priyanka on 27022014

--A4 Total net increase/ (decrease) in Input Tax Credit (C-D)
SET @AMTA1=0 --Added by Priyanka on 27022014
SET @AMTA2=0 --Added by Priyanka on 27022014
SELECT @AMTA1=SUM(AMT1),@AMTA2=SUM(AMT2) FROM #FORMDVAT16 WHERE PARTSR='13' AND SRNO='R'
print @AMTA1
print @AMTA2
SET @AMTB1=@AMTA1-@AMTA2 
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
SET @AMTB1=CASE WHEN @AMTB1 IS NULL THEN 0 ELSE @AMTB1 END
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'14','A',0,0,@AMTB1,0,'')

--Added by Priyanka on 28022014--start
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'15','A',0,0,0,0,'')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'15','B',0,0,0,0,'')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'15','C',0,0,0,0,'')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'15','D',0,0,0,0,'')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'15','D1',0,0,0,0,'')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'15','D11',0,0,0,0,'')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'15','D12',0,0,0,0,'')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'15','D2',0,0,0,0,'')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'15','D3',0,0,0,0,'')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'15','D4',0,0,0,0,'')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'15','D5',0,0,0,0,'')

--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'16','A',0,0,0,0,'')
--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'17','A',0,0,0,0,'')
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'18','A',0,0,0,0,'')
--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'19','A',0,0,0,0,'')
--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'15','D11',0,0,0,0,'')
--Added by Priyanka on 28022014--end

Update #FORMDVAT16 Set AMT2 =@AMTB1 where Partsr = '6' and Srno = 'N'

--Added by PANKAJ on 05.03.2014
-- ************************ Annexure 1B **************************************
-- Description of Asset (please specify)*,Value,ITC claimed
SET @AMTA1=0
SET @AMTA2=0 
SET @AMTA3=0
SET @AMTA4=0 
SET @AMTA5=0 
DECLARE ASSET CURSOR FOR SELECT B.IT_NAME,A.NET_AMT,A.TAXAMT from VATTBL A inner join #lcode lc on (a.bhent=lc.entry_ty)
INNER JOIN IT_MAST B ON (A.IT_CODE=B.IT_CODE) 
where a.ST_TYPE IN ('LOCAL','')  and b.type ='Machinery/Stores'
AND (lc.bcode in ('PT')) AND (a.DATE BETWEEN DATEADD(yy,-4,@SDATE)AND @EDATE) 
AND A.itemtype='C'
OPEN ASSET 
FETCH NEXT FROM ASSET INTO @PARTY_NM,@AMTA1,@AMTA2
WHILE @@FETCH_STATUS=0
	BEGIN
	INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'16','',0,@AMTA1,@AMTA2,0,@PARTY_NM)
	FETCH NEXT FROM ASSET INTO @PARTY_NM,@AMTA1,@AMTA2
	END	
CLOSE ASSET
DEALLOCATE ASSET	

--Added by PANKAJ on 05.03.2014
--Total value of assets purchased/transferred against C or F Form during the current tax period
SELECT @AMTA1=SUM(A.NET_AMT) from VATTBL A inner join #lcode lc on (a.bhent=lc.entry_ty)
where a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') AND ( RTRIM(LTRIM(REPLACE(LTRIM(RTRIM(REPLACE(A.form_nm,'FORM',''))),'-',''))) in('C','F') or  RTRIM(LTRIM(REPLACE(LTRIM(RTRIM(REPLACE(A.TAX_NAME ,'FORM',''))),'-',''))) in('C','F'))
AND (lc.bcode in ('PT')) AND (a.DATE BETWEEN @SDATE AND @EDATE) 
AND A.itemtype='C'

PRINT @AMTA1
SELECT @AMTA2=SUM(A.NET_AMT) from VATTBL A inner join #lcode lc on (a.bhent=lc.entry_ty)
where a.ST_TYPE IN ('OUT OF STATE','OUT OF COUNTRY') AND RTRIM(LTRIM(REPLACE(LTRIM(RTRIM(REPLACE(A.Rform_nm,'FORM',''))),'-',''))) ='C'
AND (lc.bcode in ('ST')) AND (a.DATE BETWEEN @SDATE AND @EDATE) 
AND A.itemtype='C'

SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END

SET @AMTA3=0
SET @AMTA3=@AMTA1+@AMTA2
UPDATE  #FORMDVAT16 SET AMT3=@AMTA3 WHERE PARTSR='16'

--Added by PANKAJ on 05.03.2014
--Details of Turnover
DECLARE TURNOVER CURSOR FOR SELECT sum(A.U_ASSEAMT+A.EXAMT+A.U_CESSAMT+A.U_HCESAMT),ST.LEVEL1,B.ST_TYPE from stitem A
INNER JOIN AC_MAST B ON (B.AC_ID=A.AC_ID AND B.S_TAX<>'') 
INNER JOIN STAX_MAS ST ON (ST.ENTRY_TY='ST' AND a.tax_name=st.tax_name) 
where B.ST_TYPE IN ('LOCAL','','OUT OF STATE')  AND ST.LEVEL1<>0 AND  (a.DATE BETWEEN @SDATE AND @EDATE) AND (ST.TAX_NAME LIKE '%VAT%'  or ST.TAX_NAME LIKE '%c.s.t%' ) AND ST.RFORM_NM=''
GROUP BY ST.LEVEL1,B.ST_TYPE
OPEN TURNOVER
FETCH NEXT FROM TURNOVER INTO @AMTA1,@PER,@TAXNAME
WHILE @@FETCH_STATUS=0
	BEGIN
		IF ((@TAXNAME='LOCAL') or (@TAXNAME=''))
		INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT4,AMT5,PARTY_NM) VALUES (1,'16','',@PER,@AMTA1,0,'')
		ELSE
		INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT4,AMT5,PARTY_NM,[ADDRESS]) VALUES (1,'16','',0,0,@AMTA1,'',CAST(@PER AS VARCHAR))
		FETCH NEXT FROM TURNOVER INTO @AMTA1,@PER,@TAXNAME

	END
	CLOSE TURNOVER
	DEALLOCATE TURNOVER 

-- ************************** Annexure 1B ************************************* END

--Added by PANKAJ on 06.03.2014
-- ************************** Annexure 1C ************************************* START
DECLARE @SDATE1 SMALLDATETIME,@EDATE1 SMALLDATETIME
--SET @SDATE1='2013-01-01'
--SET @SDATE1=DATEADD(M,3,@SDATE1)
--set @SDATE1=DATEADD(YY,YEAR(@sdate)-YEAR(@SDATE1),@SDATE1)
--SET @EDATE1=DATEADD(M,3,@SDATE1)
--SET @EDATE1=DATEADD(dd,-(DAY(DATEADD(mm,1,@EDATE1))),DATEADD(mm,1,@EDATE1))
--SET @CNT=1
--WHILE @CNT<=3 
--	BEGIN
--		SET @AMTA1=0
--		SET @AMTA2=0
--		SET @PER=0
--		SET @SRNO=CASE WHEN @CNT=1 THEN 'A' WHEN @CNT=2 THEN 'B' WHEN @CNT=3 THEN 'C' END  
--		SET @QTR=CASE WHEN @CNT=1 THEN 'Apr-Jul' WHEN @CNT=2 THEN 'Aug-Nov' WHEN @CNT=3 THEN 'Dec-Mar' END  

--		SELECT @PER=B.LEVEL1,@AMTA1=SUM(M.NET_AMT),@AMTA2=SUM(M.TAXAMT) FROM STMAIN M 
--		INNER JOIN STAX_MAS B ON (M.TAX_NAME=B.TAX_NAME AND B.ENTRY_TY='ST')
--		--WHERE M.DATE BETWEEN CONVERT(VARCHAR(25),@SDATE1,101) AND CONVERT(VARCHAr(25),@EDATE1,101) and (rtrim(ltrim(replace(replace(B.RFORM_NM,'form',''),'-','')))='H'  or rtrim(ltrim(replace(replace(B.tax_name,'form',''),'-','')))='H')
--		WHERE M.DATE BETWEEN CONVERT(VARCHAR(25),@SDATE1,101) AND CONVERT(VARCHAr(25),@EDATE1,101) and (rtrim(ltrim(replace(replace(B.RFORM_NM,'form',''),'-','')))='H'  or rtrim(ltrim(replace(replace(B.tax_name,'form',''),'-','')))='H')
--		GROUP BY B.LEVEL1
		
--		SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
--		SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
		
--		INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,PARTY_NM) VALUES (1,'17',@SRNO,@PER,@AMTA1,@AMTA2,@QTR)
		
--		SET @SDATE1=DATEADD(M,4,@SDATE1)
--		SET @EDATE1=DATEADD(M,3,@SDATE1)
--		SET @EDATE1=DATEADD(dd,-(DAY(DATEADD(mm,1,@EDATE1))),DATEADD(mm,1,@EDATE1))
--		SET @CNT=@CNT+1	
--	END
------------------------------
--set @SDATE1 = DATEADD(year,-1,@SDATE)
--set @EDATE1 = DATEADD(dd,-1,@SDATE)
--print 'last year'
--print @SDATE1 
--print  @EDATE1 
---Added by Suraj date on 29-06-2016 
print 'last year date'
print '04/01/'+cast((cast(SUBSTRING(@LYN,1,4)as integer)-1) as varchar(4))
print '03/31/'+cast((cast(SUBSTRING(@LYN,6,9) as integer )-1)as varchar(4))
SET @SDATE1 = '04/01/'+cast((cast(SUBSTRING(@LYN,1,4)as integer)-1) as varchar(4))
SET @EDATE1 ='03/31/'+cast((cast(SUBSTRING(@LYN,6,9) as integer )-1)as varchar(4))
print @SDATE1 
print @EDATE1
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,PARTY_NM) 
SELECT 1,'17','A',isnull(B.LEVEL1,0),isnull(SUM(M.gro_amt),0),isnull(SUM(M.TAXAMT),0),'Apr-Jul ' +cast(year(m.date) as varchar(30)) as quater FROM STitem M 
INNER JOIN STAX_MAS B ON (M.TAX_NAME=B.TAX_NAME AND B.ENTRY_TY='ST')
WHERE M.DATE <=CONVERT(VARCHAr(25),@EDATE1,101) and (month(m.date) in(4,5,6,7)) 
and (rtrim(ltrim(replace(replace(replace(B.RFORM_NM,'form',''),'-',''),' ','')))='H'  or rtrim(ltrim(replace(replace(replace(B.tax_name,'form',''),'-',''),' ','')))='H')
GROUP BY B.LEVEL1,(year(m.date)) order by  B.LEVEL1,(year(m.date))

--SELECT 1,'17','A',isnull(B.LEVEL1,0),isnull(SUM(M.gro_amt),0),isnull(SUM(M.TAXAMT),0),'Apr-Jul' as quater FROM STitem M 
--INNER JOIN STAX_MAS B ON (M.TAX_NAME=B.TAX_NAME AND B.ENTRY_TY='ST')
--WHERE (M.DATE BETWEEN CONVERT(VARCHAR(25),@SDATE1,101) AND CONVERT(VARCHAr(25),@EDATE1,101)) and (month(m.date) in(4,5,6,7)) 
--and (rtrim(ltrim(replace(replace(B.RFORM_NM,'form',''),'-','')))='H'  or rtrim(ltrim(replace(replace(B.tax_name,'form',''),'-','')))='H')
--GROUP BY B.LEVEL1 order by  B.LEVEL1


INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,PARTY_NM)
--VALUES (1,'17',@SRNO,@PER,@AMTA1,@AMTA2,'Apr-Jul')
SELECT 1,'17','A',isnull(B.LEVEL1,0),SUM(M.gro_amt),SUM(M.TAXAMT),'Aug-Nov ' +cast(year(m.date) as varchar(30)) as quater FROM STitem M 
INNER JOIN STAX_MAS B ON (M.TAX_NAME=B.TAX_NAME AND B.ENTRY_TY='ST')
WHERE (M.DATE <= CONVERT(VARCHAr(25),@EDATE1,101))
---(M.DATE BETWEEN CONVERT(VARCHAR(25),@SDATE1,101) AND CONVERT(VARCHAr(25),@EDATE1,101))
 and (month(m.date) in(8,9,10,11)) 
and (rtrim(ltrim(replace(replace(replace(B.RFORM_NM,'form',''),'-',''),' ','')))='H'  or rtrim(ltrim(replace(replace(replace(B.tax_name,'form',''),'-',''),' ','')))='H')
GROUP BY B.LEVEL1,year(m.date) order by B.LEVEL1,year(m.date)

INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,PARTY_NM)
--VALUES (1,'17',@SRNO,@PER,@AMTA1,@AMTA2,'Apr-Jul')
SELECT 1,'17','A',isnull(B.LEVEL1,0),isnull(SUM(M.gro_amt),0),isnull(SUM(M.TAXAMT),0),'Dec-Mar  ' +cast(year(m.date) as varchar(30)) as quater FROM STitem M 
INNER JOIN STAX_MAS B ON (M.TAX_NAME=B.TAX_NAME AND B.ENTRY_TY='ST')
WHERE (M.DATE <= CONVERT(VARCHAr(25),@EDATE1,101))  
----(M.DATE BETWEEN CONVERT(VARCHAR(25),@SDATE1,101) AND CONVERT(VARCHAr(25),@EDATE1,101)) 
and (month(m.date) in(12,1,2,3)) and (rtrim(ltrim(replace(replace(replace(B.RFORM_NM,'form',''),'-',''),' ','')))='H'  or rtrim(ltrim(replace(replace(replace(B.tax_name,'form',''),'-',''),' ','')))='H')
GROUP BY B.LEVEL1,year(m.date) order by  B.LEVEL1,year(m.date)

IF NOT EXISTS(SELECT TOP 1 SRNO FROM #FORMDVAT16 WHERE PART = 1 AND PARTSR ='17' AND SRNO ='A' )
BEGIN
	INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,PARTY_NM) VALUES (1,'17','A',0,0,0,'')
END


-- ************************** Annexure 1C ************************************* END
--Added by PANKAJ on 05.03.2014
-- ************************ Annexure 1 D ************************************** start
-- Tax rate wise details of Stock in hand as on 31st March (Year)(To be filled with 2nd quarter return)

SET @CNT=1
while @CNT<=5
BEGIN
	SET @SRNO=CASE WHEN @CNT=1 THEN 'A' WHEN @CNT=2 THEN 'B' WHEN @CNT=3 THEN 'C' WHEN @CNT=4 THEN 'D' WHEN @CNT=5 THEN 'E' END  
	INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'19',@SRNO,0,0,0,0,'')  
	SET @CNT=@CNT+1	
END
SELECT ENTRY_TY,TRAN_CD,ITSERIAL,IT_CODE,QTY,RATE,U_ASSEAMT AS AMOUNT,TAX_NAME,LEVEL1=CAST(0.00 AS NUMERIC(5,2) ) INTO #STKVAL11 FROM STITEM WHERE 1=2		--Added By Shrikant S. on 03/05/2012 for Bug-3900-->Added dc_no column by sandeep for bug-1724 on 05/06/12		--Bug8025
Insert InTo #STKVAL11 EXECUTE USP_REP_TAXWISE_STOCK
			@TMPAC, @TMPIT, @SPLCOND, @SDATE, @EDATE
		 ,@SAC, @EAC, @SIT, @EIT, @SAMT, @EAMT
		 ,@SDEPT, @EDEPT, @SCATE, @ECATE,@SWARE
		 ,@EWARE, @SINV_SR, @EINV_SR, @LYN, 'FIFO'
		--select * from #STKVAL
		delete from #STKVAL11 where QTY=0
		
		--select SUM(AMOUNT),LEVEL1 from #STKVAL 
		--where level1 in('0.00','1.00','5.00','12.5','20.00')
		--group by level1
		
		--SELECT * FROM #STKVAL
		DECLARE STOCK CURSOR FOR select LEVEL1,SUM(AMOUNT) from #STKVAL11
		where level1 in('0.00','1.00','5.00','12.5','20.00')
		group by level1
		OPEN STOCK
		FETCH NEXT FROM STOCK INTO @PER,@AMTA1
		WHILE @@FETCH_STATUS=0
			BEGIN
			SET @SRNO=CASE WHEN @PER='0.00' THEN 'A' WHEN @PER='1.00' THEN 'B' WHEN @PER='5.00' THEN 'C' WHEN @PER='12.5' THEN 'D' WHEN @PER='20.00' THEN 'E' END  
			--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'19',@SRNO,@PER,@AMTA1,0,0,'')  	
			UPDATE #FORMDVAT16 SET AMT1=@AMTA1 WHERE SRNO=@SRNO AND PARTSR='19'
			FETCH NEXT FROM STOCK INTO @PER,@AMTA1
			END
		CLOSE STOCK
		DEALLOCATE STOCK		
		
		SET @AMTA1=(SELECT SUM(AMT1) FROM  #FORMDVAT16 WHERE PARTSR='19' AND SRNO IN('A','B','C','D','E'))
		INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'19','F',0,@AMTA1,0,0,'')  	
		drop table #STKVAL11 
-- ************************ Annexure 1 D ************************************** end


--R6.5 Total Output Tax
SELECT @AMTA1=AMT2 FROM #FORMDVAT16  WHERE PARTSR='6' and SRNO='M'
SELECT @AMTB1=AMT2 FROM #FORMDVAT16  WHERE PARTSR='6' and SRNO='N'
SELECT @AMTC1=AMT1 FROM #FORMDVAT16  WHERE PARTSR='6' and SRNO='M'
SELECT @AMTC2=AMT1 FROM #FORMDVAT16  WHERE PARTSR='6' and SRNO='N'
SET @AMTA2=@AMTA1+@AMTB1
SET @AMTD1=@AMTc1+@AMTc2

SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTB1=CASE WHEN @AMTB1 IS NULL THEN 0 ELSE @AMTB1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
SET @AMTd1=CASE WHEN @AMTd1 IS NULL THEN 0 ELSE @AMTD1 END
--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'5','L',@PER,@AMTA1,@AMTA2,0,'')  
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'6','O',0,@AMTD1,@AMTA2,0,'') 
--R7.1 Net Tax 
SELECT @AMTA1=AMT2 FROM #FORMDVAT16  WHERE PARTSR='5' and SRNO='L'
SELECT @AMTB1=AMT2 FROM #FORMDVAT16  WHERE PARTSR='6' and SRNO='O'
SET @AMTA2=@AMTA1-@AMTB1
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTB1=CASE WHEN @AMTB1 IS NULL THEN 0 ELSE @AMTB1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'7A','A',0,0,@AMTA2,0,'') --Added by Priyanka on 25022014

--R7.5 Tax credit carried forward from previous tax period
SET @AMTA2=0
SELECT @AMTA2=ISNULL(SUM(C.amount),0) FROM  JVMAIN A  
inner JOIN JVACDET C on (A.entry_ty = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD AND C.amt_ty ='CR')
where A.ENTRY_TY in('J4')  and A.VAT_ADJ='Tax credit carried forward from previous tax period'  AND A.party_nm ='VAT PAYABLE' AND ( A.date BETWEEN @SDATE AND @EDATE) 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'7A','D1',0,0,@AMTA2,0,'')  

--R7.5 Balance payable (R7.1+R7.2+R7.3-R7.4)
SELECT @AMTA1=sum(AMT2) FROM #FORMDVAT16  WHERE PARTSR='7' and SRNO IN ('A','B','C')
SELECT @AMTB1=sum(AMT2) FROM #FORMDVAT16  WHERE PARTSR='7' and SRNO IN ('D')

SET @AMTA2=@AMTA1-@AMTB1
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTB1=CASE WHEN @AMTB1 IS NULL THEN 0 ELSE @AMTB1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'7','E',0,0,@AMTA2,0,'') --Commented by Priyanka on 25022014
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'7C','E',0,0,@AMTA2,0,'') --Added by Priyanka on 25022014


------------------ Amount deposited by the dealer (attach proof of payment with Form DVAT-56)
set @AMTA1 = 0
SELECT @AMTA1=isnull(sum(AMT2),0) FROM #FORMDVAT16  WHERE PARTSR='8' and SRNO IN ('A')
update #FORMDVAT16  set AMT2 = @AMTA1 WHERE PARTSR='7A' and SRNO IN ('F')

------------------


---------------
SET @AMTA4=0
SET @AMTA5=0
SELECT @AMTA4=ISNULL(sum(amt2),0) FROM #FORMDVAT16  WHERE PARTSR='7A' and SRNO IN ('A','B','C')
SELECT @AMTA5=ISNULL(sum(amt2),0) FROM #FORMDVAT16  WHERE PARTSR='7A' and SRNO IN ('D','D1','D2')
SET @AMTB2=@AMTA4-@AMTA5
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'7A','E1',0,0,@AMTB2,0,'')
------R7.1 Net Tax                       (R5.14) - (R6.6)


--R7.6 Less : Amount deposited by the dealer (attach proof of payment)
SELECT @AMTA1=AMT2 FROM #FORMDVAT16  WHERE PARTSR='7A' AND SRNO=''-- and SRNO IN ('A','B','C')
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'7C','F',0,0,@AMTA1,0,'') 

--R8 Net Balance* (R7.5-R7.6)
SELECT @AMTA1=sum(AMT2) FROM #FORMDVAT16  WHERE PARTSR='7A' and SRNO IN ('E1')
SELECT @AMTB1=sum(AMT2) FROM #FORMDVAT16  WHERE PARTSR='7A' and SRNO IN ('F')
SET @AMTA2=@AMTA1-@AMTB1
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTB1=CASE WHEN @AMTB1 IS NULL THEN 0 ELSE @AMTB1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'8','Z',0,0,@AMTA2,0,'')

--Update #FORMDVAT16 Set AMT2=CASE WHEN @AMTA2 < 0 THEN abs(@AMTA2) ELSE abs(@AMTA2)  END  where Partsr = '8A' and Srno = 'A'


--R9.0 Balance brought forward from line R8 (Positive value of R8)
SET @AMTA2=0
SET @AMTA5 = 0
SELECT @AMTA2=ISNULL(AMT2,0) FROM #FORMDVAT16  WHERE PARTSR='8' and SRNO IN ('Z')
print  @AMTA2
set @AMTA1 = 0
SET @AMTA1=CASE WHEN @AMTA2 < 0 THEN ABS(@AMTA2) ELSE 0 END
SET @AMTA5 =CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'8A','A',0,0,@AMTA1,0,'')	

--R9.1 Adjusted against liability under Central Sales Tax
SET @AMTA1=0
SELECT @AMTA1=ISNULL(SUM(C.amount),0) FROM  JVMAIN A  
inner JOIN   JVACDET C on (A.entry_ty = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD AND C.amt_ty ='CR')
where A.ENTRY_TY in('J4')  and A.VAT_ADJ='Adjusted against liability under CST'  AND A.party_nm ='VAT PAYABLE' AND ( A.date BETWEEN @SDATE AND @EDATE) 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'8A','B',0,0,CASE WHEN @AMTA5 < 0 THEN @AMTA1 ELSE 0 END ,0,'')
--R9.2 Refund Claimed
SET @AMTA1=0
print @AMTA5
SELECT @AMTA1=ISNULL(SUM(C.amount),0) FROM  JVMAIN A  
inner JOIN   JVACDET C on (A.entry_ty = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD AND C.amt_ty ='CR')
where A.ENTRY_TY in('J4')  and A.VAT_ADJ='Refund Claim'  AND A.party_nm ='VAT PAYABLE' AND ( A.date BETWEEN @SDATE AND @EDATE) 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'8A','C',0,0,CASE WHEN @AMTA5 < 0 THEN @AMTA1 ELSE 0 END,0,'')

--R9.3 Balance carried forward to next tax period
SET @AMTA1=0
SELECT @AMTA1=ISNULL(SUM(C.amount),0) FROM  JVMAIN A
inner JOIN   JVACDET C on (A.entry_ty = C.ENTRY_TY AND A.TRAN_CD = C.TRAN_CD AND C.amt_ty ='CR')
where A.ENTRY_TY in('J4')  and A.VAT_ADJ='Balance carried forward to next tax period'  AND A.party_nm ='VAT PAYABLE' AND ( A.date BETWEEN @SDATE AND @EDATE) 
INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'8A','D',0,0,CASE WHEN @AMTA5 < 0 THEN @AMTA1 ELSE 0 END,0,'')	
-------------------------------------------------------
--INSERT INTO #FORMDVAT16 (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'8A','E',0,0,0,0,'')	

Update #FORMDVAT16 set  PART = isnull(Part,'') , Partsr = isnull(PARTSR,''), SRNO = isnull(SRNO,''),
RATE = isnull(RATE,0), AMT1 = isnull(AMT1,0), AMT2 = isnull(AMT2,0), AMT3 = isnull(AMT3,0),
INV_NO = isnull(INV_NO,''), DATE = isnull(Date,''),PARTY_NM = isnull(Party_nm,''), ADDRESS = isnull(Address,''),
FORM_NM = isnull(form_nm,''), S_TAX = isnull(S_tax,'')--, Qty = isnull(Qty,0),  ITEM =isnull(item,''),
,RFORM_NM = isnull(rform_nm,''), AMT4 = isnull(AMT4,0), AMT5 = isnull(AMT5,0)  --Added by Priyanka on 27022014

SELECT * FROM #FORMDVAT16  order by cast(substring(partsr,1,case when (isnumeric(substring(partsr,1,2))=1) then 2 else 1 end) as int), partsr,SRNO
----where partsr='5'
--order by cast(substring(partsr,1,case when (isnumeric(substring(partsr,1,2))=1) then 2 else 1 end) as int), partsr,SRNO
--SET @SQLCOMMAND='SELECT * INTO '+@OUTPUTB+' FROM #FORMDVAT16 order by cast(substring(partsr,1,case when (isnumeric(substring(partsr,1,2))=1) then 2 else 1 end) as int), partsr,SRNO'
--EXECUTE SP_EXECUTESQL @SQLCOMMAND
end

set ANSI_NULLS OFF
--Print 'DL VAT FORM 16'
