If Exists (Select [name] From SysObjects Where xType='P' and [name]='USP_REP_STOCK_IN_TRANSIT_DADOS_PANDL')
Begin
	Drop Procedure USP_REP_STOCK_IN_TRANSIT_DADOS_PANDL
End
Go
Create Procedure [dbo].[USP_REP_STOCK_IN_TRANSIT_DADOS_PANDL]
 @SDATE  SMALLDATETIME,@EDATE SMALLDATETIME
 ,@SAC AS VARCHAR(60),@EAC AS VARCHAR(60)
 ,@SIT AS VARCHAR(60),@EIT AS VARCHAR(60)
 ,@SWARE AS VARCHAR(60),@EWARE AS VARCHAR(60)
As
DECLARE @FCON AS NVARCHAR(2000)
EXECUTE   USP_REP_FILTCON 
@VTMPAC ='',@VTMPIT ='',@VSPLCOND =''
,@VSDATE=NULL
,@VEDATE=@EDATE
,@VSAC =@SAC,@VEAC =@EAC
,@VSIT=@SIT,@VEIT=@EIT
,@VSAMT=0,@VEAMT=0
,@VSDEPT='',@VEDEPT=''
,@VSCATE ='',@VECATE =''
,@VSWARE =@SWARE,@VEWARE  =@EWARE
,@VSINV_SR ='',@VEINV_SR =''
,@VMAINFILE='PTMAIN',@VITFILE='PTITEM',@VACFILE=' '
,@VDTFLD ='DATE'
,@VLYN=Null
,@VEXPARA=null
,@VFCON =@FCON OUTPUT
print 'filter cond'
print @FCON
-- VNAME
--IF @FCON=''
--BEGIN
--SET @FCON='WHERE PTMAIN.DATE BETWEEN '''+CONVERT(VARCHAR(50),@SDATE)+''' AND '''+CONVERT(VARCHAR(50),@EDATE)+''''
--END
Declare @SQLCOMMAND AS NVARCHAR(4000),@ShowNil Varchar(100),@FldNmLst Varchar(4000),@FldValLst Varchar(4000),@CondCount Int
Select RecId = IDENTITY(int, 1,1),VStkCond = Cast(' ' as varchar(4000)),* 
into ##STKVALConfig from StkValConfig

SELECT RecId=Cast(0 as int),
	RawId=Cast(0 as int),
	condition=Cast(' ' as nvarchar(max)),
	descrip=Cast(' ' as nvarchar(max)),
	tbl_name=Cast(' ' as nvarchar(max))
	Into #StkValConfig1 FROM ##StkValConfig where 1 = 2
	
	
SET ARITHABORT On
Set @CondCount = 1
WHILE 1 = 1
BEGIN
	Set @SQLCOMMAND	= 'Insert into #StkValConfig1
		SELECT RecId,'+cast(@CondCount as varchar(5))+',
		vcond.value(''(//tmpvcond/condition)['+cast(@CondCount as varchar(5))+']'', ''nvarchar(max)'') as condition,
		vcond.value(''(//tmpvcond/descrip)['+cast(@CondCount as varchar(5))+']'', ''nvarchar(max)'') as descrip,
		vcond.value(''(//tmpvcond/tbl_name)['+cast(@CondCount as varchar(5))+']'', ''nvarchar(max)'') as tbl_name
		FROM ##StkValConfig'
	EXEC SP_EXECUTESQL  @SQLCOMMAND	
		
	IF Not Exists(Select * from #StkValConfig1 where RawId = @CondCount And condition Is Not Null)
		BREAK
	ELSE
		Set @CondCount = @CondCount + 1
		CONTINUE
END	

Update #StkValConfig1 Set condition = ISNULL(condition,''),descrip = ISNULL(descrip,''),tbl_name = ISNULL(tbl_name,'')
Delete from #StkValConfig1 Where condition = '' and descrip = '' and tbl_name = ''
Update #StkValConfig1 Set tbl_name = (case when tbl_name = 'STKL_VW_MAIN' then 'M' else (case when tbl_name = 'STKL_VW_ITEM' then 'I' else tbl_name end) end)

Declare @recid int,@condition Varchar(100),@descrip Varchar(4000),@tbl_name Varchar(100),@stkvcond Varchar(4000)
DECLARE C0STKVAL CURSOR FOR 
SELECT RecId FROM #StkValConfig1 Group BY RecId
OPEN C0STKVAL
FETCH NEXT FROM C0STKVAL INTO @recid
WHILE @@FETCH_STATUS=0
	BEGIN
	Set @stkvcond = ''

	DECLARE C01STKVAL CURSOR FOR 
	SELECT Condition,Descrip,Tbl_Name FROM #StkValConfig1 Where RecId = @recid
	ORDER BY RecId,Tbl_Name,Condition
	OPEN C01STKVAL
	FETCH NEXT FROM C01STKVAL INTO @Condition,@Descrip,@Tbl_Name
	WHILE @@FETCH_STATUS=0
	BEGIN
			
		if replace(replace(@stkvcond,'[','+'),']','+') like '%'+'+'+LTRIM(RTRIM(@Condition))+'+'+'%'
		Begin
			Set @stkvcond = @stkvcond + ' Or '
		End	
		if replace(replace(@stkvcond,'[','+'),']','+') not like '%'+'+'+LTRIM(RTRIM(@Condition))+'+'+'%'
		Begin
			if @stkvcond <> ''
			Begin
				Set @stkvcond = @stkvcond + ' ) And '
			End	
			Set @stkvcond = @stkvcond + ' ( '
		End	
		Set @stkvcond = @stkvcond + '['+LTRIM(RTRIM(@Condition))+']' 
		Set @stkvcond = @stkvcond + ' = '''+@Descrip+''''
		
		FETCH NEXT FROM C01STKVAL INTO @Condition,@Descrip,@Tbl_Name
	END
	CLOSE C01STKVAL
	DEALLOCATE C01STKVAL

	if @stkvcond <> ''
	Begin
		Set @stkvcond = @stkvcond + ' )'
	End	
	Set @stkvcond = REPLACE(@stkvcond,'''','''''')
	SET @SQLCOMMAND=' '
	SET @SQLCOMMAND=' Update ##STKVALConfig Set VStkCond = '''+@stkvcond+''' Where RecId = '+cast(@RecId as varchar(5))
	print @SQLCOMMAND
	EXEC SP_EXECUTESQL  @SQLCOMMAND

	FETCH NEXT FROM C0STKVAL INTO @recid
END
CLOSE C0STKVAL
DEALLOCATE C0STKVAL

Drop Table #StkValConfig1


-- VNAME


SELECT PTMAIN.ENTRY_TY,PTMAIN.INV_NO,PTMAIN.DATE,PTMAIN.TRAN_CD,PTMAIN.U_PINVNO,PTMAIN.U_PINVDT,PTMAIN.PARTY_NM,PTITEM.ITEM,PTITEM.QTY,recqty=PTITEM.QTY,balqty=PTITEM.QTY,AMOUNT=PTMAIN.NET_AMT,PTITEM.WARE_NM,ltrim((str(ptitem.tran_cd)+rtrim(ptitem.itserial))) as pkey,VNAME=CAST('' AS VARCHAR(50)),PTMAIN.DEPT,PTMAIN.CATE,PTITEM.ITSERIAL,PTMAIN.INCEXCISE,TOTPMV=PTMAIN.NET_AMT,PMI=PTMAIN.NET_AMT,ASSEAMT=PTMAIN.NET_AMT,PTITEM.PMKEY,BHENT=CAST('' AS VARCHAR(2)),PMV=PTMAIN.NET_AMT
INTO #PTMAIN1
FROM PTMAIN
INNER JOIN PTITEM ON(PTMAIN.TRAN_CD=PTITEM.TRAN_CD)
INNER JOIN IT_MAST ON(IT_MAST.IT_CODE=PTITEM.IT_CODE)
INNER JOIN AC_MAST ON(PTMAIN.AC_ID=AC_MAST.AC_ID)
LEFT OUTER JOIN ARITREF ON (PTITEM.TRAN_CD=ARITREF.ITREF_TRAN AND PTITEM.ITSERIAL=ARITREF.RITSERIAL) WHERE 1=2

--Set @SQLCOMMAND	='INSERT INTO  #PTMAIN1 SELECT PTMAIN.ENTRY_TY,PTMAIN.INV_NO,PTMAIN.DATE,PTMAIN.TRAN_CD,PTMAIN.U_PINVNO,PTMAIN.U_PINVDT,PTMAIN.PARTY_NM,PTITEM.ITEM,PTITEM.QTY,recqty=ISNULL(ARITREF.RQTY,0),BALQTY=CAST((PTITEM.QTY-ISNULL(ARITREF.RQTY,0)) AS NUMERIC(12,2)),AMOUNT=CAST((PTITEM.QTY-ISNULL(ARITREF.RQTY,0)) AS NUMERIC(12,2))*PTITEM.RATE,PTITEM.WARE_NM,ltrim((str(ptitem.tran_cd)+rtrim(ptitem.itserial))) as pkey,VNAME=CAST('''' AS VARCHAR(50)),PTMAIN.DEPT,PTMAIN.CATE,PTITEM.ITSERIAL
--Set @SQLCOMMAND	='INSERT INTO  #PTMAIN1 SELECT PTMAIN.ENTRY_TY,PTMAIN.INV_NO,PTMAIN.DATE,PTMAIN.TRAN_CD,PTMAIN.U_PINVNO,PTMAIN.U_PINVDT,PTMAIN.PARTY_NM,PTITEM.ITEM,PTITEM.QTY,recqty=ISNULL(CASE WHEN ARITEM.DATE<'''+CONVERT(VARCHAR(50),@EDATE)+''' THEN ARITREF.RQTY ELSE 0 END,0),BALQTY=CAST((PTITEM.QTY-ISNULL(CASE WHEN ARITEM.DATE<'''+CONVERT(VARCHAR(50),@EDATE)+''' THEN CAST(ARITREF.RQTY AS NUMERIC(12,3))  ELSE 0 END,0)) AS NUMERIC(12,2)),AMOUNT=CAST(PTITEM.QTY AS NUMERIC(12,3))*PTITEM.RATE,PTITEM.WARE_NM,ltrim((str(ptitem.tran_cd)+rtrim(ptitem.itserial))) as pkey,VNAME=CAST('''' AS VARCHAR(50)),PTMAIN.DEPT,PTMAIN.CATE,PTITEM.ITSERIAL,PTMAIN.INCEXCISE,0,0,0,PTITEM.PMKEY,''PT'',0		----Commented by Shrikant S. on 18/07/2015 for Bug-26464		
Set @SQLCOMMAND	='INSERT INTO  #PTMAIN1 SELECT PTMAIN.ENTRY_TY,PTMAIN.INV_NO,PTMAIN.DATE,PTMAIN.TRAN_CD,PTMAIN.U_PINVNO,PTMAIN.U_PINVDT,PTMAIN.PARTY_NM,PTITEM.ITEM,PTITEM.QTY,recqty=ISNULL(CASE WHEN ARITEM.DATE<='''+CONVERT(VARCHAR(50),@EDATE)+''' THEN ARITREF.RQTY ELSE 0 END,0),BALQTY=CAST((PTITEM.QTY-ISNULL(CASE WHEN ARITEM.DATE<'''+CONVERT(VARCHAR(50),@EDATE)+''' THEN CAST(ARITREF.RQTY AS NUMERIC(12,3))  ELSE 0 END,0)) AS NUMERIC(12,2)),AMOUNT=CAST(PTITEM.QTY AS NUMERIC(12,3))*PTITEM.RATE,PTITEM.WARE_NM,ltrim((str(ptitem.tran_cd)+rtrim(ptitem.itserial))) as pkey,VNAME=CAST('''' AS VARCHAR(50)),PTMAIN.DEPT,PTMAIN.CATE,PTITEM.ITSERIAL,PTMAIN.INCEXCISE,0,0,0,PTITEM.PMKEY,''PT'',0			--Added by Shrikant S. on 18/07/2015 for Bug-26464
FROM PTMAIN
INNER JOIN PTITEM ON(PTMAIN.TRAN_CD=PTITEM.TRAN_CD)
INNER JOIN IT_MAST ON(IT_MAST.IT_CODE=PTITEM.IT_CODE)
INNER JOIN AC_MAST ON(PTMAIN.AC_ID=AC_MAST.AC_ID)
LEFT OUTER JOIN ARITREF ON (PTITEM.TRAN_CD=ARITREF.ITREF_TRAN AND PTITEM.ITSERIAL=ARITREF.RITSERIAL)
LEFT JOIN ARITEM ON (ARITREF.TRAN_CD=ARITEM.TRAN_CD AND ARITREF.ITSERIAL=ARITEM.ITSERIAL)'
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+RTRIM(@FCON)
--WHERE (PTMAIN.DATE BETWEEN @SDATE AND @EDATE) AND (PTMAIN.PARTY_NM BETWEEN @SAC AND @EAC) AND (PTITEM.ITEM BETWEEN @SIT AND @EIT) 
--AND (PTITEM.WARE_NM BETWEEN @SWARE AND @EWARE) AND PTMAIN.GOODSINTRN=1 
SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' AND PTMAIN.GOODSINTRN=1 ORDER BY PTMAIN.INV_NO'
	PRINT @SQLCOMMAND
	EXEC SP_EXECUTESQL  @SQLCOMMAND
UPDATE 	#PTMAIN1 SET BALQTY=QTY-RECQTY		--20/07/2015
--UPDATE A SET A.RECQTY=B.RQTY FROM #PTMAIN1 A INNER JOIN PTITREF B ON (A.TRAN_CD=B.TRAN_CD AND A.ITSERIAL=B.ITSERIAL) 
--Set @SQLCOMMAND	='UPDATE A SET A.RECQTY=(CASE WHEN ARITEM.DATE<'''+CONVERT(VARCHAR(50),@EDATE)+''' THEN B.RQTY ELSE 0 END) FROM #PTMAIN1 A INNER JOIN PTITREF B ON (A.TRAN_CD=B.TRAN_CD AND A.ITSERIAL=B.ITSERIAL)		--Commented by Shrikant S. on 18/07/2015 for Bug-26464
Set @SQLCOMMAND	='UPDATE A SET A.RECQTY=(CASE WHEN ARITEM.DATE<='''+CONVERT(VARCHAR(50),@EDATE)+''' THEN B.RQTY ELSE 0 END),A.DATE=CASE WHEN ARITEM.DATE<='''+CONVERT(VARCHAR(50),@EDATE)+''' THEN ARITEM.DATE ELSE A.DATE END  FROM #PTMAIN1 A INNER JOIN PTITREF B ON (A.TRAN_CD=B.TRAN_CD AND A.ITSERIAL=B.ITSERIAL)			--Added by Shrikant S. on 18/07/2015 for Bug-26464
INNER JOIN ARITEM ON (B.ITREF_TRAN=ARITEM.TRAN_CD AND B.RITSERIAL=ARITEM.ITSERIAL)'
EXEC SP_EXECUTESQL  @SQLCOMMAND

--UPDATE 	#PTMAIN1 SET BALQTY=QTY-RECQTY		--20/07/2015

Update #PTMAIN1 Set VName = ISNULL(VName,'')
Declare @VName Varchar(100),@VType Varchar(20),@VCond Varchar(4000)
DECLARE C4STKVAL CURSOR FOR 
SELECT  VName,VType,VStkCond FROM ##STKVALConfig
ORDER BY VName
OPEN C4STKVAL
FETCH NEXT FROM C4STKVAL INTO @VName,@VType,@VCond
WHILE @@FETCH_STATUS=0
BEGIN
	If @VCond = ''
	begin
		set @VCond = 'IsNull(VName,'' '') = '' '''
	end
	ELSE
	BEGIN 
		set @VCond = '(#PTMAIN1.'+RIGHT(@VCond,LEN(@VCond)-3)
	END
	SET @SQLCOMMAND=' '
	print 'vcond'
	SET @SQLCOMMAND=' Update #PTMAIN1 Set VName = '''+@VName+''' Where '+@VCond
	print @SQLCOMMAND
	EXEC SP_EXECUTESQL  @SQLCOMMAND
		
	FETCH NEXT FROM C4STKVAL INTO @VName,@VType,@VCond
END
CLOSE C4STKVAL
DEALLOCATE C4STKVAL
drop table ##STKVALConfig


-- uPDATE RATE
Declare @ExclDutyforDealer Bit,@ENTRY_TY VARCHAR(2),@BHENT VARCHAR(2)
set @ExclDutyforDealer = 0	
select top 1 @ExclDutyforDealer = ExclDutyforDealer from Manufact	

SELECT  ENTRY_TY,(CASE WHEN EXT_VOU=1 THEN BCODE_NM ELSE ENTRY_TY END) AS BHENT,PMKEY=INV_STK  INTO #L FROM LCODE WHERE (V_ITEM<>0 ) AND INV_STK<>' ' and entry_ty='pt'  ORDER BY BHENT
SELECT  DISTINCT A.ENTRY_TY,A.FLD_NM,A.ATT_FILE,A_S=(CASE WHEN (A.CODE='D' OR A.CODE='F') THEN '-' ELSE '+' END),A.STKVAL,A.WEFSTKFROM,A.WEFSTKTO,TAX_NAME=SPACE(20),L.BHENT
INTO #TAX
FROM DCMAST A INNER JOIN #L L ON (A.ENTRY_TY=L.ENTRY_TY) WHERE A.STKVAL<>0 and a.entry_ty='pt'
UNION
SELECT DISTINCT ENTRY_TY,FLD_NM='TAXAMT   ',ATT_FILE=1,A_S='+',STKVAL,WEFSTKFROM,WEFSTKTO,TAX_NAME,BHENT=ENTRY_TY  --&& Added by Shrikant S. on 03/04/2010 for TKT-863
FROM STAX_MAS  
WHERE STKVAL<>0 and entry_ty='pt'

SELECT  DISTINCT A.ENTRY_TY,A.FLD_NM,A.ATT_FILE,A_S='-',A.STKVAL,A.WEFSTKFROM,A.WEFSTKTO,TAX_NAME=SPACE(20),L.BHENT
INTO #TAXEXCL
FROM DCMAST A INNER JOIN #L L ON (A.ENTRY_TY=L.ENTRY_TY) WHERE A.STKVAL=0 And A.Code = 'E' And @ExclDutyforDealer = 1
SELECT * INTO #RECEIPT FROM #PTMAIN1--	Bug 3450A

---<--Tax/Discount & Charges for applied Date. 

SELECT ENTRY_TY,TRAN_CD=0,ITSERIAL,AMT=GRO_AMT INTO #ITEM1 FROM STITEM  WHERE 1=2

DECLARE @TENTRY_TY AS VARCHAR(2),@FLD_NM AS VARCHAR(20),@ATT_FILE AS INT,@A_S AS VARCHAR(1),@WEFSTKFROM AS SMALLDATETIME,@WEFSTKTO AS SMALLDATETIME,@TBHENT AS VARCHAR(2),@TAX_NAME AS VARCHAR(30)
DECLARE @PARMDEFINATION NVARCHAR(50),@AMT AS NUMERIC(12,2)
UPDATE #RECEIPT SET PMI=0

--SELECT ENTRY_TY,TRAN_CD=0,ITSERIAL,AMT=GRO_AMT INTO #ITEM1 FROM STITEM  WHERE 1=2

Declare @MainTable Varchar(50),@IncExciseCol Bit,@codeType Varchar(2)		--Added By Shrikant S. on 21/02/2013 for Bug-9009

set @MainTable=''									--Added By Shrikant S. on 21/02/2013 for Bug-9009
set @IncExciseCol=0									--Added By Shrikant S. on 21/02/2013 for Bug-9009

DECLARE  C2STKVAL CURSOR FOR 
SELECT  DISTINCT ENTRY_TY,BHENT FROM #PTMAIN1 --WHERE PMKEY='+'
OPEN C2STKVAL
FETCH NEXT FROM C2STKVAL INTO @ENTRY_TY,@BHENT
WHILE @@FETCH_STATUS=0
BEGIN
	--Added By Shrikant S. on 21/02/2013 for Bug-9009		--Start
	set @MainTable='PTMain'		
	if Exists(Select c.[Name] From Syscolumns c Inner Join Sysobjects b on (b.id=c.id) Where b.[Name]=@MainTable and c.[name]='IncExcise')
	Begin
		set @IncExciseCol=1
	end
	--Added By Shrikant S. on 21/02/2013 for Bug-9009		--End

	DECLARE  C3STKVAL CURSOR FOR 
	SELECT FLD_NM,ATT_FILE,A_S,WEFSTKFROM,WEFSTKTO,BHENT,TAX_NAME FROM #TAX WHERE (ENTRY_TY=@ENTRY_TY) OR (BHENT='~~')
	OPEN C3STKVAL
	FETCH NEXT FROM  C3STKVAL INTO @FLD_NM,@ATT_FILE,@A_S,@WEFSTKFROM,@WEFSTKTO,@TBHENT,@TAX_NAME
	WHILE @@FETCH_STATUS=0
	BEGIN
		set @codeType=''	--Added By Shrikant S. on 21/02/2013 for Bug-9009
		IF @ATT_FILE='0'
		BEGIN
		    DELETE FROM #ITEM1
		    Select Top 1 @codeType=Code From Dcmast Where Entry_ty='PT' and fld_nm=@FLD_NM		--Added By Shrikant S. on 21/02/2013 for Bug-9009
			SET @SQLCOMMAND='INSERT INTO #ITEM1  (ENTRY_TY,TRAN_CD,ITSERIAL,AMT)'
			--SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+'SELECT ENTRY_TY,TRAN_CD,ITSERIAL,(CASE WHEN '+RTRIM(@FLD_NM)+' IS NULL THEN 0 ELSE '+RTRIM(@FLD_NM)+' END)  FROM '+@BHENT+'ITEM WHERE DATE BETWEEN '+CHAR(39)+CAST(@WEFSTKFROM AS VARCHAR)+CHAR(39)+ ' AND '+CHAR(39)+CAST(@WEFSTKTO AS VARCHAR)+CHAR(39) +' AND ENTRY_TY='+CHAR(39)+@ENTRY_TY+CHAR(39)  --Commented by Shrikant S. on 03 Apr, 2010 For TKT-863
			--SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+'SELECT A.ENTRY_TY,A.TRAN_CD,A.ITSERIAL,(CASE WHEN '+RTRIM(@FLD_NM)+' IS NULL THEN 0 ELSE '+RTRIM(@FLD_NM)+' END)  FROM '+@BHENT+'ITEM A INNER JOIN DCMAST B ON (A.ENTRY_TY=B.ENTRY_TY ) WHERE A.DATE BETWEEN '+CHAR(39)+CAST(@WEFSTKFROM AS VARCHAR)+CHAR(39)+ ' AND '+CHAR(39)+CAST(@WEFSTKTO AS VARCHAR)+CHAR(39) +' AND A.ENTRY_TY='+CHAR(39)+@ENTRY_TY+CHAR(39)+' AND B.FLD_NM='''+RTRIM(@FLD_NM)+''' AND B.STKVAL=1' --Added by Shrikant S. on 03 Apr, 2010 For TKT-863		----Commented By Shrikant S. on 21/02/2013 for Bug-9009		
			----Added By Shrikant S. on 21/02/2013 for Bug-9009		--Start
			SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+'SELECT A.ENTRY_TY,A.TRAN_CD,A.ITSERIAL,(CASE WHEN A.'+RTRIM(@FLD_NM)+' IS NULL THEN 0 ELSE A.'+RTRIM(@FLD_NM)+' END)  
				FROM PTITEM A INNER JOIN DCMAST B ON (A.ENTRY_TY=B.ENTRY_TY ) 
				INNER JOIN #PTMAIN1 C ON (C.TRAN_CD=A.TRAN_CD)
				WHERE A.DATE BETWEEN '+CHAR(39)+CAST(@WEFSTKFROM AS VARCHAR)+CHAR(39)+ ' AND '+CHAR(39)+CAST(@WEFSTKTO AS VARCHAR)+CHAR(39) 
				+' AND A.ENTRY_TY=''PT'' AND B.FLD_NM='''
				+RTRIM(@FLD_NM)+''' AND B.STKVAL=1 '+CASE WHEN @IncExciseCol=1 and @codeType='E' THEN +' AND C.INCEXCISE=1 ' ELSE '' END
			----Added By Shrikant S. on 21/02/2013 for Bug-9009		--End
			EXECUTE SP_EXECUTESQL @SQLCOMMAND	
			SET @SQLCOMMAND='UPDATE  A SET A.PMI=A.PMI '+@A_S+' B.AMT FROM #ITEM1 B INNER JOIN #PTMAIN1 A ON (A.ENTRY_TY=B.ENTRY_TY AND A.TRAN_CD=B.TRAN_CD AND A.ITSERIAL=B.ITSERIAL)  WHERE  A.ENTRY_TY=''PT'''
			
			EXECUTE SP_EXECUTESQL @SQLCOMMAND
		END	
		ELSE
		BEGIN
			
			--IF @TBHENT='~~'  --SALES TAX --Commented by Shrikant S. on 03 Apr, 2010 For TKT-863
			IF @TAX_NAME<>''  --SALES TAX  --Added by Shrikant S. on 03 Apr, 2010 For TKT-863
			BEGIN
				DELETE FROM #ITEM1
				
				SET @SQLCOMMAND='INSERT INTO #ITEM1  (ENTRY_TY,TRAN_CD,ITSERIAL,AMT)'
				--SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+'SELECT ENTRY_TY,TRAN_CD,ITSERIAL=0,(CASE WHEN '+RTRIM(@FLD_NM)+' IS NULL THEN 0 ELSE '+RTRIM(@FLD_NM)+' END)  FROM '+@BHENT+'MAIN WHERE DATE BETWEEN '+CHAR(39)+CAST(@WEFSTKFROM AS VARCHAR)+CHAR(39)+ ' AND '+CHAR(39)+CAST(@WEFSTKTO AS VARCHAR)+CHAR(39)+' AND ENTRY_TY='+CHAR(39)+@ENTRY_TY+CHAR(39) +' AND TAX_NAME='+CHAR(39) +@TAX_NAME+CHAR(39) --rup
				--SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+'SELECT ENTRY_TY,TRAN_CD,ITSERIAL=0,(CASE WHEN '+RTRIM(@FLD_NM)+' IS NULL THEN 0 ELSE '+RTRIM(@FLD_NM)+' END)  FROM '+@BHENT+'MAIN WHERE DATE BETWEEN '+CHAR(39)+CAST(@WEFSTKFROM AS VARCHAR)+CHAR(39)+ ' AND '+CHAR(39)+CAST(@WEFSTKTO AS VARCHAR)+CHAR(39)+' AND ENTRY_TY='+CHAR(39)+@ENTRY_TY+CHAR(39) +' AND TAX_NAME='+CHAR(39) +@TAX_NAME+CHAR(39)+' and  taxamt<>0' --Commented by Shrikant S. on 03 Apr, 2010 for TKT-863
				--SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+'SELECT A.ENTRY_TY,A.TRAN_CD,ITSERIAL=0,(CASE WHEN '+RTRIM(@FLD_NM)+' IS NULL THEN 0 ELSE '+RTRIM(@FLD_NM)+' END)  FROM '+@BHENT+'MAIN A INNER JOIN STAX_MAS B ON (A.ENTRY_TY=B.ENTRY_TY AND RTRIM(A.TAX_NAME)=RTRIM(B.TAX_NAME)) WHERE A.DATE BETWEEN '+CHAR(39)+CAST(@WEFSTKFROM AS VARCHAR)+CHAR(39)+ ' AND '+CHAR(39)+CAST(@WEFSTKTO AS VARCHAR)+CHAR(39)+' AND A.ENTRY_TY='+CHAR(39)+@ENTRY_TY+CHAR(39) +' AND A.TAX_NAME='+CHAR(39) +@TAX_NAME+CHAR(39)+' and  A.taxamt<>0 AND B.STKVAL=1 ' --Added by Shrikant S. on 03 Apr, 2010 for TKT-863
				SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+'SELECT A.ENTRY_TY,A.TRAN_CD,A.ITSERIAL,(CASE WHEN '+RTRIM(@FLD_NM)+' IS NULL THEN 0 ELSE '+RTRIM(@FLD_NM)+' END)  FROM PTITEM A INNER JOIN STAX_MAS B ON (A.ENTRY_TY=B.ENTRY_TY AND RTRIM(A.TAX_NAME)=RTRIM(B.TAX_NAME)) WHERE A.DATE BETWEEN '+CHAR(39)+CAST(@WEFSTKFROM AS VARCHAR)+CHAR(39)+ ' AND '+CHAR(39)+CAST(@WEFSTKTO AS VARCHAR)+CHAR(39)+' AND A.ENTRY_TY=''PT'' AND A.TAX_NAME='+CHAR(39) +@TAX_NAME+CHAR(39)+' and  A.taxamt<>0 AND B.STKVAL=1 ' --Changed by Shrikant S. on 06 Apr, 2010 for TKT-863
				EXECUTE SP_EXECUTESQL @SQLCOMMAND
				SET @SQLCOMMAND='UPDATE A SET A.PMI=A.PMI '+@A_S+' B.AMT FROM #ITEM1 B INNER JOIN #PTMAIN1 A ON (A.ENTRY_TY=B.ENTRY_TY AND A.TRAN_CD=B.TRAN_CD AND A.ITSERIAL=B.ITSERIAL)  WHERE  A.ENTRY_TY=''PT'' ' --Added by Shrikant S. on 20/11/2012 For Bug-7312
				--SET @SQLCOMMAND='UPDATE A SET A.PMI= B.AMT FROM #ITEM1 B INNER JOIN #RECEIPT A ON (A.ENTRY_TY=B.ENTRY_TY AND A.TRAN_CD=B.TRAN_CD AND A.ITSERIAL=B.ITSERIAL)  WHERE  A.ENTRY_TY='+CHAR(39)+@ENTRY_TY+CHAR(39)+' ' --Added by Shrikant S. on 06 Apr, 2010 for TKT-863 --Commented by Shrikant S. on 20/11/2012 For Bug-7312		
				EXECUTE SP_EXECUTESQL @SQLCOMMAND --Added by Shrikant S. on 06 Apr, 2010 for TKT-863

				
			END
			ELSE
			BEGIN
				DELETE FROM #ITEM1 --Added by Shrikant S. on 06 Apr, 2010 For TKT-863
				SET @SQLCOMMAND='INSERT INTO #ITEM1  (ENTRY_TY,TRAN_CD,ITSERIAL,AMT)'
				--SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+'SELECT ENTRY_TY,TRAN_CD,ITSERIAL=0,(CASE WHEN '+RTRIM(@FLD_NM)+' IS NULL THEN 0 ELSE '+RTRIM(@FLD_NM)+' END)  FROM '+@BHENT+'MAIN WHERE DATE BETWEEN '+CHAR(39)+CAST(@WEFSTKFROM AS VARCHAR)+CHAR(39)+ ' AND '+CHAR(39)+CAST(@WEFSTKTO AS VARCHAR)+CHAR(39)+' AND ENTRY_TY='+CHAR(39)+@ENTRY_TY+CHAR(39) --Commented by Shrikant S. on 03 Apr, 2010 for TKT-863
				--SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+'SELECT A.ENTRY_TY,A.TRAN_CD,ITSERIAL=0,(CASE WHEN '+RTRIM(@FLD_NM)+' IS NULL THEN 0 ELSE '+RTRIM(@FLD_NM)+' END)  FROM '+@BHENT+'MAIN A INNER JOIN DCMAST B ON (A.ENTRY_TY=B.ENTRY_TY) WHERE A.DATE BETWEEN '+CHAR(39)+CAST(@WEFSTKFROM AS VARCHAR)+CHAR(39)+ ' AND '+CHAR(39)+CAST(@WEFSTKTO AS VARCHAR)+CHAR(39)+' AND A.ENTRY_TY='+CHAR(39)+@ENTRY_TY+CHAR(39)+' AND B.FLD_NM='''+RTRIM(@FLD_NM)+''' AND B.STKVAL=1' --Added by Shrikant S. on 03 Apr, 2010 for TKT-863		--Commented By Shrikant S. on 21/02/2013 for Bug-9009		
				----Added By Shrikant S. on 21/02/2013 for Bug-9009		--Start
				SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+'SELECT A.ENTRY_TY,A.TRAN_CD,ITSERIAL=0,(CASE WHEN '+RTRIM(@FLD_NM)+' IS NULL THEN 0 ELSE '
										+RTRIM(@FLD_NM)+' END)  FROM PTMAIN A INNER JOIN DCMAST B ON (A.ENTRY_TY=B.ENTRY_TY) WHERE A.DATE BETWEEN '
										+CHAR(39)+CAST(@WEFSTKFROM AS VARCHAR)+CHAR(39)+ ' AND '+CHAR(39)+CAST(@WEFSTKTO AS VARCHAR)+CHAR(39)
										+' AND A.ENTRY_TY=''PT'' AND B.FLD_NM='''+RTRIM(@FLD_NM)+''' AND B.STKVAL=1' 
										+CASE WHEN @IncExciseCol=1 and @codeType='E' THEN +' AND A.INCEXCISE=1 ' ELSE '' END
				----Added By Shrikant S. on 21/02/2013 for Bug-9009		--End
				EXECUTE SP_EXECUTESQL @SQLCOMMAND	
				/* Added by shrikant s. on 06 apr, 2010*/ 				
				SET @SQLCOMMAND='select  a=1,A.TOTPMV,A.TOTPMV, B.AMT FROM #ITEM1 B INNER JOIN #PTMAIN1 A ON (A.ENTRY_TY=B.ENTRY_TY AND A.TRAN_CD=B.TRAN_CD ) WHERE  A.ENTRY_TY=''PT'''
				--EXECUTE SP_EXECUTESQL @SQLCOMMAND
				SET @SQLCOMMAND='UPDATE  A SET A.TOTPMV=A.TOTPMV '+@A_S+' B.AMT FROM #ITEM1 B INNER JOIN #PTMAIN1 A ON (A.ENTRY_TY=B.ENTRY_TY AND A.TRAN_CD=B.TRAN_CD ) WHERE  A.ENTRY_TY=''PT'''
				EXECUTE SP_EXECUTESQL @SQLCOMMAND
				/* Added by shrikant s. on 06 apr, 2010*/ 				

			END	

/* Commented by Shrikant S. on 06 Apr, 2010 for TKT-863*/		
--			EXECUTE SP_EXECUTESQL @SQLCOMMAND	
--			SET @SQLCOMMAND='select  a=1,A.TOTPMV,A.TOTPMV, B.AMT FROM #ITEM1 B INNER JOIN #RECEIPT A ON (A.ENTRY_TY=B.ENTRY_TY AND A.TRAN_CD=B.TRAN_CD ) WHERE  A.ENTRY_TY='+CHAR(39)+@ENTRY_TY+CHAR(39)
--			--EXECUTE SP_EXECUTESQL @SQLCOMMAND
--			SET @SQLCOMMAND='UPDATE  A SET A.TOTPMV=A.TOTPMV '+@A_S+' B.AMT FROM #ITEM1 B INNER JOIN #RECEIPT A ON (A.ENTRY_TY=B.ENTRY_TY AND A.TRAN_CD=B.TRAN_CD ) WHERE  A.ENTRY_TY='+CHAR(39)+@ENTRY_TY+CHAR(39)
--			EXECUTE SP_EXECUTESQL @SQLCOMMAND
/* Commented by Shrikant S. on 06 Apr, 2010 for TKT-863*/					
			

		END
		FETCH NEXT FROM  C3STKVAL INTO @FLD_NM,@ATT_FILE,@A_S,@WEFSTKFROM,@WEFSTKTO,@TBHENT,@TAX_NAME
	END
	CLOSE C3STKVAL
	DEALLOCATE C3STKVAL
	--Bug5445
	DECLARE  C4STKVAL CURSOR FOR 
	SELECT FLD_NM,ATT_FILE,A_S,WEFSTKFROM,WEFSTKTO,BHENT,TAX_NAME FROM #TAXEXCL WHERE (ENTRY_TY='PT') OR (BHENT='~~')
	OPEN C4STKVAL
	FETCH NEXT FROM  C4STKVAL INTO @FLD_NM,@ATT_FILE,@A_S,@WEFSTKFROM,@WEFSTKTO,@TBHENT,@TAX_NAME
	WHILE @@FETCH_STATUS=0
	BEGIN
		set @codeType=''
		IF @ATT_FILE='0'
		BEGIN
		    DELETE FROM #ITEM1
		    Select Top 1 @codeType=Code From Dcmast Where Entry_ty='PT' and fld_nm=@FLD_NM		
			SET @SQLCOMMAND='INSERT INTO #ITEM1  (ENTRY_TY,TRAN_CD,ITSERIAL,AMT)'
			SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+'SELECT A.ENTRY_TY,A.TRAN_CD,A.ITSERIAL,(CASE WHEN A.'+RTRIM(@FLD_NM)+' IS NULL THEN 0 ELSE A.'+RTRIM(@FLD_NM)+' END)  
				FROM PTITEM A INNER JOIN DCMAST B ON (A.ENTRY_TY=B.ENTRY_TY ) 
				INNER JOIN #PTMAIN1 C ON (C.TRAN_CD=A.TRAN_CD)
				WHERE A.ENTRY_TY=''PT'' AND B.FLD_NM='''
				+RTRIM(@FLD_NM)+''' AND B.STKVAL=0 '+CASE WHEN @IncExciseCol=1 and @codeType='E' THEN +' AND C.INCEXCISE=0 ' ELSE '' END
			EXECUTE SP_EXECUTESQL @SQLCOMMAND	
			SET @SQLCOMMAND='UPDATE  A SET A.PMI=A.PMI '+@A_S+' B.AMT FROM #ITEM1 B INNER JOIN #PTMAIN1 A ON (A.ENTRY_TY=B.ENTRY_TY AND A.TRAN_CD=B.TRAN_CD AND A.ITSERIAL=B.ITSERIAL)  WHERE  A.ENTRY_TY=''PT'''
			
			EXECUTE SP_EXECUTESQL @SQLCOMMAND
		END	
		ELSE
		BEGIN
				DELETE FROM #ITEM1
				SET @SQLCOMMAND='INSERT INTO #ITEM1  (ENTRY_TY,TRAN_CD,ITSERIAL,AMT)'
				SET @SQLCOMMAND=RTRIM(@SQLCOMMAND)+' '+'SELECT A.ENTRY_TY,A.TRAN_CD,ITSERIAL=0,(CASE WHEN '+RTRIM(@FLD_NM)+' IS NULL THEN 0 ELSE '
					+RTRIM(@FLD_NM)+' END)  FROM PTMAIN A INNER JOIN DCMAST B ON (A.ENTRY_TY=B.ENTRY_TY) 
					WHERE A.ENTRY_TY=''PT'' AND B.FLD_NM='''+RTRIM(@FLD_NM)+''' AND B.STKVAL=0' 
					+CASE WHEN @IncExciseCol=1 and @codeType='E' THEN +' AND A.INCEXCISE=0 ' ELSE '' END
				EXECUTE SP_EXECUTESQL @SQLCOMMAND	
				SET @SQLCOMMAND='select  a=1,A.TOTPMV,A.TOTPMV, B.AMT FROM #ITEM1 B INNER JOIN #PTMAIN1 A ON (A.ENTRY_TY=B.ENTRY_TY AND A.TRAN_CD=B.TRAN_CD ) WHERE  A.ENTRY_TY=''PT'''
				SET @SQLCOMMAND='UPDATE  A SET A.TOTPMV=A.TOTPMV '+@A_S+' B.AMT FROM #ITEM1 B INNER JOIN #PTMAIN1 A ON (A.ENTRY_TY=B.ENTRY_TY AND A.TRAN_CD=B.TRAN_CD ) WHERE  A.ENTRY_TY=''PT'''
				EXECUTE SP_EXECUTESQL @SQLCOMMAND
		END
		FETCH NEXT FROM  C4STKVAL INTO @FLD_NM,@ATT_FILE,@A_S,@WEFSTKFROM,@WEFSTKTO,@TBHENT,@TAX_NAME
	END
	CLOSE C4STKVAL
	DEALLOCATE C4STKVAL
	--Bug5445
	
	FETCH NEXT FROM C2STKVAL INTO @ENTRY_TY,@BHENT
END
CLOSE C2STKVAL
DEALLOCATE C2STKVAL

UPDATE A SET ASSEAMT=(select SUM(b.QTY * b.RATE) from STKL_VW_ITEM B where A.TRAN_CD=B.TRAN_CD and A.ENTRY_TY=B.ENTRY_TY) FROM #PTMAIN1 A -- Added By Pankaj B. On 24-04-2014 for Bug-23326 
UPDATE  #PTMAIN1 SET PMV=(TOTPMV*AMOUNT)/(CASE WHEN ASSEAMT=0 THEN 1 ELSE ASSEAMT END) 


update #PTMAIN1 set amount=case when balqty > 0 then ((amount/qty)*balqty )+PMV+PMI else 0 end
--SELECT * FROM #PTMAIN1

SELECT ENTRY_TY,INV_NO,DATE,TRAN_CD,U_PINVNO,U_PINVDT,PARTY_NM,ITEM,QTY,recqty,BALQTY,AMOUNT,WARE_NM,pkey,VNAME,DEPT,CATE,ITSERIAL FROM #PTMAIN1
DROP TABLE #PTMAIN1
