if exists (select [name] from sysobjects where [name]='USP_REP_CHEQUE_PRINT_AUTO' AND XTYPE='P')
BEGIN 
	DROP PROCEDURE USP_REP_CHEQUE_PRINT_AUTO
END
GO
/****** Object:  StoredProcedure [dbo].[USP_REP_OUTSTANDINGCR_AGEING]    Script Date: 04/28/2016 10:16:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Modified By: Kishor Agarwal
-- Modify date: 28/04/2016
/*
EXECUTE USP_REP_CHEQUE_PRINT_AUTO "##AdminCHQSEL_4OK0Y1C81"
*/
-- =============================================

CREATE PROCEDURE [dbo].[USP_REP_CHEQUE_PRINT_AUTO]  
@ENTRYCOND NVARCHAR(4000)
AS
Declare @SQLCOMMAND as NVARCHAR(4000),@WhereCond Varchar(100),@TBLCON as NVARCHAR(4000)
SET @TBLCON=' INNER JOIN '+RTRIM(@ENTRYCOND)+' Tmp ON BPM.ENTRY_TY = Tmp.ENTRY_TY AND BPM.TRAN_CD = Tmp.TRAN_CD '

SET @SQLCOMMAND = 'SELECT BP.AUTOGENFLG,TRAN_NO=BP.INV_NO,BPM.[DATE],BILL_DATE=(Case When BPM.entry_all=''PT'' then PT.u_pinvdt else EP.u_pinvdt END),
					BILL_NO=(Case When BPM.entry_all=''PT'' then PT.U_PINVNO else EP.U_PINVNO END),BP.PARTY_NM,BILL_AMT=BPM.NET_AMT,CHEQUE_AMT=BPM.NEW_ALL,
					DNOTEAMT=ISNULL(CN.NEW_ALL,0)+ISNULL(BPM.disc,0),BALAMT=ISNULL(BPM.NET_AMT-ISNULL(BPM.NEW_ALL,0)-ISNULL(CN.NEW_ALL,0)-ISNULL(BPM.disc,0),0),
					BP.CHEQ_NO,BP.BANK_NM,BP.[USER_NAME],AC_MAST.C_Tax
					FROM BPMALL BPM 
					INNER JOIN BPMAIN BP ON BPM.TRAN_CD=BP.TRAN_CD 
					INNER JOIN AC_MAST ON BP.BANK_NM=AC_MAST.AC_NAME
					LEFT JOIN CNMALL CN ON CN.Main_tran = BPM.Main_tran
					LEFT JOIN PTMAIN PT ON BPM.Main_tran = PT.Tran_cd
					LEFT JOIN PTMAIN EP ON BPM.Main_tran = EP.Tran_cd  '
					+@TBLCON
print @SQLCOMMAND				
EXECUTE SP_EXECUTESQL @SQLCOMMAND
