execute add_columns 'SOITEM','u_cifamt NUMERIC(9,2)'
execute add_columns 'OPITEM','u_cifamt NUMERIC(9,2)'
execute add_columns 'PTITEM','u_cifamt NUMERIC(9,2)'
execute add_columns 'POITEM','u_cifamt NUMERIC(9,2)'
execute add_columns 'IPITEM','U_CIFAMT NUMERIC(9,2)'
execute add_columns 'BRITEM','u_cifamt NUMERIC(9,2)'
execute add_columns 'ARITEM','u_cifamt NUMERIC(9,2)'
execute add_columns 'JVITEM','u_cifamt NUMERIC(9,2)'
execute add_columns 'PCITEM','u_cifamt NUMERIC(9,2)'
execute add_columns 'SQITEM','u_cifamt NUMERIC(9,2)'
execute add_columns 'SSITEM','u_cifamt NUMERIC(9,2)'
execute add_columns 'GTITEM','u_cifamt NUMERIC(9,2)'
execute add_columns 'ITEM','u_cifamt NUMERIC(9,2)'
execute add_columns 'ARMAIN','u_expmark char(35)'
execute add_columns 'BPMAIN','u_expmark char(35)'
execute add_columns 'IIMAIN','u_expmark char(35)'
execute add_columns 'OPMAIN','u_expmark char(35)'
execute add_columns 'PTMAIN','u_expmark char(35)'
execute add_columns 'SRMAIN','u_expmark char(35)'
execute add_columns 'IPMAIN','u_expmark char(35)'
execute add_columns 'PRMAIN','u_expmark char(35)'
execute add_columns 'OSMAIN','u_expmark char(35)'
execute add_columns 'CNMAIN','u_expmark char(35)'
execute add_columns 'CPMAIN','u_expmark char(35)'
execute add_columns 'CRMAIN','u_expmark char(35)'
execute add_columns 'DCMAIN','u_expmark char(35)'
execute add_columns 'DNMAIN','u_expmark char(35)'
execute add_columns 'EPMAIN','u_expmark char(35)'
execute add_columns 'EQMAIN','u_expmark char(35)'
execute add_columns 'ESMAIN','u_expmark char(35)'
execute add_columns 'TRMAIN','u_expmark char(35)'
execute add_columns 'GTMAIN','u_expmark char(35)'
execute add_columns 'SOITEM','u_expmark char(35)'
execute add_columns 'STITEM','u_expmark char(35)'
execute add_columns 'OPITEM','u_expmark char(35)'
execute add_columns 'PTITEM','U_EXPMARK char(35)'
execute add_columns 'POITEM','u_expmark char(35)'
execute add_columns 'IPITEM','U_EXPMARK char(35)'
execute add_columns 'STMAIN','u_expmark char(35)'
execute add_columns 'BRITEM','u_expmark char(35)'
execute add_columns 'sbitem','u_expmark char(35)'
execute add_columns 'JVITEM','u_expmark char(35)'
execute add_columns 'PCITEM','u_expmark char(35)'
execute add_columns 'SQITEM','u_expmark char(35)'
execute add_columns 'EIMAIN','u_expmark char(35)'
execute add_columns 'SSITEM','u_expmark char(35)'
execute add_columns 'GTITEM','u_expmark char(35)'
execute add_columns 'EIITEM','u_expmark char(35)'
execute add_columns 'SOMAIN','u_expmark char(35)'
execute add_columns 'IRMAIN','u_expmark char(35)'
execute add_columns 'MAIN','u_expmark char(35)'
execute add_columns 'OBMAIN','u_expmark char(35)'
execute add_columns 'ITEM','u_expmark char(35)'
execute add_columns 'aritem','U_ACQTY   	Decimal (12,3)' 
execute add_columns 'aritem','U_ADDDUTY 	Decimal (12,2)'            
execute add_columns 'aritem','BATCHNO   	Varchar  (10) '          
execute add_columns 'aritem','U_CHALQTY 	Decimal (13,3)'
execute add_columns 'aritem','U_RQTY    	Decimal (12,3)'          
execute add_columns 'aritem','U_DUEON    	Decimal (12,3)'          
execute add_columns 'arMAIN','U_DUEON    	Decimal (12,3)'          
execute add_columns 'armain','U_AR3ADATE   Datetime'            
execute add_columns 'armain','U_AR3ANO  	varchar (10)         '   
execute add_columns 'armain','U_BEDATE  	Datetime            '
execute add_columns 'armain','U_BENO    	varchar (10)         '   
execute add_columns 'armain','U_CHALDT  	Datetime            '
execute add_columns 'armain','U_CHALNO  	varchar (15)           ' 
execute add_columns 'armain','U_INWARD  	Varchar (20)          '  
execute add_columns 'armain','U_LRNO    	Varchar (20)         '   
execute add_columns 'armain','U_PODT    	Datetime            '
execute add_columns 'armain','U_PONO    	Varchar (20)         '   
execute add_columns 'armain','U_PINVDT  	Datetime            '
execute add_columns 'armain','U_PINVNO  	Varchar (20)            '
execute add_columns 'armain','U_TANO    	Varchar (50)            '
execute add_columns 'armain','U_DELIVER 	Varchar (20)            '
execute add_columns 'armain','U_DELI    	Varchar (50)            '
execute add_columns 'armain','U_VEHNO   	Varchar (15)            '
execute add_columns 'BPMAIN','U_B1NO Decimal (10,0)            '
execute add_columns 'BPMAIN','U_EXAREDT 	datetime'
execute add_columns 'BPMAIN','U_EXARE1  	varchar (10)'
execute add_columns 'BPMAIN','U_BANK    	varchar (30)'
execute add_columns 'BPMAIN','U_EXPBNO  	varchar (20)'
execute add_columns 'BPMAIN','U_CHQDT   	datetime'
execute add_columns 'BPMAIN','U_DOS     	datetime'
execute add_columns 'BPMAIN','U_CLDT    	datetime'
execute add_columns 'BPMAIN','U_POED    	datetime'
execute add_columns 'CTITEM','U_SRNO    	varchar (10)'            
execute add_columns 'CTITEM','U_LOP     	varchar (10)'            
execute add_columns 'CTMAIN','U_PARTYADD	Varchar (100)'            
execute add_columns 'CTMAIN','U_PINVNO  	Varchar (20)'             
execute add_columns 'CTMAIN','U_PARTY   	Varchar (100)'            
execute add_columns 'CTMAIN','U_PODT    	Datetime  '          
execute add_columns 'CTMAIN','U_PONO    	Varchar (25)'            
execute add_columns 'CTMAIN','U_LOAREF  	Varchar (40)'            
execute add_columns 'ITEM','U_BOXWT   	Decimal (12,2)'            
execute add_columns 'ITEM','U_FROM    	Decimal (12,2)'            
execute add_columns 'ITEM','U_GWT     	Decimal (12,2)'            
execute add_columns 'ITEM','U_ITEMNO  	varchar'
execute add_columns 'ITEM','U_BUNDLE  	Decimal (12,2)'            
execute add_columns 'ITEM','U_APPACK  	Decimal (12,2)'  
alter table item alter column u_appack 	Decimal (12,2)          
execute add_columns 'ITEM','U_PIECES  	Decimal (12,2)'            
execute add_columns 'ITEM','U_REMARK  	varchar (15)'
execute add_columns 'ITEM','U_SWT     	Decimal (12,3)'            
execute add_columns 'ITEM','U_TO      	Decimal (12,2)'            
execute add_columns 'ITEM','U_GROSSWT 	Decimal (12,3)'            
execute add_columns 'ITEM','U_TQTY    	Decimal (14,2)'            
execute add_columns 'ITEM','U_EXPDESC 	Decimal (12,3)'            
execute add_columns 'ITEM','U_WT      	Decimal (12,3)'            
execute add_columns 'ITEM','u_SAAMT      	Decimal (12,3)'            
execute add_columns 'MAIN','U_BOLT    	Bit'                 
execute add_columns 'MAIN','U_BUN1    	Varchar (45)'            
execute add_columns 'MAIN','U_BUN10   	Varchar (45)'            
execute add_columns 'MAIN','U_BUN11   	Varchar (45)'            
execute add_columns 'MAIN','U_BUN12   	Varchar (45)'            
execute add_columns 'MAIN','U_BUN13   	Varchar (45)'            
execute add_columns 'MAIN','U_BUN14   	Varchar (45)'            
execute add_columns 'MAIN','U_BUN15   	Varchar (45)'            
execute add_columns 'MAIN','U_BUN2    	Varchar (45)'            
execute add_columns 'MAIN','U_BUN3    	Varchar (45)'            
execute add_columns 'MAIN','U_BUN4    	Varchar (45)'            
execute add_columns 'MAIN','U_BUN5    	Varchar (45)'            
execute add_columns 'MAIN','U_BUN6    	Varchar (45)'            
execute add_columns 'MAIN','U_BUN7    	Varchar (45)'            
execute add_columns 'MAIN','U_BUN8    	Varchar (45)'            
execute add_columns 'MAIN','U_BUN9    	Varchar (45)'            
execute add_columns 'MAIN','U_EXPMARK 	varchar (30)'
execute add_columns 'MAIN','U_CONSIGNE  Varchar (100)'            
execute add_columns 'MAIN','U_COUNTAIN  varchar (30)' 
execute add_columns 'MAIN','U_CONTRACT  Varchar (100) '           
execute add_columns 'MAIN','U_GPER    	Decimal (5,2) '           
execute add_columns 'MAIN','U_GROSSWT 	Decimal (12,3)'            
execute add_columns 'MAIN','U_NOBUN1  	Decimal (10,0)'            
execute add_columns 'MAIN','U_NOBUN10 	Decimal (10,0)'            
execute add_columns 'MAIN','U_NOBUN11 	Decimal (10,0)'            
execute add_columns 'MAIN','U_NOBUN12 	Decimal (10,0)'            
execute add_columns 'MAIN','U_NOBUN13 	Decimal (10,0)'            
execute add_columns 'MAIN','U_NOBUN14 	Decimal (10,0)'            
execute add_columns 'MAIN','U_NOBUN15 	Decimal (10,0)'            
execute add_columns 'MAIN','U_NOBUN2  	Decimal (10,0)'            
execute add_columns 'MAIN','U_NOBUN3  	Decimal (10,0)'            
execute add_columns 'MAIN','U_NOBUN4  	Decimal (10,0)'            
execute add_columns 'MAIN','U_NOBUN5  	Decimal (10,0)'            
execute add_columns 'MAIN','U_NOBUN6  	Decimal (10,0)'            
execute add_columns 'MAIN','U_NOBUN7  	Decimal (10,0)'            
execute add_columns 'MAIN','U_NOBUN8  	Decimal (10,0)'            
execute add_columns 'MAIN','U_NOBUN9  	Decimal (10,0)'            
execute add_columns 'MAIN','U_CHALNO  	varchar (20)'
execute add_columns 'MAIN','U_PTRANS  	Bit          '       
execute add_columns 'MAIN','U_EXPDESC 	varchar (30)'
execute add_columns 'MAIN','U_NETWT   	Decimal (12,3)'            
execute add_columns 'MAIN','U_BLNO    	varchar (20)'
execute add_columns 'MAIN','U_HCESSAMT  Decimal (12,3)'            
execute add_columns 'BPMAIN','U_PLASR   	varchar (10)'
execute add_columns 'BPMAIN','U_TR6     	varchar (3)'
execute add_columns 'BRMAIN','U_CHALDT  	datetime'
execute add_columns 'BRMAIN','U_CHALNO  	varchar (10)'
execute add_columns 'BRMAIN','U_CHQDT   	datetime'
execute add_columns 'BRMAIN','U_CLDT    	datetime'
execute add_columns 'BRMAIN','U_ARREARS 	varchar (20)'
execute add_columns 'BRMAIN','U_PLASR   	varchar (20)'
execute add_columns 'STITEM','U_FOB     	Decimal (12,2)'            
execute add_columns 'STMAIN','U_EXARE1  	varchar (10)'
execute add_columns 'STMAIN','U_B1NO    	Decimal (10,0)'             
execute add_columns 'STMAIN','U_EXPMARK 	varchar (30)'
execute add_columns 'STMAIN','U_EXPDESC 	varchar (30)'
execute add_columns 'STMAIN','U_NOTIFY1 	varchar (30)'
execute add_columns 'STMAIN','U_NOTIFY2 	varchar (30)'
execute add_columns 'STMAIN','U_MTRATE  	Decimal (12,2)'            
execute add_columns 'STMAIN','U_PACKAGES varchar (20)'
execute add_columns 'IIITEM','BATCHNO   	Varchar  (10)'     
execute add_columns 'IIITEM','U_ASSEAMT 	Decimal  (11,2)'           
execute add_columns 'IIITEM','U_FORPICK 	varchar (20)'
execute add_columns 'IIMAIN','U_B1NO Decimal (10)'            
execute add_columns 'IIMAIN','U_B1NO Decimal (10)'            
execute add_columns 'IIMAIN','U_B1NO Decimal (10,0)'            
execute add_columns 'IIMAIN','U_CATE    	varchar (20)'
execute add_columns 'IIMAIN','U_IRNO    	varchar (20)'
execute add_columns 'IIMAIN','ARENO Varchar	(50)'
execute add_columns 'IIMAIN','AREDATE Datetime	'
execute add_columns 'IIMAIN','U_POED Datetime	'
execute add_columns 'IIMAIN','BOND_NO Varchar	(60)'
execute add_columns 'IIMAIN','U_B1NO Decimal	(10)'
execute add_columns 'IIMAIN','U_B1NO Decimal	(10)'
execute add_columns 'IIMAIN','BOND_NO Varchar	(60)'
execute add_columns 'IIITEM','U_WTJOB   	Bit'                 
execute add_columns 'IPITEM','U_ASSEAMT 	Decimal (11,2)'            
execute add_columns 'IPITEM','U_FORPICK 	varchar (20)'
execute add_columns 'IPMAIN','U_PINVNO  	Varchar (20)'
execute add_columns 'IRITEM','U_FORPICK 	varchar (20)'
execute add_columns 'IRMAIN','U_B1NO    	Decimal (10,0)'
execute add_columns 'JVMAIN','U_NATURE Varchar (20)'
execute add_columns 'OBITEM','U_JBPARTY 	varchar (35)'
execute add_columns 'OBITEM','U_GINVDT  	Datetime    '        
execute add_columns 'OBITEM','U_GINVNO  	varchar (15)'
execute add_columns 'OBMAIN','U_ARREARS 	varchar (20)'
execute add_columns 'OBMAIN','U_B1NO    	Decimal (10,0)'            
execute add_columns 'OBMAIN','U_EXPBNO  	varchar (20)'
execute add_columns 'OBMAIN','U_EXBVLDT 	Datetime'            
execute add_columns 'OBMAIN','U_IMPORM  	Bit     '            
execute add_columns 'OBMAIN','U_EXBAMT  	Decimal (13,2)'
execute add_columns 'OBMAIN','U_PLASR   	varchar (10)'
execute add_columns 'OBMAIN','U_RG23NO  	varchar (10)'
execute add_columns 'OBMAIN','U_RG23CNO 	varchar (10)'
execute add_columns 'OBMAIN','U_GCSSR   	Bit'                 
execute add_columns 'OPITEM','U_ASSEAMT NUMERIC(12,2)'            
execute add_columns 'OPITEM','U_BOMNO   	Varchar (10)'            
execute add_columns 'OSMAIN','U_PINVNO  	Varchar (20)'             
execute add_columns 'ITEM','U_IMPAMT  	Decimal (12,2)'            
execute add_columns 'ITEM','U_IMPPER  	Decimal (5,2) '           
execute add_columns 'ITEM','U_INRVAL  	Decimal (13,4)'            
execute add_columns 'ITEM','U_BASDUTY1 Decimal (5,2) '           
execute add_columns 'ITEM','U_EXAMT   	Decimal (12,2)'            
execute add_columns 'ITEM','U_CIFAMT  	Decimal (12,2)'            
execute add_columns 'ITEM','U_ACDUTY  	Decimal (5,2) '           
execute add_columns 'ITEM','U_ACDUTY1 	Decimal (5,2) '           
execute add_columns 'ITEM','U_ACAMT1  	Decimal (12,2)'            
execute add_columns 'ITEM','U_ACAMT   	Decimal (12,2)'            
execute add_columns 'ITEM','U_CESSPER 	Decimal (5,2) '           
execute add_columns 'ITEM','U_CESSAMT 	Decimal (12,2)'            
execute add_columns 'ITEM','U_FREIGHT 	Decimal (12,2)'            
execute add_columns 'ITEM','U_FRPER   	Decimal (5,2) '           
execute add_columns 'ITEM','U_INSURA  	Decimal (12,2)'            
execute add_columns 'ITEM','U_INSPER  	Decimal (6,3) '           
execute add_columns 'ITEM','U_LANDPER 	Decimal (5,2) '           
execute add_columns 'ITEM','U_LANDCH  	Decimal (12,2)'            
execute add_columns 'ITEM','U_PACKCHG 	Decimal (13,4)'            
execute add_columns 'ITEM','U_HACAMT1 	Decimal (12,2)'            
execute add_columns 'ITEM','U_HCESSAMT Decimal (12,2)'            
execute add_columns 'ITEM','U_SRNO    	varchar (10)  '          
execute add_columns 'ITEM','U_USDAMT  	Decimal (12,3)'
execute add_columns 'MAIN','U_BOLDT   	Datetime    '        
execute add_columns 'MAIN','U_BOL     	varchar (20)'
execute add_columns 'MAIN','U_DELIVER 	varchar  (35)'           
execute add_columns 'MAIN','U_COUORG  	Varchar (50) '           
execute add_columns 'MAIN','U_CORREN  	varchar (25) '           
execute add_columns 'MAIN','U_EXCHANGE Decimal(12,2)'
execute add_columns 'MAIN','U_PINVNO  	varchar (50)'            
execute add_columns 'MAIN','U_PINVDT  	Datetime    '        
execute add_columns 'MAIN','U_PODT    	Datetime    '        
execute add_columns 'MAIN','U_PONO    	varchar (25)'
execute add_columns 'MAIN','U_PORT1   	Varchar (50)'            
execute add_columns 'MAIN','U_PORT2   	Varchar (50)'            
execute add_columns 'MAIN','U_PORT3   	Varchar (50)'            
execute add_columns 'MAIN','U_PORT4   	Varchar (50)'            
execute add_columns 'MAIN','U_LOAREF  	Varchar (40)' 
execute add_columns 'item','U_EXCHANGE Decimal(12,2)'   
execute add_columns 'POITEM','U_DUEON   	Datetime '           
execute add_columns 'POMAIN','U_BANK1   	Varchar (100)'            
execute add_columns 'POMAIN','U_BANK2   	Varchar (100)'            
execute add_columns 'POMAIN','CATE VARCHAR(50)'
execute add_columns 'POMAIN','U_CORREN  	Varchar (25)'             
execute add_columns 'POMAIN','DEPT VARCHAR(50)'
execute add_columns 'POMAIN','U_DEST    	VARCHAR(50)'
execute add_columns 'POMAIN','U_COMMENT 	Varchar (100)'            
execute add_columns 'POMAIN','U_INDENTER Varchar (100)'            
execute add_columns 'POMAIN','U_DISP    	Varchar (100)'           
execute add_columns 'POMAIN','U_NOTE    	Varchar (250)'            
execute add_columns 'POMAIN','U_OTHREF  	VARCHAR(50)'
execute add_columns 'POMAIN','U_PON     	Varchar (100)'            
execute add_columns 'POMAIN','U_PARTYADD Varchar (100)'            
execute add_columns 'POMAIN','U_PARTY   	Varchar (100)'            
execute add_columns 'POMAIN','U_REF     	VARCHAR(50)'
execute add_columns 'POMAIN','INV_SR VARCHAR(50)'
execute add_columns 'POMAIN','U_SUPPREF 	Varchar (50) '           
execute add_columns 'POMAIN','U_DELIVERY Varchar (100)'            
execute add_columns 'POMAIN','U_TERMS   	Varchar (100)'            
execute add_columns 'POMAIN','U_WARR    	Varchar (100)'            
execute add_columns 'PRMAIN','U_CLDT    	datetime'
execute add_columns 'ptmain','U_EXARE3DT datetime'       
execute add_columns 'ptitem','U_VEHNO   	Varchar (15)            '
execute add_columns 'PTitem','U_RQTY    	Decimal (12,3)'          
execute add_columns 'PTitem','U_CHALQTY 	Decimal (13,3)'
execute add_columns 'PTitem','U_ACQTY   	Decimal (12,3)' 
execute add_columns 'PTITEM','U_ADDDUTY 	Decimal (12,2)'
execute add_columns 'PTITEM','U_CIFAMT  	Decimal (12,2)'            
execute add_columns 'PTITEM','U_PKG1    	Decimal (12,2)'
execute add_columns 'PTmain','U_DELI    	Varchar (50)            '
execute add_columns 'PTMAIN','U_RQTY    	Decimal (12,3)'          
execute add_columns 'PTMAIN','U_CHALQTY 	Decimal (13,3)'
execute add_columns 'PTMAIN','U_ACQTY   	Decimal (12,3)' 
execute add_columns 'PTMAIN','U_AR3ADATE Datetime'            
execute add_columns 'PTMAIN','U_AR3ANO  	varchar (10)'
execute add_columns 'PTMAIN','U_B1NO    	Decimal (10,0)'            
execute add_columns 'PTMAIN','U_BEDATE  	Datetime    '        
execute add_columns 'PTMAIN','U_BENO    	varchar (10)'
execute add_columns 'PTMAIN','U_TYPE    	Bit         '        
execute add_columns 'PTMAIN','U_CHALDT  	Datetime    '        
execute add_columns 'PTMAIN','U_CHALNO  	varchar (15)'
execute add_columns 'PTMAIN','U_DATEVF  	Datetime    '        
execute add_columns 'PTMAIN','U_PINVNO  	varchar (20)'
execute add_columns 'PTMAIN','U_PINVDT  	Datetime    '        
execute add_columns 'PTMAIN','U_PODT    	Datetime    '        
execute add_columns 'PTMAIN','U_PONO    	varchar (25)'
execute add_columns 'PTMAIN','U_INSP    	Datetime    '        
execute add_columns 'PTMAIN','U_INST    	Datetime    '        
execute add_columns 'PTMAIN','U_WNO     	varchar (15)'
execute add_columns 'PTMAIN','U_DELIVER 	varchar  (35)'           
execute add_columns 'ptmain','U_VEHNO   	Varchar (15)            '
execute add_columns 'ptmain','U_LRNO    	Varchar (20)         '   
execute add_columns 'SOMAIN','U_DELIVER 	Varchar  (35)'           
execute add_columns 'SOMAIN','U_DELI    	Varchar  (35)'           
execute add_columns 'SSITEM','BATCHNO   	Varchar  (10)'           
execute add_columns 'STITEM','U_FREIGHT 	Decimal (12,4)'
execute add_columns 'STITEM','U_INSURA  	Decimal (12,4)'
execute add_columns 'STITEM','U_BOMNO VARCHAR(10)'
execute add_columns 'STMAIN','U_EXARE1  	varchar (10) '           
execute add_columns 'STMAIN','U_AR3ADT  	Datetime     '       
execute add_columns 'STMAIN','U_AR3ANO  	varchar (10)  '          
execute add_columns 'STMAIN','U_ARE1DT  	Datetime      '      
execute add_columns 'STMAIN','U_BUNFRM  	Decimal (12,0)'
execute add_columns 'STMAIN','U_BUNTO   	Decimal (12,0)'
execute add_columns 'STMAIN','U_BUNNO   	Varchar (45) '           
execute add_columns 'STMAIN','U_COUNTAIN varchar (30)'
execute add_columns 'STMAIN','U_CT3DATE 	Datetime    '        
execute add_columns 'STMAIN','U_CT3NO   	varchar (10)'
execute add_columns 'STMAIN','U_CORREN  	varchar (25)'
execute add_columns 'STMAIN','U_EXCHANGE Decimal(12,2)'
execute add_columns 'STMAIN','U_CSEAL   	varchar(20)'
execute add_columns 'STMAIN','U_EXPMARK 	varchar (30)'
execute add_columns 'STMAIN','U_MODE    	Varchar (100)'            
execute add_columns 'STMAIN','U_PACKAGES varchar (20)'
execute add_columns 'STMAIN','U_MTRATE  	Decimal (12,0)'
execute add_columns 'STMAIN','U_GROSSWT 	Decimal (12,0)'
execute add_columns 'STMAIN','U_NETWT   	Decimal (12,0)'
execute add_columns 'IIMAIN','u_choice Bit'
execute add_columns 'IIMAIN','U_CLDT    	Datetime'
execute add_columns 'ARMAIN','u_notify1 char(35)'
execute add_columns 'BPMAIN','u_notify1 char(35)'
execute add_columns 'IIMAIN','u_notify1 char(35)'
execute add_columns 'OPMAIN','u_notify1 char(35)'
execute add_columns 'PTMAIN','u_notify1 char(35)'
execute add_columns 'SRMAIN','u_notify1 char(35)'
execute add_columns 'IPMAIN','u_notify1 char(35)'
execute add_columns 'PRMAIN','u_notify1 char(35)'
execute add_columns 'OSMAIN','u_notify1 char(35)'
execute add_columns 'CNMAIN','u_notify1 char(35)'
execute add_columns 'CPMAIN','u_notify1 char(35)'
execute add_columns 'CRMAIN','u_notify1 char(35)'
execute add_columns 'DCMAIN','u_notify1 char(35)'
execute add_columns 'DNMAIN','u_notify1 char(35)'
execute add_columns 'EPMAIN','u_notify1 char(35)'
execute add_columns 'EQMAIN','u_notify1 char(35)'
execute add_columns 'ESMAIN','u_notify1 char(35)'
execute add_columns 'TRMAIN','u_notify1 char(35)'
execute add_columns 'GTMAIN','u_notify1 char(35)'
execute add_columns 'STMAIN','u_notify1 char(35)'
execute add_columns 'EIMAIN','u_notify1 char(35)'
execute add_columns 'SOMAIN','u_notify1 char(35)'
execute add_columns 'IRMAIN','u_notify1 char(35)'
execute add_columns 'tmpso','u_notify1 char(35)'
execute add_columns 'MAIN','u_notify1 char(35)'
execute add_columns 'OBMAIN','u_notify1 char(35)'
execute add_columns 'IRMAIN','U_BENO    	varchar (10)'

EXECUTE Update_table_column_default_value 'lother',1



