IF NOT EXISTS(SELECT [RULE] FROM RULES WHERE [RULE] = 'IMPORTED' )BEGIN INSERT INTO RULES([RULE],[REMARKS],[VALIDITY],[APGEN],[APGENBY],[COMPID]) VALUES ('IMPORTED','IMPORTED','PT OS II IR','','',0) END 
IF NOT EXISTS(SELECT [RULE] FROM RULES WHERE [RULE] = 'INDIGENIOUS' )BEGIN INSERT INTO RULES([RULE],[REMARKS],[VALIDITY],[APGEN],[APGENBY],[COMPID]) VALUES ('INDIGENIOUS','INDIGENIOUS','PT OS ST II IR','','',0) END 

EXECUTE Update_table_column_default_value 'rules',1
