
execute add_columns 'stmain','U_173H    	numeric (14,3)' 
execute add_columns 'stmain','U_EXB1    	Decimal (14,3)' 
execute add_columns 'stmain','U_EXSPEC    	Decimal (14,3)' 
execute add_columns 'stmain','U_DISAMT1    	numeric (10,2)' 
execute add_columns 'stmain','U_DISAMT2    	numeric (10,2)' 
execute add_columns 'stmain','U_add5    	numeric (11,2)'
execute add_columns 'stmain','U_ACAMT1      numeric (5,2)' 
execute add_columns 'stmain','U_ACDUTY1     NUMERIC (12,2)'
execute add_columns 'stmain','U_ACAMT    NUMERIC (12,2)'
execute add_columns 'stmain','U_ACDUTY    NUMERIC (5,2)'
execute add_columns 'stmain','U_IMPAMT   NUMERIC (12,2)'
execute add_columns 'stmain','U_IMPPER   NUMERIC (5,2)'
execute add_columns 'stmain','u_hacamt1  NUMERIC (12,2)'
execute add_columns 'stmain','U_HACPER    NUMERIC (5,2)'
execute add_columns 'stmain','u_hcessamt NUMERIC (12,2)'
execute add_columns 'stmain','U_HCESSPER   NUMERIC (5,2)'
execute add_columns 'stmain','U_ADDVAT    NUMERIC (10,2)'
execute add_columns 'stmain','U_OCT       NUMERIC (14,2)'
execute add_columns 'stmain','U_SURCH     NUMERIC (9,2)'
execute add_columns 'stmain','U_TOT        NUMERIC (9,2)' 
execute add_columns 'stmain','U_FREI      	numeric (14,2)' 
execute add_columns 'stmain','U_EXAMT      	numeric (11,2)' 
execute add_columns 'stitem','U_OTHCHRG    	numeric (10,2)' 
execute add_columns 'stitem','U_OTHCHRG    	numeric (10,2)' 
execute add_columns 'stitem','u_cessamt    	numeric (11,2)' 
execute add_columns 'stitem','u_cessamt    	numeric (11,2)'
execute add_columns 'stitem','U_EXAMT   	numeric (18,2)'
execute add_columns 'stitem','U_BASDUTY1    numeric (5,2)'
execute add_columns 'stitem','U_FREIGH numeric (5,2)'
execute add_columns 'Eimain','U_ACAMT1      numeric (5,2)' 
execute add_columns 'Eimain','U_ACDUTY1     NUMERIC (12,2)'
execute add_columns 'Eimain','U_ACAMT    NUMERIC (12,2)'
execute add_columns 'Eimain','U_ACDUTY    NUMERIC (5,2)'
execute add_columns 'Eimain','U_IMPAMT   NUMERIC (12,2)'
execute add_columns 'Eimain','U_IMPPER   NUMERIC (5,2)'
execute add_columns 'Eimain','u_hacamt1  NUMERIC (12,2)'
execute add_columns 'Eimain','U_HACPER    NUMERIC (5,2)'
execute add_columns 'Eimain','u_hcessamt NUMERIC (12,2)'
execute add_columns 'Eimain','U_HCESSPER   NUMERIC (5,2)'
execute add_columns 'Eimain','U_HCESAMTA  NUMERIC(12,2)'
execute add_columns 'Eimain','U_HCESAMTC  NUMERIC(12,2)'
execute add_columns 'Eimain','U_HCESAMTP  NUMERIC(12,2)'
execute add_columns 'Eimain','BCDAMTC    NUMERIC(12,2)'
execute add_columns 'Eimain','U_CVDAMTA   NUMERIC(12,2)'
execute add_columns 'Eimain','U_CVDAMTC  NUMERIC(12,2)'
execute add_columns 'Eimain','BCDAMTA    NUMERIC(12,2)'
execute add_columns 'EiITEM','U_CVDAMT  NUMERIC(12,2)'
execute add_columns 'EiITEM','U_CVDPER  NUMERIC(5,2)'
execute add_columns 'Eimain','U_ADDVAT    NUMERIC (10,2)'
execute add_columns 'ptitem','U_HCESAMT    	numeric (11,2)' 
execute add_columns 'ptitem','U_ROUND     	numeric (11,2)' 
execute add_columns 'PTMAIN','U_FRIGHT    numeric (11,2)' 
execute add_columns 'PTMAIN','U_FRPER     numeric (5,2)'
execute add_columns 'ptmain','u_addvat      numeric (10,2)' 
execute add_columns 'ptmain','U_FREI        numeric (10,2)' 
execute add_columns 'ptmain','U_ROUND       numeric (9,2)' 
execute add_columns 'ptmain','U_ROUND1      numeric (9,2)' 
execute add_columns 'ptmain','U_SURCH       numeric (12,2)' 
execute add_columns 'ptmain','u_TOT       numeric (12,2)' 
execute add_columns 'ptmain','u_TOT       numeric (12,2)' 
execute add_columns 'ptmain','U_ADD5      numeric (10,2)' 
execute add_columns 'ptmain','U_ROUND1    numeric (9,2)' 
execute add_columns 'ptmain','U_ADDVAT    numeric (10,2)' 
execute add_columns 'ptmain','U_FREI      numeric (10,2)' 
execute add_columns 'ptmain','U_OCT        numeric (10,2)' 
execute add_columns 'ptmain','U_SURCH    numeric (10,2)'
execute add_columns 'ptmain','U_TOT      numeric (10,2)'
execute add_columns 'ptmain','U_HACAMT1      numeric (10,2)'  
execute add_columns 'ptmain','U_ACAMT      numeric (10,2)'  
execute add_columns 'ptMAIN','u_acamt1  numeric (11,2)'  
execute add_columns 'ptmain','U_EXAMT      numeric (11,2)'  
execute add_columns 'ptmain','U_HCESSAMT    numeric (11,2)'  
execute add_columns 'ptmain','U_IMPDUTY    numeric (9,2)'  
execute add_columns 'ptitem','U_FREIG       numeric (10,2)' 
execute add_columns 'ptitem','u_hacamt1     numeric (10,2)' 
execute add_columns 'ptitem','u_impduty     numeric (9,2)' 
execute add_columns 'ptitem','U_OCT         numeric (9,2)' 
execute add_columns 'ptitem','U_PACKING     numeric (9,2)' 
execute add_columns 'ptitem','U_FREIG      numeric (10,2)'  
execute add_columns 'ptitem','U_DISC1   numeric (10,2)' 
execute add_columns 'ptitem','u_acamt   numeric (11,2)'  
execute add_columns 'ptitem','u_acamt1  numeric (11,2)'  
execute add_columns 'ptitem','u_examt   numeric (11,2)'  
execute add_columns 'ptitem','u_hacamt1  numeric (10,2)' 
execute add_columns 'ptitem','u_hcessamt  numeric (10,2)' 
execute add_columns 'ptitem','u_impduty  numeric (9,2)' 
execute add_columns 'ptitem','U_INSURIT   numeric (10,2)' 
execute add_columns 'ptitem','U_FREIGH    numeric (5,2)' 
execute add_columns 'ptitem','U_DISC1PER  numeric (5,2)' 
execute add_columns 'ptitem','U_ACDUTY   numeric (4,2)' 
execute add_columns 'ptitem','U_ACDUTY1  numeric (4,2)' 
execute add_columns 'ptitem','U_BASDUTY1  numeric (4,2)' 
execute add_columns 'ptitem','U_HACPER  numeric (4,2)' 
execute add_columns 'ptitem','U_HCESSPER  numeric (4,2)' 
execute add_columns 'ptitem','U_IMPPER   numeric (4,2)' 
execute add_columns 'ptitem','U_INSURPR  numeric (5,2)' 
execute add_columns 'ptitem','U_FRIGHT    numeric (11,2)' 
execute add_columns 'ptitem','U_FRPER     numeric (5,2)'
execute add_columns 'PTITEM','U_aDDDUTY   numeric (12,2)' 
execute add_columns 'PTITEM','U_PACKIT    numeric (10,2)'  
execute add_columns 'PTITEM','U_PACKITPR  numeric (10,2)'  
execute add_columns 'PTITEM','U_INSURIT   numeric (10,2)'
execute add_columns 'PTITEM','U_INSURPR   numeric (5,2)' 
execute add_columns 'PTITEM','U_FREIGHT   numeric (11,2)' 
execute add_columns 'PTITEM','u_freigper  numeric (5,2)' 
execute add_columns 'PTITEM','U_DISC2     numeric (12,2)' 
execute add_columns 'PTITEM','U_DISCO2    numeric (5,2)'   
execute add_columns 'pomain','U_PACK     numeric (9,2)' 
execute add_columns 'pomain','U_PACKIT     numeric (10,2)' 
execute add_columns 'pomain','U_INSUR      numeric (10,2)' 
execute add_columns 'pomain','U_INSURIT   numeric (10,2)' 
execute add_columns 'POmain','U_INSPER     numeric (5,3)' 
execute add_columns 'POmain','U_PACKPER    numeric (10,3)' 
execute add_columns 'POMAIN','U_HCESSAMT  numeric (10,2)' 
execute add_columns 'POITEM','U_FREIG     numeric (10,2)' 
execute add_columns 'POITEM','U_DISC2     numeric (5,2)' 
execute add_columns 'POITEM','U_FREIGHT   numeric (10,2)' 
execute add_columns 'POITEM','U_PACKIT    numeric (10,2)' 
execute add_columns 'POITEM','U_DISCO2    numeric (5,2)' 
execute add_columns 'POITEM','U_FREIGPER  numeric (5,2)' 
execute add_columns 'POITEM','U_INSURPR   numeric (5,2)' 
execute add_columns 'POITEM','U_PACKITPR  numeric (5,2)' 
execute add_columns 'POITEM','U_HCESSAMT  numeric (10,2)' 
execute add_columns 'POITEM','U_addduty   numeric (11,2)'
execute add_columns 'somain','U_PACK     numeric (9,2)' 
execute add_columns 'somain','U_PACKIT     numeric (10,2)' 
execute add_columns 'somain','U_INSUR      numeric (10,2)' 
execute add_columns 'somain','U_INSURIT   numeric (10,2)' 
execute add_columns 'sOmain','U_INSPER     numeric (5,3)' 
execute add_columns 'sOmain','U_PACKPER    numeric (10,3)' 
execute add_columns 'sOMAIN','U_HCESSAMT  numeric (10,2)' 
execute add_columns 'somain','u_cessamt numeric(11,2)'           
execute add_columns 'somain','u_hcesamt numeric(11,2)'           
execute add_columns 'somain','examt numeric(11,2)'           
execute add_columns 'somain','u_acamt numeric(11,2)'           
execute add_columns 'somain','u_acamt1 numeric(11,2)'           
execute add_columns 'somain','u_examt numeric(11,2)'           
execute add_columns 'somain','u_hacamt1 numeric(11,2)'           
execute add_columns 'somain','u_hcessamt numeric(11,2)'           
execute add_columns 'somain','u_impduty numeric(11,2)'           
execute add_columns 'sOITEM','U_FREIG     numeric (10,2)' 
execute add_columns 'sOITEM','U_DISC2     numeric (5,2)' 
execute add_columns 'sOITEM','U_FREIGHT   numeric (10,2)' 
execute add_columns 'sOITEM','U_PACKIT    numeric (10,2)' 
execute add_columns 'sOITEM','U_DISCO2    numeric (5,2)' 
execute add_columns 'sOITEM','U_FREIGPER  numeric (5,2)' 
execute add_columns 'sOITEM','U_INSURPR   numeric (5,2)' 
execute add_columns 'sOITEM','U_PACKITPR  numeric (5,2)' 
execute add_columns 'sOITEM','U_HCESSAMT  numeric (10,2)' 
execute add_columns 'sOITEM','U_addduty   numeric (11,2)'
execute add_columns 'soitem','u_cessper numeric(5,2)'           
execute add_columns 'soitem','u_hcessper numeric(5,2)'           
execute add_columns 'soitem','u_basduty numeric(5,2)'           
execute add_columns 'soitem','u_acduty numeric(5,2)'           
execute add_columns 'soitem','u_acduty1 numeric(5,2)'           
execute add_columns 'soitem','u_basduty1 numeric(5,2)'           
execute add_columns 'soitem','u_hacper numeric(5,2)'           
execute add_columns 'soitem','u_hcessper numeric(5,2)'           
execute add_columns 'soitem','u_impper numeric(5,2)'           
execute add_columns 'soitem','u_cessamt numeric(11,2)'           
execute add_columns 'soitem','u_hcesamt numeric(11,2)'           
execute add_columns 'soitem','examt numeric(11,2)'           
execute add_columns 'soitem','u_acamt numeric(11,2)'           
execute add_columns 'soitem','u_acamt1 numeric(11,2)'           
execute add_columns 'soitem','u_examt numeric(11,2)'           
execute add_columns 'soitem','u_hacamt1 numeric(11,2)'           
execute add_columns 'soitem','u_hcessamt numeric(11,2)'           
execute add_columns 'soitem','u_impduty numeric(11,2)'           
execute add_columns 'IRmain','U_PACK     numeric (9,2)' 
execute add_columns 'TRmain','U_PACKIT     numeric (10,2)' 
execute add_columns 'TRmain','U_INSUR      numeric (10,2)' 
execute add_columns 'TRmain','U_INSURIT   numeric (10,2)' 
execute add_columns 'TRmain','U_INSPER     numeric (5,3)' 
execute add_columns 'TRmain','U_PACKPER    numeric (10,3)' 
execute add_columns 'TRMAIN','U_HCESSAMT  numeric (10,2)' 
execute add_columns 'TRMAIN','U_PACK  numeric (10,2)' 
execute add_columns 'TRMAIN','U_PACKPER (5,2)' 

execute add_columns 'TRITEM','U_FREIG     numeric (10,2)' 
execute add_columns 'TRITEM','U_DISC2     numeric (5,2)' 
execute add_columns 'TRITEM','U_FREIGHT   numeric (10,2)' 
execute add_columns 'TRITEM','U_PACKIT    numeric (10,2)' 
execute add_columns 'TRITEM','U_DISCO2    numeric (5,2)' 
execute add_columns 'TRITEM','U_FREIGPER  numeric (5,2)' 
execute add_columns 'TRITEM','U_INSURPR   numeric (5,2)' 
execute add_columns 'TRITEM','U_PACKITPR  numeric (5,2)' 
execute add_columns 'TRITEM','U_HCESSAMT  numeric (10,2)' 
execute add_columns 'TRITEM','U_addduty   numeric (11,2)'
execute add_columns 'TRITEM','U_CESSPER numeric (5,2)'
execute add_columns 'TRITEM','U_HCESSPER numeric (5,2)'
execute add_columns 'TRITEM','U_CVDPER  numeric (5,2)'
execute add_columns 'TRITEM','U_ACDUTY numeric (5,2)'
execute add_columns 'TRITEM','U_ACDUTY1 numeric (5,2)'
execute add_columns 'TRITEM','U_BASDUTY1 numeric (5,2)'
execute add_columns 'TRITEM','U_HACPER  numeric (5,2)'
execute add_columns 'TRITEM','U_HCESSPER numeric (5,2)' 
execute add_columns 'TRITEM','U_IMPPER  numeric (5,2)'
execute add_columns 'TRITEM','U_BASDUTY  numeric (5,2)'
execute add_columns 'TRITEM','U_CESSAMT  numeric (11,2)'
execute add_columns 'TRITEM','U_HCESAMT  numeric (11,2)'
execute add_columns 'TRITEM','U_CVDAMT   numeric (11,2)'
execute add_columns 'TRITEM','U_ACAMT    numeric (11,2)'
execute add_columns 'TRITEM','U_ACAMT1   numeric (11,2)'
execute add_columns 'TRITEM','U_EXAMT    numeric (11,2)'
execute add_columns 'TRITEM','u_hacamt1  numeric (11,2)'
execute add_columns 'TRITEM','u_hcessamt numeric (11,2)'
execute add_columns 'TRITEM','U_IMPAMT   numeric (11,2)'
execute add_columns 'TRITEM','U_INSURIT   numeric (10,2)'
execute add_columns 'ARMAIN','U_HCESSAMT Decimal (12,2)' 
execute add_columns 'armain','U_INSPER     numeric (10,3)' 
execute add_columns 'armain','U_PACKPER    numeric (10,3)' 
execute add_columns 'armain','U_PACKIT     numeric (10,2)'  
execute add_columns 'armain','U_INSUR      numeric (10,2)' 
execute add_columns 'armain','U_INSURIT   numeric (10,2)'
execute add_columns 'ARMAIN','U_FRIGHT    numeric (11,2)' 
execute add_columns 'ARMAIN','U_FRPER     numeric (5,2)'
execute add_columns 'ARITEM','U_HCESSAMT Decimal (12,2)' 
execute add_columns 'ARitem','U_FRIGHT    numeric (11,2)' 
execute add_columns 'ARitem','U_FRPER     numeric (5,2)'
execute add_columns 'ARITEM','U_DISC2     numeric (12,2)' 
execute add_columns 'ARITEM','U_aDDDUTY   numeric (12,2)' 
execute add_columns 'ARITEM','U_PACKIT    numeric (10,2)'  
execute add_columns 'ARITEM','U_PACKITPR  numeric (10,2)'  
execute add_columns 'ARITEM','U_INSURIT   numeric (10,2)'
execute add_columns 'ARITEM','U_INSURPR   numeric (5,2)' 
execute add_columns 'ARITEM','U_FREIGHT   numeric (11,2)' 
execute add_columns 'ARITEM','u_freigper  numeric (5,2)' 
execute add_columns 'ARITEM','U_DISC2     numeric (12,2)' 
execute add_columns 'ARITEM','U_DISCO2    numeric (5,2)'   
execute add_columns 'ARITEM','U_ACMT    NUMERIC (12,2)'
execute add_columns 'ARITEM','U_ACDUTY    NUMERIC (5,2)'
execute add_columns 'ARITEM','U_BEDATE 	Datetime'
execute add_columns 'ARITEM','U_BENO 	varchar	(25)'
execute add_columns 'SOmain','U_PARTYADD    Varchar (100)'
execute add_columns 'SOmain','U_PINVNO  	Varchar (20)'
execute add_columns 'SOmain','U_PARTY   	Varchar (100)'
execute add_columns 'SOmain','U_PODT    	Datetime'
execute add_columns 'SOmain','U_PONO    	varchar	(25)'
execute add_columns 'SOmain','U_LOAREF  	varchar	(40)'
execute add_columns 'SOITEM','U_SRNO    	varchar             	(10)'
execute add_columns 'SOITEM','U_LOP     	Varchar             	(10)'
execute add_columns 'SOITEM','U_INSURIT  Numeric (12,2)' 
execute add_columns 'sOITEM','U_INSURPR    Decimal (5,2) '        
execute add_columns 'sOITEM','U_IMPAMT   Decimal (11,2)'   
execute add_columns 'sOITEM','U_IMPPER  Decimal (4,2) ' 
execute add_columns 'BPmain','u_b1no   	numeric (10,2)' 
execute add_columns 'brmain','u_b1no   	numeric (10,2)' 
execute add_columns 'IRITEM','u_impduty Decimal (12,2)'            
execute add_columns 'IRITEM','u_hacper Decimal (12,2)'
execute add_columns 'IRITEM','U_HCESSPER Decimal (12,2)'            
execute add_columns 'IRITEM','U_IMPAMT  	Decimal (12,2)'            
execute add_columns 'IRITEM','U_IMPPER  	Decimal (5,2) '           
execute add_columns 'IRITEM','U_INRVAL  	Decimal (13,4)'            
execute add_columns 'IRITEM','U_BASDUTY1 Decimal (5,2) '           
execute add_columns 'IRITEM','U_EXAMT   	Decimal (12,2)'            
execute add_columns 'IRITEM','U_CIFAMT  	Decimal (12,2)'            
execute add_columns 'IRITEM','U_ACDUTY  	Decimal (5,2) '           
execute add_columns 'IRITEM','U_ACDUTY1 	Decimal (5,2) '           
execute add_columns 'IRITEM','U_ACAMT1  	Decimal (12,2)'            
execute add_columns 'IRITEM','U_ACAMT   	Decimal (12,2)'            
execute add_columns 'IRITEM','U_CESSPER 	Decimal (5,2) '           
execute add_columns 'IRITEM','U_CESSAMT 	Decimal (12,2)'            
execute add_columns 'IRITEM','U_FREIGHT 	Decimal (12,2)'            
execute add_columns 'IRITEM','U_FRPER   	Decimal (5,2) '           
execute add_columns 'IRITEM','U_INSURA  	Decimal (12,2)'            
execute add_columns 'IRITEM','U_INSPER  	Decimal (6,3) '           
execute add_columns 'IRITEM','U_LANDPER 	Decimal (5,2) '           
execute add_columns 'IRITEM','U_LANDCH  	Decimal (12,2)'            
execute add_columns 'IRITEM','U_PACKCHG 	Decimal (13,4)'            
execute add_columns 'IRITEM','U_HACAMT1 	Decimal (12,2)'            
execute add_columns 'IRITEM','U_HCESSAMT Decimal (12,2)'            
execute add_columns 'IRITEM','U_HCESAMT Decimal (12,2)'            
execute add_columns 'IRITEM','U_USDAMT  	Decimal (12,3)'
execute add_columns 'IiITEM','U_ACAMT1      numeric (5,2)' 
execute add_columns 'IiITEM','U_ACDUTY1     NUMERIC (12,2)'
execute add_columns 'IiITEM','U_ACAMT    NUMERIC (12,2)'
execute add_columns 'IiITEM','U_ACDUTY    NUMERIC (5,2)'
execute add_columns 'IiITEM','U_IMPAMT   NUMERIC (12,2)'
execute add_columns 'IiITEM','U_IMPPER   NUMERIC (5,2)'
execute add_columns 'IiITEM','u_hacamt1  NUMERIC (12,2)'
execute add_columns 'IiITEM','U_HACPER    NUMERIC (5,2)'
execute add_columns 'IiITEM','u_hcessamt NUMERIC (12,2)'
execute add_columns 'IiITEM','U_HCESSPER   NUMERIC (5,2)'
execute add_columns 'IiITEM','U_ADDVAT    NUMERIC (10,2)'
execute add_columns 'IiITEM','U_BASDUTY   NUMERIC (5,2)'
execute add_columns 'IiITEM','u_cessamt NUMERIC (10,2)'
execute add_columns 'IiITEM','U_CESSPER NUMERIC (10,2)'
execute add_columns 'IiITEM','u_examt   NUMERIC (10,2)'
execute add_columns 'IiITEM','U_BASDUTY1  NUMERIC (5,2)'
execute add_columns 'IiITEM','u_impduty  NUMERIC (5,2)'
execute add_columns 'IiITEM','U_IMPPER   NUMERIC (5,2)'
execute add_columns 'IIitem','U_addduty   numeric (11,2)'
execute add_columns 'Iimain','U_ACAMT    NUMERIC (12,2)'
execute add_columns 'Iimain','U_ACAMT1    NUMERIC (12,2)'
execute add_columns 'Iimain','U_ACDUTY    NUMERIC (5,2)'
execute add_columns 'Iimain','U_IMPAMT   NUMERIC (12,2)'
execute add_columns 'Iimain','U_IMPPER   NUMERIC (5,2)'
execute add_columns 'Iimain','u_hacamt1  NUMERIC (12,2)'
execute add_columns 'Iimain','U_HACPER    NUMERIC (5,2)'
execute add_columns 'Iimain','u_hcessamt NUMERIC (12,2)'
execute add_columns 'Iimain','U_HCESSPER   NUMERIC (5,2)'
execute add_columns 'Iimain','U_ADDVAT    NUMERIC (10,2)'
execute add_columns 'Iimain','U_BASDUTY   NUMERIC (5,2)'
execute add_columns 'Iimain','u_cessamt NUMERIC (10,2)'
execute add_columns 'Iimain','U_CESSPER NUMERIC (10,2)'
execute add_columns 'Iimain','u_examt   NUMERIC (10,2)'
execute add_columns 'Iimain','U_BASDUTY1  NUMERIC (5,2)'
execute add_columns 'Iimain','u_impduty  NUMERIC (5,2)'
execute add_columns 'Iimain','U_IMPPER   NUMERIC (5,2)'
execute add_columns 'IIMAIN','U_addduty   numeric (11,2)'
execute add_columns 'IPITEM','U_ACAMT1      numeric (5,2)' 
execute add_columns 'IPITEM','U_ACDUTY1     NUMERIC (12,2)'
execute add_columns 'IPITEM','U_ACAMT    NUMERIC (12,2)'
execute add_columns 'IPITEM','U_ACDUTY    NUMERIC (5,2)'
execute add_columns 'IPITEM','U_IMPAMT   NUMERIC (12,2)'
execute add_columns 'IPITEM','U_IMPPER   NUMERIC (5,2)'
execute add_columns 'IPITEM','u_hacamt1  NUMERIC (12,2)'
execute add_columns 'IPITEM','U_HACPER    NUMERIC (5,2)'
execute add_columns 'IPITEM','u_hcessamt NUMERIC (12,2)'
execute add_columns 'IPITEM','U_HCESSPER   NUMERIC (5,2)'
execute add_columns 'IPITEM','U_ADDVAT    NUMERIC (10,2)'
execute add_columns 'IPITEM','U_BASDUTY   NUMERIC (5,2)'
execute add_columns 'IPITEM','u_cessamt NUMERIC (10,2)'
execute add_columns 'IPITEM','U_CESSPER NUMERIC (10,2)'
execute add_columns 'IPITEM','u_examt   NUMERIC (10,2)'
execute add_columns 'IPITEM','U_BASDUTY1  NUMERIC (5,2)'
execute add_columns 'IPITEM','u_impduty  NUMERIC (5,2)'
execute add_columns 'IPITEM','U_IMPPER   NUMERIC (5,2)'
execute add_columns 'IPITEM','U_addduty   numeric (11,2)'
execute alter_columns 'DCMAST','dac_name  varchar(254)'
EXECUTE Update_table_column_default_value 'DCMAST',1


