/****** Object:  Table [dbo].[EIMAIN]    Script Date: 01/16/2010 11:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF not EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EIMAIN]') AND type in (N'U'))
CREATE TABLE [dbo].[EIMAIN](
	[entry_ty] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[date] [datetime] NULL,
	[doc_no] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dept] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[cate] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[party_nm] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[inv_no] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[inv_sr] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[l_yn] [varchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[due_dt] [datetime] NULL,
	[gro_amt] [numeric](17, 2) NULL,
	[tot_deduc] [numeric](10, 2) NULL,
	[tot_add] [numeric](10, 2) NULL,
	[examt] [numeric](10, 2) NULL,
	[excise_ty] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[taxamt] [numeric](10, 2) NULL,
	[tax_name] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[tot_tax] [numeric](10, 2) NULL,
	[net_amt] [numeric](17, 2) NULL,
	[re_all] [numeric](17, 2) NULL,
	[disc] [numeric](11, 2) NULL,
	[memo_op] [bit] NULL,
	[narr] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[lock] [bit] NULL,
	[tot_nontax] [numeric](10, 2) NULL,
	[tot_fdisc] [numeric](10, 2) NULL,
	[form_nm] [char](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[form_no] [char](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[cheq_no] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[bank_nm] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[drawn_on] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[slipno] [numeric](6, 0) NULL,
	[cqyn] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[salesman] [varchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_chalno] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_chaldt] [datetime] NULL,
	[user_name] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[up_reall] [numeric](17, 2) NULL,
	[v_b] [numeric](1, 0) NULL,
	[u_tot] [numeric](9, 2) NULL,
	[u_surch] [numeric](9, 2) NULL,
	[lessamt] [numeric](10, 2) NULL,
	[taddamt] [numeric](10, 2) NULL,
	[addamt] [numeric](10, 2) NULL,
	[stchgamt] [numeric](10, 2) NULL,
	[u_ldisc] [numeric](9, 2) NULL,
	[u_taxable] [numeric](9, 2) NULL,
	[u_nontax] [numeric](9, 2) NULL,
	[u_expla] [numeric](9, 2) NULL,
	[u_exrg23ii] [numeric](9, 2) NULL,
	[u_lrdt] [datetime] NULL,
	[u_lrno] [char](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_pack] [numeric](9, 2) NULL,
	[u_plasr] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_pono] [char](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_removdt] [datetime] NULL,
	[u_rg23cno] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_rg23no] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_rg2amt] [numeric](9, 2) NULL,
	[u_timep] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_timep1] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_vehno] [char](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_exgoods] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_deliver] [char](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[rp] [numeric](1, 0) NULL,
	[u_cldt] [datetime] NULL,
	[u_deli] [char](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_expbno] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_exbdt] [datetime] NULL,
	[u_exbamt] [numeric](14, 2) NULL,
	[u_exaredt] [datetime] NULL,
	[u_imporm] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_disamt1] [numeric](9, 2) NULL,
	[u_tempd] [numeric](9, 2) NULL,
	[u_tempad] [numeric](9, 2) NULL,
	[roundoff] [numeric](4, 2) NULL,
	[u_exare3] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_exare3dt] [datetime] NULL,
	[u_are2co] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_are2cno] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_are2cdt] [datetime] NULL,
	[u_are2not] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_are2dt] [datetime] NULL,
	[u_disclaim] [char](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_sbdt] [datetime] NULL,
	[u_vesselno] [char](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[fdebit] [bit] NULL,
	[fdate] [datetime] NULL,
	[rule] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ettype] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[tot_examt] [numeric](10, 2) NULL,
	[u_cessamt] [numeric](10, 2) NULL,
	[u_insuno] [char](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[sysdate] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[apgenby] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[apgentime] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[apledby] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[apledtime] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[apledps] [bit] NULL,
	[apgenps] [bit] NULL,
	[approve] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[apled] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[apgen] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_gddate] [datetime] NULL,
	[u_port1] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_port2] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_port3] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_port4] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_precarri] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_vessel] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_port] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_receipt] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_loading] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_expdel] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_origin] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_fdesti] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_payment] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_expdesc] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_expmark] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_exchange] [numeric](11, 2) NULL,
	[u_b17srno] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_countain] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_shipdet] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_cseal] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_tseal] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_expproof] [bit] NULL,
	[u_othref] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_buyer] [char](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_corren] [char](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_freight] [numeric](11, 2) NULL,
	[u_insura] [numeric](11, 2) NULL,
	[u_blno1] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_bldt1] [datetime] NULL,
	[u_sbno1] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_sbdt1] [datetime] NULL,
	[u_grno1] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_grdt1] [datetime] NULL,
	[u_bol] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_boldt] [datetime] NULL,
	[u_cha] [char](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_ar3adate] [datetime] NULL,
	[u_type] [bit] NULL,
	[u_gper] [numeric](4, 2) NULL,
	[u_mtrate] [numeric](11, 2) NULL,
	[u_datevf] [datetime] NULL,
	[u_loaref] [char](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_exform] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_notify1] [char](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_notify2] [char](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_examt] [numeric](11, 2) NULL,
	[u_acamt] [numeric](11, 2) NULL,
	[u_acamt1] [numeric](11, 2) NULL,
	[u_blno] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_bldt] [datetime] NULL,
	[u_packages] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_grosswt] [numeric](11, 3) NULL,
	[u_bolt] [bit] NULL,
	[u_basduty1] [numeric](4, 2) NULL,
	[u_acduty] [numeric](4, 2) NULL,
	[u_acduty1] [numeric](4, 2) NULL,
	[u_basduty] [numeric](4, 2) NULL,
	[u_cessper] [numeric](4, 2) NULL,
	[u_impamt] [numeric](9, 2) NULL,
	[u_impper] [numeric](4, 2) NULL,
	[u_impduty] [numeric](9, 2) NULL,
	[tds] [numeric](11, 2) NULL,
	[u_podt] [datetime] NULL,
	[u_pfor] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_qadinv] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_netwt] [numeric](11, 3) NULL,
	[u_disamt2] [numeric](10, 2) NULL,
	[u_add5] [numeric](11, 2) NULL,
	[u_exare1dt] [datetime] NULL,
	[aapurc] [bit] NULL,
	[u_cessamtp] [numeric](10, 2) NULL,
	[u_cessamta] [numeric](10, 2) NULL,
	[u_cessamtc] [numeric](10, 2) NULL,
	[round_off] [numeric](4, 2) NULL,
	[nil] [numeric](9, 2) NULL,
	[u_ptrans] [bit] NULL,
	[u_cate] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_hacamt1] [numeric](10, 2) NULL,
	[u_hcessamt] [numeric](10, 2) NULL,
	[U_SDATE] [datetime] NULL,
	[R_recond] [bit] NULL,
	[Godown] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cusamt] [numeric](11, 2) NULL,
	[Apzentime] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Manuname] [varchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Print_flag] [bit] NULL,
	[Tran_cd] [int] IDENTITY(1,1) NOT NULL,
	[Bk_id] [int] NULL,
	[Ac_id] [int] NULL,
	[Compid] [int] NULL,
	[Cuscess] [numeric](10, 2) NULL,
	[Int_adv] [numeric](9, 2) NULL,
	[Broker] [varchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cons_id] [int] NULL,
	[BUYER_NM] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[U_PINVNO] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[U_PINVDT] [datetime] NULL,
	[U_EXARE1] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_ct3no] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_ar3ano] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_bunno] [varchar](45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_bunfrm] [numeric](12, 0) NULL,
	[u_bunto] [numeric](12, 0) NULL,
	[U_173H] [decimal](14, 3) NULL,
	[U_EXB1] [decimal](14, 3) NULL,
	[U_EXSPEC] [decimal](14, 3) NULL,
	[U_OCT] [decimal](14, 3) NULL,
	[U_SUR] [decimal](14, 3) NULL,
	[U_FREI] [decimal](14, 3) NULL,
	[U_TMODE] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ctdate] [datetime] NULL,
	[aredate] [datetime] NULL,
	[u_exbvaldt] [datetime] NULL,
	[ctdesc] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[aredesc] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[U_CT3DATE] [datetime] NULL,
	[U_ARE1DT] [datetime] NULL,
	[U_CHDATE] [datetime] NULL,
	[U_AR3ADT] [datetime] NULL,
	[u_hacper] [numeric](4, 2) NULL,
	[u_hcessper] [numeric](4, 2) NULL,
	[U_ADDVAT] [numeric](10, 0) NULL,
	[U_AVPER] [numeric](5, 0) NULL,
	[u_gcssr] [bit] NULL,
	[u_choice] [bit] NULL,
	[u_countai2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_tseal2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[u_cseal2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[areno] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ctno] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ctid] [numeric](18, 0) NULL,
	[areid] [numeric](18, 0) NULL,
	[U_B1NO] [decimal](10, 0) NULL,
	[U_CHQDT] [datetime] NULL,
 CONSTRAINT [PK_EIMAIN] PRIMARY KEY CLUSTERED 
(
	[Tran_cd] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_EIMAIN_ac_mast]') AND parent_object_id = OBJECT_ID(N'[dbo].[EIMAIN]'))
ALTER TABLE [dbo].[EIMAIN]  WITH NOCHECK ADD  CONSTRAINT [FK_EIMAIN_ac_mast] FOREIGN KEY([Ac_id])
REFERENCES [dbo].[AC_MAST] ([Ac_id])
NOT FOR REPLICATION 
GO
ALTER TABLE [dbo].[EIMAIN] CHECK CONSTRAINT [FK_EIMAIN_ac_mast]