
/****** Object:  StoredProcedure [dbo].[USP_REP_GRN]    Script Date: 02/05/2010 10:04:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO






CREATE  PROCEDURE [dbo].[USP_REP_GRN] 
@TMPAC NVARCHAR(50),@TMPIT NVARCHAR(50),@SPLCOND VARCHAR(8000),@SDATE  SMALLDATETIME,@EDATE SMALLDATETIME
,@SAC AS VARCHAR(60),@EAC AS VARCHAR(60)
,@SIT AS VARCHAR(60),@EIT AS VARCHAR(60)
,@SAMT FLOAT,@EAMT FLOAT
,@SDEPT AS VARCHAR(60),@EDEPT AS VARCHAR(60)
,@SCATE AS VARCHAR(60),@ECATE AS VARCHAR(60)
,@SWARE AS VARCHAR(60),@EWARE AS VARCHAR(60)
,@SINV_SR AS VARCHAR(60),@EINV_SR AS VARCHAR(60)
,@LYN VARCHAR(20)
,@EXPARA  AS VARCHAR(60)= null
AS
SET QUOTED_IDENTIFIER OFF

Declare @FCON as NVARCHAR(2000),@VSAMT DECIMAL(14,2),@VEAMT DECIMAL(14,2)
EXECUTE   USP_REP_FILTCON 
@VTMPAC =@TMPAC,@VTMPIT =@TMPIT,@VSPLCOND =@SPLCOND
,@VSDATE=@SDATE
 ,@VEDATE=@EDATE
,@VSAC =@SAC,@VEAC =@EAC
,@VSIT=@SIT,@VEIT=@EIT
,@VSAMT=@SAMT,@VEAMT=@EAMT
,@VSDEPT=@SDEPT,@VEDEPT=@EDEPT
,@VSCATE =@SCATE,@VECATE =@ECATE
,@VSWARE =@SWARE,@VEWARE  =@EWARE
,@VSINV_SR =@SINV_SR,@VEINV_SR =@SINV_SR
,@VMAINFILE='ARMAIN',@VITFILE='ARITEM',@VACFILE='ARACDET'
,@VDTFLD ='DATE'
,@VLYN =NULL
,@VEXPARA=@EXPARA
,@VFCON =@FCON OUTPUT

DECLARE @SQLCOMMAND NVARCHAR(4000), @VCOND NVARCHAR(2000)

SET @SQLCOMMAND=' SELECT ARITEM.TRAN_CD,ARITEM.ENTRY_TY,ARITEM.INV_NO,ARITEM.DATE,AC_MAST.AC_NAME,IT_MAST.IT_NAME,ARITEM.QTY,ARITEM.ITEM_NO,ARITREF.RENTRY_TY,ARITREF.RINV_NO'
SET @SQLCOMMAND=@SQLCOMMAND+' ,ARMAIN.U_PINVNO,ARMAIN.U_PINVDT,ARMAIN.U_BENO,ARMAIN.U_BEDATE,ARMAIN.U_AR3ANO,ARMAIN.U_AR3ADaTe,IT_MAST.P_UNIT,ARITEM.U_CHALQTY,ARITEM.U_ACQTY,ARITEM.U_RQTY,ARMAIN.DEPT'
SET @SQLCOMMAND=@SQLCOMMAND+' FROM ARITEM'
SET @SQLCOMMAND=@SQLCOMMAND+' INNER JOIN ARMAIN ON(ARITEM.ENTRY_TY=ARMAIN.ENTRY_TY AND ARITEM.TRAN_CD=ARMAIN.TRAN_CD)'
SET @SQLCOMMAND=@SQLCOMMAND+' LEFT JOIN IT_MAST ON (ARITEM.ITEM=IT_MAST.IT_NAME)'
SET @SQLCOMMAND=@SQLCOMMAND+' LEFT JOIN AC_MAST ON (ARITEM.PARTY_NM=AC_MAST.AC_NAME)'
SET @SQLCOMMAND=@SQLCOMMAND+' LEFT JOIN ARITREF ON (ARITEM.ENTRY_TY=ARITREF.ENTRY_TY  AND ARITEM.DATE=ARITREF.DATE AND ARITEM.DOC_NO=ARITREF.DOC_NO AND ARITEM.ITSERIAL=ARITREF.ITSERIAL)'
SET @SQLCOMMAND=@SQLCOMMAND+RTRIM(@FCON) 
SET @SQLCOMMAND=@SQLCOMMAND+' ORDER BY ARITEM.DATE,ARITEM.DOC_NO'

EXECUTE SP_EXECUTESQL @SQLCOMMAND















