
/****** Object:  StoredProcedure [dbo].[USP_REP_SALESUM]    Script Date: 02/05/2010 10:06:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE  PROCEDURE [dbo].[USP_REP_SALESUM] 
@TMPAC NVARCHAR(50),@TMPIT NVARCHAR(50),@SPLCOND VARCHAR(8000),@SDATE  SMALLDATETIME,@EDATE SMALLDATETIME
,@SAC AS VARCHAR(60),@EAC AS VARCHAR(60)
,@SIT AS VARCHAR(60),@EIT AS VARCHAR(60)
,@SAMT FLOAT,@EAMT FLOAT
,@SDEPT AS VARCHAR(60),@EDEPT AS VARCHAR(60)
,@SCATE AS VARCHAR(60),@ECATE AS VARCHAR(60)
,@SWARE AS VARCHAR(60),@EWARE AS VARCHAR(60)
,@SINV_SR AS VARCHAR(60),@EINV_SR AS VARCHAR(60)
,@LYN VARCHAR(20)
,@EXPARA  AS VARCHAR(60)= null
AS
SET QUOTED_IDENTIFIER OFF

Declare @FCON as NVARCHAR(2000),@VSAMT DECIMAL(14,2),@VEAMT DECIMAL(14,2)
EXECUTE   USP_REP_FILTCON 
@VTMPAC =NULL,@VTMPIT =NULL,@VSPLCOND =@SPLCOND
,@VSDATE=@SDATE
 ,@VEDATE=@EDATE
,@VSAC =NULL,@VEAC =NULL
,@VSIT=NULL,@VEIT=null
,@VSAMT=@SAMT,@VEAMT=@EAMT
,@VSDEPT=@SDEPT,@VEDEPT=@EDEPT
,@VSCATE =@SCATE,@VECATE =@ECATE
,@VSWARE =@SWARE,@VEWARE  =@EWARE
,@VSINV_SR =@SINV_SR,@VEINV_SR =@SINV_SR
,@VMAINFILE='STMAIN',@VITFILE='STITEM',@VACFILE=' '
,@VDTFLD ='DATE'
,@VLYN =NULL
,@VEXPARA=@EXPARA
,@VFCON =@FCON OUTPUT

DECLARE @SQLCOMMAND NVARCHAR(4000), @VCOND NVARCHAR(2000)

SET @SQLCOMMAND = 'select STMAIN.date,STMAIN.cate,sum(STITEM.qty),IT_MAST.[GROUP],STMAIN.INV_SR from STITEM '
SET @SQLCOMMAND = @SQLCOMMAND+' INNER JOIN STMAIN ON(STITEM.ENTRY_TY=STMAIN.ENTRY_TY AND STITEM.TRAN_CD=STMAIN.TRAN_CD)'
SET @SQLCOMMAND = @SQLCOMMAND+' INNER JOIN IT_MAST ON(STITEM.ITEM=IT_MAST.IT_NAME)'
SET @SQLCOMMAND = @SQLCOMMAND+RTRIM(@FCON)
SET @SQLCOMMAND = @SQLCOMMAND+'AND STMAIN.ENTRY_TY=''ST'''
SET @SQLCOMMAND = @SQLCOMMAND+' GROUP BY STMAIN.date,STMAIN.cate,STMAIN.inv_sr,IT_MAST.[GROUP]'
SET @SQLCOMMAND = @SQLCOMMAND+' ORDER BY STMAIN.date,STMAIN.cate,STMAIN.inv_sr,IT_MAST.[GROUP]'

---SELECT @SQLCOMMAND

EXECUTE SP_EXECUTESQL @SQLCOMMAND





