ALTER TABLE IT_MAST ADD MFGITID VARCHAR(25)

ALTER TABLE AC_MAST ADD MFGACID VARCHAR(25)
ALTER TABLE shipto ADD MFGACID VARCHAR(25)

ALTER TABLE PTMAIN ADD HDRID VARCHAR(25)
ALTER TABLE PTITEM ADD HDRID VARCHAR(25)
ALTER TABLE PTITEM ADD DTLID VARCHAR(25)

ALTER TABLE STMAIN ADD HDRID VARCHAR(25)
ALTER TABLE STITEM ADD HDRID VARCHAR(25)
ALTER TABLE STITEM ADD DTLID VARCHAR(25)

ALTER TABLE IPMAIN ADD HDRID VARCHAR(25)
ALTER TABLE IPITEM ADD HDRID VARCHAR(25)
ALTER TABLE IPITEM ADD DTLID VARCHAR(25)

ALTER TABLE OPMAIN ADD HDRID VARCHAR(25)
ALTER TABLE OPITEM ADD HDRID VARCHAR(25)
ALTER TABLE OPITEM ADD DTLID VARCHAR(25)

ALTER TABLE IIMAIN ADD HDRID VARCHAR(25)
ALTER TABLE IIITEM ADD HDRID VARCHAR(25)
ALTER TABLE IIITEM ADD DTLID VARCHAR(25)
ALTER TABLE IIRMDET ADD REFHDRID VARCHAR(25)
ALTER TABLE IIRMDET ADD REFDTLID VARCHAR(25)

ALTER TABLE IRMAIN ADD HDRID VARCHAR(25)
ALTER TABLE IRITEM ADD HDRID VARCHAR(25)
ALTER TABLE IRITEM ADD DTLID VARCHAR(25)
ALTER TABLE IRRMDET ADD REFHDRID VARCHAR(25)
ALTER TABLE IRRMDET ADD REFDTLID VARCHAR(25)

ALTER TABLE ARMAIN ADD HDRID VARCHAR(25)
ALTER TABLE ARITEM ADD HDRID VARCHAR(25)
ALTER TABLE ARITEM ADD DTLID VARCHAR(25)
ALTER TABLE MANU_DET ADD HDRID VARCHAR(25)
ALTER TABLE MANU_DET ADD DTLID VARCHAR(25)

ALTER TABLE DCMAIN ADD HDRID VARCHAR(25)
ALTER TABLE DCITEM ADD HDRID VARCHAR(25)
ALTER TABLE DCITEM ADD DTLID VARCHAR(25)
ALTER TABLE LITEMALL ADD HDRID VARCHAR(25)
ALTER TABLE LITEMALL ADD DTLID VARCHAR(25)
ALTER TABLE LITEMALL ADD PUR_PARTY_NM VARCHAR(35)
ALTER TABLE LITEMALL ADD MANUBILL VARCHAR(15)
ALTER TABLE LITEMALL ADD MANUDATE SMALLDATETIME

