If exists(Select * from sysobjects where [name]='USP_REP_MH_ANNEXUREB_DADOS' and xtype='P')
Begin
	Drop Procedure USP_REP_MH_ANNEXUREB_DADOS
End
go
-- =============================================
-- Author:		Pankaj M. Borse.
-- Create date: 29-10-2014
-- Description:	this procedure is for Maharashtra VAT Form 704 Annexure A dados report
-- =============================================
CREATE PROCEDURE [dbo].[USP_REP_MH_ANNEXUREB_DADOS]
@SDATE  SMALLDATETIME,@EDATE SMALLDATETIME
AS
BEGIN
SELECT ROWNO=ROW_NUMBER() OVER (ORDER BY NET_AMT DESC),TAXAMT=(CASE WHEN U_NATURE='' THEN NET_AMT ELSE 0 END),DATE,INTREST=(CASE WHEN U_NATURE<>'' THEN NET_AMT ELSE 0 END) 
INTO #TEMPTBL
FROM BPMAIN 
WHERE PARTY_NM='CST PAYABLE' and (DATE BETWEEN @SDATE AND @EDATE)  ORDER BY NET_AMT DESC

SELECT * INTO #TEMPTBL1 FROM #TEMPTBL WHERE 1=2

IF EXISTS(SELECT ROWNO FROM #TEMPTBL WHERE ROWNO>50)
	BEGIN
		INSERT INTO #TEMPTBL1 SELECT * FROM #TEMPTBL WHERE ROWNO<50
		DELETE FROM #TEMPTBL WHERE ROWNO<50
		INSERT INTO #TEMPTBL1 SELECT 50,SUM(TAXAMT),'',SUM(INTREST) FROM #TEMPTBL
		DROP TABLE #TEMPTBL
	END
ELSE
	BEGIN
		INSERT INTO #TEMPTBL1 SELECT * FROM #TEMPTBL 
		DROP TABLE #TEMPTBL
	END

SELECT ROWNO,FRMDT=@SDATE,ENDDT=@EDATE,DUEDT='',RETTYPE='',TAXAMT,DATE,DELAYAMT='',INTREST FROM #TEMPTBL1
DROP TABLE #TEMPTBL1

END
