If exists (Select [Name] from sysobjects Where xtype='P' and [name]='USP_REP_EXPORT_REG')
Begin
	Drop Procedure USP_REP_EXPORT_REG
End
Go
CREATE PROCEDURE  [dbo].[USP_REP_EXPORT_REG]
@TMPAC NVARCHAR(50),@TMPIT NVARCHAR(50),@SPLCOND VARCHAR(8000),@SDATE  SMALLDATETIME,@EDATE SMALLDATETIME
,@SAC AS VARCHAR(60),@EAC AS VARCHAR(60)
,@SIT AS VARCHAR(60),@EIT AS VARCHAR(60)
,@SAMT FLOAT,@EAMT FLOAT
,@SDEPT AS VARCHAR(60),@EDEPT AS VARCHAR(60)
,@SCATE AS VARCHAR(60),@ECATE AS VARCHAR(60)
,@SWARE AS VARCHAR(60),@EWARE AS VARCHAR(60)
,@SINV_SR AS VARCHAR(60),@EINV_SR AS VARCHAR(60)
,@LYN VARCHAR(20)
,@EXPARA  AS VARCHAR(60)= NULL
AS
SET QUOTED_IDENTIFIER OFF 
DECLARE @FCON AS NVARCHAR(1000)

EXECUTE   USP_REP_FILTCON 
@VTMPAC =@TMPAC,@VTMPIT =@TMPIT,@VSPLCOND =@SPLCOND
,@VSDATE=NULL
 ,@VEDATE=@EDATE
,@VSAC =@SAC,@VEAC =@EAC
,@VSIT=@SIT,@VEIT=@EIT
,@VSAMT=@SAMT,@VEAMT=@EAMT
,@VSDEPT=@SDEPT,@VEDEPT=@EDEPT
,@VSCATE =@SCATE,@VECATE =@ECATE
,@VSWARE =@SWARE,@VEWARE  =@EWARE
,@VSINV_SR =@SINV_SR,@VEINV_SR =@SINV_SR
,@VMAINFILE='STMAIN',@VITFILE=NULL,@VACFILE=NULL
,@VDTFLD ='AREDATE'
,@VLYN =NULL
,@VEXPARA=@EXPARA
,@VFCON =@FCON OUTPUT

IF @FCON IS NOT NULL OR @FCON <> ''
BEGIN
	SET @FCON = @FCON 
END

DECLARE @SQLCOMMAND NVARCHAR(4000),@VCOND NVARCHAR(2000)
DECLARE @U_BASDUTY NUMERIC(12,2),@U_CESSPER NUMERIC(12,2),@U_HCESPER NUMERIC(12,2)	

SET @SQLCOMMAND='SELECT STMAIN.ENTRY_TY,STMAIN.TRAN_CD,STMAIN.DATE,STMAIN.PARTY_NM,STMAIN.NET_AMT,STMAIN.[RULE],STMAIN.BONDSRNO'
SET @SQLCOMMAND=@SQLCOMMAND+', STMAIN.INV_NO,STMAIN.U_EXPDEL,STMAIN.ARENO,STMAIN.AREDESC,STMAIN.U_CSEAL,GRO_AMT = STITEM.U_ASSEAMT,STITEM.ITEM'
SET @SQLCOMMAND=@SQLCOMMAND+', STITEM.QTY,STITEM.RATE,STITEM.FCRATE,STMAIN.U_EXCHANGE AS FCEXRATE,STITEM.FCGRO_AMT,STITEM.ITSERIAL,STITEM.U_ASSEAMT'
SET @SQLCOMMAND=@SQLCOMMAND+', STITEM.U_CUSTAMT,STITEM.U_CUSTPER,STITEM.BCDAMT,STITEM.BCDPER,STITEM.U_CESSAMT,STITEM.U_CESSPER,STITEM.U_HCESAMT'
SET @SQLCOMMAND=@SQLCOMMAND+', STITEM.U_HCESSPER,STITEM.CCDAMT,STITEM.CCDPER,STITEM.HCDAMT,STITEM.HCDPER,STITEM.U_CESSAMT3'
SET @SQLCOMMAND=@SQLCOMMAND+', STITEM.U_CESSPER3,STITEM.U_HCESAMT3,STITEM.U_HCESPER3,IT_DESC=(CASE WHEN ISNULL(IT_MAST.IT_ALIAS,'''')='''''
SET @SQLCOMMAND=@SQLCOMMAND+' THEN IT_MAST.IT_NAME ELSE IT_MAST.IT_ALIAS END),MAILNAME=(CASE WHEN ISNULL(AC_MAST.MAILNAME,'''')='''' '
SET @SQLCOMMAND=@SQLCOMMAND+'  THEN AC_MAST.AC_NAME ELSE AC_MAST.MAILNAME END),IT_MAST.RATEUNIT '
SET @SQLCOMMAND=@SQLCOMMAND+' FROM STMAIN'
SET @SQLCOMMAND=@SQLCOMMAND+' INNER JOIN STITEM ON (STMAIN.ENTRY_TY=STITEM.ENTRY_TY AND STMAIN.TRAN_CD=STITEM.TRAN_CD) '
SET @SQLCOMMAND=@SQLCOMMAND+' INNER JOIN AC_MAST ON (AC_MAST.AC_ID=STMAIN.AC_ID) '
--,CAST(IT_MAST.IT_DESC AS VARCHAR(4000)) AS IT_DESC'
SET @SQLCOMMAND=@SQLCOMMAND+' INNER JOIN IT_MAST ON (IT_MAST.IT_CODE=STITEM.IT_CODE)'
--SET @SQLCOMMAND=@SQLCOMMAND+', MailName=(CASE WHEN ISNULL(ac_mast.MailName,'''')='''' THEN ac_mast.ac_name ELSE ac_mast.mailname END)'	
--SET @SQLCOMMAND=@SQLCOMMAND+', IT_MAST.EIT_NAME,IT_MAST.CHAPNO,IT_MAST.IDMARK,IT_MAST.RATEUNIT '
--SET @SQLCOMMAND=@SQLCOMMAND+', AC_MAST.AC_NAME,AC_MAST.ADD1,AC_MAST.ADD2,AC_MAST.ADD3,AC_MAST.CITY,AC_MAST.ZIP,AC_MAST.S_TAX,AC_MAST.I_TAX'
--SET @SQLCOMMAND=@SQLCOMMAND+', AC_MAST.ECCNO ,AC_MAST1.ADD1 ADD11,AC_MAST1.ADD2 ADD22,AC_MAST1.ADD3 ADD33,AC_MAST1.CITY CITY1'
--SET @SQLCOMMAND=@SQLCOMMAND+', AC_MAST1.ZIP ZIP1,AC_MAST1.S_TAX S_TAX1,AC_MAST1.I_TAX I_TAX1,AC_MAST1.ECCNO ECCNO1,STITEM.ITSERIAL'
--SET @SQLCOMMAND=@SQLCOMMAND+', STMAIN.U_OTHREF,STMAIN.U_PAYMENT,STMAIN.U_VESSEL,STMAIN.U_SBNO,STMAIN.U_SBDT'
--SET @SQLCOMMAND=@SQLCOMMAND+', totqty = (select sum(qty) from stitem inner join stmain on stitem.tran_cd = stmain.tran_cd)'
--SET @SQLCOMMAND=@SQLCOMMAND+', stmain.u_bknm,stmain.u_bkadd1,stmain.u_bkadd2,stmain.u_bkadd3,stmain.u_shipdet,stmain.party_nm'
--SET @SQLCOMMAND=@SQLCOMMAND+', stmain.u_frei,stmain.u_comm,stmain.u_fobamt,stmain.u_grno,stmain.u_grdt,stmain.narr,stmain.u_disc2,stmain.fcexrate'
--SET @SQLCOMMAND=@SQLCOMMAND+', stmain.u_bank,stmain.u_throu1,stmain.u_throu2,stmain.u_throu3'
--SET @SQLCOMMAND=@SQLCOMMAND+' FROM STMAIN  INNER JOIN STITEM ON (STMAIN.TRAN_CD=STITEM.TRAN_CD)'
--SET @SQLCOMMAND=@SQLCOMMAND+' INNER JOIN IT_MAST ON (STITEM.IT_CODE=IT_MAST.IT_CODE) '
--SET @SQLCOMMAND=@SQLCOMMAND+' INNER JOIN CURR_MAST ON (STMAIN.FCID = CURR_MAST.CURRENCYID)'
--SET @SQLCOMMAND=@SQLCOMMAND+' INNER JOIN AC_MAST ON (AC_MAST.AC_ID=STMAIN.AC_ID) '
--SET @SQLCOMMAND=@SQLCOMMAND+' LEFT JOIN AC_MAST AC_MAST1 ON (AC_MAST1.AC_NAME=STMAIN.U_DELIVER) '
SET @SQLCOMMAND=@SQLCOMMAND+RTRIM(@FCON)
SET @SQLCOMMAND=@SQLCOMMAND+' and STMAIN.ENTRY_TY = ''EI'''

print @SQLCOMMAND
EXECUTE SP_EXECUTESQL @SQLCOMMAND

