If Exists(Select [name] From SysObjects Where xtype='P' and [Name]='USP_REP_TG_FORMVAT200C')
Begin
	Drop Procedure USP_REP_TG_FORMVAT200C
End
GO
-- =============================================
-- Author:		Guarav Tanna
-- Create date: 10/10/2014	for BUG-23935 (Initially created same as AP VAT)
-- Description:	This Stored procedure is useful to generate TG VAT FORM 200C.
-- Remark	  :
-- Modify by  : Sumit Gavate
-- Remark	  : Modify for Bug no - 27971
-- Modify date: 19/04/2015
-- =============================================

/*
	EXECUTE USP_REP_TG_FORMVAT200C'','','','04/01/2015','04/30/2017','','','','',0,0,'','','','','','','','','2015-2016',''
*/

CREATE Procedure [dbo].[USP_REP_TG_FORMVAT200C]
@TMPAC NVARCHAR(50),@TMPIT NVARCHAR(50),@SPLCOND VARCHAR(8000),@SDATE  SMALLDATETIME,@EDATE SMALLDATETIME
,@SAC AS VARCHAR(60),@EAC AS VARCHAR(60)
,@SIT AS VARCHAR(60),@EIT AS VARCHAR(60)
,@SAMT FLOAT,@EAMT FLOAT
,@SDEPT AS VARCHAR(60),@EDEPT AS VARCHAR(60)
,@SCATE AS VARCHAR(60),@ECATE AS VARCHAR(60)
,@SWARE AS VARCHAR(60),@EWARE AS VARCHAR(60)
,@SINV_SR AS VARCHAR(60),@EINV_SR AS VARCHAR(60)
,@LYN VARCHAR(20)
,@EXPARA  AS VARCHAR(60)= null
AS
BEGIN
Declare @FCON as NVARCHAR(2000),@VSAMT DECIMAL(14,2),@VEAMT DECIMAL(14,2)
EXECUTE   USP_REP_FILTCON 
@VTMPAC =@TMPAC,@VTMPIT =@TMPIT,@VSPLCOND =@SPLCOND
,@VSDATE=NULL
,@VEDATE=@EDATE
,@VSAC =@SAC,@VEAC =@EAC
,@VSIT=@SIT,@VEIT=@EIT
,@VSAMT=@SAMT,@VEAMT=@EAMT
,@VSDEPT=@SDEPT,@VEDEPT=@EDEPT
,@VSCATE =@SCATE,@VECATE =@ECATE
,@VSWARE =@SWARE,@VEWARE  =@EWARE
,@VSINV_SR =@SINV_SR,@VEINV_SR =@SINV_SR
,@VMAINFILE='M',@VITFILE=NULL,@VACFILE=NULL
,@VDTFLD ='DATE'
,@VLYN=NULL
,@VEXPARA=@EXPARA
,@VFCON =@FCON OUTPUT

DECLARE @SQLCOMMAND NVARCHAR(4000)
DECLARE @RATE NUMERIC(12,2),@AMTA1 NUMERIC(12,2),@AMTB1 NUMERIC(12,2),@AMTC1 NUMERIC(12,2),@AMTD1 NUMERIC(12,2),@AMTE1 NUMERIC(12,2),@AMTF1 NUMERIC(12,2),@AMTG1 NUMERIC(12,2),@AMTH1 NUMERIC(12,2),@AMTI1 NUMERIC(12,2),@AMTJ1 NUMERIC(12,2),@AMTK1 NUMERIC(12,2),@AMTL1 NUMERIC(12,2),@AMTM1 NUMERIC(12,2),@AMTN1 NUMERIC(12,2),@AMTO1 NUMERIC(12,2)
DECLARE @AMTA2 NUMERIC(12,2),@AMTB2 NUMERIC(12,2),@AMTC2 NUMERIC(12,2),@AMTD2 NUMERIC(12,2),@AMTE2 NUMERIC(12,2),@AMTF2 NUMERIC(12,2),@AMTG2 NUMERIC(12,2),@AMTH2 NUMERIC(12,2),@AMTI2 NUMERIC(12,2),@AMTJ2 NUMERIC(12,2),@AMTK2 NUMERIC(12,2),@AMTL2 NUMERIC(12,2),@AMTM2 NUMERIC(12,2),@AMTN2 NUMERIC(12,2),@AMTO2 NUMERIC(12,2)
DECLARE @AMTA3 NUMERIC(12,2)
DECLARE @PER NUMERIC(12,2),@TAXAMT NUMERIC(12,2),@CHAR INT,@LEVEL NUMERIC(12,2)

SELECT DISTINCT AC_NAME=SUBSTRING(AC_NAME1,2,CHARINDEX('"',SUBSTRING(AC_NAME1,2,100))-1) INTO #VATAC_MAST FROM STAX_MAS WHERE AC_NAME1 NOT IN ('"SALES"','"PURCHASES"') AND ISNULL(AC_NAME1,'')<>''
INSERT INTO #VATAC_MAST SELECT DISTINCT AC_NAME=SUBSTRING(AC_NAME1,2,CHARINDEX('"',SUBSTRING(AC_NAME1,2,100))-1) FROM STAX_MAS WHERE AC_NAME1 NOT IN ('"SALES"','"PURCHASES"') AND ISNULL(AC_NAME1,'')<>''

Declare @PSDate smalldatetime, @PEDate smalldatetime
		  
Set @PSDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, @SDATE) - 1, 0)
Set @PEDate = (DATEADD(DAY, -(DAY(@SDATE)), @SDATE))

Declare @NetEff as numeric (12,2), @NetTax as numeric (12,2)

----Temporary Cursor1
-- bug-23933 - start here
/*
SELECT BHENT='PT',M.INV_NO,M.Date,A.AC_NAME,A.AMT_TY,STM.TAX_NAME,SET_APP=ISNULL(SET_APP,0),STM.ST_TYPE,M.NET_AMT,M.GRO_AMT,TAXONAMT=M.GRO_AMT+M.TOT_DEDUC+M.TOT_TAX+M.TOT_EXAMT+M.TOT_ADD,PER=STM.LEVEL1,MTAXAMT=M.TAXAMT,TAXAMT=A.AMOUNT,STM.FORM_NM,PARTY_NM=AC1.AC_NAME,AC1.S_TAX,M.U_IMPORM
,ADDRESS=LTRIM(AC1.ADD1)+ ' ' + LTRIM(AC1.ADD2) + ' ' + LTRIM(AC1.ADD3),M.TRAN_CD,VATONAMT=99999999999.99,Dbname=space(20),ItemType=space(1),It_code=999999999999999999-999999999999999999,ItSerial=Space(5)
INTO #FORMVAT200C_1
FROM PTACDET A 
INNER JOIN PTMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)
INNER JOIN STAX_MAS STM ON (M.TAX_NAME=STM.TAX_NAME)
INNER JOIN AC_MAST AC ON (A.AC_NAME=AC.AC_NAME)
INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID)
WHERE 1=2 --A.AC_NAME IN ( SELECT AC_NAME FROM #VATAC_MAST)

alter table #FORMVAT200C_1 add recno int identity
*/
-- bug-23933 - end here

---Temporary Cursor2
SELECT PART=3,PARTSR='AAA',SRNO='AAA',RATE=99999999.999,AMT1=NET_AMT,AMT2=M.TAXAMT,AMT3=M.TAXAMT,
M.INV_NO,M.DATE,PARTY_NM=AC1.AC_NAME,ADDRESS=Ltrim(AC1.Add1)+' '+Ltrim(AC1.Add2)+' '+Ltrim(AC1.Add3),STM.FORM_NM,AC1.S_TAX
INTO #FORMVAT200C
FROM PTACDET A 
INNER JOIN STMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD)
INNER JOIN STAX_MAS STM ON (M.TAX_NAME=STM.TAX_NAME)
INNER JOIN AC_MAST AC ON (A.AC_NAME=AC.AC_NAME)
INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID)
WHERE 1=2

 SET @AMTA1=0.00
 
IF NOT EXISTS (SELECT 1 
           FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_NAME='FORMVAT_201C') 
	begin
		 SELECT PART=3,PARTSR='AAA',SRNO='AAA',RATE=9999999999.999,AMT1=NET_AMT,AMT2=M.TAXAMT,AMT3=M.TAXAMT,M.INV_NO,M.DATE,PARTY_NM=AC1.AC_NAME,
		 ADDRESS=Ltrim(AC1.Add1)+' '+Ltrim(AC1.Add2)+' '+Ltrim(AC1.Add3),STM.FORM_NM,AC1.S_TAX INTO FORMVAT_201C FROM PTACDET A
		 INNER JOIN STMAIN M ON (A.ENTRY_TY=M.ENTRY_TY AND A.TRAN_CD=M.TRAN_CD) INNER JOIN STAX_MAS STM ON (M.TAX_NAME=STM.TAX_NAME)
		 INNER JOIN AC_MAST AC ON (A.AC_NAME=AC.AC_NAME) INNER JOIN AC_MAST AC1 ON (M.AC_ID=AC1.AC_ID) WHERE 1=2
		 print 'Previous month credit'
		 DECLARE @LASTLYN VARCHAR(25)
		 SET @LASTLYN = RTRIM(LTRIM(CAST(YEAR(@PEDate) as CHAR))) + '-' + RTRIM(LTRIM(CAST(YEAR(@PEDate) + 1 as CHAR)))
		 Print @PSDate
		 PRINT @PEDate
		 insert into FORMVAT_201C EXECUTE USP_REP_TG_FORMVAT200C '','','',@PSDate,@PEDate,'','','','',0,0,'','','','','','','','',@LASTLYN,''
		 SELECT @AMTA1 = AMT3 FROM FORMVAT_201C WHERE PARTSR = '4' AND SRNO = 'A'

		 DROP TABLE FORMVAT_201C
	end

SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0.00 ELSE @AMTA1 END
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (0,'0','A',0,@AMTA1,0,0,'')  
-- bug-23933 - end here

Declare @MultiCo	VarChar(3)
Declare @MCON as NVARCHAR(2000)
IF Exists(Select A.ID From SysObjects A Inner Join SysColumns B On(A.ID = B.ID) Where A.[Name] = 'STMAIN' And B.[Name] = 'DBNAME')
	Begin	------Fetch Records from Multi Co. Data
		 Set @MultiCo = 'YES'
		 EXECUTE USP_REP_MULTI_CO_DATA
		  @TMPAC, @TMPIT, @SPLCOND, @SDATE, @EDATE
		 ,@SAC, @EAC, @SIT, @EIT, @SAMT, @EAMT
		 ,@SDEPT, @EDEPT, @SCATE, @ECATE,@SWARE
		 ,@EWARE, @SINV_SR, @EINV_SR, @LYN, @EXPARA
		 ,@MFCON = @MCON OUTPUT

		--SET @SQLCOMMAND='Select * from '+@MCON
		---EXECUTE SP_EXECUTESQL @SQLCOMMAND
		
		-- bug-23933 - start here
		--SET @SQLCOMMAND='Insert InTo  #FORMVAT200C_1 Select * from '+@MCON
		SET @SQLCOMMAND='Insert InTo  vattbl Select * from '+@MCON
		-- bug-23933 - end here
		EXECUTE SP_EXECUTESQL @SQLCOMMAND		
		
		---Drop Temp Table 
		SET @SQLCOMMAND='Drop Table '+@MCON
		EXECUTE SP_EXECUTESQL @SQLCOMMAND
	End
else
	Begin ------Fetch Single Co. Data
		 Set @MultiCo = 'NO'
		 
		-- bug-23933 - start here 
		 --EXECUTE USP_REP_SINGLE_CO_DATA
		 EXECUTE USP_REP_SINGLE_CO_DATA_VAT
		  @TMPAC, @TMPIT, @SPLCOND, @SDATE, @EDATE
		 ,@SAC, @EAC, @SIT, @EIT, @SAMT, @EAMT
		 ,@SDEPT, @EDEPT, @SCATE, @ECATE,@SWARE
		 ,@EWARE, @SINV_SR, @EINV_SR, @LYN, @EXPARA
		 ,@MFCON = @MCON OUTPUT

		/*
		--SET @SQLCOMMAND='Select * from '+@MCON
		---EXECUTE SP_EXECUTESQL @SQLCOMMAND
		SET @SQLCOMMAND='Insert InTo  #FORMVAT200C_1 Select * from '+@MCON
		EXECUTE SP_EXECUTESQL @SQLCOMMAND
		
		---Drop Temp Table 
		SET @SQLCOMMAND='Drop Table '+@MCON
		EXECUTE SP_EXECUTESQL @SQLCOMMAND
		*/
		-- bug-23933 - end here 
	End
-----
-----SELECT * from #form221_1 where (Date Between @Sdate and @Edate) and Bhent in('EP','PT','CN') and TAX_NAME In('','NO-TAX') and U_imporm = ''
-----

---Part 1 (6-11)

---Purchase Details Exempt Purchases
SELECT @AMTA1=0,@AMTA2=0,@AMTB1=0,@AMTB2=0,@AMTC1=0,@AMTC2=0
-- bug-23933 - start here 
--SELECT @AMTA1=SUM(NET_AMT) FROM #FORMVAT200C_1  WHERE (st_type = 'Out of Country' or TAX_NAME='EXEMPTED') AND BHENT='PT' AND (DATE BETWEEN @SDATE AND @EDATE)
--SELECT @AMTA1=SUM(GRO_AMT) FROM VATTBL  
--WHERE ((ST_TYPE = 'LOCAL' AND TAX_NAME IN ('EXEMPTED')) OR (ST_TYPE = 'OUT OF STATE') OR (ST_TYPE = 'OUT OF COUNTRY')) AND BHENT='PT' AND (DATE BETWEEN @SDATE AND @EDATE)
--SELECT @AMTA1=sum(GRO_AMT),@AMTA2=sum(TAXAMT) FROM PTITEM where tax_name like '[^VS]%' AND (DATE BETWEEN @SDATE AND @EDATE) 
Select @AMTA1 = ISNULL(SUM(GRO_AMT),0) - ISNULL(SUM(TAXAMT),0),@AMTA2 = ISNULL(SUM(TAXAMT),0) FROM VATTBL WHERE BHENT = 'PT'
AND (DATE BETWEEN @SDATE AND @EDATE) AND TAX_NAME = 'EXEMPTED'

Select @AMTB1 = ISNULL(SUM(GRO_AMT),0) - ISNULL(SUM(TAXAMT),0),@AMTB2 = ISNULL(SUM(TAXAMT),0) FROM VATTBL WHERE BHENT = 'PT'
AND (DATE BETWEEN @SDATE AND @EDATE) AND ST_type IN('OUT OF STATE','OUT OF COUNTRY') AND TAX_NAME <> 'EXEMPTED'

Select @AMTC1 = ISNULL(SUM(GRO_AMT),0) - ISNULL(SUM(TAXAMT),0),@AMTC2 = ISNULL(SUM(TAXAMT),0) FROM VATTBL WHERE BHENT = 'PT'
AND (DATE BETWEEN @SDATE AND @EDATE) AND ST_type IN('LOCAL') AND S_TAX = '' AND TAX_NAME <> 'EXEMPTED'

-- bug-23933 - end here 
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'1','A',0,@AMTA1 + @AMTB1 + @AMTC1,@AMTA2 + @AMTB2 + @AMTC2,0,'')

/*
---VAT 4% Purchases
SET @AMTA1=0
SET @AMTA2=0
SET @PER  =0
SELECT @AMTA1=SUM(NET_AMT),@AMTA2=SUM(TAXAMT),@Per=Per FROM #FORMVAT200C_1 WHERE (BHENT='PT')AND PER = 4 and Tax_Name like '%VAT%' AND (DATE BETWEEN @SDATE AND @EDATE) Group by per
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'1','B',@PER,@AMTA1-@AMTA2,@AMTA2,0,'')


---VAT 12.5% Purchases
SET @AMTA1=0
SET @AMTA2=0
SET @PER=0
SELECT @AMTA1=SUM(NET_AMT),@AMTA2=SUM(TAXAMT),@Per=Per FROM #FORMVAT200C_1 WHERE (BHENT='PT') AND PER = 12.5 and Tax_Name like '%VAT%' AND (DATE BETWEEN @SDATE AND @EDATE) Group by per
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
SET @Per=CASE WHEN @Per IS NULL THEN 0 ELSE @Per END
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'1','C',@PER,@AMTA1-@AMTA2,@AMTA2,0,'')


---VAT 1% Purchases
SET @AMTA1=0
SET @AMTA2=0
SET @PER=0
SELECT @AMTA1=SUM(NET_AMT),@AMTA2=SUM(TAXAMT),@Per=Per FROM #FORMVAT200C_1 WHERE (BHENT='PT') AND PER = 1 and Tax_Name like '%VAT%' AND (DATE BETWEEN @SDATE AND @EDATE) Group by per
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'1','D',@PER,@AMTA1-@AMTA2,@AMTA2,0,'')
*/
 SELECT @AMTA1=0,@AMTB1=0,@AMTC1=0,@AMTD1=0,@AMTE1=0,@AMTF1=0,@AMTG1=0,@AMTH1=0,@AMTI1=0,@AMTJ1=0,@AMTK1=0,@AMTL1=0,@AMTM1=0,@AMTN1=0,@AMTO1=0 
 SET @CHAR=66
 DECLARE  CUR_FORM221 CURSOR FOR 
 select distinct level1 from stax_mas where ST_TYPE='LOCAL'--CHARINDEX('VAT',TAX_NAME)>0
 OPEN CUR_FORM221
 FETCH NEXT FROM CUR_FORM221 INTO @PER
 WHILE (@@FETCH_STATUS=0)
 BEGIN
  
    -- bug-23933 - (instead of FROM #FORMVAT200C_1, changed it to FROM VATTBL)  
	Begin
		SELECT @AMTA1=SUM(GRO_AMT)  FROM VATTBL WHERE ST_TYPE='LOCAL' AND BHENT='PT' AND PER=@PER AND (DATE BETWEEN @SDATE AND @EDATE) AND Tax_Name like '%VAT%' and s_tax<>''
		SELECT @AMTB1=SUM(TAXAMT)   FROM VATTBL WHERE ST_TYPE='LOCAL' AND BHENT='PT' AND PER=@PER AND (DATE BETWEEN @SDATE AND @EDATE) AND Tax_Name like '%VAT%' and s_tax<>''
		SELECT @AMTC1=SUM(GRO_AMT) FROM VATTBL WHERE ST_TYPE='LOCAL' AND BHENT='SR' AND PER=@PER AND (DATE BETWEEN @SDATE AND @EDATE) AND Tax_Name like '%VAT%' and s_tax<>''
		SELECT @AMTD1=SUM(TAXAMT)   FROM VATTBL WHERE ST_TYPE='LOCAL' AND BHENT='SR' AND PER=@PER AND (DATE BETWEEN @SDATE AND @EDATE) AND Tax_Name like '%VAT%' and s_tax<>''
		SELECT @AMTF1=SUM(GRO_AMT) FROM VATTBL WHERE ST_TYPE='LOCAL' AND BHENT='EP' AND PER=@PER AND (DATE BETWEEN @SDATE AND @EDATE) AND Tax_Name like '%VAT%' and s_tax<>''
		SELECT @AMTF2=SUM(TAXAMT)   FROM VATTBL WHERE ST_TYPE='LOCAL' AND BHENT='EP' AND PER=@PER AND (DATE BETWEEN @SDATE AND @EDATE) AND Tax_Name like '%VAT%' and s_tax<>''
		SELECT @AMTG1=SUM(GRO_AMT) FROM VATTBL WHERE ST_TYPE='LOCAL' AND BHENT='CN' AND PER=@PER AND (DATE BETWEEN @SDATE AND @EDATE) AND Tax_Name like '%VAT%' and s_tax<>''
		SELECT @AMTG2=SUM(TAXAMT)   FROM VATTBL WHERE ST_TYPE='LOCAL' AND BHENT='CN' AND PER=@PER AND (DATE BETWEEN @SDATE AND @EDATE) AND Tax_Name like '%VAT%' and s_tax<>''
	End


  --Purchase Invoice
  SET @AMTA1=ISNULL(@AMTA1,0)
  SET @AMTB1=ISNULL(@AMTB1,0)
  --Return Invoice
  SET @AMTC1=ISNULL(@AMTC1,0)
  SET @AMTD1=ISNULL(@AMTD1,0)
  --Expense Purchase Invoice
  SET @AMTF1=ISNULL(@AMTF1,0)
  SET @AMTF2=ISNULL(@AMTF2,0)
  --Debit Note Invoice
  SET @AMTG1=ISNULL(@AMTG1,0)
  SET @AMTG2=ISNULL(@AMTG2,0)
  --Sales Invoice Where U_imporm = 'Purchase Return'
  SET @AMTH1=ISNULL(@AMTH1,0)
  SET @AMTH2=ISNULL(@AMTH2,0)

  --Set @NetEFF = ((@AMTA1 - @AMTB1) + (@AMTF1 ) - (@AMTC1 - @AMTD1) - (@AMTG1 - @AMTG2) - (@AMTH1 - @AMTH2)) 
  --Set @NetTAX = (@AMTB1 + @AMTF2) - @AMTD1 - @AMTG2 - @AMTH2
  
  -- Net Purchase = (Purchase + Expense Purchase + Sales Return+ Credit Note)
  Set @NetEFF = ((@AMTA1 - @AMTB1) + (@AMTF1  - @AMTF2) + (@AMTC1 - @AMTD1)+ (@AMTG1 - @AMTG2))
  Set @NetTAX = (@AMTB1 + @AMTF2 + @AMTD1 + @AMTG2)


  -- bug-23933 - start here 
  /*
  if @nettax <> 0
	  Begin
		  INSERT INTO #FORMVAT200C
		  (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,Party_nm) VALUES
		  (1,'1',CHAR(@CHAR),@PER,@NETEFF,@NETTAX,0,'')

		  SET @AMTM1=@AMTM1+@NETEFF --TOTAL TAXABLE AMOUNT
		  SET @AMTO1=@AMTO1+@NETTAX --TOTAL TAX
		  SET @CHAR=@CHAR+1
	  end
  */	  
  
  if (@nettax <> 0) Or (@Per = 1.00 Or @Per = 4.00 Or @Per = 12.50)  
	  Begin
			IF (@per = 4.00)		
				INSERT INTO #FORMVAT200C
	           (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,Party_nm)
			   VALUES (1,'1', 'B',@PER,@NETEFF,@NETTAX,0,'')
			ELSE IF (@per = 12.50)
				INSERT INTO #FORMVAT200C
	           (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,Party_nm)
			   VALUES (1,'1', 'C',@PER,@NETEFF,@NETTAX,0,'')
			ELSE IF (@per = 1.00)
			   INSERT INTO #FORMVAT200C
	           (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,Party_nm)
			   VALUES (1,'1', 'D',@PER,@NETEFF,@NETTAX,0,'')
	  end
  -- bug-23933 - end here 
  
  
  FETCH NEXT FROM CUR_FORM221 INTO @PER
 END
 CLOSE CUR_FORM221
 DEALLOCATE CUR_FORM221
/* 
SELECT DISTINCT @AMTA1=SUM(GRO_AMT),@AMTA2=SUM(TAXAMT),@Per=Per FROM vattbl
WHERE (BHENT='PT') AND PER = 1 AND (DATE BETWEEN @SDATE AND @EDATE) and Tax_Name like '%VAT%' and s_tax<>'' Group by per

SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
SET @Per=CASE WHEN @Per IS NULL THEN 0 ELSE @Per END
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'1','D',@PER,@AMTA1-@AMTA2,@AMTA2,0,'')  
*/
---VAT Special Rates Purchases
Declare @s_tax as varchar(15)

SET @AMTA1=0
SET @AMTA2=0
SET @PER=0
Set @S_tax = ''
-- bug-23933 - start here 
--SELECT @AMTA1=SUM(NET_AMT),@AMTA2=SUM(TAXAMT),@per = per,@S_Tax = Tax_Name FROM #FORMVAT200C_1 WHERE (BHENT='PT') and (TaxAmt <> 0 and per = 0) and Tax_Name like '%VAT%' AND (DATE BETWEEN @SDATE AND @EDATE) group by Per, Tax_name
SELECT @AMTA1=SUM(GRO_AMT),@AMTA2=SUM(TAXAMT),@per = per,@S_Tax = Tax_Name FROM vattbl WHERE (BHENT In ('PT', 'EP', 'SR', 'CN')) AND ST_TYPE='LOCAL' AND TAX_NAME LIKE '%SPECIAL%' and s_tax<>''  AND (DATE BETWEEN @SDATE AND @EDATE) group by Per, Tax_name
-- bug-23933 - end here 

SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'1','E',@PER,@AMTA1-@AMTA2,@AMTA2,0,'')


---Total Tax Amount B,C,D Purchases
SET @AMTA1=0
SET @AMTA2=0
SET @AMTA3=0
SET @PER=0
SELECT @AMTA1=SUM(AMT1),@AMTA2=SUM(AMT2) FROM #FORMVAT200C WHERE PARTSR = '1' and SRNO in('B','C','D')
SELECT @AMTA3=SUM(AMT1) FROM #FORMVAT200C WHERE PARTSR = '0'

SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
SET @AMTA3=CASE WHEN @AMTA3 IS NULL THEN 0 ELSE @AMTA3 END

INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'1','F',@PER,0,@AMTA2+@AMTA3,0,'')

--part 2 (12-20)

--Sales Details Total Exempted Sales
SET @AMTA1=0
SET @AMTA2=0
SET @PER=0
-- bug-23933 - start here 
--SELECT @AMTA1=SUM(NET_AMT),@AMTA2=SUM(TAXAMT) FROM #FORMVAT200C_1 WHERE (BHENT='ST') and Per = 0 AND (DATE BETWEEN @SDATE AND @EDATE) and tax_name = 'Exempted'
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0),@AMTA2 = ISNULL(SUM(TAXAMT),0) FROM VATTBL WHERE (BHENT='ST') AND
Per = 0 AND (DATE BETWEEN @SDATE AND @EDATE) and tax_name = 'Exempted'
-- bug-23933 - end here 
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'2','A',0,@AMTA1,0,0,'')

---Export Sales
SELECT @AMTA1=0,@AMTA2=0,@PER=0
-- bug-23933 - start here 
--SELECT @AMTA1=SUM(NET_AMT),@AMTA2=SUM(TAXAMT) FROM #FORMVAT200C_1 WHERE (DATE BETWEEN @SDATE AND @EDATE) and St_type = 'Out of Country' and BHENT = 'ST'
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0),@AMTA2 = ISNULL(SUM(TAXAMT),0) FROM VATTBL WHERE (DATE BETWEEN @SDATE AND @EDATE) and
St_type = 'Out of Country' and BHENT = 'ST'  and Per = 0
-- bug-23933 - end here 
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'2','B',0,@AMTA1-@AMTA2,0,0,'')

---Inter States/CST Sales
SELECT @AMTA1=0,@AMTA2=0,@PER=0
-- bug-23933 - start here 
--SELECT @AMTA1=SUM(NET_AMT),@AMTA2=SUM(TAXAMT) FROM #FORMVAT200C_1  WHERE (st_type = 'Out of State') AND BHENT='ST' AND (DATE BETWEEN @SDATE AND @EDATE)
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0),@AMTA2 = ISNULL(SUM(TAXAMT),0) FROM VATTBL  WHERE (st_type = 'Out of State')
AND BHENT='ST' AND (DATE BETWEEN @SDATE AND @EDATE)  and Per = 0
-- bug-23933 - end here 
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'2','C',0,@AMTA1-@AMTA2,@AMTA2,0,'')
---Tax Due on Purchases
SELECT @AMTA1=0,@AMTA2=0,@PER=0
-- bug-23933 - start here 
--SELECT @AMTA1=SUM(NET_AMT),@AMTA2=SUM(TAXAMT),@per = per FROM #FORMVAT200C_1 WHERE (BHENT='ST') and s_tax = ' ' AND (DATE BETWEEN @SDATE AND @EDATE) group by Per
SELECT @AMTA1 = ISNULL(SUM(GRO_AMT),0),@AMTA2 = ISNULL(SUM(TAXAMT),0) FROM VATTBL WHERE (BHENT='PT') AND S_TAX='' AND
TAXAMT <> 0 AND (DATE BETWEEN @SDATE AND @EDATE)
-- bug-23933 - end here 
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'2','D',0,@AMTA1,@AMTA2,0,'')

/*
---Local 4% VAT Sales
SET @AMTA1=0
SET @AMTA2=0
SET @PER=0
SELECT @AMTA1=SUM(NET_AMT),@AMTA2=SUM(TAXAMT),@per = per FROM #FORMVAT200C_1 WHERE (BHENT='ST') and Tax_name like '%VAT%' and Per = 4 AND (DATE BETWEEN @SDATE AND @EDATE) group by Per
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'2','E',@PER,@AMTA1-@AMTA2,@AMTA2,0,'')

---Lcoal 12.5% VAT Sales
SET @AMTA1=0
SET @AMTA2=0
SET @PER=0
SELECT @AMTA1=SUM(NET_AMT),@AMTA2=SUM(TAXAMT),@per = per FROM #FORMVAT200C_1 WHERE (BHENT='ST') and Tax_name like '%VAT%' and Per = 12.50 AND (DATE BETWEEN @SDATE AND @EDATE) group by Per
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'2','F',@PER,@AMTA1-@AMTA2,@AMTA2,0,'')
*/

 SELECT @AMTA1=0,@AMTB1=0,@AMTC1=0,@AMTD1=0,@AMTE1=0,@AMTF1=0,@AMTG1=0,@AMTH1=0,@AMTI1=0,@AMTJ1=0,@AMTK1=0,@AMTL1=0,@AMTM1=0,@AMTN1=0,@AMTO1=0 
 SET @CHAR=69
 
 DECLARE  CUR_FORM221 CURSOR FOR 
 select distinct level1 from stax_mas where ST_TYPE='LOCAL'--CHARINDEX('VAT',TAX_NAME)>0
 
 OPEN CUR_FORM221
 FETCH NEXT FROM CUR_FORM221 INTO @PER
 WHILE (@@FETCH_STATUS=0)
 BEGIN
	
		begin
			SELECT @AMTA1=SUM(GRO_AMT) FROM VATTBL where ST_TYPE='LOCAL' AND bhent = 'ST' AND (DATE BETWEEN @SDATE AND @EDATE) and Tax_name like '%VAT%'  AND PER=@PER 
			SELECT @AMTB1=SUM(TAXAMT)  FROM VATTBL where ST_TYPE='LOCAL' AND bhent = 'ST' AND (DATE BETWEEN @SDATE AND @EDATE) and Tax_name like '%VAT%'  AND PER=@PER 
			SELECT @AMTC1=SUM(GRO_AMT) FROM VATTBL where ST_TYPE='LOCAL' AND bhent = 'PR' AND (DATE BETWEEN @SDATE AND @EDATE) and Tax_name like '%VAT%' AND PER=@PER
			SELECT @AMTD1=SUM(TAXAMT)  FROM VATTBL where ST_TYPE='LOCAL' AND bhent = 'PR' AND (DATE BETWEEN @SDATE AND @EDATE) and Tax_name like '%VAT%'  AND PER=@PER
			SELECT @AMTE1=SUM(GRO_AMT) FROM VATTBL where ST_TYPE='LOCAL' AND bhent = 'DN' AND (DATE BETWEEN @SDATE AND @EDATE) and Tax_name like '%VAT%'  AND PER=@PER
			SELECT @AMTF1=SUM(TAXAMT)  FROM VATTBL where ST_TYPE='LOCAL' AND bhent = 'DN' AND (DATE BETWEEN @SDATE AND @EDATE) and Tax_name like '%VAT%'  AND PER=@PER
		end
	
  --Sales Invoices
  SET @AMTA1=ISNULL(@AMTA1,0)
  SET @AMTB1=ISNULL(@AMTB1,0)
 
  -- Purchase Return Invoices
  SET @AMTC1=ISNULL(@AMTC1,0)
  SET @AMTD1=ISNULL(@AMTD1,0)
  
   -- Debit Note
  SET @AMTE1=ISNULL(@AMTE1,0)
  SET @AMTF1=ISNULL(@AMTF1,0)

  --Net Effect = (Sales + Purchase Return + Debit Note)
  
  Set @NetEFF = ((@AMTA1-@AMTB1)+(@AMTC1-@AMTD1)+(@AMTE1-@AMTF1))
  --Set @NetEFF = (@AMTA1-@AMTB1)-(@AMTC1-@AMTD1)
  Set @NetTAX = (@AMTB1+@AMTD1+@AMTF1)

  -- bug-23933 - start here 
  /*
  if @nettax <> 0
	  begin
		  INSERT INTO #FORMVAT200C
		  (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,Party_nm) VALUES
		  (1,'2',CHAR(@CHAR),@PER,@NETEFF,@NETTAX,0,'')
		  SET @AMTJ1=@AMTJ1+@NETEFF --TOTAL TAXABLE AMOUNT
		  SET @AMTK1=@AMTK1+@NETTAX --TOTAL TAX
		  SET @CHAR=@CHAR+1
	  end
  */
    
   if (@nettax <> 0) Or (@Per = 4.00 Or @Per = 12.50)  
	  Begin
			IF (@per = 4.00)		
				INSERT INTO #FORMVAT200C
	           (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,Party_nm)
			   VALUES (1,'2','E',@PER,@NETEFF,@NETTAX,0,'')
			ELSE IF (@per = 12.50)
				INSERT INTO #FORMVAT200C
	           (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,Party_nm)
			   VALUES (1,'2','F',@PER,@NETEFF,@NETTAX,0,'')			
	  end
  -- bug-23933 - end here   
    
  FETCH NEXT FROM CUR_FORM221 INTO @PER
 END
 CLOSE CUR_FORM221
 DEALLOCATE CUR_FORM221
 
 
---Local Special Rate VAT Sales
SET @AMTA1=0
SET @AMTA2=0
SET @PER=0
Set @S_Tax = ''
-- bug-23933 - start here 
--SELECT @AMTA1=SUM(NET_AMT),@AMTA2=SUM(TAXAMT),@per = per,@S_tax=Tax_Name FROM #FORMVAT200C_1 WHERE (BHENT='ST') and Tax_name like '%VAT%' and (TaxAmt <> 0 and per = 0) AND (DATE BETWEEN @SDATE AND @EDATE) group by Per, Tax_Name
SELECT @AMTA1=SUM(GRO_AMT),@AMTA2=SUM(TAXAMT),@per = per,@S_tax=Tax_Name FROM VATTBL WHERE (BHENT IN ('ST', 'PR', 'DN')) and Tax_name like '%SPECIAL%' AND ST_TYPE='LOCAL'  AND (DATE BETWEEN @SDATE AND @EDATE) group by Per, Tax_Name
-- bug-23933 - end here 

SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
-- As per govt. site format don't show and also not include in total this special rate amount and tax
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'2','G',@PER,0,0,0,'')
--INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'2','G',@PER,@AMTA1-@AMTA2,@AMTA2,0,'')

---Local 1% VAT Sales
SET @AMTA1=0
SET @AMTA2=0
SET @PER=0
-- bug-23933 - start here 
--SELECT @AMTA1=SUM(NET_AMT),@AMTA2=SUM(TAXAMT),@per = per FROM #FORMVAT200C_1 WHERE (BHENT='ST') and Per = 1 and Tax_name like '%VAT%' AND (DATE BETWEEN @SDATE AND @EDATE) group by Per
SELECT @AMTA1=SUM(GRO_AMT),@AMTA2=SUM(TAXAMT),@per = per FROM VATTBL WHERE (BHENT IN ('ST', 'PR', 'DN')) and Per = 1 and Tax_name like '%VAT%' AND ST_TYPE='LOCAL' AND (DATE BETWEEN @SDATE AND @EDATE) group by Per
-- bug-23933 - end here 

SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'2','H',@PER,@AMTA1-@AMTA2,@AMTA2,0,'')


---Total Tax Amount D,E,F,H Sales
SET @AMTA1=0
SET @AMTA2=0
SET @PER=0
SELECT @AMTA1=SUM(AMT1),@AMTA2=SUM(AMT2) FROM #FORMVAT200C WHERE PARTSR = '2' and SRNO In ('D','E','F','H')
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'2','I',@PER,0,@AMTA2,0,'')

--part 3 (21-22)
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'3','A',0,0,0,0,'')

---VAT Payable From Bank Payment Details
Declare @TAXONAMT as numeric(12,2),@TAXAMT1 as numeric(12,2),@ITEMAMT as numeric(12,2),@INV_NO as varchar(10),
	    @DATE as smalldatetime,@PARTY_NM as varchar(50),@ADDRESS as varchar(100),
		@FORM_NM as varchar(30) ---,@S_TAX as varchar(30)


SELECT @TAXONAMT=0,@TAXAMT =0,@ITEMAMT =0,@INV_NO ='',@DATE ='',@PARTY_NM ='',@ADDRESS ='',@FORM_NM='',@S_TAX =''

SET @CHAR=66
SET @PER = 0

-- bug-23933 - start here 
/*
declare Cur_VatPay cursor  for
select A.Taxonamt,A.taxamt,A.Gro_amt,A.inv_no,A.Date,A.Party_nm,Address='',A.Form_nm,A.S_tax
from #formvat200C_1 A
Inner Join Bpmain B on(A.Bhent = B.Entry_ty And A.Tran_Cd = B.Tran_cd)
where A.BHENT = 'BP' And A.Date Between @sdate and @edate And B.Party_nm like '%VAT%'
*/
declare Cur_VatPay cursor  for
select A.vatonamt,A.taxamt,A.Gro_amt,A.inv_no,A.Date,B.Bank_nm,Address='',A.Form_nm,A.S_tax
from vattbl A
Inner Join Bpmain B on(A.Bhent = B.Entry_ty And A.Tran_Cd = B.Tran_cd)
where A.BHENT = 'BP' And A.Date Between @sdate and @edate And B.Party_nm = 'VAT PAYABLE'
-- bug-23933 - end here 

Declare @Bank_Pymt NUMERIC(12,2)

set @Bank_Pymt =0

open Cur_VatPay
FETCH NEXT FROM Cur_VatPay INTO @TAXONAMT,@TAXAMT,@ITEMAMT,@INV_NO,@DATE,@PARTY_NM,@ADDRESS,@FORM_NM,@S_TAX
 WHILE (@@FETCH_STATUS=0)
 BEGIN

	SET @Per=CASE WHEN @Per IS NULL THEN 0 ELSE @Per END
	SET @TAXONAMT=CASE WHEN @TAXONAMT IS NULL THEN 0 ELSE @TAXONAMT END
	SET @TAXAMT=CASE WHEN @TAXAMT IS NULL THEN 0 ELSE @TAXAMT END
	SET @ITEMAMT=CASE WHEN @ITEMAMT IS NULL THEN 0 ELSE @ITEMAMT END
	SET @PARTY_NM=CASE WHEN @PARTY_NM IS NULL THEN '' ELSE @PARTY_NM END
	SET @INV_NO=CASE WHEN @INV_NO IS NULL THEN '' ELSE @INV_NO END
	SET @DATE=CASE WHEN @DATE IS NULL THEN '' ELSE @DATE END
	SET @ADDRESS=CASE WHEN @ADDRESS IS NULL THEN '' ELSE @ADDRESS END
	SET @S_TAX=CASE WHEN @S_TAX IS NULL THEN '' ELSE @S_TAX END
	SET @FORM_NM=CASE WHEN @FORM_NM IS NULL THEN '' ELSE @FORM_NM END
	
	set @Bank_Pymt = @Bank_Pymt + @TAXONAMT
	
	INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,INV_NO,DATE,PARTY_NM,ADDRESS,FORM_NM,S_TAX) VALUES (1,'3',CHAR(@CHAR),@PER,@TAXONAMT,@TAXAMT,@ITEMAMT,@INV_NO,@DATE,@PARTY_NM,@ADDRESS,@FORM_NM,@S_TAX)

 SET @CHAR=@CHAR+1
 FETCH NEXT FROM CUR_VatPay INTO @TAXONAMT,@TAXAMT,@ITEMAMT,@INV_NO,@DATE,@PARTY_NM,@ADDRESS,@FORM_NM,@S_TAX
END
CLOSE CUR_VatPay
DEALLOCATE CUR_VatPay

----

INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'3','Z',0,0,0,0,'')

--part 4

----23 Refund
SET @AMTA1=0
SET @AMTA2=0
SET @PER=0

--bug-23933 - start here
SELECT @AMTA1=SUM(NET_AMT) FROM (select distinct A.tran_cd,A.bhent,C.NET_AMT,dbname  FROM vattbl A
 INNER JOIN JVMAIN C ON A.TRAN_cD=C.TRAN_cD WHERE A.BHENT IN ('JV','J4') 
 AND C.VAT_ADJ='Refund Claim' AND (A.DATE BETWEEN @SDATE AND @EDATE))B 

SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'23','A',0,@AMTA1,0,0,'')  

--24(b) Net credit carried forward
SET @AMTA1=0
SET @AMTA2=0
SET @AMTA3=0
SET @PER=0

SELECT @AMTA1=SUM(NET_AMT) FROM (select distinct A.tran_cd,A.bhent,C.NET_AMT,dbname  FROM vattbl A 
INNER JOIN JVMAIN C ON A.TRAN_cD=C.TRAN_cD WHERE A.BHENT IN ('JV','J4') AND C.VAT_ADJ='VAT' 
AND (A.DATE BETWEEN @SDATE AND @EDATE))B 

SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'23','C',@PER,@AMTA1,@AMTA2,@AMTA3,'')  

SET @AMTA1=0
SET @AMTA2=0
SET @PER=0

SELECT @AMTA1=SUM(NET_AMT) FROM (select distinct A.tran_cd,A.bhent,C.NET_AMT,dbname  FROM vattbl A 
INNER JOIN JVMAIN C ON A.TRAN_cD=C.TRAN_cD WHERE A.BHENT IN ('JV','J4') AND C.VAT_ADJ='CST' 
AND (A.DATE BETWEEN @SDATE AND @EDATE))B 

SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES  (1,'23','Z',0,@AMTA1,0,0,'')  

SET @AMTA1=0
SET @AMTA2=0
SET @AMTA3=0
SET @PER=0

SELECT @AMTA1=SUM(AMT1) FROM #FORMVAT200C WHERE PARTSR IN ( '23') and SRNO In ('C')
SELECT @AMTA2=SUM(AMT1) FROM #FORMVAT200C WHERE PARTSR IN ( '23') and SRNO In ('Z')
SELECT @PER=SUM(AMT1) FROM #FORMVAT200C WHERE PARTSR IN ( '23') and SRNO In ('A')

SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
SET @PER=CASE WHEN @PER IS NULL THEN 0 ELSE @PER END
SET @AMTA3=@AMTA1-@AMTA2
INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) 
VALUES  (1,'23','B',0,@AMTA3,0,0,'')  

SET @AMTA1=0
SET @AMTA2=0
SET @AMTA3=0

Declare @AMTP NUMERIC(12,2), @AMTS NUMERIC(12,2), @AMTNET NUMERIC(12,2)
SET @AMTP =0
SET @AMTS = 0
SET @AMTnet = 0 

SELECT @PER=SUM(AMT1) FROM #FORMVAT200C  WHERE PARTSR IN ( '23') and SRNO In ('A')
--SELECT @AMTA1=SUM(AMT1) FROM #FORMVAT200C  WHERE PARTSR IN ( '23') and SRNO In ('C') 
SELECT @AMTA2=SUM(AMT1) FROM #FORMVAT200C  WHERE PARTSR IN ( '23') and SRNO In ('Z')
--SELECT @AMTA3=SUM(AMT1) FROM #FORMVAT200C  WHERE PARTSR IN ( '23') and SRNO In ('B')

SELECT @AMTA3=SUM(AMT1) FROM #FORMVAT200C  WHERE PARTSR IN ( '2') and SRNO In ('B')
SELECT @AMTP=SUM(AMT2) FROM #FORMVAT200C  WHERE PARTSR IN ( '1') and SRNO In ('F')
SELECT @AMTS=SUM(AMT2) FROM #FORMVAT200C  WHERE PARTSR IN ( '2') and SRNO In ('I')

SET @PER=CASE WHEN @PER IS NULL THEN 0.00 ELSE @PER END -- Refund Claim
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END -- CST Adjustment
SET @AMTA3=CASE WHEN @AMTA3 IS NULL THEN 0 ELSE @AMTA3 END -- Export sale with 0 percent 
SET @AMTP=CASE WHEN @AMTP IS NULL THEN 0 ELSE @AMTP END -- Total Purchase
SET @AMTS=CASE WHEN @AMTS IS NULL THEN 0 ELSE @AMTS END -- Total Sales
SET @Bank_Pymt=CASE WHEN @Bank_Pymt IS NULL THEN 0 ELSE @Bank_Pymt END -- Bank Vat Payment

IF @AMTA3 >= 0 And @AMTA2 = 0 -- If Export sales is there and no CST Adjustment
	IF @AMTP > @AMTS -- If Purchase tax credit exceeds sales tax payable
		    SET @AMTA1 = (@AMTP - @AMTS)
		    
	-- If Sales Tax Payable exceeds Purchase Tax Credit and Paid more through bank then its difference   
	ELSE IF ((@AMTS - @AMTP) >= 0) And ((@Bank_Pymt) > (@AMTS - @AMTP))
		    SET @AMTA1 = ((@Bank_Pymt) - (@AMTS - @AMTP))

--SET @PER=CASE WHEN @PER IS NULL THEN 0.00 ELSE @PER END -- Refund Claim
SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0.00 ELSE @AMTA1 END -- Credit Carry Forward

   
IF @Per > 0 And @AMTA1 > 0
   
   IF (@AMTA1 >= @PER)
	  SET @AMTA1 = (@AMTA1 - @PER)       
   ELSE
      SET @AMTA1 = 0

INSERT INTO #FORMVAT200C  (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) 
VALUES  (1,'4','A',@AMTA1,@PER,@AMTA2,@AMTA3,'')  

--VALUES  (1,'4','A',@PER,@AMTA2,@AMTA3,@AMTA1,'')  


/*
SELECT @PER=SUM(AMT1) FROM #FORMVAT200C WHERE PARTSR IN ( '23') and SRNO In ('A')
SELECT @AMTA1=SUM(AMT1) FROM #FORMVAT200C WHERE PARTSR IN ( '23') and SRNO In ('C') 
SELECT @AMTA2=SUM(AMT1) FROM #FORMVAT200C WHERE PARTSR IN ( '23') and SRNO In ('Z')
--SELECT @AMTA3=SUM(AMT1) FROM #FORMVAT200C WHERE PARTSR IN ( '23') and SRNO In ('B')
SELECT @AMTA3=SUM(AMT1) FROM #FORMVAT200C WHERE PARTSR IN ( '2') and SRNO In ('B')

SET @AMTA1=CASE WHEN @AMTA1 IS NULL THEN 0 ELSE @AMTA1 END
SET @AMTA2=CASE WHEN @AMTA2 IS NULL THEN 0 ELSE @AMTA2 END
SET @AMTA3=CASE WHEN @AMTA3 IS NULL THEN 0 ELSE @AMTA3 END

INSERT INTO #FORMVAT200C (PART,PARTSR,SRNO,RATE,AMT1,AMT2,AMT3,PARTY_NM) VALUES (1,'4','A',@PER,@AMTA2,@AMTA3,0,'')
*/
Update #FORMVAT200C set  PART = isnull(Part,0) , Partsr = isnull(PARTSR,''), SRNO = isnull(SRNO,''),
		             RATE = isnull(RATE,0), AMT1 = isnull(AMT1,0), AMT2 = isnull(AMT2,0), 
					 AMT3 = isnull(AMT3,0), INV_NO = isnull(INV_NO,''), DATE = isnull(Date,''), 
					 PARTY_NM = isnull(Party_nm,''), ADDRESS = isnull(Address,''), 
					 FORM_NM = isnull(form_nm,''), S_TAX = isnull(S_tax,'')


SELECT * FROM #FORMVAT200C order by cast(substring(partsr,1,case when (isnumeric(substring(partsr,1,2))=1) then 2 else 1 end) as int)
                           
END
--Print 'AP VAT FORM 200C'